### ISSUE TITLE
[BUG]ERROR running "pyarmor gen" : 'cp932' codec can't decode byte 0x83  

### ISSUE THREAD

**Issue by xiene** [dashingsoft/pyarmor#1000]
I ran the following command then I got an error.:
>pyarmor gen xxxx.py
INFO     Python 3.11.2
INFO     Pyarmor 8.0.9 (basic), 004002, XXX
INFO     search inputs ...
INFO     find script xxxx.py
INFO     find 1 top resources
CRITICAL unknown error, please check pyarmor.error.log
ERROR    'cp932' codec can't decode byte 0x83 in position 216: illegal multibyte sequence

pyarmor.error.log:
7992 MainProcess 2023-03-24 08:56:58,882
Traceback (most recent call last):
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 144, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\generate.py", line 143, in process
    Pytransform3.pre_build(self.ctx)
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\core\__init__.py", line 63, in pre_build
    return m.pre_build(ctx)
           ^^^^^^^^^^^^^^^^
  File "<maker>", line 729, in pre_build
  File "<maker>", line 620, in build
  File "<maker>", line 2954, in process
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\resource.py", line 97, in reparse
    lines = self.readlines(encoding=encoding)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\resource.py", line 93, in readlines
    return f.readlines()
           ^^^^^^^^^^^^^
UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 216: illegal multibyte sequence

**Comment by jondy** [comment]
duplicated of #999

**Comment by jondy** [comment]
Fixed it in 8.0.10
