### ISSUE TITLE
[BUG] When storing runtime files inside package, an "ImportError" will appear during package execution

### ISSUE THREAD

**Issue by fO-000** [dashingsoft/pyarmor#1004]
Environment:

* Python 3.11.2
* pyarmor 8.0.9
* pyarmor.cli.core 1.0.3
* OS: `Linux x 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux`

After running `pyarmor gen --recursive` with `-i` option (store runtime files inside package), I got the output hierarchy as below:

```txt
test_package/
    ├── __init__.py
    ├── __main__.py
    └── pyarmor_runtime_00xxxx/
        ├── __init__.py
        └── pyarmor_runtime.so
```

The content of `package_name/__init__.py` is as follows:

```py
# Pyarmor 8.0.9 (basic), 00xxxx, 2023-03-24T16:10:26.011623
from ..pyarmor_runtime_00xxxx import __pyarmor__
__pyarmor__(__name__, __file__, b'PY00xxxx\x..\x..\x..')
```

Maybe the second line `from ..pyarmor_runtime_00xxxx ...` should be changed to `from .pyarmor_runtime_00xxxx ...`?

If not modified, the execution of `test_package` will report the `ImportError`:

```txt
$ python -m test_package
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/x/x/test_package/__init__.py", line 2, in <module>
    from ..pyarmor_runtime_00xxxx import __pyarmor__
ImportError: attempted relative import beyond top-level package
```

But after I made the above modifications manually (change `from ..pyarmor_runtime_00xxxx ...` to `from .pyarmor_runtime_00xxxx ...`), the following error will be reported when running `test_package`:

```txt
$ python -m test_package
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/x/x/test_package/__init__.py", line 2, in <module>
    from .pyarmor_runtime_00xxxx import __pyarmor__
  File "/home/x/x/test_package/pyarmor_runtime_00xxxx/__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: unauthorized use of script (1:10385)
```

**Comment by jondy** [comment]
Got it, thanks. I'll check it.
