### ISSUE TITLE
[BUG] ERROR not machine id (pyarmor 8.0.17 / pyarmor.cli.core 1.0.7)

### ISSUE THREAD

**Issue by kjl2875** [dashingsoft/pyarmor#1012]
```
root@pug:~/test# pyarmor gen --recursive a.py
INFO     Python 3.9.2
INFO     Pyarmor 8.0.17 (pro), 005021, upbitbot
INFO     search inputs ...
INFO     find script a.py
INFO     find 1 top resources
CRITICAL unknown error, please check pyarmor.error.log
ERROR    not machine id
```

```
root@pug:~/test# pyarmor --version
Pyarmor 8.0.17 (pro), 005021, upbitbot

License Type    : pyarmor-pro
License No.     : pyarmor-vax-005021
License To      : upbitbot (WONKI BANG)

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Internet connection is required to verify Pyarmor license
```

```
root@pug:~/test# pip list | grep pyarmor
pyarmor             8.0.17
pyarmor.cli.core    1.0.7
```

```
root@pug:~/test# cat pyarmor.error.log
126206 MainProcess 2023-03-26 23:17:11,732
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/cli/__main__.py", line 567
    main_entry(sys.argv[1:])
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/cli/__main__.py", line 555
    args.func(ctx, args)
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/cli/__main__.py", line 147
    builder.process(options, pack=args.pack)
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/cli/generate.py", line 143
    Pytransform3.pre_build(self.ctx)
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/cli/core/__init__.py", lin
    m = Pytransform3.init(ctx)
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/cli/core/__init__.py", lin
    m.init_ctx(ctx)
RuntimeError: not machine id
```

```
root@pug:~/test# cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
```

**Comment by jondy** [comment]
Try to register pyarmor again in this machine with `.zip`
