### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by Santhosh1509** [dashingsoft/pyarmor#102]
**Python: 3.7.2
OS: Windows 10**

Pip list

> Package               Version
> --------------------- ---------
> altgraph              0.16.1
> future                0.17.1
> macholib              1.11
> numpy                 1.16.4
> object-detection      0.1
> opencv-contrib-python 4.1.0.25
> opencv-python         4.1.0.25
> pbr                   5.3.0
> pefile                2019.4.18
> pip                   19.1.1
> pyarmor               5.5.2
> PyInstaller           3.4
> pywin32-ctypes        0.2.0
> setuptools            41.0.1
> six                   1.12.0
> stevedore             1.30.1
> virtualenv            16.6.1
> virtualenv-clone      0.5.3
> virtualenvwrapper-win 1.2.5
> wheel                 0.33.4

I am trying to test how the pyarmor works which this code to [capture video from camera using opencv](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html#capture-video-from-camera) 

`myscript.py`

```
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Display the resulting frame
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()
```

followed this [Work with PyInstaller](https://pyarmor.readthedocs.io/en/latest/pack-obfuscated-scripts.html#work-with-pyinstaller)

Here's my spec file

```
# -*- mode: python -*-

block_cipher = None

a = Analysis(['myscript.py', 'dist\\obf\\myscript.py'],
             pathex=['D:\\pyarmortest'],
             binaries=[],
             datas=[('dist\\obf\\license.lic', '.'), ('dist/obf/pytransform.key', '.'), ('dist/obf/_pytransform.dll', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
a.scripts[-1] = 'myscript', 'dist/obf/myscript.py', 'PYSOURCE'
for i in range(len(a.pure)):
    if a.pure[i][1].startswith(a.pathex[0]):
        x = a.pure[i][1].replace(a.pathex[0], os.path.abspath('dist/obf'))
        if os.path.exists(x):
            if hasattr(a.pure, '_code_cache'):
                with open(x) as f:
                    a.pure._code_cache[a.pure[i][0]] = compile(f.read(), a.pure[i][1], 'exec')
            a.pure[i] = a.pure[i][0], x, a.pure[i][2]
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='myscript',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='myscript')
```

Since i got 

> 
> Traceback (most recent call last):
>   File "dist/obf\myscript.py", line 3, in <module>
>   File "<frozen myscript>", line 4, in <module>
> ModuleNotFoundError: No module named 'numpy'
> [12208] Failed to execute script myscript

I changed my spec file to add `numpy` as hidden module

```
# -*- mode: python -*-

from PyInstaller.utils.hooks import collect_submodules

block_cipher = None

hidden_imports_numpy = collect_submodules('numpy')

a = Analysis(['myscript.py', 'dist\\obf\\myscript.py'],
             pathex=['D:\\pyarmortest'],
             binaries=[],
             datas=[('dist\\obf\\license.lic', '.'), ('dist/obf/pytransform.key', '.'), ('dist/obf/_pytransform.dll', '.')],
             hiddenimports=hidden_imports_numpy,
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
a.scripts[-1] = 'myscript', 'dist/obf/myscript.py', 'PYSOURCE'
for i in range(len(a.pure)):
    if a.pure[i][1].startswith(a.pathex[0]):
        x = a.pure[i][1].replace(a.pathex[0], os.path.abspath('dist/obf'))
        if os.path.exists(x):
            if hasattr(a.pure, '_code_cache'):
                with open(x) as f:
                    a.pure._code_cache[a.pure[i][0]] = compile(f.read(), a.pure[i][1], 'exec')
            a.pure[i] = a.pure[i][0], x, a.pure[i][2]
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='myscript',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='myscript')
```
Ran my spec file 

`pyinstaller myscript.spec`

but still i am getting the same error

What is going wrong?

**Comment by jondy** [comment]
Could pyinstaller bundle your script successfully?
```
pyinstaller myscript.py
```

If it works, try to use pyarmor command `pack`
```
pyarmor pack myscript.py
```
Or pass hidden import by option `-e`
```
pyarmor -e " --hidden-import numpy" myscript.py
```
Note that myscript.py isn't obfuscated script, once it's obfuscated, all the dependent moudles/packages coundn't be found any more.

Generally if the python script could be bundle by PyInstaller, it could be packed by pyarmor, just pass the extra options of PyInstaller by `-e`
