### ISSUE TITLE
Unable to get signature of functions

### ISSUE THREAD

**Issue by joonis** [dashingsoft/pyarmor#1021]
Importing the following obfuscated module:

```
from inspect import signature

def foo(a, b, c):
    pass

s = signature(foo)
```

Results in the following error:

```
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mypackage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "</home/.../mypackage/__init__.py>", line 3, in <module>
  File "<mypackage.__init__>", line 6, in <module>
  File "/usr/lib/python3.8/inspect.py", line 3105, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib/python3.8/inspect.py", line 2854, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/lib/python3.8/inspect.py", line 2304, in _signature_from_callable
    return _signature_from_function(sigcls, obj,
  File "/usr/lib/python3.8/inspect.py", line 2167, in _signature_from_function
    annotation = annotations.get(name, _empty)
SystemError: Type does not define the tp_name field.
```

**Comment by joonis** [comment]
Same for `inspect.getfullargspec()`

**Comment by jondy** [comment]
Got it, I'll check it. If inspect uses some features changed by obfuscated scripts, it may not work.

**Comment by jondy** [comment]
Fixed in 8.0.20

**Comment by fanxing2022** [comment]
我也遇到了同样的问题 ，8.0.20预计什么时候发布

**Comment by joonis** [comment]
At least in 8.0.22 it works.
