### ISSUE TITLE
[BUG] PyArmor in a portable Virtual Machine. When the VM is moved, it needs to be re-registered.

### ISSUE THREAD

**Issue by fO-000** [dashingsoft/pyarmor#1022]
Hi @jondy,

I installed pyarmor in a VMware virtual machine, and the virtual machine was stored on a portable SSD so that I can keep the same working environment on different PCs.

But after I move the virtual machine, pyarmor will report an error about "built-in function fspath" while obfuscating a simple py script unless I re-register pyarmor. This is inconvenient and leads to an increasing number of license registrations.

Environment:

* Python 3.11.2
* pyarmor 8.0.19 (basic)
* pyarmor.cli.core 1.0.8
* OS: VMware guest  `Linux x 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux`

The simple py script is as follows:

```py
#!/usr/bin/env python

print('!!!')
```

After obfuscating it, I got the following:

```txt
$ pyarmor gen main.py
INFO     Python 3.11.2
INFO     Pyarmor 8.0.19 (basic), 00xxxx, TBD
INFO     search inputs ...
INFO     find script main.py
INFO     find 1 top resources
CRITICAL unknown error, please check pyarmor.error.log
ERROR    <built-in function fspath> returned a result with an exception set
```

The corresponding `pyarmor.error.log` is as follows:

```txt
32237 MainProcess 2023-03-27 16:47:44,649
RuntimeError: not machine id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/context.py", line 159, in save_token
    with open(self.license_token, 'wb') as f:
              ^^^^^^^^^^^^^^^^^^
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/context.py", line 276, in license_token
    return os.path.join(self.reg_path, '.license.token')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 82, in join
SystemError: <built-in function fspath> returned a result with an exception set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 572, in main
    main_entry(sys.argv[1:])
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 560, in main_entry
    args.func(ctx, args)
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 152, in cmd_gen
    builder.process(options, pack=args.pack)
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/generate.py", line 143, in process
    Pytransform3.pre_build(self.ctx)
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/core/__init__.py", line 62, in pre_build
    m = Pytransform3.init(ctx)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/core/__init__.py", line 42, in init
    m.init_ctx(ctx)
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/context.py", line 163, in clear_token
    if os.path.exists(self.license_token):
                      ^^^^^^^^^^^^^^^^^^
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/context.py", line 276, in license_token
    return os.path.join(self.reg_path, '.license.token')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 82, in join
SystemError: <built-in function fspath> returned a result with an exception set
```

**Comment by jondy** [comment]
Pyarmor will query Mac address or hard disk serial number as machine id. If they're changed, it will report error `not machine id`.

Is net interface changed when using VM in different PCs?

**Comment by fO-000** [comment]
When using VM on different PCs:

* The MAC address returned by `ip link show eth0` has changed.
* The `product_id` returned by `sudo cat /sys/class/dmi/id/product_uuid` has changed.
* The disk configuration GUID returned by `sudo lshw -class disk` has **NOT** changed.

And what is your method of obtaining the hard disk serial number?

**Comment by jondy** [comment]
Got it. It will be fixed in next release.

**Comment by jondy** [comment]
Fixed in 8.0.20

**Comment by fO-000** [comment]
After updating to 8.0.20, I can't register the license anymore. Got a "RuntimeError: Permission denied" in the corresponding `pyarmor.error.log`:

```txt
8148 MainProcess 2023-03-28 10:27:56,508
RuntimeError: Permission denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 572, in main
    main_entry(sys.argv[1:])
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 560, in main_entry
    args.func(ctx, args)
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 192, in cmd_reg
    getattr(regsvr, meth)(regfile, args.product)
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 290, in upgrade
    self.update_token()
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 110, in update_token
    Pytransform3._update_token(self.ctx)
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/core/__init__.py", line 72, in _update_token
    m = Pytransform3.init(ctx)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/core/__init__.py", line 42, in init
    m.init_ctx(ctx)
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/context.py", line 159, in save_token
    with open(self.license_token, 'wb') as f:
              ^^^^^^^^^^^^^^^^^^
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/context.py", line 276, in license_token
    return os.path.join(self.reg_path, '.license.token')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 82, in join
SystemError: <built-in function fspath> returned a result with an exception set
```

The register command is as follows:

```txt
$ pyarmor reg -u -p "TBD" assets/pyarmor-regcode-xxxx.txt
INFO     Python 3.11.2
INFO     Pyarmor 8.0.20 (trial), 000000, non-profits
INFO     prepare "assets/pyarmor-regcode-xxxx.txt"
INFO     query key file from server

You are about to upgrade old Pyarmor license to Pyarmor Basic
License for Pyarmor 8.0+

The original license no: pyarmor-vax-00xxxx

The upgraded license information will be

License Type    : pyarmor-old
License Owner   : xxx
Bind Product    : TBD


Are you sure to continue? (yes/no) yes
INFO     process upgrading file "assets/pyarmor-regcode-xxxx.txt"
INFO     old license no: pyarmor-vax-00xxxx
INFO     send upgrade request to server
INFO     update license token
CRITICAL unknown error, please check pyarmor.error.log
ERROR    <built-in function fspath> returned a result with an exception set
```

Maybe reading the disk configuration GUID requires root privileges? `sudo lshw -class disk`

**Comment by jondy** [comment]
Yes, it may require root privileges, it's a problem.

**Comment by jondy** [comment]
And do not use `-u` option once this code has been upgraded.

How about `sudo` to run pyarmor?

**Comment by fO-000** [comment]
Without `-u` option, I got an unknown license type old error:

```txt
$ pyarmor reg -p "TBD" assets/pyarmor-regcode-xxxx.txt
INFO     Python 3.11.2
INFO     Pyarmor 8.0.20 (trial), 000000, non-profits
INFO     prepare "assets/pyarmor-regcode-xxxx.txt"
INFO     query key file from server
CRITICAL unknown error, please check pyarmor.error.log
ERROR    unknown license type OLD
```

When pyarmor is installed in normal user mode `pip install pyarmor`, executing pyarmor with `sudo` will cause the system to not find it. Because `sudo` environments don't search for pyarmor in normal user environments:

```txt
$ sudo pyarmor reg -p "TBD" assets/pyarmor-regcode-xxxx.txt
sudo: pyarmor: command not found

$ sudo python -m pyarmor reg -p "TBD" assets/pyarmor-regcode-xxxx.txt
/usr/bin/python: No module named pyarmor
```

**Comment by jondy** [comment]
You should get `.zip` file if upgrading successfully, use it for later register. Do not use `.txt` to register Pyarmor.

**Comment by fO-000** [comment]
I have successfully upgraded before, where should I find this `.zip` file now?

**Comment by jondy** [comment]
I'll refine upgrading processing to download `.zip` file

**Comment by jondy** [comment]
Fixed in 8.0.21, also upgrading process is refined.

**Comment by fO-000** [comment]
Regardless of whether the `-u` option is used, the following error occurs:
```txt
$ pyarmor reg [-u] -p "TBD" assets/pyarmor-regcode-xxxx.txt
INFO     Python 3.11.2
INFO     Pyarmor 8.0.21 (trial), 000000, non-profits
INFO     prepare "assets/pyarmor-regcode-2329.txt"
INFO     query key file from server
CRITICAL unknown error, please check pyarmor.error.log
ERROR    product name has been set to "non-profits"
```

**Comment by jondy** [comment]
Well, I have reset `non-profits` to `TBD`

**Comment by fO-000** [comment]
The registration problem is solved, I got the `pyarmor-regfile-xxxx.zip` file.

However, I haven't tested the scenario of running pyarmor in portable virtual machines on different PCs yet. So I'll leave this issue open for now.

**Comment by fO-000** [comment]
Confirmed, issue resolved
