### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Bajirak** [dashingsoft/pyarmor#1041]
The following error occurred in the process of executing pyarmor register

Why did the error occur and what should I do to fix it?

**COMMAND**: 
`pyarmor-7 register pyarmor-regcode-1540.txt`

**ERROR**:
`INFO     PyArmor Version 8.0.21
INFO     Python 3.8.13
INFO     Read registration code file: pyarmor-regcode-1540.txt
INFO     Start to activate this code
Traceback (most recent call last):
  File "xxx/venv/lib/python3.8/site-packages/pyarmor/utils.py", line 1685, in _urlopen
    return urlopen(*args, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xxx/venv/bin/pyarmor-7", line 8, in <module>
    sys.exit(main_entry())
  File "xxx/venv/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1612, in main_entry
    main(sys.argv[1:])
  File "xxx/venv/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1604, in main
    args.func(args)
  File "xxx/venv/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 866, in _register
    filename = activate_regcode(ucode)
  File "xxx/venv/lib/python3.8/site-packages/pyarmor/register.py", line 74, in activate_regcode
    res = _urlopen(reg_url % ucode, timeout=6.0)
  File "xxx/venv/lib/python3.8/site-packages/pyarmor/utils.py", line 1689, in _urlopen
    return urlopen(*args, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable`

**ENVIROMENT**:
python version : 3.8
register-key : About 2years ago purchased

**Comment by jondy** [comment]
Refer to #985 and #980

And it's better there is clear title.

**Comment by Bajirak** [comment]
@jondy 

Thank you for your advice
