### ISSUE TITLE
[BUG] licence activation error

### ISSUE THREAD

**Issue by panregedit** [dashingsoft/pyarmor#1042]
Hi, just run into a problem when I try to update my licence from old version to 8.x. I have already read #983 and upgraded the package to the latest version (8.0.21), but the error still occured.

Here's the error and log.

![飞书20230329-154531](https://user-images.githubusercontent.com/5083153/228463049-48c3d91b-f059-418b-abf3-bdd5147b5bd6.jpg)

```
29934 MainProcess 2023-03-29 15:11:40,539
Traceback (most recent call last):
  File "/data/zl/miniconda3/envs/dev/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 576, in main
    main_entry(sys.argv[1:])
  File "/data/zl/miniconda3/envs/dev/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 564, in main_entry
    args.func(ctx, args)
  File "/data/zl/miniconda3/envs/dev/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 193, in cmd_reg
    return regsvr.register(regfile, args.product, upgrade=True)
  File "/data/zl/miniconda3/envs/dev/lib/python3.9/site-packages/pyarmor/cli/register.py", line 314, in register
    self.register_regfile(regfile)
  File "/data/zl/miniconda3/envs/dev/lib/python3.9/site-packages/pyarmor/cli/register.py", line 156, in register_regfile
    self.update_token()
  File "/data/zl/miniconda3/envs/dev/lib/python3.9/site-packages/pyarmor/cli/register.py", line 113, in update_token
    Pytransform3._update_token(self.ctx)
  File "/data/zl/miniconda3/envs/dev/lib/python3.9/site-packages/pyarmor/cli/core/__init__.py", line 72, in _update_token
    m = Pytransform3.init(ctx)
  File "/data/zl/miniconda3/envs/dev/lib/python3.9/site-packages/pyarmor/cli/core/__init__.py", line 42, in init
    m.init_ctx(ctx)
RuntimeError: request license token faild (3)
```
Tried both on ubuntu and centos.

**Comment by jondy** [comment]
Try it in 8.0.22

There are big changes in Pyarmor 8.0, please check this #980 

Do not upgrade to 8.0 before understand what're changed.
