### ISSUE TITLE
View unencrypted source for debugging

### ISSUE THREAD

**Issue by AlecHaring** [dashingsoft/pyarmor#1053]
So, I'm testing the different obfuscation methods (mix-str, assert-call, etc.), but find it hard to see the specific modifications made by each method.

For instance, [in the documentation](https://pyarmor.readthedocs.io/en/latest/tutorial/obfuscation.html?highlight=mix-str#more-options-to-protect-script), there is an example demonstrating how
```shell
pyarmor gen --enable-jit --mix-str --assert-call foo.py
```
transforms
```python
data = "abcxyz"

def fib(n):
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b

if __name__ == '__main__':
    fib(n)
```
into
```python
data = __mix_str__(b"******")

def fib(n):
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b

if __name__ == '__main__':
    __assert_call__(fib)(n)
```
This example is quite helpful, but it would be even more beneficial if users could visualize changes like this in their scripts while testing and debugging Pyarmor's obfuscation.

Would it be possible to add an option, such as `--debug=disable-encrypt`, that would make the output script resemble the example above instead of like this?
```python
from pyarmor_runtime import __pyarmor__
__pyarmor__(__name__, __file__, b'\x28\x83\x20\x58....')
```

**Comment by jondy** [comment]
Thank you advice, good idea. I have designed this feature, it will be implemented later.

My idea is to add an option something like `--trace`, then pyarmor will generate a log to record which string is encrypted, which function is converted to bcc etc. 

For example, if `--trace mix-str`, a log file `pyarmor-mix-str.log` is generated, each line `mod name:lineno:str`
```
foo:1:"abcxyz"
...
```

if `--trace assert-call`, a log file `pyarmor-assert-call.log` is generated, each line `mod name:lineno:function`
```
foo:10:fib
```

**Comment by AlecHaring** [comment]
I love that idea. It's a perfect balance

**Comment by jondy** [comment]
It's partly implemented  in dev version `8.1.dev1`

Check `--enable-rft` result by this way:
```
pyarmor cfg trace_rft=1
pyarmor gen --enable-rft foo.py
```

It will generate the result script in the `.pyarmor/rft/foo.py`

Check `--mix-str` and `--assert-call` by this way
```
pyarmor cfg enable_trace=1
pyarmor gen --mix-str --assert-call --assert-import foo.py
```

It will generate a log file `.pyarmor/pyarmor.trace.log` to log protected str/function/module

**Comment by AlecHaring** [comment]
Yes! Exactly what I had envisioned. You are amazing @jondy!

**Comment by AlecHaring** [comment]
If a python script has the following string in it: `"✓"` while `trace_rft=1`, the following error will be thrown while obfuscating:
```
CRITICAL unknown error, please check pyarmor.error.log
ERROR    'charmap' codec can't encode character '\u2713' in position 1600: character maps to <undefined>
```

**pyarmor.error.log**
```
14184 MainProcess 2023-04-04 18:48:54,440
Traceback (most recent call last):
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\generate.py", line 158, in process
    self._obfuscate_scripts()
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\generate.py", line 120, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\core\__init__.py", line 48, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 760, in generate_obfuscated_script
  File "<maker>", line 26, in process
  File "<maker>", line 550, in process
  File "<maker>", line 550, in <listcomp>
  File "<rftmaker>", line 27, in process
  File "<rftmaker>", line 376, in process
  File "C:\Users\alec\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2713' in position 1600: character maps to <undefined>
```

**Comment by jondy** [comment]
Got it, thanks. There is no encoding when save unparsed file.
