### ISSUE TITLE
[BUG] `RuntimeError: co_info inner error` when obfuscating scripts

### ISSUE THREAD

**Issue by ddi98** [dashingsoft/pyarmor#1065]
hi @jondy , i tried with the following command:
pyarmor gen -r C:/Users/Giuseppe/Dropbox/PROGETTI_PYCHARM/FormulariTools/app.py C:/Users/Giuseppe/Dropbox/PROGETTI_PYCHARM/FormulariTools

but the following error is returned in the pyarmor.error.log file:
18088 MainProcess 2023-04-01 11:26:50,522 Traceback (most recent call last): File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 629, in main main_entry(sys.argv[1:]) File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 617, in main_entry args.func(ctx, args) File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen builder.process(options, pack=args.pack) File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\generate.py", line 153, in process self._obfuscate_scripts() File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\generate.py", line 118, in _obfuscate_scripts code = Pytransform3.generate_obfuscated_script(self.ctx, r) File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\core\__init__.py", line 48, in generate_obfuscated_script return m.generate_obfuscated_script(ctx, res) File "<maker>", line 719, in generate_obfuscated_script File "<maker>", line 522, in process File "<maker>", line 522, in <listcomp> File "<maker>", line 1812, in handle File "<maker>", line 1807, in visit File "<maker>", line 1804, in visit File "<maker>", line 1771, in patch_co_object File "<maker>", line 1756, in _check_co_info RuntimeError: co_info inner error

**Comment by jondy** [comment]
This is some code can't handled by pyarmor v8.

Check the log, it will show last handle script, a quick workaround is ignore this script, do not obfuscate it, only obfuscate all the others, the copy plain script to final output path.

In next version, when this error occurs, pyarmor will report which script and function results in this problem.

**Comment by ddi98** [comment]
thanks for the answer, how do I set the path of a script to ignore ?  and in this case which script is it?

**Comment by jondy** [comment]
Upgrade Pyarmor to `8.1.dev2`, exclude a script `mypkg.name.py` like this
```
pyarmor gen --exclude mypkg.name.py mypkg/
```

**Comment by ddi98** [comment]
16624 MainProcess 2023-04-03 14:11:22,835
Traceback (most recent call last):
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\generate.py", line 145, in process
    Pytransform3.pre_build(self.ctx)
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\core\__init__.py", line 63, in pre_build
    return m.pre_build(ctx)
  File "<maker>", line 737, in pre_build
  File "<maker>", line 627, in build
  File "<maker>", line 3054, in process
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\resource.py", line 107, in reparse
    self.mtree = ast.parse(''.join(lines), self.frozenname, 'exec')
  File "C:\Python37\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<frozen FormulariTools..idea..gitignore>", line 2
    /shelf/
    ^
SyntaxError: invalid syntax

**Comment by ddi98** [comment]
you don't provide private support even for a fee?

**Comment by jondy** [comment]
No. I'm busy on building new platforms, full test and bug fix for Pyarmor 8.
