### ISSUE TITLE
[BUG] Class method names not being renamed at reference calls

### ISSUE THREAD

**Issue by AlecHaring** [dashingsoft/pyarmor#1069]
RTF mode renames the class methods (as expected), but the references aren't being renamed, causing `AttributeError` during runtime.

**Executed command:** `pyarmor -d gen --enable-rft .\pyarmor_test\`

**main.py**
```python
from pyarmor_test.class_test import MainClass, SubClass


def testing():
    MainClass().test()
    SubClass().test()


if __name__ == "__main__":
    testing()
```

**class_test.py**
```python
class MainClass:
    def __init__(self):
        pass

    def test(self):
        print("MainClass.test")


class SubClass(MainClass):
    def __init__(self):
        super().__init__()

    def test(self):
        print("SubClass.test")

```

Error during runtime:
```
AttributeError: 'pyarmor__1' object has no attribute 'test'
```

This is what the RTF output of the `testing` method looks like (thanks #1053):
```python
def pyarmor__6():
    pyarmor__1().test()
    pyarmor__4().test()
```

**Comment by jondy** [comment]
Got it, thanks. I'll fix it.

**Comment by jondy** [comment]
Fixed in dev version `8.1.dev2`

**Comment by AlecHaring** [comment]
The reported error is fixed, but now I'm getting this error during runtime, same files:

```
MainClass.test
Traceback (most recent call last):
  File "C:\Users\alecs\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\alecs\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<frozen __main__>", line 3, in <module>
  File "<frozen pyarmor_test.main>", line 50, in <module>
  File "<frozen pyarmor_test.main>", line 46, in pyarmor__16
  File "<frozen pyarmor_test.class_test>", line 11, in __init__
RuntimeError: super(): __class__ cell not found
```

**Comment by jondy** [comment]
Reproduced, thanks.

**Comment by jondy** [comment]
It seems `super` can't be renamed. In next release `rft mode` doesn't touch `super`.

**Comment by jondy** [comment]
Fixed `super` issue in `8.1.dev3`

**Comment by jondy** [comment]
Fixed super issue in `8.1.dev4`
