### ISSUE TITLE
[BUG] RFT import renaming not being handled correctly

### ISSUE THREAD

**Issue by AlecHaring** [dashingsoft/pyarmor#1070]
RFT mode isn't renaming external module imports properly when it's referenced in 2 different files.

**Executed command:** `pyarmor -d gen --enable-rft .\pyarmor_test\`

**pyarmor_test/main.py**
```python
import traceback

from pyarmor_test.exception import dummy_exception_external


def dummy_exception():
    try:
        raise Exception("Exception from dummy_exception")
    except:
        traceback.print_exc()


def testing():
    dummy_exception()
    dummy_exception_external()


if __name__ == "__main__":
    testing()
```

**pyarmor_test/exception.py**
```python
import traceback


def dummy_exception_external():
    try:
        inner_exception_external()
    except:
        traceback.print_exc()


def inner_exception_external():
    raise Exception("Exception from inner_exception_external")
```

Exception during runtime:
```
  File "<frozen __main__>", line 3, in <module>
  File "<frozen pyarmor_test.main>", line 19, in <module>
  File "<frozen pyarmor_test.main>", line 14, in pyarmor__7
  File "<frozen pyarmor_test.main>", line 10, in pyarmor__6
NameError: name 'pyarmor__1' is not defined
```

It's renaming `traceback` in `dummy_exception` to `pyarmor__1`, but `pyarmor__1` is not imported

**Comment by jondy** [comment]
Reproduced, thank you very much.

**Comment by jondy** [comment]
Fixed in dev version `8.1.dev2`

**Comment by jondy** [comment]
Fixed in dev version `8.1.dev2`

**Comment by AlecHaring** [comment]
Same setup and command is now causing the following error:
```
13344 MainProcess 2023-04-02 20:50:30,419
Traceback (most recent call last):
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\generate.py", line 141, in process
    finder.process(pack=pack)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\generate.py", line 57, in process
    self.prepare(self.ctx.input_paths)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\generate.py", line 52, in prepare
    res.rebuild(**options)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\resource.py", line 180, in rebuild
    self.resfiles = [x for x in [
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\resource.py", line 182, in <listcomp>
    else FileResource(name, parent=self) if in_filter(path, name)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\resource.py", line 167, in in_filter
    return not ex_filter(s) and (
TypeError: ex_filter() missing 1 required positional argument: 'name'
```

**Comment by jondy** [comment]
It seems `C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\resource.py` is not the latest version.

If you install `pyarmor/cli/resource.py` from GitHub, pull it again. I just push the latest now.

**Comment by AlecHaring** [comment]
Yep, you're right. Not sure how that happened. I pip installed from GitHub right before I got the error. The problem's fixed :)
