### ISSUE TITLE
加密脚本，出现ERROR    name 'Component' is not defined错误

### ISSUE THREAD

**Issue by wsxhd7881** [dashingsoft/pyarmor#1080]
D:\Atest>"D:\Program Files\Python\Python37\Scripts\pyarmor" gen --expired "2023-03-30" D:\Atest\test.py
INFO     Python 3.7.9
INFO     Pyarmor 8.0.26 (basic), 004001, XXXX
INFO     search inputs ...
INFO     find script D:\Atest\test.py
INFO     find 1 top resources
CRITICAL unknown error, please check pyarmor.error.log
ERROR    name 'Component' is not defined

6384 MainProcess 2023-04-04 09:53:00,419
Traceback (most recent call last):
  File "d:\program files\python\python37\lib\site-packages\pyarmor\cli\__main__.py", line 629, in main
    main_entry(sys.argv[1:])
  File "d:\program files\python\python37\lib\site-packages\pyarmor\cli\__main__.py", line 617, in main_entry
    args.func(ctx, args)
  File "d:\program files\python\python37\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "d:\program files\python\python37\lib\site-packages\pyarmor\cli\generate.py", line 143, in process
    Pytransform3.pre_build(self.ctx)
  File "d:\program files\python\python37\lib\site-packages\pyarmor\cli\core\__init__.py", line 62, in pre_build
    m = Pytransform3.init(ctx)
  File "d:\program files\python\python37\lib\site-packages\pyarmor\cli\core\__init__.py", line 39, in init
    from . import pytransform3 as m
  File "<maker>", line 476, in <module>
NameError: name 'Component' is not defined

**Comment by jondy** [comment]
升级到 8.1.dev3 看看

**Comment by jondy** [comment]
请升级到 `8.1.dev4` 或者更新一下 pycore.cli.core

**Comment by wsxhd7881** [comment]
升级到8.1.dev4，没有问题了
D:\Atest>"D:\Program Files\Python\Python37\Scripts\pyarmor" gen --expired "2023-03-30" D:\Atest\test.py
INFO     Python 3.7.9
INFO     Pyarmor 8.1.0 (basic), 004001, XXXX
INFO     search inputs ...
INFO     find script D:\Atest\test.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write dist\pyarmor_runtime_004001\pyarmor_runtime.pyd
INFO     patch runtime file
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "test"
INFO     obfuscating file test.py
INFO     write dist\test.py
INFO     obfuscate scripts OK

D:\Atest>
D:\Atest>"D:\Program Files\Python\Python37\python37.exe" D:\Atest\test.py
hello world!

D:\Atest>
