### ISSUE TITLE
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wsxhd7881** [dashingsoft/pyarmor#1084]
pyarmor  8.1.dev4 版本
在windwos下使用pyarmor-regcode-4001.txt注册生成pyarmor-regfile-4001.zip。
将pyarmor-regfile-4001.zip文件拷贝到linux下进行注册，出现错误：

[user@xc pyarmor]$ ll
total 12
-rw-rw-r--. 1 user user 1186 Apr  4 16:35 pyarmor.error.log
-rw-rw-r--. 1 user user 4287 Apr  4 16:31 pyarmor-regfile-4001.zip
[user@xc pyarmor]$ 
[user@xc pyarmor]$ pyarmor -v
Pyarmor 8.1.0 (trial), 000000, non-profits

License Type    : pyarmor-trial
License No.     : pyarmor-vax-000000
License To      : 

BCC Mode        : No
RFT Mode        : No

Notes
* Internet connection is required to verify Pyarmor license
* Trial license can't obfuscate big script and mix str

[user@xc pyarmor]$ 
[user@xc pyarmor]$ pyarmor reg pyarmor-regfile-4001.zip 
INFO     Python 3.7.15
INFO     Pyarmor 8.1.0 (trial), 000000, non-profits
INFO     register "pyarmor-regfile-4001.zip"
INFO     update license token
CRITICAL unknown error, please check pyarmor.error.log
ERROR    libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
[user@xc pyarmor]$ 
[user@xc pyarmor]$ 

error.log
118971 MainProcess 2023-04-04 16:36:18,483
Traceback (most recent call last):
  File "/u02/usr/python3/python3.7/lib/python3.7/site-packages/pyarmor/cli/__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "/u02/usr/python3/python3.7/lib/python3.7/site-packages/pyarmor/cli/__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "/u02/usr/python3/python3.7/lib/python3.7/site-packages/pyarmor/cli/__main__.py", line 224, in cmd_reg
    reg.register_regfile(regfile)
  File "/u02/usr/python3/python3.7/lib/python3.7/site-packages/pyarmor/cli/register.py", line 156, in register_regfile
    self.update_token()
  File "/u02/usr/python3/python3.7/lib/python3.7/site-packages/pyarmor/cli/register.py", line 113, in update_token
    Pytransform3._update_token(self.ctx)
  File "/u02/usr/python3/python3.7/lib/python3.7/site-packages/pyarmor/cli/core/__init__.py", line 72, in _update_token
    m = Pytransform3.init(ctx)
  File "/u02/usr/python3/python3.7/lib/python3.7/site-packages/pyarmor/cli/core/__init__.py", line 39, in init
    from . import pytransform3 as m
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

**Comment by jondy** [comment]
这个不是Pyarmor 的 bug，请百度搜索错误信息找解决方案
