### ISSUE TITLE
AttributeError: 'int' object has no attribute 'lower' (pyarmor 8.1.dev4)

### ISSUE THREAD

**Issue by ddi98** [dashingsoft/pyarmor#1093]
hi, when you run this command: 
pyarmor gen -r --enable-jit --mix-str --assert-call --enable-rft C:/Users/Giuseppe/Dropbox/PROGETTI_PYCHARM/FormulariTools --exclude C:/Users/Giuseppe/Dropbox/PROGETTI_PYCHARM/FormulariTools/migrations --exclude C:/Users/Giuseppe/Dropbox/PROGETTI_PYCHARM/FormulariTools/poppler --exclude C:/Users/Giuseppe/Dropbox/PROGETTI_PYCHARM/FormulariTools/pdfjs --exclude C:/Users/Giuseppe/Dropbox/PROGETTI_PYCHARM/FormulariTools/static --exclude C:/Users/Giuseppe/Dropbox/PROGETTI_PYCHARM/FormulariTools/venv

i get the following error:

3112 MainProcess 2023-04-06 16:06:21,709
Traceback (most recent call last):
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\generate.py", line 158, in process
    self._obfuscate_scripts()
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\generate.py", line 120, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\core\__init__.py", line 48, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 760, in generate_obfuscated_script
  File "<maker>", line 26, in process
  File "<maker>", line 563, in process
  File "<maker>", line 563, in <listcomp>
  File "<maker>", line 26, in process
  File "<maker>", line 1838, in handle
  File "<maker>", line 1833, in visit
  File "<maker>", line 1834, in visit
  File "<maker>", line 53, in __getattr__
AttributeError: 'int' object has no attribute 'lower'

**Comment by jondy** [comment]
Fixed in `8.1.dev5`

**Comment by ddi98** [comment]
again error with the same command:

24040 MainProcess 2023-04-06 17:17:40,287
Traceback (most recent call last):
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\generate.py", line 145, in process
    Pytransform3.pre_build(self.ctx)
  File "C:\Users\Giuseppe\Dropbox\PROGETTI_PYCHARM\FormulariTools\venv\lib\site-packages\pyarmor\cli\core\__init__.py", line 63, in pre_build
    return m.pre_build(ctx)
  File "<maker>", line 767, in pre_build
  File "<maker>", line 657, in build
  File "<maker>", line 3257, in process
  File "<maker>", line 2778, in rebuild
  File "<maker>", line 2947, in _get_module_types
  File "<maker>", line 2937, in visit
  File "<maker>", line 2937, in visit
  File "<maker>", line 2937, in visit
  [Previous line repeated 1 more times]
  File "<maker>", line 2870, in visit
  File "<maker>", line 2787, in guess_type
AttributeError: 'Str' object has no attribute 'value'

**Comment by jondy** [comment]
Fixed in `8.1.dev6`
