### ISSUE TITLE
[BUG]  `'Subscript' object has no attribute 'attr'`

### ISSUE THREAD

**Issue by AlecHaring** [dashingsoft/pyarmor#1099]
**Executed command:** `pyarmor -d gen --enable-rft .\pyarmor_test\`

**main.py**
```python
class TestDictWrapper:
    def __init__(self):
        self.test_dict = {'test': {}}

    def get_test(self, method: str, data: str):
        return self.test_dict[method].get(data)


def testing():
    wrapper = TestDictWrapper()
    wrapper.get_test("test", "test123")


if __name__ == "__main__":
    testing()

```

**pyarmor.error.log:**
```
11684 MainProcess 2023-04-06 21:38:36,764
Traceback (most recent call last):
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\generate.py", line 155, in process
    self._obfuscate_scripts()
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\generate.py", line 120, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\core\__init__.py", line 48, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 749, in generate_obfuscated_script
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__init__.py", line 10, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 512, in process
  File "<maker>", line 512, in <listcomp>
  File "<rftmaker>", line 16, in process
  File "<rftmaker>", line 528, in process
  File "<rftmaker>", line 399, in _refactor
  File "<rftmaker>", line 390, in visit
  File "<rftmaker>", line 390, in visit
  File "<rftmaker>", line 390, in visit
  [Previous line repeated 2 more times]
  File "<rftmaker>", line 382, in visit
  File "<rftmaker>", line 298, in _rename_attrnode
  File "<rftmaker>", line 284, in rename_name_node
  File "<rftmaker>", line 224, in _rename_attrs
AttributeError: 'Subscript' object has no attribute 'attr'
```

**Comment by jondy** [comment]
Got it, thanks.

**Comment by jondy** [comment]
Fixed in `8.1.dev7`
