### ISSUE TITLE
[BUG] MacOS bug obfustcating script on 8.1.dev4

### ISSUE THREAD

**Issue by JFuqX** [dashingsoft/pyarmor#1113]
The command I use:

### `sudo pyarmor gen -O dist/obfuscated /Users/test/Desktop/TEST/srcs/__main__.py`

The error log I get:
```
29268 MainProcess 2023-04-08 14:26:19,150
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/generate.py", line 148, in process
    Pytransform3.pre_build(self.ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/core/__init__.py", line 62, in pre_build
    m = Pytransform3.init(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/core/__init__.py", line 39, in init
    from . import pytransform3 as m
  File "<maker>", line 13, in <module>
ImportError: cannot import name 'resoptions' from 'pyarmor.cli' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__init__.py)

```

On version 8.0.26 I get the following error:

```
30195 MainProcess 2023-04-08 14:39:32,081
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 629, in main
    main_entry(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 617, in main_entry
    args.func(ctx, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/generate.py", line 149, in process
    self.generate_runtime_package(self.ctx.outputs[0])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/generate.py", line 88, in generate_runtime_package
    Pytransform3.generate_runtime_package(self.ctx, output)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/core/__init__.py", line 53, in generate_runtime_package
    return m.generate_runtime_package(ctx, output, platforms)
  File "<maker>", line 720, in generate_runtime_package
  File "<maker>", line 438, in build
  File "<maker>", line 302, in patch_extension
TypeError: string argument without an encoding
```

**Comment by AlecHaring** [comment]
Try `8.1.dev6` or `8.1.dev7`

**Comment by jondy** [comment]
How about `8.1.dev9`?

**Comment by JFuqX** [comment]
Now I get this on windows and macOS :C

```
INFO     obfuscating file .DS_Store
CRITICAL unknown error, please check pyarmor.error.log
ERROR    'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
```

**Comment by jondy** [comment]
Please upgrade to `8.1.0`
