### ISSUE TITLE
[BUG] `KeyError: 'rft'`

### ISSUE THREAD

**Issue by AlecHaring** [dashingsoft/pyarmor#1115]
**Executed command:** `pyarmor -d gen --enable-rft .\pyarmor_test\`

**Version:** `8.1.dev7`

**pyarmor.error.log**
```
19688 MainProcess 2023-04-08 13:44:08,980
Traceback (most recent call last):
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\generate.py", line 145, in process
    Pytransform3.pre_build(self.ctx)
  File "C:\Users\alec\Desktop\PythonProjects\pyarmor-test\venv\lib\site-packages\pyarmor\cli\core\__init__.py", line 63, in pre_build
    return m.pre_build(ctx)
  File "<maker>", line 779, in pre_build
  File "<maker>", line 664, in build
  File "<maker>", line 634, in init_variable_types
  File "C:\Users\alec\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'rft'
```

**Comment by jondy** [comment]
Fixed it in `8.1.dev9`
