### ISSUE TITLE
[BUG] Error when run scripts with -- bcc & spp. 

### ISSUE THREAD

**Issue by crasyjoel** [dashingsoft/pyarmor#1117]
**After obfuscate scripts via bcc as well as spp(This also happens in 7.7.4), it runs with such errors:**
Traceback (most recent call last): 
  File "<frozen packs.Project_Info.Controller.Controller_Project_Info_02>", line 316, in __next 
  File "<frozen packs.Project_Info.Controller.Controller_Project_Info_02>", line 169, in save_data_to_database
  File "<frozen packs.Project_Info.Controller.Controller_Project_Info_02>", line 335, in save_check
  File "C:\Users\xx\Documents\ita_final_v1_20230105\venv\lib\site-packages\pandas\core\generic.py", line 1538, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last): 
  File "<frozen packs.Project_Info.Controller.Controller_Project_Info_02>", line 316, in __next 
  File "<frozen packs.Project_Info.Controller.Controller_Project_Info_02>", line 169, in save_data_to_database
  File "<frozen packs.Project_Info.Controller.Controller_Project_Info_02>", line 335, in save_check
  File "C:\Users\xx\Documents\ita_final_v1_20230105\venv\lib\site-packages\pandas\core\generic.py", line 1538, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Here's the source code of Controller_Project_Info_02.py:**
```
# coding:utf-8
import sys

import pandas as pd
from PySide2.QtCore import Signal as pyqtSignal, Qt, QCoreApplication
from PySide2.QtWidgets import QApplication, QTableWidgetItem, QMessageBox, QComboBox

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

import IT_Task.Controller.Controller_IT_Task_info
import IT_Task.View.View_Task_Menu_Bar
import IT_Understanding.Controller.Controller_IT_Understanding_01_project_info
from IT_Task.Model.Model_project_info_Mapping import Task_crud_database
from Project_Info.Model.Model_Project_Info_02 import M_Project_Info_02
from Project_Info.Model.Model_Project_Info_Mapping import Project_Info_crud_database
from Project_Info.View.View_Project_Info_02 import v_Project_Info_02


pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)


class c_Project_Info_02(v_Project_Info_02):
    signal_str = pyqtSignal(list)

    def __init__(self, parent=None):
        super(c_Project_Info_02, self).__init__(parent)
        self.engine_Project_Info = create_engine('sqlite:///Config/Project_Info.db', echo=True)
        self.Session_Project_Info = sessionmaker(bind=self.engine_Project_Info)
        self.session_Project_Info = self.Session_Project_Info()
        self.Employee_Info = Project_Info_crud_database('Employee_Info_Database')
        self.list_to_delete = list()
        self.tabel1_order = ['员工编号', '姓名', '级别', '项目角色', '是否关闭']
        self.Role_Info = Project_Info_crud_database('Role_Info_Database')
        self.role_list = self.get_role_list()
        self.level_list = ['A1', 'A2', 'B1', 'B2', 'B3', 'C', 'D', 'E', 'P']
        self.__init_tabel1()
        self.__init_btns()
        self.pushButton_3.setVisible(False)

    def get_role_list(self):
        role_df = self.Role_Info.get()
        return role_df['role_name'].to_list()

    def __init_tabel1(self):
        self.tabel1_df = self.get_tabel1_df()
        tabel1_row_count = len(self.tabel1_df)
        tabel1_col_count = len(self.tabel1_df.columns)
        self.tabel1.setRowCount(tabel1_row_count)
        self.tabel1.setColumnCount(tabel1_col_count)
        self.tabel1.setMinimumHeight(300)
        # self.tabel1.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)
        self.tabel1.setMinimumWidth(800)
        # self.tabel1.verticalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)
        self.tabel1.setHorizontalHeaderLabels(self.tabel1_order)
        self.__collect_data_to_dataTable_para(tabel1_row_count, tabel1_col_count, self.tabel1_df, self.tabel1, [])
        for i in range(tabel1_row_count):
            self.combox_col_level = QComboBox()
            self.combox_col_level.addItems(self.level_list)
            self.combox_col_level.setCurrentText(self.tabel1_df.iloc[i, 2])
            self.tabel1.setCellWidget(i, 2, self.combox_col_level)
            self.combox_col_role = QComboBox()
            self.combox_col_role.addItems(self.role_list)
            self.combox_col_role.setCurrentText(self.tabel1_df.iloc[i, 3])
            self.tabel1.setCellWidget(i, 3, self.combox_col_role)
            self.combox_col_status = QComboBox()
            self.combox_col_status.addItems(['是', '否'])
            self.combox_col_status.setCurrentText(self.tabel1_df.iloc[i, 4])
            self.tabel1.setCellWidget(i, 4, self.combox_col_status)

    def get_tabel1_df(self):
        df_Employee_Info = self.Employee_Info.get()
        row_no = len(df_Employee_Info)
        # permission_list = [str()] * row_no
        # df_Employee_Info.insert(4, 'permission', '')
        return df_Employee_Info

    def show_sys_select_dialog(self, row_no, col_no):
        for i in self.tabel1.selectedItems():
            if i.column() == 13:
                list_system = self.comboCheckBox_list
                # self.child_sys = View_ITAC_RAFITS_child_01(list_system)
                # self.child_sys.signal_str.connect(self.get_system_to_tablewidget)
                # self.child_sys.show()

    def __init_btns(self):
        self.btn_add.pressed.connect(self.add_data_table1)
        self.btn_del.pressed.connect(self.del_data_table1)
        self.pushButton_1.pressed.connect(lambda: self.save_data_to_database(True))
        self.pushButton_2.pressed.connect(self.__exit)
        self.pushButton_3.pressed.connect(self.__previous)
        self.pushButton_4.pressed.connect(self.__next)

    def add_data_table1(self):
        row_no = self.tabel1.rowCount()
        self.tabel1.insertRow(row_no)
        for i in range(self.tabel1.columnCount()):
            value_1 = QTableWidgetItem('')
            self.tabel1.setItem(row_no, i, value_1)
        self.tabel1.scrollToBottom()
        self.combox_col_level = QComboBox()
        self.combox_col_level.addItems(self.level_list)
        self.tabel1.setCellWidget(row_no, 2, self.combox_col_level)
        self.combox_col_role = QComboBox()
        self.combox_col_role.addItems(self.role_list)
        self.tabel1.setCellWidget(row_no, 3, self.combox_col_role)
        self.combox_col_status = QComboBox()
        self.combox_col_status.addItems(['是', '否'])
        self.tabel1.setCellWidget(row_no, 4, self.combox_col_status)

    def del_data_table1(self):
        del_row_no = self.tabel1.currentRow()
        if del_row_no >= 0:
            self.__del_data(self.tabel1)

    def __del_data(self, tableWidget):
        currentRow = tableWidget.currentRow()
        if tableWidget.rowCount() == 0 or currentRow < 0:
            return
        if tableWidget.rowCount() > 0:
            # self.tabel1_df.iloc[currentRow,14]='1'
            # self.tabel1.item(currentRow,14).setText('1')
            number = self.tabel1.item(currentRow, 0).text()
            self.list_to_delete.append(number)
            tableWidget.removeRow(currentRow)

    def ban_edit(self, row_no, control_nature, first_flag):
        ban_edit_col_list1 = list()
        edit_col_list1 = list()
        if str(first_flag) == '1':
            ban_edit_col_list1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11]
        elif str(first_flag) == '0':
            if control_nature == 'Manual':
                self.tabel1.removeCellWidget(row_no, 9)
                self.tabel1.item(row_no, 9).setText('N/A')
                self.tabel1.removeCellWidget(row_no, 10)
                self.tabel1.item(row_no, 10).setText('N/A')
                self.tabel1.removeCellWidget(row_no, 13)
                self.tabel1.item(row_no, 13).setText('N/A')
                ban_edit_col_list1 = [9, 10, 13]
            elif control_nature == 'Automated':
                edit_col_list1 = [9, 10, 13]
                if len(edit_col_list1) >= 0:
                    for j in edit_col_list1:
                        self.tabel1.item(row_no, j).setFlags(Qt.ItemFlag(63))
                        # self.tabel1.item(row_no, j).setFlags(Qt.ItemIsEnabled | Qt.ItemIsEditable)
                self.combox_col_9 = QComboBox()
                self.combox_col_9.addItems(
                    ['System access controls, including enforcing segregation of duties', 'Edit checks',
                     'Configuration of system generated reports or other data outputs', 'System configuration controls',
                     'System calculations controls', 'Interface controls'])
                self.tabel1.setCellWidget(row_no, 9, self.combox_col_9)
                self.combox_col_10 = QComboBox()
                self.combox_col_10.addItems(['Coded', 'Configured'])
                self.tabel1.setCellWidget(row_no, 10, self.combox_col_10)
                self.tabel1.item(row_no, 13).setText('')
        if len(ban_edit_col_list1) >= 0:
            for i in ban_edit_col_list1:
                self.tabel1.item(row_no, i).setFlags(Qt.ItemFlag(0))
                self.tabel1.item(row_no, i).setFlags(Qt.ItemIsEnabled)

    def save_data_to_database(self, success_QMessageBox_show_bool):
        if self.save_check() is True:
            save_df = self.__collect_tableWidget_DataFrame(self.tabel1, self.tabel1_order)
            if M_Project_Info_02().database_changed(save_df) is True and M_Project_Info_02().task_completed() is True:
                reply = QMessageBox.question(self, '提示', '项目成员变更将导致任务重新分配，是否继续？', QMessageBox.Yes,
                                             QMessageBox.No)
                if reply == QMessageBox.Yes:
                    M_Project_Info_02().delete_task_data(save_df)
                    M_Project_Info_02().save_data(save_df)
                    M_Project_Info_02().delete_data(self.list_to_delete)
                    M_Project_Info_02().update_member_info_database(save_df)
                    self.__init_tabel1()
                    self.win02 = IT_Task.Controller.Controller_IT_Task_info.c_IT_Task_info()
                    self.win02.signal_str.connect(self.to_show)
                    self.win02.show()
                    self.hide()
                if reply == QMessageBox.No:
                    return False
            else:
                M_Project_Info_02().save_data(save_df)
                M_Project_Info_02().delete_data(self.list_to_delete)
                M_Project_Info_02().update_member_info_database(save_df)
                self.__init_tabel1()
                if success_QMessageBox_show_bool:
                    QMessageBox.question(self, '提示', '项目成员创建成功', QMessageBox.Yes)
                return True
        else:
            return False

    def __collect_data_to_dataTable_para(self, df_row_count, df_column_count, Dataframe, tableWidget,
                                         list_hide):  # 读取数据逻辑
        for i in range(df_row_count):
            for j in range(df_column_count):
                if pd.isna(Dataframe.iloc[i, j]):
                    value_1 = QTableWidgetItem(str())
                else:
                    try:
                        value_1 = QTableWidgetItem(str(Dataframe.iloc[i, j]))
                    except Exception:
                        continue
                    tableWidget.setItem(i, j, value_1)
        for hide_ele in list_hide:
            tableWidget.hideColumn(hide_ele)

    def __collect_tableWidget_DataFrame(self, tableWidget, cols_name):
        list_result = []
        rowCount = tableWidget.rowCount()
        columnCount = tableWidget.columnCount()
        for row in range(rowCount):
            list_ele_row = []
            for column in range(columnCount):
                try:
                    if isinstance(tableWidget.cellWidget(row, column), QComboBox):
                        try:
                            tmp = tableWidget.cellWidget(row, column).currentText()
                        except Exception:
                            tmp = tableWidget.item(row, column).text()
                    else:
                        tmp = tableWidget.item(row, column).text()
                except Exception:
                    tmp = str()

                list_ele_row.append(tmp)

            list_result.append(list_ele_row)
        df = pd.DataFrame(list_result, columns=cols_name)
        return df


    def __exit(self):
        if self.tabel1.rowCount() <= 0:  # 如果Employee_Info表为空
            self.win = IT_Task.View.View_Task_Menu_Bar.v_Task_Menu()
            self.win.show()
            self.hide()
            # self.destroy()
        else:
            reply_01 = QMessageBox.question(self, '提示', '关闭窗口前是否保存当前内容？',
                                            QMessageBox.Yes | QMessageBox.No | QMessageBox.Cancel, QMessageBox.Yes)
            if reply_01 == QMessageBox.Yes:
                if self.save_data_to_database(False) == True:
                    pass
                else:
                    pass
            elif reply_01 == QMessageBox.No:
                pass
            else:
                return 1
            self.win = IT_Task.View.View_Task_Menu_Bar.v_Task_Menu()
            self.win.show()
            self.hide()

    def __previous(self):
        reply_01 = QMessageBox.question(self, '提示', '是否保存当前内容？',
                                        QMessageBox.Yes | QMessageBox.No | QMessageBox.Cancel, QMessageBox.Yes)
        if reply_01 == QMessageBox.Yes:
            if self.save_data_to_database(False) == True:
                self.signal_str.emit('back')
                self.hide()
            else:
                return
        elif reply_01 == QMessageBox.No:
            pass
        else:
            return
        # self.signal_str.emit('back')
        self.hide()
        # self.win = Project_Info.Controller.Controller_Project_Info_01.c_Project_Info_01()
        # self.win.show()
        # self.hide()

    def __next(self):
        reply_01 = QMessageBox.question(self, '提示', '是否保存当前内容？',
                                        QMessageBox.Yes | QMessageBox.No | QMessageBox.Cancel, QMessageBox.Yes)
        if reply_01 == QMessageBox.Yes:
            if self.save_data_to_database(False) == True:
                self.win02 = IT_Understanding.Controller.Controller_IT_Understanding_01_project_info.c_IT_understanding_01()
                # self.win02.signal_str.connect(self.to_show)
                self.win02.show()
                self.hide()
            else:
                return
        elif reply_01 == QMessageBox.No:
            return
        else:
            return

    def to_show(self, str):
        self.show()

    def save_check(self):
        if self.tabel1.rowCount() == 0:
            QMessageBox.question(self, '提示', '项目组成员不得为空', QMessageBox.Yes, QMessageBox.Yes)
            return False
        # 项目角色准确性检验
        save_df = self.__collect_tableWidget_DataFrame(self.tabel1, self.tabel1_order)
        if len(save_df[save_df['项目角色'] == '管理员']) > 1:
            QMessageBox.question(self, '提示', '不得存在多个管理员', QMessageBox.Ok)
            return False
        elif len(save_df[save_df['项目角色'] == '管理员']) == 0:
            QMessageBox.question(self, '提示', '至少存在一个管理员', QMessageBox.Ok)
            return False
        elif len(save_df[save_df['项目角色'] == '项目组成员']) == 0:
            QMessageBox.question(self, '提示', '至少存在一个项目组成员', QMessageBox.Ok)
            return False
        # 员工编号重复检验
        duplicated_df = save_df.duplicated('员工编号', keep='first')
        for i in range(len(duplicated_df)):
            if duplicated_df[i]:
                duplicated_name = save_df['员工编号'].to_list()[i]
                QMessageBox.question(self, '提示', '员工编号存在重复项：' + duplicated_name, QMessageBox.Ok)
                return False
        # 姓名重复检验
        duplicated_df = save_df.duplicated('姓名', keep='first')
        for i in range(len(duplicated_df)):
            if duplicated_df[i]:
                duplicated_name = save_df['姓名'].to_list()[i]
                QMessageBox.question(self, '提示', '姓名存在重复项：' + duplicated_name, QMessageBox.Ok)
                return False
        # 非空校验
        for i in range(len(save_df)):
            for j in [0, 1]:
                if self.tabel1.item(i, j).text().strip() == '':
                    QMessageBox.question(self, '提示', '表格存在未填项', QMessageBox.Ok)
                    return False
        return True


```

**Comment by jondy** [comment]
The issue is `bcc script` called by third party tool `pandas\core\generic.py`

Please check this guide to solve this kind of problem
https://pyarmor.readthedocs.io/en/latest/tutorial/advanced.html#using-bccmode-pro
