### ISSUE TITLE
`No such file or directory: 'codesign'` with --platform darwin.x86_64

### ISSUE THREAD

**Issue by sergionuc** [dashingsoft/pyarmor#1122]
Hi pyarmor team!

I have run the gen command with --platform darwin.x86_64 option and got the following error: 

INFO     Python 3.9.5
INFO     Pyarmor 8.1.0 (pro), 005000, XXXX
INFO     search inputs ...
INFO     find package at src/XXXX
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'darwin.x86_64'}
INFO     write XXXX/XXXXX/pyarmor_runtime_005000/pyarmor_runtime.so
INFO     patch runtime file
INFO     sign runtime file
CRITICAL unknown error, please check pyarmor.error.log
ERROR    [Errno 2] No such file or directory: 'codesign'

Content of the pyarmor.error.log file: 

Traceback (most recent call last):
  File "/app/worker_venv/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "/app/worker_venv/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "/app/worker_venv/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "/app/worker_venv/lib/python3.9/site-packages/pyarmor/cli/generate.py", line 151, in process
    self.generate_runtime_package(self.ctx.outputs[0])
  File "/app/worker_venv/lib/python3.9/site-packages/pyarmor/cli/generate.py", line 88, in generate_runtime_package
    Pytransform3.generate_runtime_package(self.ctx, output)
  File "/app/worker_venv/lib/python3.9/site-packages/pyarmor/cli/core/__init__.py", line 53, in generate_runtime_package
    return m.generate_runtime_package(ctx, output, platforms)
  File "<maker>", line 761, in generate_runtime_package
  File "<maker>", line 444, in build
  File "<maker>", line 261, in osx_sign_binary
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'codesign'

I would appreciate any help you can give me. Thx!

**Comment by jondy** [comment]
In pyarmor `8.1.1a1` with pyarmor.cli.core `2.1.a1`, it will be a warning if build platform is not MacOs:

Code signing is a macOS security technology, no codesign runtime file "%s" may not work in MacOS. Please consult Apple developer documentation to codesign it by yourself
