### ISSUE TITLE
We are unable to upgrade our Pyarmor old license.

### ISSUE THREAD

**Issue by neetunarayanan** [dashingsoft/pyarmor#1124]
We need to upgrade Python to version 3.11.2 for a High security vulnerability.
We are using Pyarmor to obfuscate our source code.
Please find below the current version of Pyarmor and registration code.
 
PyArmor Version 6.7.3
Registration Code: pyarmor-vax-000881
 
Since older Pyarmor commands does not support Python 3.11.2, we need to upgrade Pyarmor to latest version(8.1.0).
We installed Pyarmor 8.1.0 and tried to upgrade our current license and got the following error.
 
# pyarmor reg -u pyarmor-regcode-1.txt
INFO     Python 3.11.2
INFO     Pyarmor 8.1.0 (trial), 000000, non-profits
 
Pyarmor 8.0 changes EULA and uses new commands
It's different from previous Pyarmor totally
Please read this import notes first:
[https://github.com/dashingsoft/pyarmor/issues/980 [github.com]](https://urldefense.com/v3/__https:/github.com/dashingsoft/pyarmor/issues/980__;!!LpKI!mW28fAjJrf1izixJ0xOl7ITkoBcoQzbb0eWr2u1tKJyzHtzHbPO9X_eBSb0YkeuytuJ1hFCOzezr2-Txu8k$)
Do not upgrade to Pyarmor 8 if you don't known what's changed
 
I have known the changes of Pyarmor 8? (yes/no/help) yes
INFO     prepare "pyarmor-regcode-1.txt"
INFO     query key file from server
 
You are about to upgrade old Pyarmor license to Pyarmor Basic
License for Pyarmor 8.0+
 
The upgraded license information will be
 
License Type    : pyarmor-old
License Owner   : Pradeep Kuppam
Bind Product    : TBD
 
This license is about to be used for non-profits
 
Are you sure to continue? (yes/no) yes
INFO     process activation file "pyarmor-regcode-1.txt"
INFO     send request to server
INFO     write registration file "pyarmor-regfile.zip"
INFO     register "pyarmor-regfile.zip"
CRITICAL unknown error, please check pyarmor.error.log
ERROR    File is not a zip file
 
# cat pyarmor.error.log
497 MainProcess 2023-04-10 11:49:33,195
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "/root/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "/root/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 245, in cmd_reg
    return regsvr.register(regfile, args.product, upgrade=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pyarmor/cli/register.py", line 318, in register
    self.register_regfile(regfile)
  File "/root/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pyarmor/cli/register.py", line 150, in register_regfile
    with ZipFile(regfile, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.2/lib/python3.11/zipfile.py", line 1299, in __init__
    self._RealGetContents()
  File "/root/.pyenv/versions/3.11.2/lib/python3.11/zipfile.py", line 1366, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
 

Tried again with the zip file recently downloaded.

# pyarmor reg -u pyarmor-regfile-881.zip
INFO     Python 3.11.2
INFO     Pyarmor 8.1.0 (trial), 000000, non-profits
CRITICAL unknown error, please check pyarmor.error.log
ERROR    upgrade need text file "pyarmor-keycode-xxxx.txt"
 
# cat pyarmor.error.log
547 MainProcess 2023-04-10 11:50:56,485
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "/root/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "/root/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 204, in cmd_reg
    raise CliError('upgrade need text file "pyarmor-keycode-xxxx.txt"')
pyarmor.cli.errors.CliError: upgrade need text file "pyarmor-keycode-xxxx.txt"

**Comment by jondy** [comment]
Please read this
https://pyarmor.readthedocs.io/en/latest/licenses.html
