### ISSUE TITLE
[BUG] RFT `AttributeError: startswith`

### ISSUE THREAD

**Issue by AlecHaring** [dashingsoft/pyarmor#1143]
I'm not sure how to debug what in my project is causing the error, but it seems like it occurs before any files are obfuscated.

**Executed command:** `pyarmor -d gen --enable-rft .\fake_name\ `

**Version:** `8.1.2`

**pyarmor.error.log**
```
8512 MainProcess 2023-04-12 01:27:45,749
Traceback (most recent call last):
  File "C:\users\alec\desktop\pythonprojects\fake_name\venv\lib\site-packages\pyarmor\cli\__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "C:\users\alec\desktop\pythonprojects\fake_name\venv\lib\site-packages\pyarmor\cli\__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "C:\users\alec\desktop\pythonprojects\fake_name\venv\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\users\alec\desktop\pythonprojects\fake_name\venv\lib\site-packages\pyarmor\cli\generate.py", line 145, in process
    Pytransform3.pre_build(self.ctx)
  File "C:\users\alec\desktop\pythonprojects\fake_name\venv\lib\site-packages\pyarmor\cli\core\__init__.py", line 63, in pre_build
    return m.pre_build(ctx)
  File "<maker>", line 779, in pre_build
  File "<maker>", line 666, in build
  File "<maker>", line 3389, in process
  File "<maker>", line 3330, in _format_module_types
  File "<maker>", line 3331, in <listcomp>
  File "<maker>", line 2762, in __getattr__
AttributeError: startswith
```

**Comment by jondy** [comment]
Fixed it in `8.1.3`

**Comment by AlecHaring** [comment]
Huh, weird. Still experiencing the issue

**Comment by jondy** [comment]
Try it in `8.1.4`, make sure pyarmor.cli.core==`2.1.4`

**Comment by AlecHaring** [comment]
Fixed. Thanks!
