### ISSUE TITLE
offline license registration error RuntimeError: request license token faild (3)

### ISSUE THREAD

**Issue by vzubin** [dashingsoft/pyarmor#1172]
Hi, We have registered the product using the command

`pyarmor reg -p XXX pyarmor-regcode-XXXX.txt`
 
and generated the pyarmor-regfile-XXXX.zip

we have been using `pyarmor reg /path/to/pyarmor-regfile-XXXX.zip` it has been working fine, but from yesterday we are getting the following error

`ERROR    request license token faild`

`16295 MainProcess 2023-04-18 09:07:01,067
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 629, in main
    main_entry(sys.argv[1:])
  File "/home/anaconda3/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 617, in main_entry
    args.func(ctx, args)
  File "/home/anaconda3/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 224, in cmd_reg
    reg.register_regfile(regfile)
  File "/home/anaconda3/lib/python3.8/site-packages/pyarmor/cli/register.py", line 156, in register_regfile
    self.update_token()
  File "/home/anaconda3/lib/python3.8/site-packages/pyarmor/cli/register.py", line 113, in update_token
    Pytransform3._update_token(self.ctx)
  File "/home/anaconda3/lib/python3.8/site-packages/pyarmor/cli/core/__init__.py", line 72, in _update_token
    m = Pytransform3.init(ctx)
  File "/home/anaconda3/lib/python3.8/site-packages/pyarmor/cli/core/__init__.py", line 42, in init
    m.init_ctx(ctx)
RuntimeError: request license token faild (3)`

we are using 
pyarmor==8.1.2
python==3.10

Thank you

**Comment by vzubin** [comment]
Adding some aditional information

Tried on a sample file
```
------
root@icexd-dev:/event_prediction# pyarmor gen -O dist --assert-call foo.py
INFO     Python 3.10.11
INFO     Pyarmor 8.1.1 (basic), 004033, [productName]
INFO     search inputs ...
INFO     find script foo.py
INFO     find 1 top resources
CRITICAL unknown error, please check pyarmor.error.log
ERROR    request license token faild (3)
```
------
The license is not getting read properly

**Comment by jondy** [comment]
Try it now.

**Comment by vzubin** [comment]
Thank You its works now
