### ISSUE TITLE
ERROR request license token faild (3)

### ISSUE THREAD

**Issue by sana888999** [dashingsoft/pyarmor#1202]
![image](https://user-images.githubusercontent.com/67665857/235368616-02c5148f-3c3e-426c-86c5-eceb4352f8ca.png)
![image](https://user-images.githubusercontent.com/67665857/235368800-abe26480-310f-4213-8670-8267b7322347.png)

I just bought Lic last night been trying to register no luck. I keep getting error i tried everything..
I am tired of going through issues with no valid solution. Please advice!  

------------------------------------

8840 MainProcess 2023-04-30 10:52:50,681
Traceback (most recent call last):
  File "C:\Users\sana8\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 689, in main
    main_entry(sys.argv[1:])
  File "C:\Users\sana8\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 677, in main_entry
    args.func(ctx, args)
  File "C:\Users\sana8\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 280, in cmd_reg
    reg.register_regfile(regfile)
  File "C:\Users\sana8\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\register.py", line 163, in register_regfile
    self.update_token()
  File "C:\Users\sana8\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\register.py", line 111, in update_token
    Pytransform3._update_token(self.ctx)
  File "C:\Users\sana8\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\core\__init__.py", line 89, in _update_token
    m = Pytransform3.init(ctx)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sana8\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\core\__init__.py", line 59, in init
    m.init_ctx(ctx)
RuntimeError: request license token faild (3)

**Comment by jondy** [comment]
You're using old license in Pyarmor 8.0, please check documentation to upgrade it.
