### ISSUE TITLE
[BUG] Pyarmor may cause `python -m build` to fail when using the version string defined by a sub-package in setup.cfg

### ISSUE THREAD

**Issue by fO-000** [dashingsoft/pyarmor#1223]
Environment:

* Python 3.11.2
* pyarmor 8.1.9 (basic)
* pyarmor.cli.core 2.1.9
* OS: `VMware guest Linux x 6.1.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2kali1 (2023-04-18) x86_64 GNU/Linux`

The `test-project` hierarchy is as follows:

```txt
$ tree test-project
test-project
├── MANIFEST.in
├── pyproject.toml
├── setup.cfg
└── src
    └── parent
        ├── child
        │   └── __init__.py
        └── __init__.py

4 directories, 5 files
```

The content of each file is as follows:

* `MANIFEST.in`

  ```txt
  recursive-include dist/parent/pyarmor_runtime_00xxxx *.so
  ```

* `pyproject.toml`
  
  ```txt
  [build-system]
  requires = [
      "setuptools>=66.1.1",
      "wheel"
  ]
  build-backend = "setuptools.build_meta"
  ```

* `setup.cfg`

  ```txt
  [metadata]
  name = parent.child
  version = attr: parent.child.VERSION

  [options]
  package_dir =
      =dist/

  packages =
      parent
      parent.child
      parent.pyarmor_runtime_00xxxx

  include_package_data = True
  ```

* `src/parent/__init__.py` and `src/parent/child/__init__.py`  are the same:

  ```py
  VERSION = '0.0.1'
  ```

The output of `pyarmor gen --recursive -i src/parent` after successful execution is the following directory:

```txt
$ tree dist
dist
└── parent
    ├── child
    │   ├── __init__.py
    │   └── __pycache__
    │       └── __init__.cpython-311.pyc
    ├── __init__.py
    └── pyarmor_runtime_00xxxx
        ├── __init__.py
        └── pyarmor_runtime.so
```

Next, executing `python -m build --skip-dependency-check --no-isolation` to build the wheel package raises the following error:

```txt
$ python -m build --skip-dependency-check --no-isolation
* Building sdist...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/config/expand.py", line 81, in __getattr__
    return next(
           ^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/config/expand.py", line 191, in read_attr
    return getattr(StaticModule(module_name, spec), attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/config/expand.py", line 87, in __getattr__
    raise AttributeError(f"{self.name} has no attribute {attr}") from e
AttributeError: parent.child has no attribute VERSION

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/lib/python3/dist-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pep517/in_process/_in_process.py", line 302, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 417, in build_sdist
    return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
    self.run_setup()
  File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 868, in parse_config_files
    setupcfg.parse_configuration(
  File "/usr/lib/python3/dist-packages/setuptools/config/setupcfg.py", line 174, in parse_configuration
    meta.parse()
  File "/usr/lib/python3/dist-packages/setuptools/config/setupcfg.py", line 503, in parse
    section_parser_method(section_options)
  File "/usr/lib/python3/dist-packages/setuptools/config/setupcfg.py", line 477, in parse_section
    self[name] = value
    ~~~~^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/config/setupcfg.py", line 285, in __setitem__
    value = parser(value)
            ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/config/setupcfg.py", line 609, in _parse_version
    return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/config/setupcfg.py", line 419, in _parse_attr
    return expand.read_attr(attr_desc, package_dir, root_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/config/expand.py", line 194, in read_attr
    module = _load_spec(spec, module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/config/expand.py", line 214, in _load_spec
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/path/to/test-project/dist/parent/child/__init__.py", line 2, in <module>
    from ..pyarmor_runtime_00xxxx import __pyarmor__
ModuleNotFoundError: No module named 'parent.pyarmor_runtime_00xxxx'

ERROR Backend subprocess exited when trying to invoke build_sdist
```

The reason for the error can be seen as "AttributeError: parent.child has no attribute VERSION".

If we change ` version = attr: parent.child.VERSION` to ` version = attr: parent.VERSION` in `setup.cfg`, the problem can be solved. But I need to put the `VERSION` in `parent.child`.

**Comment by jondy** [comment]
Replacing `parent.child` with plain script.

`StaticModule` use `ast.parse` to get locals, it's impossible for obfuscated scripts.
