### ISSUE TITLE
[BUG] using `--pack` in MacOS, the final bundle raises error `Library not loaded: @loader_path/../libpython3.7.dylib`

### ISSUE THREAD

**Issue by jondy** [dashingsoft/pyarmor#1243]
Reproduce steps:
```
$ pyinstaller foo.py

$ pyarmor gen --pack dist/foo/foo foo.py
INFO     Python 3.7.0
INFO     Pyarmor 8.2.0 (trial), 000000, non-profits
INFO     Platform darwin.x86_64
...

$ dist/foo/foo
Traceback (most recent call last):
  File ".pyarmor/pack/dist/foo.py", line 2, in <module>
    from my_runtime import __pyarmor__
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "<frozen my_runtime>", line 2, in <module>
ImportError: dlopen(/Users/jondy/workspace/pytransform/src-v8/debug/dist/foo/my_runtime/pyarmor_runtime.so, 2): Library not loaded: @loader_path/../libpython3.7.dylib
  Referenced from: /Users/jondy/workspace/pytransform/src-v8/debug/dist/foo/my_runtime/pyarmor_runtime.so
  Reason: image not found
[29414] Failed to execute script foo
```

**Comment by jondy** [comment]
Fixed in 8.2.1
