### ISSUE TITLE
NameError: global name '__armor_enter__' is not defined

### ISSUE THREAD

**Issue by deuterium1729** [dashingsoft/pyarmor#125]
When I ran my scripts, everything went well. Then suddenly an exception was thrown. Could you tell me what caused this error and how to fix it? Thanks

NameError: global name '__armor_enter__' is not defined

**Comment by jondy** [comment]
Could you run the obfuscated scripts with `-d`, for example,
```
python -d obf_foo.py 
```
and show the console output here?

**Comment by deuterium1729** [comment]
Hi @jondy,

Thanks a lot for your quick reply!

Here are some log messages. I was running some pyspark scripts. This is from my script:

19/10/13 11:50:44 INFO CodeGenerator: Code generated in 9.600792 ms
19/10/13 11:50:44 ERROR Executor: Exception in task 0.0 in stage 433.0 (TID 16480)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/Users/apple/software/spark-2.2.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/Users/apple/software/spark-2.2.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/Users/apple/software/spark-2.2.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/Users/apple/software/spark-2.2.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/rdd.py", line 1339, in takeUpToNumLeft
  File "<frozen dist.program>", line 281, in <lambda>
  File "<frozen dist.program>", line 274, in check_program
NameError: global name '__armor_enter__' is not defined

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
19/10/13 11:50:44 ERROR Utils: Uncaught exception in thread stdout writer for python
java.lang.AssertionError: assertion failed: Block rdd_685_0 is not locked for reading
	at scala.Predef$.assert(Predef.scala:170)
	at org.apache.spark.storage.BlockInfoManager.unlock(BlockInfoManager.scala:299)
	at org.apache.spark.storage.BlockManager.releaseLock(BlockManager.scala:720)
	at org.apache.spark.storage.BlockManager$$anonfun$1.apply$mcV$sp(BlockManager.scala:516)
	at org.apache.spark.util.CompletionIterator$$anon$1.completion(CompletionIterator.scala:46)
	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:35)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificColumnarIterator.hasNext(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:120)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:112)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:112)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:518)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:333)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1948)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)
Exception in thread "stdout writer for python" java.lang.AssertionError: assertion failed: Block rdd_685_0 is not locked for reading
	at scala.Predef$.assert(Predef.scala:170)
	at org.apache.spark.storage.BlockInfoManager.unlock(BlockInfoManager.scala:299)
	at org.apache.spark.storage.BlockManager.releaseLock(BlockManager.scala:720)
	at org.apache.spark.storage.BlockManager$$anonfun$1.apply$mcV$sp(BlockManager.scala:516)
	at org.apache.spark.util.CompletionIterator$$anon$1.completion(CompletionIterator.scala:46)
	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:35)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificColumnarIterator.hasNext(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:120)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:112)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:112)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:518)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:333)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1948)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)

I have a local function working as a lambda function. Here is the log from pytransform.log:

PT-IM-00
WR-PA-00
WR-PA-01
WR-PA-02
WR-PA-03
WR-PA-04
WR-PA-05.1
WR-PA-05.2
PT-IM-01
PT-ITC-00
PT-ITC-01
PT-ITC-02
PT-ITC-03
PT-ITC-04
PT-ITC-05
PT-ITC-06
PT-IM-02
LC-IV-01
LC-IV-02
LC-IV-03
LC-IV-04
LC-IV-05
PT-IM-03
PT-VL-00
PT-IM-04
Marshal loads

Appreciate your work!

**Comment by deuterium1729** [comment]
The functions look like:
def generate_result(....):
    ......
    def check_program(row_entry):
274           user_id = row_entry['id']
                  .....
                  return Row(id=id, ...)
    result_rdd = result.rdd.map(lambda row: check_program(row))
    .....

**Comment by jondy** [comment]
I think there are 2 solutions. 

1.  Rename `check_program` as `lambda_check_program`
By this way, the function `check_program` will not be obfuscated, but it should work. It's better way if there is no sensitive data in the `check_program`

2.  Let python recognize obfuscated scripts automatically
Refer to https://pyarmor.readthedocs.io/en/latest/advanced.html#let-python-interpreter-recognize-obfuscated-scripts-automatically

**Comment by deuterium1729** [comment]
Since we are running the script in cluster mode, we would need to add all files including runtime files to the paths on each server in the cluster when we run spark-submit command. This should be dynamic. Let me try the first option.

Thanks a lot Jondy! I will get back to you after I try.

**Comment by deuterium1729** [comment]
Hi Jondy,

I tried the first option:

Rename check_program as lambda_check_program

I could run the obfuscated scripts using python. Since I need to run the scripts in spark cluster mode, I zipped all of the runtime files and copied it to the spark server. I made necessary configuration changes. Seems it did not work in spark mode (either client or cluster). Could you tell me what to do in order to run the obfuscated scripts in spark?

Thanks a lot!

**Comment by jondy** [comment]
I have no idea about spark cluster mode. 

There are something changed in the obfuscated scripts,  Check these changes conflict with spark mode or not.
https://pyarmor.readthedocs.io/en/latest/differences.html

And here the key points to use the obfuscated scripts 
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts
This may be helpful to understand how to configure spark cluster or client mode.

**Comment by deuterium1729** [comment]
Hi @jondy Thanks a lot for your quick reply! 

Do I need to install pyarmor on the servers I plan to run the obfuscated scripts if I have all the runtime files ready? I remember you said something about it somewhere. I just want to make sure about this.

Appreciate it again!

**Comment by jondy** [comment]
No. Only the runtime files are required to run the obfuscated files.

**Comment by deuterium1729** [comment]
Got it. I will do some testing. Thanks a lot!

**Comment by Lychfindel** [comment]
Hi, I'm also trying to obfuscate a script that must run on spark cluster. @deuterium1729  did you have any success?
