### ISSUE TITLE
[BUG] `TypeError: 'tuple' object is not callable`

### ISSUE THREAD

**Issue by goraje** [dashingsoft/pyarmor#1286]
While using `--obf-code 2` the resulting code fails to execute with `TypeError: 'tuple' object is not callable`, while trying to obfuscate string joining using a generator expression.

```
$ pyarmor gen --obf-code 2 obf2_generator_expression.py
INFO     Python 3.10.11
INFO     Pyarmor 8.2.1 (group), 006005, R****t
INFO     Platform darwin.aarch64
```

Example:

```python
# obf2_generator_expression.py

def join_parts(parts):
    return ".".join("Upper" if x.isupper() else "lower" for x in parts)

print(join_parts(["A", "b", "C"]))
```

```
cd dist
python3.10 -c "import obf2_generator_expression"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen obf2_generator_expression>", line 3, in <module>
  File "<frozen obf2_generator_expression>", line 4, in <module>
  File "<frozen obf2_generator_expression>", line 2, in join_parts
TypeError: 'tuple' object is not callable
```

Changing the generator expression to a list comprehension seems to circumvent the problem:

```python
# obf2_generator_expression.py

def join_parts(parts):
    return ".".join(["Upper" if x.isupper() else "lower" for x in parts])

print(join_parts(["A", "b", "C"]))
```

```
cd dist
python3.10 -c "import obf2_generator_expression"

Upper.lower.Upper
```

The problem is also not present while obfuscating with the default `--obf-code 1`.

**Comment by jondy** [comment]
Fixed it in v8.2.3
