### ISSUE TITLE
[BUG] `Pyarmor 8.0 RuntimeError: c compiler "clang.exe" return error: [WinError 2] 系统找不到指定的文件。`

### ISSUE THREAD

**Issue by 130347665** [dashingsoft/pyarmor#1335]
I'm supposed to try to pack my scripts using pyarmor 8.0+ but at the end when pack up I get the following error
I see on the question that there are related issues that have not been resolved?

```
2023-06-26 19:39:33,321 Python 3.9.16
2023-06-26 19:39:33,322 Pyarmor 8.2.8 (pro), 005028, non-profits(TBD)
2023-06-26 19:39:33,322 Platform windows.x86_64
2023-06-26 19:39:33,322 native platform windows.amd64
2023-06-26 19:39:33,322 home path: C:\Users\benso\.pyarmor
2023-06-26 19:39:33,322 implicitly set output to ".pyarmor\pack\dist"
2023-06-26 19:39:33,322 command options: {'recursive': True, 'no_runtime': False, 'enable_bcc': True, 'enable_rft': True, 'outer': True, 'inputs': ['C:\\Users\\benso\\Desktop\\test\\pack\\lineNotifySdk.py', 'C:\\Users\\benso\\Desktop\\test\\pack\\test.py', 'C:\\Users\\benso\\Desktop\\test\\pack\\apicheck.py'], 'output': '.pyarmor\\pack\\dist'}
2023-06-26 19:39:33,323 install plugin: CodesignPlugin
2023-06-26 19:39:33,323 extracting bundle "dist\test.exe"
2023-06-26 19:39:33,341 pylib_name is "python39.dll"
2023-06-26 19:39:33,342 extract struct
2023-06-26 19:39:33,342 extract pyimod01_archive
2023-06-26 19:39:33,342 extract pyimod02_importers
2023-06-26 19:39:33,342 extract pyimod03_ctypes
2023-06-26 19:39:33,342 extract pyimod04_pywin32
2023-06-26 19:39:33,342 extract pyiboot01_bootstrap
2023-06-26 19:39:33,342 extract pyi_rth_inspect
2023-06-26 19:39:33,342 extract pyi_rth_pkgutil
```

```
2023-06-26 19:39:38,341 obfuscating file lineNotifySdk.py
2023-06-26 19:39:38,342 process inline marker
2023-06-26 19:39:38,342 parse script
2023-06-26 19:39:38,348 start to generate bcc code ...
2023-06-26 19:39:38,349 c sources has been patched by plugin
2023-06-26 19:39:38,349 CC: clang.exe
2023-06-26 19:39:38,351 Failed to handle request
Traceback (most recent call last):
  File "<bccmaker>", line 698, in check_compiler
  File "E:\anaconda3\envs\badminton\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\anaconda3\envs\badminton\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\anaconda3\envs\badminton\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\anaconda3\envs\badminton\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\webui\server.py", line 81, in do_POST
    result['data'] = self.root_handler.dispatch(self.path[1:], args)
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\webui\handler.py", line 49, in dispatch
    return handler.dispatch(path[i+1:], args)
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\webui\handler.py", line 43, in dispatch
    return getattr(self, 'do_' + path)(args)
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\webui\handler8.py", line 446, in do_diagnose
    return self.do_build(args, debug=True)
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\webui\handler8.py", line 443, in do_build
    return self._build_target(path, args, debug=debug)
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\webui\handler8.py", line 341, in _build_target
    call_pyarmor(cmd_args, homepath=homepath, debug=debug)
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\webui\handler8.py", line 54, in call_pyarmor
    pyarmor_main(extra_opts + args)
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\cli\__main__.py", line 687, in main_entry
    args.func(ctx, args)
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\cli\__main__.py", line 222, in cmd_gen
    builder.process(options, packer=packer)
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\cli\generate.py", line 156, in process
    self._obfuscate_scripts()
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\cli\generate.py", line 119, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\cli\core\__init__.py", line 103, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 871, in generate_obfuscated_script
  File "E:\anaconda3\envs\badminton\lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 602, in process
  File "<maker>", line 602, in <listcomp>
  File "<bccmaker>", line 948, in process
  File "<bccmaker>", line 664, in build
  File "<bccmaker>", line 701, in check_compiler
RuntimeError: c compiler "clang.exe" return error: [WinError 2] 系统找不到指定的文件。

```

**Comment by 130347665** [comment]
If you don't use BCC, an package it normally

**Comment by jondy** [comment]
Please install clang in windows, search bcc mode in documentation.

**Comment by 130347665** [comment]
@jondy Thank you! I saw it.
