### ISSUE TITLE
[BUG] `Error while executing eval: NameError: name is not defined`

### ISSUE THREAD

**Issue by NishaKurur** [dashingsoft/pyarmor#1354]
While trying to execute any obfuscated code that contains eval method call, NameError happens. Note that it works well without obfuscations. 
The below is the python code: 
```
def test_basic_eval():
    print("Executing eval function")
    x = 1
    y = None
    y = eval("x+1")
    assert y == 2, "Result 'y' should be 2."
    print("Successfully executed eval function.")

if __name__ == "__main__":
    test_basic_eval()
```
The output of executing the above code is as follows:
```
$ python test_pyarmor_obfuscation_eval.py
Executing eval function
Successfully executed eval function.
```
The obfuscation is done as given below:
```
$ pyarmor gen test_pyarmor_obfuscation_eval.py
INFO     Python 3.10.6
INFO     Pyarmor 8.1.8 (trial), 000000, non-profits
INFO     Platform linux.x86_64
```
After obfuscation, the execution is done and below shows the output:
```
$ python dist/test_pyarmor_obfuscation_eval.py
Executing eval function
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen test_pyarmor_obfuscation_eval>", line 11, in <module>
  File "<frozen test_pyarmor_obfuscation_eval>", line 5, in test_basic_eval
  File "<string>", line 1, in <module>
NameError: name 'x' is not defined
```

**Comment by jondy** [comment]
By default, all the local variables are renamed, so `eval` can't find `x`.

Using the following configuration could disable this behavior and make it works

```
pyarmor cfg mix_localnames 0
pyarmor gen test_pyarmor_obfuscation_eval.py
python dist/test_pyarmor_obfuscation_eval.py
```

**Comment by NishaKurur** [comment]
Thank you @jondy for the prompt response. It worked well. Closing the bug.
