### ISSUE TITLE
[BUG] `Error -3 while decompressing data: incorrect header check`

### ISSUE THREAD

**Issue by bondbenz** [dashingsoft/pyarmor#1355]
Trying to obfuscate a pyinstaller exe packed with this command:

 `pyarmor gen -O obfdist --pack .\dist\foo.exe .\foo.py` 

```
$ pyarmor gen -O obfdist --pack .\dist\foo.exe .\foo.py
INFO     Python 3.11.2
INFO     Pyarmor 8.2.9 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     implicitly set output to ".pyarmor\pack\dist"
INFO     extracting bundle ".\dist\foo.exe"
ERROR    Error -3 while decompressing data: incorrect header check
```

**Comment by jondy** [comment]
Please find solution at this page: https://pyarmor.readthedocs.io/en/stable/topic/repack.html

By the way, what's PyInstaller version? And what' the content of `pyarmor.error.log`  which should be in the current path?

**Comment by bondbenz** [comment]
Yes I did follow exactly as the documentation unfortunately I didn't succeed, here is the pyarmor.error.log

```
14228 MainProcess 2023-07-07 15:13:34,140
Traceback (most recent call last):
  File "D:\Documents\my work\autoimport\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 698, in main
    main_entry(sys.argv[1:])
  File "D:\Documents\my work\autoimport\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 686, in main_entry
    args.func(ctx, args)
  File "D:\Documents\my work\autoimport\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 221, in cmd_gen
    packer = Repacker(args.pack, ctx.repack_path, codesign=codesign)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\my work\autoimport\venv\Lib\site-packages\pyarmor\cli\repack.py", line 313, in __init__
    self.extract_carchive(executable, buildpath)
  File "D:\Documents\my work\autoimport\venv\Lib\site-packages\pyarmor\cli\repack.py", line 337, in extract_carchive
    contents.append(extract_pyzarchive(name, pyzarch, buildpath))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\my work\autoimport\venv\Lib\site-packages\pyarmor\cli\repack.py", line 189, in extract_pyzarchive
    f.write(_code_to_timestamp_pyc(fix_extract(pyzarch.extract(name))))
                                               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\my work\autoimport\venv\Lib\site-packages\PyInstaller\loader\pyimod01_archive.py", line 197, in extract
    obj = zlib.decompress(obj)
          ^^^^^^^^^^^^^^^^^^^^
zlib.error: Error -3 while decompressing data: incorrect header check
```
Versions:

```
387 INFO: PyInstaller: 5.13.0
387 INFO: Python: 3.11.2
399 INFO: Platform: Windows-10-10.0.19045-SP0
```

**Comment by jondy** [comment]
Try to downgrade PyInstaller to 5.12 or 5.10

And do you really read the manual solution in the link in my previous comment?

**Comment by bondbenz** [comment]
My bad I didn't see the manual part, I tried to downgrade the same issue occured

Log
```
INFO     Python 3.11.2
INFO     Pyarmor 8.2.9 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     implicitly set output to ".pyarmor\pack\dist"
INFO     extracting bundle ".\dist\automovies.exe"
ERROR    Error -3 while decompressing data: incorrect header check
```

**Comment by jondy** [comment]
If PyInstaller 3.10 doesn't work, then you might encrypt `dist/xxx.exe` by PyInstaller.

Try not encrypt the final bundle when generating `.exe` by PyInstaller.

**Comment by jondy** [comment]
If PyInstaller 3.10 doesn't work, then you might encrypt `dist/xxx.exe` by PyInstaller.

Try not encrypt the final bundle when generating `.exe` by PyInstaller.

**Comment by jondy** [comment]
If PyInstaller 3.10 doesn't work, then you might encrypt `dist/xxx.exe` by PyInstaller.

Try to use default option to generate one hello world script by PyInstaller.
