### ISSUE TITLE
[BUG] `Error message` RuntimeError: Permission denied (1:10143)

### ISSUE THREAD

**Issue by alikaz3mi** [dashingsoft/pyarmor#1356]
```
$pyarmor gen -O deepdev_bind_hard -b 860_EVO_250GB_CS_0123459948 -r armor/
INFO     Python 3.9.,13
INFO     Pyarmor 8.2.9 (trial), 000000, non-profits
INFO     Platform ubuntu 22.04

```

Running the code gives the following error:

```
Traceback (most recent call last):
  File "/home/deepdev/PycharmProjects/deepdev_bind_hard/armor/main.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "/home/deepdev/PycharmProjects/deepdev_bind_hard/armor/pyarmor_runtime_000000/__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: Permission denied (1:10143)
```

**Comment by jondy** [comment]
It need root user to read harddisk serial number.
