### ISSUE TITLE
[BUG] `Unsupport relocation type 1026` with BCC mode on ARM64

### ISSUE THREAD

**Issue by hongphu8790** [dashingsoft/pyarmor#1387]
I have sample script for preproduce bug:

foo.py
```
class Foo:
    def bar(self):
        f1 = None
        f2 = None
        f3 = None
        f4 = None
        f5 = None
        f6 = None
        f7 = None
        f8 = None
        f9 = None
        f10 = None
        f11 = None
        f12 = None
        f13 = None
        f14 = None
        f15 = None
        f16 = None
        f17 = None
        f18 = None
        f19 = None
        f20 = None
        f21 = None
        f22 = None
        f23 = None
        f24 = None
 ```
 
 Command:
 
 ```
 pyarmor -d gen --output ./dist  --enable-bcc  --private foo.py
```
 
```
INFO     Python 3.11.4
INFO     Pyarmor 8.2.9 (pro), 005235, <<removed>>
INFO     Platform linux.aarch64
DEBUG    native platform linux.aarch64
DEBUG    home path: /root/.pyarmor
DEBUG    command options: {'output': './dist', 'no_runtime': False, 'enable_bcc': True, 'restrict_module': 2, 'inputs': ['foo.py']}
```
 
 When you remove field f24, the obfuscation will be fine, but add f24 or more fields may get this issue:
 
 ```
 ...
DEBUG    CC: gcc
DEBUG    cflags: -O3 -Wno-unsequenced -fno-asynchronous-unwind-tables -fno-unwind-tables -fPIC -fno-stack-protector -shared -nostdlib -T.pyarmor/bcc/linux.aarch64.ldscript
Unsupport relocation type 1026
DEBUG    unknown error, please check pyarmor.error.log
ERROR    link bcc code failed
```

The obfuscation was working fine on AMD64 with same configuration.

**Comment by jondy** [comment]
Got it, I'll check it.

**Comment by jondy** [comment]
Can't reproduced in my virtual machine: Ubuntu (jammy), aarch64, gcc 11.3.0

It works fine with same options

**Comment by hongphu8790** [comment]
> Can't reproduced in my virtual machine: Ubuntu (jammy), aarch64, gcc 11.3.0
> 
> It works fine with same options


I've updated gcc to 11.3.0, the bellow scripts working, but next script problem:

Runned on real arm64 device. Ignore logic, just a demo for figure out bugs:

```
pyarmor -d gen --output ./dist  --enable-bcc  --private foo.py 
INFO     Python 3.11.4
INFO     Pyarmor 8.3.dev1 (pro), 005235, <<removed>>
INFO     Platform linux.aarch64
DEBUG    native platform linux.aarch64
DEBUG    home path: /root/.pyarmor
DEBUG    command options: {'output': './dist', 'no_runtime': False, 'enable_bcc': True, 'restrict_module': 2, 'inputs': ['foo.py']}
DEBUG    install plugin: CodesignPlugin
INFO     search inputs ...
INFO     find script foo.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'linux.aarch64'}
INFO     write ./dist/pyarmor_runtime_005235/pyarmor_runtime.so
INFO     patch runtime file
DEBUG    patching runtime data at 588032
DEBUG    patch runtime file OK
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "foo"
INFO     obfuscating file foo.py
DEBUG    process inline marker
DEBUG    parse script
INFO     start to generate bcc code ...
DEBUG    c sources has been patched by plugin
DEBUG    CC: gcc-11
DEBUG    cflags: -O3 -Wno-unsequenced -fno-asynchronous-unwind-tables -fno-unwind-tables -fPIC -fno-stack-protector -shared -nostdlib -T.pyarmor/bcc/linux.aarch64.ldscript
Unsupport relocation type 1026
DEBUG    unknown error, please check pyarmor.error.log
ERROR    link bcc code failed
````

gcc-11 -v:

```
Using built-in specs.
COLLECT_GCC=gcc-11
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/11/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-2ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-2ubuntu1~20.04
```

foo.py

```
class Foo:
    def reload_config(self):

        url = None

        cfg = None
        authen = None
        cfg = None
        dns = None
        cfg = None
        max_connect = None
        cfg = None
        authentication = None

        if True:
            la = None
            nma = None
            akk = None
            ama = None
            aa = None
        cfg = None
        if True:
            xy = None
            yz = None
        if True:
            zz = None
            zk = None
        if True:
            mn = None
            kk = None
        if True:
            xx = None
            xz = None
        if True:
            aa = None
            a1 = None
        cfg = None
        if False:
            mm = None
        if proxy_user:
            cfg = None
        if True:
            mm = None
            cfg = None
        if False:
            cfg = None
        if False:
            zka=None
            kak=None
            aja=None
        if False:
            blist_config = None
        if False:
            cfg = None
        if False:
            wlist_config = None
        if False:
            cfg = None
        if False:
            zz = None
            if zz:
                cfg = None
        cfg = None
        xxxx = None
        x2 = None
        x3 = None
        f20 = None
        f21 = None
        f22 = None
        f23 = None
        f24 = None
        f20 = None
        f21 = None
        f22 = None
        f23 = None
        f24 = None
        x = None
        return None
```

 cat pyarmor.error.log:
 ```
 2224968 MainProcess 2023-07-25 18:23:18,912
Traceback (most recent call last):
  File "/root/.env/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 698, in main
    main_entry(sys.argv[1:])
  File "/root/.env/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 686, in main_entry
    args.func(ctx, args)
  File "/root/.env/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 225, in cmd_gen
    builder.process(options)
  File "/root/.env/lib/python3.11/site-packages/pyarmor/cli/generate.py", line 156, in process
    self._obfuscate_scripts()
  File "/root/.env/lib/python3.11/site-packages/pyarmor/cli/generate.py", line 119, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.env/lib/python3.11/site-packages/pyarmor/cli/core/__init__.py", line 103, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 871, in generate_obfuscated_script
  File "/root/.env/lib/python3.11/site-packages/pyarmor/cli/__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 602, in process
  File "<maker>", line 602, in <listcomp>
  File "<bccmaker>", line 949, in process
RuntimeError: link bcc code failed
```

**Comment by hongphu8790** [comment]
If you can't reproduce, should give me exactly emulator are you using and how to install it. 

Also, i can make a buildx docker with arm64 for test if needed.

**Comment by hongphu8790** [comment]
This is docker reproduce version:

Enable qemu & aarch64 if you are running with amd64 platform:

GCC: 12.x
Python: 11.4

```
sudo apt-get update -y
sudo apt-get install qemu qemu-user-static binfmt-support -y
sudo update-binfmts --enable qemu-aarch64
```

```
docker pull --platform=linux/arm64 python:3.11.4-bookworm
```

Go to a folder contains:
- foo.py (reproduce script)
- pyarmor-regfile-xxxx.zip
- run.sh

with run.sh:
```
#!/bin/bash

# register pyarmor
pip3 install pyarmor==8.2.9
pyarmor reg /workdir/pyarmor-regfile-xxxx.zip

# run obfuscate script:
cd /workdir
pyarmor -d gen --output ./dist  --enable-bcc  --private foo.py 
```

Execute:

```
docker run --platform=linux/arm64 -v $PWD:/workdir -it python:3.11.4-bookworm /bin/bash -c "chmod +x /workdir/run.sh && /workdir/run.sh"
```

**Comment by jondy** [comment]
Reproduced with new script, I'll check it.

**Comment by jondy** [comment]
Found the problem, it will be fixed in next release.

**Comment by hongphu8790** [comment]
> Found the problem, it will be fixed in next release.

could you bring this patch into a release ?

**Comment by jondy** [comment]
It will be released in next week

**Comment by jondy** [comment]
Fixed in 8.3.dev2
