### ISSUE TITLE
[BUG] `Error message`

### ISSUE THREAD

**Issue by lcylln** [dashingsoft/pyarmor#1396]
```
INFO     Python 3.9.17
INFO     Pyarmor 8.2.9 (basic), 004110, non-profits(TBD)
INFO     Platform linux.aarch64

```
root@dc5429a6af59:/code# python encrypt.py 
DEBUG:root:PyArmor installation path: /usr/local/lib/python3.9/site-packages/pyarmor
DEBUG:root:PyArmor home path: /root/.pyarmor
DEBUG:root:Native platform is linux.aarch64
DEBUG:root:Search dynamic library in the path: /usr/local/lib/python3.9/site-packages/pyarmor/platforms
DEBUG:root:Search dynamic library in the path: /root/.pyarmor/platforms
INFO:root:Search library for platform: linux.aarch64
DEBUG:root:Load platform list from /root/.pyarmor/platforms/index.json
INFO:root:Found available libraries: ['linux.aarch64.3']
INFO:root:Target path for linux.aarch64.3: /root/.pyarmor/platforms/linux/aarch64/3
INFO:root:Downloading library file for linux.aarch64.3 ...
DEBUG:root:Got license data from /root/.pyarmor/license.lic
INFO:root:Getting remote file: https://pyarmor.dashingsoft.com/files/r52.6/armv8.64-bit/_pytransform.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyarmor/utils.py", line 1685, in _urlopen
    return urlopen(*args, **kwargs)
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by jondy** [comment]
Pyarmor Basic license doesn't work for Pyarmor 7 features.
