### ISSUE TITLE
[BUG] `File is not a zip file` during license upgrade

### ISSUE THREAD

**Issue by dmitriy-pryan** [dashingsoft/pyarmor#1417]
When I'm trying to upgrade my license to use Pyarmor 8, it fails with the following error:
```
$ pyarmor reg -u -p "my_project" pyarmor-regcode.txt
INFO     Python 3.10.3
INFO     Pyarmor 8.3.1 (trial), 000000, non-profits
INFO     Platform darwin.x86_64

Pyarmor 8 changes EULA and uses new commands
It's different from previous Pyarmor totally
Please read this import notes first:
https://github.com/dashingsoft/pyarmor/issues/980
Do not upgrade to Pyarmor 8 if don't know what are changed

I have known the changes of Pyarmor 8? (yes/no/help) yes
INFO     prepare "pyarmor-regcode.txt"
INFO     query key file from server

You are about to upgrade old Pyarmor license to Pyarmor Basic License

The upgraded license information will be

License Type    : pyarmor-old
License To      : *REDACTED*
License Product : *REDACTED*

This license is about to be used for product "*REDACTED*"

Are you sure to continue? (yes/no) yes
INFO     process activation file "pyarmor-regcode.txt"
INFO     send request to server
INFO     write registration file "pyarmor-regfile.zip"
INFO     register "pyarmor-regfile.zip"
ERROR    File is not a zip file

```

The contents of `pyarmor.error.log` after the failure:

```
39134 MainProcess 2023-08-09 20:50:53,963
Traceback (most recent call last):
  File "/Users/user/.local/share/virtualenvs/venv/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 702, in main
    main_entry(sys.argv[1:])
  File "/Users/user/.local/share/virtualenvs/venv/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 690, in main_entry
    return args.func(ctx, args)
  File "/Users/user/.local/share/virtualenvs/venv/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 313, in cmd_reg
    return regsvr.register(regfile, args.product, upgrade=True)
  File "/Users/user/.local/share/virtualenvs/venv/lib/python3.10/site-packages/pyarmor/cli/register.py", line 427, in register
    self.register_regfile(regfile)
  File "/Users/user/.local/share/virtualenvs/venv/lib/python3.10/site-packages/pyarmor/cli/register.py", line 150, in register_regfile
    with ZipFile(regfile, 'r') as f:
  File "/Users/user/.asdf/installs/python/3.10.3/lib/python3.10/zipfile.py", line 1265, in __init__
    self._RealGetContents()
  File "/Users/user/.asdf/installs/python/3.10.3/lib/python3.10/zipfile.py", line 1332, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by dmitriy-pryan** [comment]
@jondy Is it in fact wrong usage or a bug?

**Comment by jondy** [comment]
I guess this old license could not be upgrade to Pyarmor Basic, please check
http://pyarmor.readthedocs.io/en/stable/licenses.html#upgrading-old-license

**Comment by jondy** [comment]
> I don't intend to break the EULA

In this case, do not upgrade old license.
