### ISSUE TITLE
[BUG] `FileNotFoundError: [Errno 2] No such file or directory: 'dist'`

### ISSUE THREAD

**Issue by Gaimoydev** [dashingsoft/pyarmor#1431]
Please read this first before report any issue
https://pyarmor.readthedocs.io/en/latest/questions.html

Please copy the whole command line `pyarmor gen` and first 4 lines in the console, do not mask anything, and do not paste snapshot image

```
$ pyarmor gen -O dist --assert-call foo.py
INFO     Python: 3.11.3
INFO     Pyarmor 8.3.3 (trial), 000000, non-profits
INFO     Platform darwin.x86_64

```
ERROR    Failed to handle request
Traceback (most recent call last):
  File "E:\py\Lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'dist' -> 'D:/obf\\dist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\py\Lib\site-packages\pyarmor\webui\server.py", line 81, in do_POST
    result['data'] = self.root_handler.dispatch(self.path[1:], args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\py\Lib\site-packages\pyarmor\webui\handler.py", line 49, in dispatch
    return handler.dispatch(path[i+1:], args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\py\Lib\site-packages\pyarmor\webui\handler.py", line 43, in dispatch
    return getattr(self, 'do_' + path)(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\py\Lib\site-packages\pyarmor\webui\handler8.py", line 440, in do_build
    return self._build_temp(args, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\py\Lib\site-packages\pyarmor\webui\handler8.py", line 380, in _build_temp
    return self._build_target(path, args, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\py\Lib\site-packages\pyarmor\webui\handler8.py", line 349, in _build_target
    shutil.move(distpath, output)
  File "E:\py\Lib\shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "E:\py\Lib\shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "E:\py\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dist'
127.0.0.1 - - [19/Aug/2023 19:50:13] "POST /project/build HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2023 19:50:13] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 11763)
Traceback (most recent call last):
  File "E:\py\Lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "E:\py\Lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "E:\py\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\py\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "E:\py\Lib\http\server.py", line 432, in handle
    self.handle_one_request()
  File "E:\py\Lib\http\server.py", line 420, in handle_one_request
    method()
  File "E:\py\Lib\site-packages\pyarmor\webui\server.py", line 103, in do_GET
    self.copyfile(f, self.wfile)
  File "E:\py\Lib\site-packages\pyarmor\webui\server.py", line 186, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "E:\py\Lib\shutil.py", line 200, in copyfileobj
    fdst_write(buf)
  File "E:\py\Lib\socketserver.py", line 834, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。
----------------------------------------

**Comment by jondy** [comment]
Can't reproduce it by your report. 

Please write well format bug and all the shell commands used to reproduce it correctly.
