### ISSUE TITLE
[BUG] `Binding to GPU cards Failed`

### ISSUE THREAD

**Issue by freeenergylab** [dashingsoft/pyarmor#1462]
Firstly, this basic info about my installed pyarmor:

```
$ pyarmor gen 
INFO     Python 3.9.7
INFO     Pyarmor 8.3.5 (pro), 005289, singleparticle
INFO     Platform linux.x86_64
INFO     search inputs ...
```

I found my GPU cards UUID are:
```
$ nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 3080 Ti (UUID: GPU-e0e9e4b9-ba8c-e1a2-5a22-8857cc13a3c3)
GPU 1: NVIDIA GeForce RTX 3080 Ti (UUID: GPU-df7305d3-516a-769d-24ca-1f588e1f0989)
GPU 2: NVIDIA GeForce RTX 3080 Ti (UUID: GPU-e2c68f3c-f57b-4033-c314-e892d6a6fee4)
GPU 3: NVIDIA GeForce RTX 3080 Ti (UUID: GPU-691f303b-459b-1741-f050-6e579895b541)
```

Then, I obfuscated my code repo as:
```
$ pyarmor gen --platform linux.x86_64 -b "GPU-e0e9e4b9-ba8c-e1a2-5a22-8857cc13a3c3" -b "GPU-df7305d3-516a-769d-24ca-1f588e1f0989" -b "GPU-e2c68f3c-f57b-4033-c314-e892d6a6fee4" -b "GPU-691f303b-459b-1741-f050-6e579895b541" ./my_code_repo
```

But when I submit jobs using my code repo, the error massage is:
```
Traceback (most recent call last):
  File "/home/lpf/dist/abfe/abfe_main.py", line 2, in <module>
    from pyarmor_runtime_005289 import __pyarmor__
  File "/home/lpf/dist/pyarmor_runtime_005289/__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: Permission denied (1:10143)
```

Thanks for helping in advance!

**Comment by jondy** [comment]
Pyarmor could not bind to GPU, so it thinks they're serial numer of harddisk, but the current user has no right to read harddisk sn, that's why it report this error.

Please use option `--bind-data` to bint GPU, and write your own scripts to check it by Pyarmor runtime hook.

**Comment by freeenergylab** [comment]
@jondy Could you give some guide how to use `--bind-data` and Pyarmor runtime hook? Thanks!

**Comment by jondy** [comment]
Refer to
https://pyarmor.readthedocs.io/en/latest/tutorial/customization.html#using-hook-to-bind-script-to-docker-id

**Comment by freeenergylab** [comment]
Thanks @jondy help.

It works well now. I just wanted to check if all GPU cards are licensed or not. 
If not, my program will report one RuntimeError.

I pasted my implementation here:

Firstly, create one ```.pyarmor/hooks/your_repo_main.py``` in your local workdir where you will obfuscate YOUR_CODE_REPO.
```
# TODO: need to collect all GPU cards UUID from the user-defined Slurm partition
ALL_GPU_UUID = ['GPU-e0e9e4b9-ba8c-e1a2-5a22-8857cc13a3c3',
                'GPU-df7305d3-516a-769d-24ca-1f588e1f0989',
                'GPU-e2c68f3c-f57b-4033-c314-e892d6a6fee4',
                'GPU-691f303b-459b-1741-f050-6e579895b541']

def is_all_gpu_licensed(licensed_gpu_ids, all_gpu_ids):
    licensed_gpu_ids = [id.strip() for id in licensed_gpu_ids]
    for id in all_gpu_ids:
        id = id.strip()
        if id not in licensed_gpu_ids:
            return False
    else:
        return True

def _pyarmor_check_gpu():
    licensed_gpu_ids = __pyarmor__(0, None, b'keyinfo', 1).decode('utf-8')
    licensed_gpu_ids = licensed_gpu_ids.split(',')
    if not is_all_gpu_licensed(licensed_gpu_ids, ALL_GPU_UUID):
        err_msg = '\nThese machines have non-licensed GPU cards.'
        err_msg += '\nPlease remove the machines with non-licensed GPU cards.'
        raise RuntimeError(err_msg)

_pyarmor_check_gpu()
```

Secondly, in your local workdir,
```
pyarmor gen --platform linux.x86_64 --bind-data "GPU-e0e9e4b9-ba8c-e1a2-5a22-8857cc13a3c3, GPU-df7305d3-516a-769d-24ca-1f588e1f0989, GPU-e2c68f3c-f57b-4033-c314-e892d6a6fee4, GPU-691f303b-459b-1741-f050-6e579895b541" ./YOUR_CODE_REPO
```
