### ISSUE TITLE
[BUG] `could not get docker host machine id`

### ISSUE THREAD

**Issue by Hemnaath26** [dashingsoft/pyarmor#1472]
```
pyarmor -v
Pyarmor 8.3.5 (trial), 000000, non-profits

License Type    : pyarmor-trial
License No.     : pyarmor-vax-000000
License To      : 
License Product : non-profits

BCC Mode        : No
RFT Mode        : No

Notes
* Can't obfuscate big script and mix str
```

I have  used pyarmor in the same Ec2 instance for 2 months by mistake someone deleted .pyarmor in the home directory.
tried to generate new license but getting some issue and tried to refer privious github issue but not sure steps to solve issue.

Vm is not restarted for last 2 months

```
pyarmor -d reg pyarmor-regfile-6033.zip 
INFO     Python 3.11.0
INFO     Pyarmor 8.3.5 (trial), 000000, non-profits
INFO     Platform linux.x86_64
DEBUG    native platform linux.x86_64
DEBUG    home path: /home/ubuntu/.pyarmor
INFO     register "pyarmor-regfile-6033.zip"
DEBUG    extracting license.lic
DEBUG    extracting .pyarmor_capsule.zip
INFO     refer to http://pyarmor.readthedocs.io/en/stable/how-to/register.html#using-group-license
ERROR    wrong usage for group license
ubuntu@ip-172-31-40-30:~$ pyarmor -d reg pyarmor-device-regfile-6033.9.zip 
INFO     Python 3.11.0
INFO     Pyarmor 8.3.5 (trial), 000000, non-profits
INFO     Platform linux.x86_64
DEBUG    native platform linux.x86_64
DEBUG    home path: /home/ubuntu/.pyarmor
INFO     register "pyarmor-device-regfile-6033.9.zip"
DEBUG    extracting license.lic
DEBUG    extracting .pyarmor_capsule.zip
DEBUG    group license for machines: ['tokens/k598a56b4dc9db34197f8b189d50fb35e']
DEBUG    got machine id: k4404a91648bfc9620cda9979fbc8fc92
DEBUG    got machine id: g4404a91648bfc9620cda9979fbc8fc92
DEBUG    got machine id: b350b05d638c7d1dc8d7c421a8c803980
ERROR    could not get docker host machine id
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 194, in _get_docker_hostname
    s.connect((host, port))
socket.gaierror: [Errno -2] Name or service not known
ERROR    could not get docker host machine id
```

# created new VM to create new license  

created virtuval environment using python -m venv venv and activated 
```
pip install pyarmor 
pyarmor reg -g 10
 pyarmor reg -g 10 pyarmor-regfile-6033.zip 
 (venv) ubuntu@ip-172-31-46-159:~$ pyarmor -d reg pyarmor-device-regfile-6033.10.zip
INFO     Python 3.10.12
INFO     Pyarmor 8.3.5 (trial), 000000, non-profits
INFO     Platform linux.x86_64
DEBUG    native platform linux.x86_64
DEBUG    home path: /home/ubuntu/.pyarmor
INFO     register "pyarmor-device-regfile-6033.10.zip"
DEBUG    extracting license.lic
DEBUG    extracting .pyarmor_capsule.zip
DEBUG    group license for machines: ['tokens/kcd31387ce43d695e1f1454990846333e']
DEBUG    got machine id: k1eab935eb082457920954ef8faf1bba8
DEBUG    got machine id: g1eab935eb082457920954ef8faf1bba8
DEBUG    got machine id: b87d560253fe0dff9b4d3b23554bfd97f
ERROR    could not get docker host machine id
Traceback (most recent call last):
  File "/home/ubuntu/workspace/venv/lib/python3.10/site-packages/pyarmor/cli/register.py", line 194, in _get_docker_hostname
    s.connect((host, port))
socket.gaierror: [Errno -2] Name or service not known
ERROR    could not get docker host machine id
```

@jondy  please help me with issue to use pyarmor

**Comment by jondy** [comment]
Following this guide to check VM machine id 
https://pyarmor.readthedocs.io/en/latest/licenses.html#check-device-for-group-license
