### ISSUE TITLE
[BUG] `pyarmor-auth could not get docker host machine id`

### ISSUE THREAD

**Issue by ryanpennellblacksage** [dashingsoft/pyarmor#1475]
We're having trouble booting the pyarmor auth service for authorizing containers

```
$ pyarmor-auth --debug ~/.pyarmor/pyarmor-device-regfile-XXXX.X.zip 
2023-09-13 16:32:40,961: work path: XXX/.pyarmor/docker
2023-09-13 16:32:40,962: register "XXX/.pyarmor/pyarmor-device-regfile-XXXX.X.zip"
2023-09-13 16:32:40,967: extracting license.lic
2023-09-13 16:32:40,968: extracting .pyarmor_capsule.zip
2023-09-13 16:32:40,968: group license for machines: ['tokens/g1eb360180a8fe5dc0d2a91eafe17a902']
2023-09-13 16:32:40,969: got machine id: kb14abd12014279c57c9aa5967b08a444
2023-09-13 16:32:40,969: got machine id: g638bffd6c13c7a5b5e666061f2471901
2023-09-13 16:32:40,969: got machine id: b4aae98403fd8c54ddb48b0dc3c4c1fda
2023-09-13 16:32:40,970: could not get docker host machine id
Traceback (most recent call last):
  File "XXX/.local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 194, in _get_docker_hostname
    s.connect((host, port))
socket.gaierror: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "XXX/.local/bin/pyarmor-auth", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "XXX/.local/lib/python3.11/site-packages/pyarmor/cli/docker.py", line 107, in main
    main_entry()
  File "XXX/.local/lib/python3.11/site-packages/pyarmor/cli/docker.py", line 90, in main_entry
    register_pyarmor(ctx, args.regfile[0])
  File "XXX/.local/lib/python3.11/site-packages/pyarmor/cli/docker.py", line 62, in register_pyarmor
    reg.register_regfile(regfile)
  File "XXX/.local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 167, in register_regfile
    raise CliError('could not get docker host machine id')
pyarmor.cli.CliError: could not get docker host machine id


```

**Comment by ryanpennellblacksage** [comment]
After rebooting my laptop, I tried reregistering device 2 because it was not working.  I got the "error: device (2) is not for this machine"

I can confirm that device 2 has always been bound to this exact laptop and no OS resinstall has taken place.  Why is this no longer recognizing my machine?

**Comment by drebbe-intrepid** [comment]
Turns out my issue is license related here: https://github.com/dashingsoft/pyarmor/issues/1446

**Comment by ryanpennellblacksage** [comment]
Thanks @drebbe-intrepid, 

Looks like the issue is WIP?  I'm still running into it with all licensing on this particular machine:
```
INFO     Python 3.11.4
INFO     Pyarmor 8.3.4
...
ERROR    could not get docker host machine id
Traceback (most recent call last):
  File "XXX/.local/lib/python3.11/site-packages/pyarmor/cli/register.py", line 194, in _get_docker_hostname
    s.connect((host, port))
socket.gaierror: [Errno -2] Name or service not known
ERROR    could not get docker host machine id

```

**Comment by jondy** [comment]
duplicated and documentated.

Please upgrade Pyarmor to 8.3.7

**Comment by drebbe-intrepid** [comment]
@jondy Commenting here also, 8.3.7 did not fix my issue
