### ISSUE TITLE
[BUG] hdinfo on mac 'unauthorized'

### ISSUE THREAD

**Issue by mastrolube** [dashingsoft/pyarmor#1482]
Hello, I'm not able to run the hdinfo command on mac mini m2 (arm64).
On windows and linux is working
`% pyarmor-7 hdinfo `
```
INFO     Search library for platform: darwin.aarch64
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r52.6/index.json
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mastrolube/PycharmProjects/GA/.venv3.10/lib/python3.10/site-packages/pyarmor/utils.py", line 1685, in _urlopen
    return urlopen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mastrolube/PycharmProjects/GA/.venv3.10/bin/pyarmor-7", line 8, in <module>
    sys.exit(main_entry())
  File "/Users/mastrolube/PycharmProjects/GA/.venv3.10/lib/python3.10/site-packages/pyarmor/pyarmor.py", line 1612, in main_entry
    main(sys.argv[1:])
  File "/Users/mastrolube/PycharmProjects/GA/.venv3.10/lib/python3.10/site-packages/pyarmor/pyarmor.py", line 1600, in main
    pytransform_bootstrap(capsule=DEFAULT_CAPSULE, force=args.boot)
  File "/Users/mastrolube/PycharmProjects/GA/.venv3.10/lib/python3.10/site-packages/pyarmor/utils.py", line 154, in pytransform_bootstrap
    rid = download_pytransform(platid, libpath, firstonly=1)[0]
  File "/Users/mastrolube/PycharmProjects/GA/.venv3.10/lib/python3.10/site-packages/pyarmor/utils.py", line 291, in download_pytransform
    plist = _get_platform_list(platid=platid)
  File "/Users/mastrolube/PycharmProjects/GA/.venv3.10/lib/python3.10/site-packages/pyarmor/utils.py", line 239, in _get_platform_list
    res = _get_remote_file(platform_config, timeout=PYARMOR_TIMEOUT)
  File "/Users/mastrolube/PycharmProjects/GA/.venv3.10/lib/python3.10/site-packages/pyarmor/utils.py", line 230, in _get_remote_file
    return _urlopen(req, None, timeout)
  File "/Users/mastrolube/PycharmProjects/GA/.venv3.10/lib/python3.10/site-packages/pyarmor/utils.py", line 1689, in _urlopen
    return urlopen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

[Link](https://pyarmor.dashingsoft.com/files/r52.6/index.json) required authentication

**Comment by jondy** [comment]
It need old license (Pyarmor-old) to run Pyarmor-7 in darwin.aarch64
