### ISSUE TITLE
[BUG] --enable-rft `ImportError: cannot import name 'XX' from 'XX'`

### ISSUE THREAD

**Issue by zssyqpgdll** [dashingsoft/pyarmor#1485]
When I encrypt project packages using rft, I get the following error

```
$ pyarmor gen -O output -r --enable-rft Chat2DB-Landing
or
$ pyarmor gen -O output -r --assert-import --enable-rft --mix-str Chat2DB-Landing

Encryption succeeded！

However, running the encrypted project results in an error that the package cannot be found.
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen Chat2DB-Landing.chat2db.chat2model>", line 9, in <module>
ImportError: cannot import name 'ModelRequest' from 'entity.requestDto' (G:\pyarmor_encrypt\output\Chat2DB-Landing\chat2db\entity\requestDto.py)

```

How to solve it？

**Comment by jondy** [comment]
Please check the documentation `Inside RFT mode` to find the solution
