### ISSUE TITLE
[BUG] (docker group license) invalid license token, try to run `pyarmor reg` to register license again

### ISSUE THREAD

**Issue by hadywalied** [dashingsoft/pyarmor#1498]
when I run the pack command on docker using group license, I always get this error no matter what, the project is big and has over 700+ python scripts, it works normally on the local machine using the group license but when deployed on docker it doesn't work

`docker`
``` shell
(ADT) [root@ip-172-31-26-205 Builder]# pyarmor gen --pack ../dist/ADTv1/ADT_launcher -r ../ADT.py @file.list
INFO     Python 3.7.7
INFO     Pyarmor 8.3.5 (group), 006013, ADTv1
INFO     Platform linux.x86_64
INFO     implicitly set output to ".pyarmor/pack/dist"
INFO     extracting bundle "../dist/ADTv1/ADT_launcher"
INFO     search inputs ...
INFO     find script ../ADT.py
INFO     find script /home/data/ADT/LUT/Core/ElectronicsCore/Amplifiers/circuits/A010001F/A010001_Code.py
INFO     find script /home/data/ADT/LUT/Core/ElectronicsCore/Amplifiers/circuits/A010001F/A010001_LT.py

...

INFO     write .pyarmor/pack/dist/Utility/geometry.py
INFO     obfuscating file parseBool.py
INFO     patch runtime file
INFO     write .pyarmor/pack/dist/Utility/parseBool.py
INFO     obfuscating file filePaths.py
ERROR    invalid license token, try to run `pyarmor reg` to register license again
```

` docker host `
``` shell
(ADT) ubuntu@ip-172-31-26-205:~$ pyarmor-auth ~/pyarmor-device-regfile-6013.3.zip 
2023-09-25 14:11:43,927: work path: /home/ubuntu/.pyarmor/docker
2023-09-25 14:11:43,929: register "/home/ubuntu/pyarmor-device-regfile-6013.3.zip"
2023-09-25 14:11:43,983: listen container auth request on 0.0.0.0:29092
2023-09-25 14:12:22,118: receive request from ('172.31.28.57', 60974)
2023-09-25 14:12:22,118: send auth result to ('172.31.28.57', 60974)
2023-09-25 14:12:30,520: receive request from ('172.31.28.57', 48016)
2023-09-25 14:12:30,521: send auth result to ('172.31.28.57', 48016)
2023-09-25 14:12:31,797: receive request from ('172.31.28.57', 48030)

...

2023-09-25 14:26:51,545: send auth result to ('172.31.28.57', 54436)
2023-09-25 14:26:51,576: receive request from ('172.31.28.57', 54444)
2023-09-25 14:26:51,578: invalid license token, try to run `pyarmor reg` to register license again

```

`pyarmor.error.log `

``` shell
(ADT) [root@ip-172-31-26-205 Builder]# cat pyarmor.error.log
3143 MainProcess 2023-09-25 14:26:51,578
Traceback (most recent call last):
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/__main__.py", line 702, in main
    main_entry(sys.argv[1:])
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/__main__.py", line 690, in main_entry
    return args.func(ctx, args)
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/__main__.py", line 226, in cmd_gen
    builder.process(options, packer=packer)
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/generate.py", line 156, in process
    self._obfuscate_scripts()
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/generate.py", line 119, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/core/__init__.py", line 103, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 665, in generate_obfuscated_script
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 504, in process
  File "<maker>", line 510, in coserialize
  File "<maker>", line 555, in _build_ast_body
RuntimeError: invalid license token, try to run `pyarmor reg` to register license again
```

**Comment by jondy** [comment]
Duplicated.

Please upgrade Pyarmor to 8.3.9, and generate new device file.

**Comment by hadywalied** [comment]
@jondy Bro, the problem persists even after upgrading and all 

`pyarmor.error.log`
``` shell
(ADT) [root@ip-172-31-26-205 LUT]# cat pyarmor.error.log 
3127 MainProcess 2023-09-26 13:56:29,749
Traceback (most recent call last):
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/__main__.py", line 702, in main
    main_entry(sys.argv[1:])
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/__main__.py", line 690, in main_entry
    return args.func(ctx, args)
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/__main__.py", line 226, in cmd_gen
    builder.process(options, packer=packer)
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/generate.py", line 156, in process
    self._obfuscate_scripts()
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/generate.py", line 119, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/core/__init__.py", line 103, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 665, in generate_obfuscated_script
  File "/root/anaconda3/envs/ADT/lib/python3.7/site-packages/pyarmor/cli/__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 504, in process
  File "<maker>", line 510, in coserialize
  File "<maker>", line 555, in _build_ast_body
RuntimeError: invalid license token, try to run `pyarmor reg` to register license again

```

**Comment by jondy** [comment]
Please first check
https://pyarmor.readthedocs.io/en/latest/how-to/register.html#run-unlimited-dockers-in-offline-device
