### ISSUE TITLE
[BUG] `ERROR    Failed to handle request` when trying to register pro license

### ISSUE THREAD

**Issue by FredHaa** [dashingsoft/pyarmor#1506]
I'm trying to register my new pro license, but it fails to connect with the license server. I've tried from both the cli and web-ui.

I get the following error failing to connect:

```
INFO     Call pyarmor: ['reg', '-y', '-p', 'xxxx', 'pyarmor-regcode-xxxx.txt']
INFO     Python 3.10.12
INFO     Pyarmor 8.2.9 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     prepare "pyarmor-regcode-5372.txt"
INFO     query key file from server
ERROR    Failed to handle request
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frederik/.local/lib/python3.10/site-packages/pyarmor/webui/server.py", line 81, in do_POST
    result['data'] = self.root_handler.dispatch(self.path[1:], args)
  File "/home/frederik/.local/lib/python3.10/site-packages/pyarmor/webui/handler.py", line 43, in dispatch
    return getattr(self, 'do_' + path)(args)
  File "/home/frederik/.local/lib/python3.10/site-packages/pyarmor/webui/handler8.py", line 103, in do_register
    call_pyarmor(cmd_args, homepath=self._config['homepath'])
  File "/home/frederik/.local/lib/python3.10/site-packages/pyarmor/webui/handler8.py", line 54, in call_pyarmor
    pyarmor_main(extra_opts + args)
  File "/home/frederik/.local/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 686, in main_entry
    args.func(ctx, args)
  File "/home/frederik/.local/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 299, in cmd_reg
    info, msg = regsvr.prepare(regfile, args.product, upgrade=upgrade)
  File "/home/frederik/.local/lib/python3.10/site-packages/pyarmor/cli/register.py", line 298, in prepare
    with self._send_request(url) as res:
  File "/home/frederik/.local/lib/python3.10/site-packages/pyarmor/cli/register.py", line 278, in _send_request
    return urlopen(url, None, timeout, context=context)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
```

When I try to ping the server I get the IP but no responses:
```
frederik@mc-gpu-1 ~> ping api.dashingsoft.com                  
PING api.dashingsoft.com (119.23.58.77) 56(84) bytes of data.
```

I have tried with various VPNs, proxies, etc. but still no ping responses, so I have a hard time seeing it is due to my network settings.

I have 1 VPN where it is possible for me to connect to `pyarmor.dashingsoft.com` in the browser but here I get an insecure connection suggesting that your ssl certificates have expired.
Without the VPN I cannot access the site at all.

Any ideas what I can do in order to use my pro license?

**Comment by jondy** [comment]
`ping` is blocked by pyarmor server, so there is alwyas no repsonse for `ping`.

Try to use http proxy by setting enviornment variables `https_proxy` and `http_proxy`

**Comment by FredHaa** [comment]
As written, I have tried various proxies.

And I have validated they work using `http_proxy=PROXY curl ifconfig.me` which gives me a different IP than without using the proxy. I have tried with the https_proxy as well.

**Comment by FredHaa** [comment]
Setting https_proxy as well as http_proxy did something:

```
http_proxy=PROXY https_proxy=PROXY pyarmor reg -p "PRODUCT" pyarmor-regcode-5372.txt

INFO     Python 3.10.12
INFO     Pyarmor 8.3.9 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     prepare "pyarmor-regcode-5372.txt"
INFO     query key file from server
This license registration information will be

License Type    : pyarmor-pro
License To      : XXXX
License Product : PRODUCT

This license is about to be used for product "PRODUCT"

Are you sure to continue? (yes/no) yes
INFO     process activation file "pyarmor-regcode-5372.txt"
INFO     send request to server
INFO     write registration file "pyarmor-regfile-5372.zip"
INFO     register "pyarmor-regfile-5372.zip"
INFO     update license token
ERROR    request license token failed (3): <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2020 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: Cache Access Denied</title>
<style type="text/css"><!-- 
 /*
 * Copyright (C) 1996-2019 The Squid Software Foundation and contributors
 *
 * Squid software is distributed under GPLv2+ license and includes
 * contributions from numerous individuals and organizations.
 * Please see the COPYING and CONTRIBUTORS files for details.
 */
XYZXYZ_LONG_STRING_MAYBE_PRIVATE_KEY_XYZXYZ
```

Which created a `pyarmor-regfile-5372.zip` . However, it does not seem to work:
```
http_proxy=PROXY https_proxy=PROXY pyarmor gen --mix-str --enable-jit --assert-call app.py 

INFO     Python 3.10.12
INFO     Pyarmor 8.3.9 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     search inputs ...
INFO     find script app.py
INFO     find 1 top resources
ERROR    request license token failed (3): <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2020 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: Cache Access Denied</title>
<style type="text/css"><!-- 
 /*
 * Copyright (C) 1996-2019 The Squid Software Foundation and contributors
 *
 * Squid software is distributed under GPLv2+ license and includes
 * contributions from numerous individuals and organizations.
 * Please see the COPYING and CONTRIBUTORS files for details.
 */
XYZXYZ_LONG_STRING_MAYBE_PRIVATE_KEY_XYZXYZ
```

Also, requiring us to use a proxy is not viable for our production environment...

**Comment by FredHaa** [comment]
Hmm, just got it to work on a different machine using a different VPN.
