### ISSUE TITLE
[BUG] RFT mode generates wrong code on import statement like `import a.b.c as abc`

### ISSUE THREAD

**Issue by noobOriented** [dashingsoft/pyarmor#1509]
Code like `import a.b.c as abc` is mistranslated as `import a as ...` when using `--enable-rft`

e.g. `import numpy.typing as npt` (local modules don't work either):

## content of `main.py`
```python
import numpy.typing as npt

def main():
    print(npt)
    npt.ArrayLike

if __name__ == '__main__':
    main()
```

### Original script
```bash
$ python -m main
<module 'numpy.typing' from '/home/aetherai/playground/play-pyarmor/.venv/lib/python3.10/site-packages/numpy/typing/__init__.py'>
```

### Obfuscated Script
```bash
$ python -m main
<module 'numpy' from '/home/aetherai/playground/play-pyarmor/.venv/lib/python3.10/site-packages/numpy/__init__.py'>
Traceback (most recent call last):
  File "/home/aetherai/.pyenv/versions/3.10.7/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aetherai/.pyenv/versions/3.10.7/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<frozen __main__>", line 3, in <module>
  File "<frozen main>", line 10, in <module>
  File "<frozen main>", line 6, in pyarmor__1
  File "/home/aetherai/playground/play-pyarmor/.venv/lib/python3.10/site-packages/numpy/__init__.py", line 333, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'ArrayLike'
```

Name `npt` is bound to `numpy` instead of `numpy.typing`

### `pyarmor gen`
```bash
$ pyarmor gen --enable-rft main.py
INFO     Python 3.10.7
INFO     Pyarmor 8.3.6 (pro), 005363, aetherSlide
INFO     Platform linux.x86_64
INFO     search inputs ...
INFO     find script main.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'linux.x86_64'}
INFO     write dist/pyarmor_runtime_005363/pyarmor_runtime.so
INFO     patch runtime file
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "main"
INFO     obfuscating file main.py
INFO     write dist/main.py
INFO     obfuscate scripts OK
```

### pyarmor.trace.log
```
trace.rft            main:1 (import numpy.typing as pyarmor__2)
trace.rft            main:4 (main->pyarmor__1)
trace.rft            main:5 (print->pyarmor__3)
trace.rft            main:5 (npt->pyarmor__2)
trace.rft            main:6 (npt->pyarmor__2)
trace.rft            main:10 (main->pyarmor__1)
trace.co             main:1:<module>
trace.co             main:4:pyarmor__1
```

## Workaround
Change all
```python
import a.b.c as abc
```
to
```python
from a.b import c as abc
```

**Comment by jondy** [comment]
Thanks, it will be fixed in next release.

**Comment by jondy** [comment]
Fixed in 8.3.10

**Comment by noobOriented** [comment]
So excited to see the fast release!

However... the results of 8.3.10:

```
$ python -m main
(<module 'numpy.typing' from '/home/aetherai/playground/play-pyarmor/.venv/lib/python3.10/site-packages/numpy/typing/__init__.py'>,)
Traceback (most recent call last):
  File "/home/aetherai/.pyenv/versions/3.10.7/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aetherai/.pyenv/versions/3.10.7/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<frozen __main__>", line 3, in <module>
  File "<frozen main>", line 10, in <module>
  File "<frozen main>", line 6, in pyarmor__1
AttributeError: 'tuple' object has no attribute 'ArrayLike'
```

`npt` is bound to `tuple` instead of mudule.

```
$ pyarmor gen --enable-rft main.py
INFO     Python 3.10.7
INFO     Pyarmor 8.3.10 (pro), 005363, aetherSlide
INFO     Platform linux.x86_64
INFO     search inputs ...
INFO     find script main.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'linux.x86_64'}
INFO     write dist/pyarmor_runtime_005363/pyarmor_runtime.so
INFO     patch runtime file
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "main"
INFO     obfuscating file main.py
INFO     write dist/main.py
INFO     obfuscate scripts OK
```

**Comment by jondy** [comment]
Got it.

Here is a pre-release 8.3.11 which fix this problem

http://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.3.11.zip

**Comment by noobOriented** [comment]
8.3.11 works. Thanks for the kind support!
