### ISSUE TITLE
RuntimeError: out of license

### ISSUE THREAD

**Issue by Gaia-Wu** [dashingsoft/pyarmor#1519]
error.log:
101979 MainProcess 2023-10-08 11:33:44,974
Traceback (most recent call last):
  File "/home/wukaiyan/.conda/envs/py310_rasa358/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 702, in main
    main_entry(sys.argv[1:])
  File "/home/wukaiyan/.conda/envs/py310_rasa358/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 690, in main_entry
    return args.func(ctx, args)
  File "/home/wukaiyan/.conda/envs/py310_rasa358/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 229, in cmd_gen
    builder.process(options)
  File "/home/wukaiyan/.conda/envs/py310_rasa358/lib/python3.10/site-packages/pyarmor/cli/generate.py", line 156, in process
    self._obfuscate_scripts()
  File "/home/wukaiyan/.conda/envs/py310_rasa358/lib/python3.10/site-packages/pyarmor/cli/generate.py", line 119, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "/home/wukaiyan/.conda/envs/py310_rasa358/lib/python3.10/site-packages/pyarmor/cli/core/__init__.py", line 103, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 666, in generate_obfuscated_script
  File "/home/wukaiyan/.conda/envs/py310_rasa358/lib/python3.10/site-packages/pyarmor/cli/__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 505, in process
  File "<maker>", line 511, in coserialize
  File "<maker>", line 556, in _build_ast_body
RuntimeError: out of license

I don't know what's going on here. I use "pyarmor gen -O dist2 src/mypkg", some .py encrypted,but some do not.

**Comment by jondy** [comment]
Please search `out of license` in the documentation
