### ISSUE TITLE
[BUG] `UnicodeEncodeError: 'gbk' codec can't encode character '\u2070' in position 73: illegal multibyte sequence`

### ISSUE THREAD

**Issue by Sakura4036** [dashingsoft/pyarmor#1524]
我的python代码中含有Unicode字符，使用`--mix-str`报错：
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\drug\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2070' in position 73: illegal multibyte sequence
```

以下是含Unicode的代码段
```python
    superscript = str.maketrans("0123456789+-", "⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻")
    subscript = str.maketrans("0123456789", "₀₁₂₃₄₅₆₇₈₉")
```

尝试使用 过滤加密字符串 的方法，依旧是上面的错误。
```
pyarmor cfg mix.str:excludes ^ "/[^\x00-\x7F]+/"
```

**Comment by jondy** [comment]
请参阅文档设置正确 encoding

**Comment by Sakura4036** [comment]
pytest code:
```
aaa = "dafagfgasdf" + "₀₁₂₃₄₅₆₇₈₉"

def aa():
    print('aa')


def say():
    print('say', aa())
    print(aaa)


if __name__ == '__main__':
    pass
```

pyarmor encoding set:
```
>pyarmor cfg --encoding=utf-8
```
or
```
>pyarmor cfg --encoding=UTF-8
```


加密命令：
```
pyarmor gen  --enable-jit --obf-code 1 --outer --no-wrap --assert-import --restrict  --mix-str test.py
```

报错：
```
INFO     patch runtime file
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "aa"
INFO     obfuscating file aa.py
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\drug\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2080' in position 28: illegal multibyte sequence
Call stack:
  File "C:\Users\user\miniconda3\envs\drug\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\miniconda3\envs\drug\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\miniconda3\envs\drug\Scripts\pyarmor.exe\__main__.py", line 7, in <module>
    sys.exit(main_entry_8())
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\pyarmor.py", line 1643, in main_entry_8
    call_pyarmor_cli()
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\pyarmor.py", line 1617, in call_pyarmor_cli
    main()
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__main__.py", line 702, in main
    main_entry(sys.argv[1:])
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__main__.py", line 690, in main_entry
    return args.func(ctx, args)
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__main__.py", line 229, in cmd_gen
    builder.process(options)
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\generate.py", line 156, in process
    self._obfuscate_scripts()
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\generate.py", line 119, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\core\__init__.py", line 103, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 665, in generate_obfuscated_script
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 495, in process
  File "<maker>", line 495, in <listcomp>
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 881, in process
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__init__.py", line 46, in trace
    self.logger.info('%s:%s:%s', res.fullname, lineno, value)
Message: '%s:%s:%s'
Arguments: ('aa', 17, "'₀₁₂₃₄₅₆₇₈₉'")
INFO     write dist\aa.py
INFO     obfuscate scripts OK
```




> 请参阅文档设置正确 encoding
