### ISSUE TITLE
[BUG] `NameError: name '__assert_armored__' is not defined`

### ISSUE THREAD

**Issue by Sakura4036** [dashingsoft/pyarmor#1525]
使用`--mix-str`后加密脚本报错：

```
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen Pack.run>", line 14, in <module>
NameError: name '__assert_armored__' is not defined
```

运行平台windows，
运行版本：8.3.8
运行命令：
```
>pyarmor gen -O Packtest -r Pack --enable-jit --obf-code 1 --outer --no-wrap --assert-import --restrict
```

当不使用`--mix-str`后加密脚本运行正常

**Comment by jondy** [comment]
请按照模块提供必要的信息， Pyarmor 的版本是什么，升级到最新版本，另外，最好提供一个简单的例子脚本

**Comment by Sakura4036** [comment]
## test code:

package a
 - aa.py
```
aaa = "dafagfgasdf"

def aa():
    print('aa')


def say():
    print('say', aa())
    print(aaa)


if __name__ == '__main__':
    pass
```

package b
 - bb.py
```
from a import aa


def bb():
    print('bb')


def say():
    print('say', bb())


def merge():
    print('merge', aa.say(), say())


if __name__ == '__main__':
    pass
```

main.py
```
from b import bb

if __name__ == '__main__':
    bb.merge()
```

---
pyarmor：8.3.8, 集团版
python：3.7.12
平台：windows 10, anaconda


#### 无`--mix-str`加密命令：
```
pyarmor gen -O pack_test_py -r pack_test --enable-jit --obf-code 1 --outer --no-wrap --assert-import --restrict --mix-str
```
run main.py:
```
aa
say None
dafagfgasdf
bb
say None
merge None None
```

#### 有`--mix-str`加密命令：
```
pyarmor gen -O pack_test_py -r pack_test --enable-jit --obf-code 1 --outer --no-wrap --assert-import --restrict --mix-str
```
run main.py:
```
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen pack_test.main>", line 14, in <module>
NameError: name '__assert_armored__' is not defined

```

**Comment by jondy** [comment]
现在我都不知道你的 Pyarmor 的版本是多少，请首先升级到最新版本。

请参阅常见问题中的报告模版报告问题

**Comment by Sakura4036** [comment]
> 现在我都不知道你的 Pyarmor 的版本是多少，请首先升级到最新版本。
> 
> 请参阅常见问题中的报告模版报告问题

我说了呀：
![image](https://github.com/dashingsoft/pyarmor/assets/42060616/f2bcb85a-f9fc-4fd1-bffd-4a003a14df78)


```
Pyarmor 8.3.8 (group), 006112, Medix

License Type    : pyarmor-group
```

**Comment by jondy** [comment]
最好能提供一个实例，不要使用 `--pack`，直接加密之后运行能够重现。

**Comment by Sakura4036** [comment]
上面的代码就是我的测试实例包， 以及并没有使用`--pack`命令。

**加密使用的选项和命令**
```
$ pyarmor gen -O pack_test_py -r pack_test  --enable-jit --obf-code 1 --outer --no-wrap --assert-import

INFO     Python 3.7.12
INFO     Pyarmor 8.3.10 (group), xxx
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find package at pack_test
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write pack_test_py\pyarmor_runtime_006112\pyarmor_runtime.pyd
INFO     patch runtime file
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "pack_test"
INFO     obfuscating file main.py
INFO     write pack_test_py\pack_test\main.py
INFO     obfuscating file __init__.py
INFO     write pack_test_py\pack_test\__init__.py
INFO     obfuscating file aa.py
INFO     write pack_test_py\pack_test\a\aa.py
INFO     obfuscating file __init__.py
INFO     write pack_test_py\pack_test\a\__init__.py
INFO     obfuscating file bb.py
INFO     write pack_test_py\pack_test\b\bb.py
INFO     obfuscating file __init__.py
INFO     write pack_test_py\pack_test\b\__init__.py
INFO     obfuscate scripts OK
```

**运行加密后的main.py**
```
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen pack_test.main>", line 14, in <module>
NameError: name '__assert_armored__' is not defined
```
---

### 经过测试不使用`--no-wrap`则运行正常，不会报错

**Comment by jondy** [comment]
Fixed in 8.3.11
