### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\u2080' in position 28: illegal multibyte sequence

### ISSUE THREAD

**Issue by Sakura4036** [dashingsoft/pyarmor#1526]
pytest code:
```
aaa = "dafagfgasdf" + "₀₁₂₃₄₅₆₇₈₉"

def aa():
    print('aa')


def say():
    print('say', aa())
    print(aaa)


if __name__ == '__main__':
    pass
```

pyarmor encoding set:
```
>pyarmor cfg --encoding=utf-8
```
or
```
>pyarmor cfg --encoding=UTF-8
```

加密命令：
```
pyarmor gen  --enable-jit --obf-code 1 --outer --no-wrap --assert-import --restrict  --mix-str test.py
```

报错：
```
INFO     patch runtime file
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "aa"
INFO     obfuscating file aa.py
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\drug\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2080' in position 28: illegal multibyte sequence
Call stack:
  File "C:\Users\user\miniconda3\envs\drug\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\miniconda3\envs\drug\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\miniconda3\envs\drug\Scripts\pyarmor.exe\__main__.py", line 7, in <module>
    sys.exit(main_entry_8())
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\pyarmor.py", line 1643, in main_entry_8
    call_pyarmor_cli()
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\pyarmor.py", line 1617, in call_pyarmor_cli
    main()
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__main__.py", line 702, in main
    main_entry(sys.argv[1:])
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__main__.py", line 690, in main_entry
    return args.func(ctx, args)
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__main__.py", line 229, in cmd_gen
    builder.process(options)
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\generate.py", line 156, in process
    self._obfuscate_scripts()
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\generate.py", line 119, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\core\__init__.py", line 103, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 665, in generate_obfuscated_script
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 495, in process
  File "<maker>", line 495, in <listcomp>
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 881, in process
  File "C:\Users\user\miniconda3\envs\drug\lib\site-packages\pyarmor\cli\__init__.py", line 46, in trace
    self.logger.info('%s:%s:%s', res.fullname, lineno, value)
Message: '%s:%s:%s'
Arguments: ('aa', 17, "'₀₁₂₃₄₅₆₇₈₉'")
INFO     write dist\aa.py
INFO     obfuscate scripts OK
```

> 请参阅文档设置正确 encoding

_Originally posted by @Sakura4036 in https://github.com/dashingsoft/pyarmor/issues/1524#issuecomment-1756602683_

**Comment by Sakura4036** [comment]
Pyarmor 8.3.8 (group), 006112, Medix

License Type    : pyarmor-group

windows， anaconda3, python 3.7.12

**Comment by jondy** [comment]
如果启用了日志 `--enable-trace` ，可以尝试应用这个补丁
d89e6f455b08dabb33f57d413829de63ac028f8e

**Comment by Sakura4036** [comment]
使用上述补丁， 无报错， it works！

感谢！
