### ISSUE TITLE
[BUG] `enable-rft cause ImportError：cannot import name 'pyarmor__x' from 'x.xx' `

### ISSUE THREAD

**Issue by Sakura4036** [dashingsoft/pyarmor#1532]
**加密使用的选项和命令**
```
$ pyarmor gen -O pack_test_py -r pack_test  --enable-jit --obf-code 1 --outer  --mix-str --enable-rft
```
平台：
```
pyarmor 8.3.11,
python 3.7.12
windows 10
```

Suppose the project structure is:

```
project/
├── main.py
├── a/
    ├── __init__.py
    └── aa.py
├── b/
    ├── __init__.py
    └── bb.py
```

aa.py:
```
aaa = "dafagfgasdf" + "⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻"

def say():
    print(aaa)
```

bb.py:
```
from a.aa import say, aaa


def sayb():
    print("bbb")
    print("from a.aa import {}".format(aaa))


def merge():
    print('merge', )
    say()
    sayb()
```

main.py:
```
from b.bb import merge

if __name__ == '__main__':
    merge()
```
---

### Error
```
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen pack_test.main>", line 6, in <module>
  File "<frozen b.bb>", line 3, in <module>
  File "<frozen pack_test.b.bb>", line 5, in <module>
ImportError: cannot import name 'aaa' from 'a'
```
### trace log:
```
trace.co             pack_test.main:1:<module>
trace.co             pack_test.__init__:1:<module>
trace.rft            pack_test.a.aa:5 (aaa->pyarmor__3)
trace.rft            pack_test.a.aa:9 (print->pyarmor__5)
trace.rft            pack_test.a.aa:9 (aaa->pyarmor__3)
trace.mix.str        pack_test.a.aa:5:'dafagfgasdf'
trace.mix.str        pack_test.a.aa:5:'⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻'
trace.co             pack_test.a.aa:1:<module>
trace.co             pack_test.a.aa:8:say
trace.rft            pack_test.b.bb:5 (from a.aa import say, aaa as pyarmor__3)
trace.rft            pack_test.b.bb:8 (sayb->pyarmor__4)
trace.rft            pack_test.b.bb:9 (print->pyarmor__5)
trace.rft            pack_test.b.bb:10 (print->pyarmor__5)
trace.rft            pack_test.b.bb:10 (aaa->pyarmor__3)
trace.rft            pack_test.b.bb:14 (print->pyarmor__5)
trace.rft            pack_test.b.bb:16 (sayb->pyarmor__4)
trace.mix.str        pack_test.b.bb:10:'from a.aa import {}'
trace.co             pack_test.b.bb:1:<module>
trace.co             pack_test.b.bb:8:pyarmor__4
trace.co             pack_test.b.bb:13:merge
```

### When I import `aaa` in the `__init__.py` of the a module:
```
from .aa import aaa, say

__all__ = [
    'aaa',
    'say'
]
```
#### new Error:
```
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen pack_test.main>", line 6, in <module>
  File "<frozen b.bb>", line 3, in <module>
  File "<frozen pack_test.b.bb>", line 5, in <module>
  File "<frozen a>", line 3, in <module>
  File "<frozen pack_test.a>", line 5, in <module>
ImportError: cannot import name 'pyarmor__3' from 'a.aa'
``` 

trace log:
```
trace.co             pack_test.main:1:<module>
trace.co             pack_test.__init__:1:<module>
trace.rft            pack_test.a.aa:9 (print->pyarmor__5)
trace.mix.str        pack_test.a.aa:5:'dafagfgasdf'
trace.mix.str        pack_test.a.aa:5:'⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻'
trace.co             pack_test.a.aa:1:<module>
trace.co             pack_test.a.aa:8:say
trace.co             pack_test.a.__init__:1:<module>
trace.rft            pack_test.b.bb:5 (from a import say, aaa as pyarmor__3)
trace.rft            pack_test.b.bb:8 (sayb->pyarmor__4)
trace.rft            pack_test.b.bb:9 (print->pyarmor__5)
trace.rft            pack_test.b.bb:10 (print->pyarmor__5)
trace.rft            pack_test.b.bb:10 (aaa->pyarmor__3)
trace.rft            pack_test.b.bb:14 (print->pyarmor__5)
trace.rft            pack_test.b.bb:16 (sayb->pyarmor__4)
trace.mix.str        pack_test.b.bb:10:'from a.aa import {}'
trace.co             pack_test.b.bb:1:<module>
trace.co             pack_test.b.bb:8:pyarmor__4
trace.co             pack_test.b.bb:13:merge
```

我查看了 [深入了解RFT](https://pyarmor.readthedocs.io/zh/latest/topic/rftmode.html) , 不是所有在模块`__init__`中定义的属性都会被保留，而不是替换吗？不太理解为什么会出现这样的问题

**Comment by Sakura4036** [comment]
after using config `pyarmor cfg rft_excludes + "aaa"`,  it works fine

**Comment by Sakura4036** [comment]
我需要加密的应用比较复杂， 使用`--enable-rft`完整加密一次需要15分钟， 我遇到这种错误总不能一次一次修改配置然后重新加密吧，有没有什么其他方法呢？

**Comment by jondy** [comment]
重命名本来就是一个复杂的过程，并且不可能完全实现自动化，这是 Python 语言本身的特点决定的。

目前有些情况是必须进行人工配置的，以后会尽可能的改进算法，但是这需要一个过程。

**Comment by Sakura4036** [comment]
那针对这种复杂情况我应该如何操作可以快速找出应用中出错且需要修改的重命名变量呢？ 

> 我需要加密的应用比较复杂， 使用`--enable-rft`完整加密一次需要30分钟， 我遇到这种错误总不能一次一次修改配置然后重新加密吧，有没有什么其他方法呢？

**Comment by jondy** [comment]
请关注 Pyarmor 的版本更新，在后续版本会有优化的
