### ISSUE TITLE
[BUG] code does not run with joblib parallel after obfuscating using pyarmor

### ISSUE THREAD

**Issue by andersonspy** [dashingsoft/pyarmor#1537]
the codes do not run until I manually interrupt it and the following errors are shown:
```
pyarmor gen -O dst Codes
INFO     Python 3.9.16
INFO     Pyarmor 8.3.11 (pro), 005387, RCBld
INFO     Platform windows.x86_64

```
Starting 8 workers in parallel.
错误: 没有找到进程 "18516"。
错误: 没有找到进程 "26360"。
错误: 没有找到进程 "2168"。
错误: 没有找到进程 "4156"。
错误: 没有找到进程 "9460"。
错误: 没有找到进程 "20620"。
错误: 没有找到进程 "22208"。
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen Codes.RCBldSim>", line 589, in <module>
  File "<frozen Codes.RCBldSim>", line 571, in main
  File "<frozen Codes.RCBldSim>", line 501, in calibrate_CEN
  File "<frozen Codes.differentialevolution>", line 193, in differential_evolution
  File "<frozen Codes.differentialevolution>", line 372, in solve
  File "<frozen Codes.JLpool>", line 51, in map
  File "C:\Users\ander\anaconda3\envs\RCBldSim\lib\site-packages\joblib\parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "C:\Users\ander\anaconda3\envs\RCBldSim\lib\site-packages\joblib\parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\ander\anaconda3\envs\RCBldSim\lib\site-packages\joblib\parallel.py", line 1707, in _retrieve
    time.sleep(0.01)

**Comment by andersonspy** [comment]
Just to add that the original code can run successfully in parallel.

**Comment by jondy** [comment]
尝试使用 `--obf-code 0` 去加密需要并行的代码

如果没有使用第三方库，请提供一个能够重现问题的简单脚本和重现步骤

**Comment by andersonspy** [comment]
> 尝试使用 `--obf-code 0` 去加密需要并行的代码
> 
> 如果没有使用第三方库，请提供一个能够重现问题的简单脚本和重现步骤

嗯，用常规加密方法时使用--obf-code 0对并行部分代码进行加密就可以了~但是我的代码还是无法在-enable-rft模式下顺利实现加密，加密完的程序经常出现一些函数无法调用的错误。

**Comment by jondy** [comment]
RFT 模式的使用请参阅文档中 `深入 RFT 模式` 的相关内容
