### ISSUE TITLE
[BUG] `OSError: could not get source code`

### ISSUE THREAD

**Issue by saucebing** [dashingsoft/pyarmor#1567]
在使用pyarmor 8.3.3对模型推理代码进行加密之后，在推理的过程出现下面的错误，triton这个包已经安装，经过排查，发现只要含有带@triton.jit的装饰器的python代码都会出现这个错误，详细错误如下：
```
root@localhost:/root/test# python main.py 
triton not installed.
Traceback (most recent call last):
  File "/root/test/dist/main.py", line 1, in <module>
    from quantization.quantizer import QuantForLLM
  File "<frozen quantization.quantizer>", line 3, in <module>
  File "<frozen quantization.quantizer>", line 3, in <module>
  File "<frozen quantization.llama.quantization>", line 3, in <module>
  File "<frozen quantization.llama.quantization>", line 6, in <module>
  File "<frozen quantization.llama.gptq_for_llama>", line 3, in <module>
  File "<frozen quantization.llama.gptq_for_llama>", line 10, in <module>
  File "<frozen quantization.llama.quant>", line 3, in <module>
  File "<frozen quantization.llama.quant>", line 2, in <module>
  File "<frozen quantization.llama.quant.fused_attn>", line 3, in <module>
  File "<frozen quantization.llama.quant.fused_attn>", line 9, in <module>
  File "/usr/local/lib/python3.10/site-packages/triton/runtime/jit.py", line 542, in jit
    return decorator(fn)
  File "/usr/local/lib/python3.10/site-packages/triton/runtime/jit.py", line 534, in decorator
    return JITFunction(
  File "/usr/local/lib/python3.10/site-packages/triton/runtime/jit.py", line 416, in init
    self.src = textwrap.dedent(inspect.getsource(fn))
  File "/usr/local/lib/python3.10/inspect.py", line 1139, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/local/lib/python3.10/inspect.py", line 1121, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/local/lib/python3.10/inspect.py", line 958, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

**Comment by jondy** [comment]
加密后的脚本是无法得到 source code 的，这不是 bug。

**Comment by saucebing** [comment]
感谢您的解答，您的意思是如果代码中使用了@triton.jit这种装饰器，pyarmor是不支持这段代码加密后运行的是吧，有没有什么解决方法或者替代方案？

**Comment by hkunzhe** [comment]
> 可以考虑使用 `--obf-code 0` 加密部分代码。

仍然还是会出现相同的问题，请问有解决方法吗？

**Comment by jondy** [comment]
可以看一下 9.1+ 中新功能 RFT 加密脚本能否满足需要
https://eke.dashingsoft.com/pyarmor/docs/en/index.html
