### ISSUE TITLE
[BUG] `DLL load failed while importing pytransform3: The specified module could not be found` in platform windows.x86_64 for Python3.11

### ISSUE THREAD

**Issue by remackad** [dashingsoft/pyarmor#1604]
I use Anaconda.
When I install Python 3.11 in the environment, but I get an error.
```
(pyarmor) PS C:\Portable\VS\projects\pyarmor> pyarmor gen .\little.py
INFO     Python 3.11.5
INFO     Pyarmor 8.4.3 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find script little.py
INFO     find 1 top resources
ERROR    DLL load failed while importing pytransform3: The specified module could not be found.
```
Error log
```
18144 MainProcess 2023-11-24 18:58:40,897
Traceback (most recent call last):
  File "C:\Portable\Conda\envs\pyarmor\Lib\site-packages\pyarmor\cli\__main__.py", line 718, in main
    main_entry(sys.argv[1:])
  File "C:\Portable\Conda\envs\pyarmor\Lib\site-packages\pyarmor\cli\__main__.py", line 706, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\Conda\envs\pyarmor\Lib\site-packages\pyarmor\cli\__main__.py", line 236, in cmd_gen
    builder.process(options)
  File "C:\Portable\Conda\envs\pyarmor\Lib\site-packages\pyarmor\cli\generate.py", line 148, in process
    Pytransform3.pre_build(self.ctx)
  File "C:\Portable\Conda\envs\pyarmor\Lib\site-packages\pyarmor\cli\core\__init__.py", line 117, in pre_build
    m = Pytransform3.init(ctx)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\Conda\envs\pyarmor\Lib\site-packages\pyarmor\cli\core\__init__.py", line 95, in init
    Pytransform3._pytransform3 = m = _import_pytransform3()
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\Conda\envs\pyarmor\Lib\site-packages\pyarmor\cli\core\__init__.py", line 75, in _import_pytransform3
    return __import__(
           ^^^^^^^^^^^
ImportError: DLL load failed while importing pytransform3: The specified module could not be found.
```
```
def _import_pytransform3():
    try:
        return __import__(
            'pytransform3', globals=globals(), locals=locals(),
            fromlist=('__pyarmor__',), level=1
        )
    except ModuleNotFoundError: <-------------------- This except doesn't work
        plat, arch = format_platform()
        modname = '.'.join([plat, arch, 'pytransform3'])
        return __import__(
            modname, globals=globals(), locals=locals(),
            fromlist=('__pyarmor__',), level=1
        )
```
There is no error on python 3.10.
```
ls c:\Portable\Conda\envs\pyarmor\Lib\site-packages\pyarmor\cli\core\

    Directory: C:\Portable\Conda\envs\pyarmor\Lib\site-packages\pyarmor\cli\core

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          24.11.2023    18:56                __pycache__
d----          12.11.2023    14:05                themida
d----          24.11.2023    19:18                windows
-a---          24.11.2023     1:45           4680 __init__.py
-a---          24.11.2023     1:45           1513 features.py
-a---          24.11.2023     1:45         617472 pyarmor_runtime.pyd
-a---          24.11.2023     1:45         453632 pytransform3.pyd
-a---          24.11.2023     1:45           2798 runtime.py
```
```
pip install --upgrade --force-reinstall  pyarmor.cli.core.windows
Collecting pyarmor.cli.core.windows
  Using cached pyarmor.cli.core.windows-5.4.0-cp311-none-any.whl.metadata (808 bytes)
Using cached pyarmor.cli.core.windows-5.4.0-cp311-none-any.whl (835 kB)
Installing collected packages: pyarmor.cli.core.windows
  Attempting uninstall: pyarmor.cli.core.windows
    Found existing installation: pyarmor.cli.core.windows 5.4.0
    Uninstalling pyarmor.cli.core.windows-5.4.0:
      Successfully uninstalled pyarmor.cli.core.windows-5.4.0
Successfully installed pyarmor.cli.core.windows-5.4.0
```

**Comment by jondy** [comment]
Please install `pyarmor.cli.core`, other than `pyarmor.cli.core.windows`

**Comment by jondy** [comment]
Please upgrade Pyarmor to the latest version 8.4.4

**Comment by hello-abson** [comment]
Python 3.11.11

pyarmor                           9.1.1
pyarmor.cli.core                  7.6.4
pyarmor-webui                     2.6

pytransform3.pyd 导入表显示的是python312  
![Image](https://github.com/user-attachments/assets/29401570-78bf-4b63-861e-dd39c9dc0c60)
