### ISSUE TITLE
RuntimeError: invalid license token, try to run `pyarmor reg` to register license again - observed while using Docker

### ISSUE THREAD

**Issue by goraje** [dashingsoft/pyarmor#1605]
While using Pyarmor 8.4.3 with Docker I ran into a problem, where after successfully obfuscating some number of files in a Python package the process crashes with "RuntimeError: invalid license token, try to run `pyarmor reg` to register license again". I've reproduced the same scenario on a VM and the obfuscation completed as expected.

pyarmor.debug.log (redacted)
```
2023-11-24 14:40:34,541 Python 3.9.18
2023-11-24 14:40:34,542 Pyarmor 8.4.3 (group), 006005, ******
2023-11-24 14:40:34,544 Platform linux.aarch64
2023-11-24 14:40:34,544 native platform linux.aarch64
2023-11-24 14:40:34,544 home path: /home/builder/.pyarmor
2023-11-24 14:40:34,544 use runtime platforms: ['darwin.arm64']
2023-11-24 14:40:34,545 command options: {'output': '/home/builder/standalone/armored/*****/darwin.arm64/src3.9', 'no_runtime': False, 'enable_jit': True, 'obf_code': 2, 'import_prefix': 1, 'platforms': ['darwin.arm64'], 'expired': '.2024-02-22', 'inputs': ['src/*****']}
2023-11-24 14:40:34,546 install plugin: MultiPythonPlugin
2023-11-24 14:40:34,547 search inputs ...
2023-11-24 14:40:34,547 find package at src/*****
2023-11-24 14:40:34,553 find 1 top resources
2023-11-24 14:40:34,634 patching runtime data at 579680
2023-11-24 14:40:34,634 patch runtime file OK
2023-11-24 14:40:34,644 patching runtime data at 579680
2023-11-24 14:40:34,644 patch runtime file OK
2023-11-24 14:40:34,649 patching runtime data at 579680
2023-11-24 14:40:34,650 patch runtime file OK
2023-11-24 14:40:34,653 start to generate runtime files
2023-11-24 14:40:34,653 target platforms {'darwin.arm64'}
2023-11-24 14:40:34,655 got /home/builder/.local/python/versions/3.9.18/lib/python3.9/site-packages/pyarmor/cli/core/darwin/arm64/pyarmor_runtime.so
2023-11-24 14:40:34,656 write /home/builder/standalone/armored/*****darwin.arm64/src3.9/*****/pyarmor_runtime_006005/pyarmor_runtime.so
2023-11-24 14:40:34,656 patching runtime data at 591824
2023-11-24 14:40:34,656 patch runtime file OK
2023-11-24 14:40:34,656 call post runtime plugin <class 'pyarmor.cli.plugin.MultiPythonPlugin'>
2023-11-24 14:40:34,656 generate runtime files OK
2023-11-24 14:40:34,657 start to obfuscate scripts
2023-11-24 14:40:34,657 process resource "*****"
... (lots of output where everything goes smoothly)
2023-11-24 14:42:54,759 patch runtime file OK
2023-11-24 14:42:54,775 patching runtime data at 579680
2023-11-24 14:42:54,775 patch runtime file OK
2023-11-24 14:42:54,788 patching runtime data at 579680
2023-11-24 14:42:54,789 patch runtime file OK
2023-11-24 14:42:54,804 patching runtime data at 579680
2023-11-24 14:42:54,804 patch runtime file OK
2023-11-24 14:42:54,881 unknown error, please check pyarmor.error.log
2023-11-24 14:42:54,904 invalid license token, try to run `pyarmor reg` to register license again
```

pyarmor.error.log
```
55 MainProcess 2023-11-24 14:42:54,887
Traceback (most recent call last):
  File "/home/builder/.local/python/versions/3.9.18/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 718, in main
    main_entry(sys.argv[1:])
  File "/home/builder/.local/python/versions/3.9.18/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 706, in main_entry
    return args.func(ctx, args)
  File "/home/builder/.local/python/versions/3.9.18/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 236, in cmd_gen
    builder.process(options)
  File "/home/builder/.local/python/versions/3.9.18/lib/python3.9/site-packages/pyarmor/cli/generate.py", line 157, in process
    self._obfuscate_scripts()
  File "/home/builder/.local/python/versions/3.9.18/lib/python3.9/site-packages/pyarmor/cli/generate.py", line 120, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "/home/builder/.local/python/versions/3.9.18/lib/python3.9/site-packages/pyarmor/cli/core/__init__.py", line 103, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 675, in generate_obfuscated_script
  File "/home/builder/.local/python/versions/3.9.18/lib/python3.9/site-packages/pyarmor/cli/__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 496, in process
  File "<maker>", line 496, in <listcomp>
  File "/home/builder/.local/python/versions/3.9.18/lib/python3.9/site-packages/pyarmor/cli/__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 1016, in process
  File "<maker>", line 999, in pyarmor_core_233
RuntimeError: invalid license token, try to run `pyarmor reg` to register license again
```

 - the `pyarmor-auth` service was running the whole time
 - I was trying to build a multi-Python package for `darwin.arm64` on a `linux.aarch64` machine (not `universal`)
 - the command that I used was `python3.9 -m pyarmor.cli --debug gen -e .2024-02-22 --obf-code 2 --platform darwin.arm64 --enable-jit -O <destination> -i <scr_dir_of_python_package>`

**Comment by jondy** [comment]
Try to reinstall `pyarmor.cli.core` in docker container, make sure it's v5.4.1, not v5.4.0

**Comment by goraje** [comment]
This was in fact encountered on `pyarmor.cli.core` 5.4.1
```
$ python3.9 -m pip list
Package                  Version
------------------------ -------
pip                      23.3.1
pyarmor                  8.4.3
pyarmor.cli.core         5.4.1
pyarmor.cli.core.alpine  5.4.0
pyarmor.cli.core.darwin  5.4.0
pyarmor.cli.core.linux   5.4.0
pyarmor.cli.core.windows 5.4.0
setuptools               58.1.0
```

**Comment by goraje** [comment]
As I have noticed that you have pushed and update to all Pyarmor packages I updated my Docker container accordingly and I still get the same error.
```
$ python3.9 -m pip list
Package                  Version
------------------------ -------
pip                      23.3.1
pyarmor                  8.4.4
pyarmor.cli.core         5.4.2
pyarmor.cli.core.alpine  5.4.2
pyarmor.cli.core.darwin  5.4.2
pyarmor.cli.core.linux   5.4.2
pyarmor.cli.core.windows 5.4.2
setuptools               58.1.0
```

**Comment by jondy** [comment]
If the device reg file is generated by Pyarmor < 8.4, please generate device reg file again by Pyarmor 8.4.4.

If the device reg file is generated by Pyarmor 8.4+, please provide all the logs for `pyarmor -d reg ...`, `pyarmor-auth -d ...`

**Comment by goraje** [comment]
The reg file was generated with Pyarmor 8.4+.

`pyarmor -d reg` (in the Docker container):
```
python3.9 -m pyarmor.cli --debug reg pyarmor-device-regfile-6005.14.zip
INFO     Python 3.9.18
INFO     Pyarmor 8.4.4 (trial), 000000, non-profits
INFO     Platform linux.aarch64
DEBUG    native platform linux.aarch64
DEBUG    home path: /home/builder/.pyarmor
INFO     register "pyarmor-device-regfile-6005.14.zip"
DEBUG    extracting license.lic
DEBUG    extracting .pyarmor_capsule.zip
INFO     machine id in group license: m88f687b18066063d0b2c1ba3a844ca1c
INFO     got machine id: me3f477f03b6b571263f9a6158b3a01ef
INFO     got machine id: le3f477f03b6b571263f9a6158b3a01ef
INFO     got machine id: i4bafb552920ca31746fe28c6ec82e54d
INFO     got machine id: k71d5192de0ceef0cf257ca5111b5a96d
INFO     got machine id: g71d5192de0ceef0cf257ca5111b5a96d
INFO     got machine id: bf06a32b77488cfbbe87c721238e366df
INFO     no machine id matchs this group license
INFO     take this machine as docker container, and connect to docker host for authentication...
INFO     got docker host machine id: m88f687b18066063d0b2c1ba3a844ca1c
INFO     got docker host machine id: l88f687b18066063d0b2c1ba3a844ca1c
INFO     got docker host machine id: i88f687b18066063d0b2c1ba3a844ca1c
INFO     got docker host machine id: k99acb229632c1f0420f1ab514b726eb5
INFO     got docker host machine id: g601225dcc70acaba40530829d9d558d8
INFO     got docker host machine id: b205a32a9cd4139e51091c349bfee196b
DEBUG    extracting tokens/m88f687b18066063d0b2c1ba3a844ca1c
INFO     This license registration information:

License Type    : pyarmor-group
License No.     : pyarmor-vax-006005
License To      : *****
License Product : ******

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Offline obfuscation
```
`pyarmor-auth -d` (on the Docker host):
```
pyarmor-auth -d pyarmor-device-regfile-6005.14.zip 2>&1 | tee pyarmor-auth-debug.log
2023-11-28 08:00:51,290: work path: /home/jgora/.pyarmor/docker
2023-11-28 08:00:51,292: register "pyarmor-device-regfile-6005.14.zip"
2023-11-28 08:00:51,297: extracting license.lic
2023-11-28 08:00:51,297: extracting .pyarmor_capsule.zip
2023-11-28 08:00:51,297: machine id in group license: m88f687b18066063d0b2c1ba3a844ca1c
2023-11-28 08:00:51,300: got machine id: m88f687b18066063d0b2c1ba3a844ca1c
2023-11-28 08:00:51,300: this machine id matchs group license
2023-11-28 08:00:51,300: extracting tokens/m88f687b18066063d0b2c1ba3a844ca1c
2023-11-28 08:00:51,301: machine id: [b'm88f687b18066063d0b2c1ba3a844ca1c', b'l88f687b18066063d0b2c1ba3a844ca1c', b'i88f687b18066063d0b2c1ba3a844ca1c', b'k99acb229632c1f0420f1ab514b726eb5', b'g601225dcc70acaba40530829d9d558d8', b'b205a32a9cd4139e51091c349bfee196b']
2023-11-28 08:00:51,301: listen container auth request on 0.0.0.0:29092
2023-11-28 08:01:14,614: receive request from ('172.17.0.2', 50954)
2023-11-28 08:01:14,614: request data (64): b'PADHxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
2023-11-28 08:01:14,614: send auth result to ('172.17.0.2', 50954)
2023-11-28 08:01:14,614: response data (204): b'm88f687b18066063d0b2c1ba3a844ca1c\nl88f687b18066063d0b2c1ba3a844ca1c\ni88f687b18066063d0b2c1ba3a844ca1c\nk99acb229632c1f0420f1ab514b726eb5\ng601225dcc70acaba40530829d9d558d8\nb205a32a9cd4139e51091c349bfee196b\x00'
```

**Comment by goraje** [comment]
The Docker host is a Ubuntu 22.04 VM and the communication between the host and the container seems to work perfectly fine during the registration process and for the first 30 or so submodules of the package that I am obfuscating. Then suddenly during the obfuscation of one of the leftover submodules I get `invalid license token, try to run `pyarmor reg` to register license again`. The interesting thing is that even with `--debug` the `pyarmor-auth` side of the log shows that request was received and a response was sent normally (no indications of error). Could it be that during one of the requests from the Docker container the response sent by `pyarmor-auth` somehow gets truncated, some packet loss occurs and it generates the error? If so I could try and monitor the communication with `tcpdump`.

**Comment by jondy** [comment]
What's pyarmor.cli.core version in docker host? This bug has been fixed in pyarmor.cli.core=5.4.1.

**Comment by goraje** [comment]
The versions on the Docker host match the ones in the container
```
(pyarmor-venv) jgora@manypython:~$ pip list
Package                  Version
------------------------ -------
pip                      23.3.1
pyarmor                  8.4.4
pyarmor.cli.core         5.4.2
pyarmor.cli.core.darwin  5.4.2
pyarmor.cli.core.windows 5.4.2
setuptools               65.5.0
wheel                    0.41.2
```

**Comment by jondy** [comment]
Please apply this patch to `/path/to/pyarmor/cli/docker.py` in docker host
```patch
diff --git a/src/cli/docker.py b/src/cli/docker.py
index 3605f5fc..54e84987 100644
--- a/src/cli/docker.py
+++ b/src/cli/docker.py
@@ -26,6 +26,7 @@ class DockerAuthHandler(socketserver.BaseRequestHandler):
         try:
             logging.debug('request data (%d): %s', len(data), data)
             response = self.process(data)
+            logging.info('machine id: %s', Pytransform3.get_hd_info(22))
             logging.info('send auth result to %s', self.client_address)
             logging.debug('response data (%d): %s', len(response), response)
         except Exception as e:
```

Then run `pyarmor-auth xxxx.zip` (without `--debug`), after docker container failed, report the full log of `pyarmor-auth`.

**Comment by jondy** [comment]
How about run `pyarmor-auth` with extra option `--home` to specify a fresh path, for example
```
rm -rf ~/.pyarmor/docker2
pyarmor-auth --home ~/.pyarmor/docker2 xxx.zip
```

**Comment by jondy** [comment]
Thanks.

After check the log, I make a little change and upload a new version
http://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.4.5.zip

Reinstall it in docker container, and try it again.

If it still fails, just paste the last ~100 lines of pyarmor-debug.log

**Comment by goraje** [comment]
Hi, this time there is indeed additional information which indicates some sort of OOM issue:
Output of `tail -n 100 pyarmor.debug.log`:
```
2023-12-01 12:56:26,629 patching runtime data at 583808
2023-12-01 12:56:26,630 patch runtime file OK
2023-12-01 12:56:26,630 pyarmor-auth importing "pydkkionbeambldo.pyarmor_runtime"
2023-12-01 12:56:26,639 pyarmor-auth got key b'hcocpomloqfoieogkglk'
2023-12-01 12:56:26,640 write /home/builder/standalone/armored/*****_*****/darwin.arm64/src3.9/*****/pty_stream/middlewares/jumphosts/linux.py
2023-12-01 12:56:26,640 obfuscating file vmanage.py
2023-12-01 12:56:26,641 process inline marker
2023-12-01 12:56:26,641 parse script
2023-12-01 12:56:26,646 patching runtime data at 583808
2023-12-01 12:56:26,647 patch runtime file OK
2023-12-01 12:56:26,647 pyarmor-auth importing "pydkldkkfpnkfpdg.pyarmor_runtime"
2023-12-01 12:56:26,656 pyarmor-auth got key b'ekafchbnpilkjgkfbkin'
2023-12-01 12:56:26,657 process co
2023-12-01 12:56:26,660 process attribute
2023-12-01 12:56:26,665 patching runtime data at 583808
2023-12-01 12:56:26,665 patch runtime file OK
2023-12-01 12:56:26,666 pyarmor-auth importing "pydkmgbeahfijipo.pyarmor_runtime"
2023-12-01 12:56:26,675 pyarmor-auth got key b'pkoqofniillcclolhpoi'
2023-12-01 12:56:26,679 patching runtime data at 583808
2023-12-01 12:56:26,680 patch runtime file OK
2023-12-01 12:56:26,680 pyarmor-auth importing "pydkjmlmkkflboin.pyarmor_runtime"
2023-12-01 12:56:26,690 pyarmor-auth got key b'ahkcanadpqilmgnbjhcm'
2023-12-01 12:56:26,695 patching runtime data at 583808
2023-12-01 12:56:26,695 patch runtime file OK
2023-12-01 12:56:26,696 pyarmor-auth importing "pydkhcakomiiofnb.pyarmor_runtime"
2023-12-01 12:56:26,705 pyarmor-auth got key b'michinognegfelkkijfh'
2023-12-01 12:56:26,710 patching runtime data at 583808
2023-12-01 12:56:26,711 patch runtime file OK
2023-12-01 12:56:26,711 pyarmor-auth importing "pydkhkiphbhphidl.pyarmor_runtime"
2023-12-01 12:56:26,721 pyarmor-auth got key b'fojjgbloefkjcfglgbhh'
2023-12-01 12:56:26,726 patching runtime data at 583808
2023-12-01 12:56:26,726 patch runtime file OK
2023-12-01 12:56:26,727 pyarmor-auth importing "pydkafdjaemolebm.pyarmor_runtime"
2023-12-01 12:56:26,735 pyarmor-auth got key b'klkeepbelqgfglenfifd'
2023-12-01 12:56:26,740 patching runtime data at 583808
2023-12-01 12:56:26,741 patch runtime file OK
2023-12-01 12:56:26,741 pyarmor-auth importing "pydkljcqndhdlqgk.pyarmor_runtime"
2023-12-01 12:56:26,751 pyarmor-auth got key b'ipjqppomocddofeikmph'
2023-12-01 12:56:26,756 patching runtime data at 583808
2023-12-01 12:56:26,756 patch runtime file OK
2023-12-01 12:56:26,756 pyarmor-auth importing "pydkbnfildbppmab.pyarmor_runtime"
2023-12-01 12:56:26,766 pyarmor-auth got key b'jjiibojcekifahclchbb'
2023-12-01 12:56:26,771 patching runtime data at 583808
2023-12-01 12:56:26,771 patch runtime file OK
2023-12-01 12:56:26,771 pyarmor-auth importing "pydkbbchbnlkbqfk.pyarmor_runtime"
2023-12-01 12:56:26,781 pyarmor-auth got key b'mooplffnmkmopdcddkck'
2023-12-01 12:56:26,786 patching runtime data at 583808
2023-12-01 12:56:26,787 patch runtime file OK
2023-12-01 12:56:26,787 pyarmor-auth importing "pydkmdcbahjfbldk.pyarmor_runtime"
2023-12-01 12:56:26,795 pyarmor-auth got key b'aeeiappohiblbejnmjmc'
2023-12-01 12:56:26,800 patching runtime data at 583808
2023-12-01 12:56:26,800 patch runtime file OK
2023-12-01 12:56:26,800 pyarmor-auth importing "pydkpkcipgdieemg.pyarmor_runtime"
2023-12-01 12:56:26,808 pyarmor-auth got key b'mopdpecjebigidmfpibk'
2023-12-01 12:56:26,813 patching runtime data at 583808
2023-12-01 12:56:26,814 patch runtime file OK
2023-12-01 12:56:26,814 pyarmor-auth importing "pydkeqkokepkjkph.pyarmor_runtime"
2023-12-01 12:56:26,823 pyarmor-auth got key b'jofqkepofjdkljdgppep'
2023-12-01 12:56:26,828 patching runtime data at 583808
2023-12-01 12:56:26,828 patch runtime file OK
2023-12-01 12:56:26,828 pyarmor-auth importing "pydkjimibbdbdemd.pyarmor_runtime"
2023-12-01 12:56:26,837 pyarmor-auth got key b'jbngofbliokofdccnlbc'
2023-12-01 12:56:26,842 patching runtime data at 583808
2023-12-01 12:56:26,842 patch runtime file OK
2023-12-01 12:56:26,843 pyarmor-auth importing "pydkcpmhfbppkjnc.pyarmor_runtime"
2023-12-01 12:56:26,851 pyarmor-auth got key b'jdpqanmpbhcqfceinbkc'
2023-12-01 12:56:26,856 patching runtime data at 583808
2023-12-01 12:56:26,857 patch runtime file OK
2023-12-01 12:56:26,857 pyarmor-auth importing "pydkffbhdljqlcai.pyarmor_runtime"
2023-12-01 12:56:26,865 pyarmor-auth got key b'jkmmabejolcjnffenolq'
2023-12-01 12:56:26,870 patching runtime data at 583808
2023-12-01 12:56:26,870 patch runtime file OK
2023-12-01 12:56:26,870 pyarmor-auth importing "pydkhkhiechifflh.pyarmor_runtime"
2023-12-01 12:56:26,878 pyarmor-auth got key b'mhlmidejbcddbegcdjej'
2023-12-01 12:56:26,882 patching runtime data at 583808
2023-12-01 12:56:26,883 patch runtime file OK
2023-12-01 12:56:26,883 pyarmor-auth importing "pydkhocohlgjhjno.pyarmor_runtime"
2023-12-01 12:56:26,892 pyarmor-auth got key b'ldfkekaqajkoiifgpipb'
2023-12-01 12:56:26,896 patching runtime data at 583808
2023-12-01 12:56:26,897 patch runtime file OK
2023-12-01 12:56:26,897 pyarmor-auth importing "pydkjpmgmilebpfm.pyarmor_runtime"
2023-12-01 12:56:26,906 pyarmor-auth got key b'mkkennmdjlhhiecqpkoe'
2023-12-01 12:56:26,910 patching runtime data at 583808
2023-12-01 12:56:26,911 patch runtime file OK
2023-12-01 12:56:26,911 pyarmor-auth importing "pydkpfpqiqnojdjp.pyarmor_runtime"
2023-12-01 12:56:26,921 pyarmor-auth got key b'aqncmopfcfjlomepgghk'
2023-12-01 12:56:26,925 patching runtime data at 583808
2023-12-01 12:56:26,926 patch runtime file OK
2023-12-01 12:56:26,927 pyarmor-auth importing "pydkdockjpplnljb.pyarmor_runtime"
2023-12-01 12:56:26,936 pyarmor-auth got key b'ohdpcnlieiklndiibmgp'
2023-12-01 12:56:26,940 patching runtime data at 583808
2023-12-01 12:56:26,941 patch runtime file OK
2023-12-01 12:56:26,941 pyarmor-auth importing "pydklbjkpqpojdjm.pyarmor_runtime"
2023-12-01 12:56:26,949 pyarmor-auth got key b'aoebdjjfbbgbcfpbeonq'
2023-12-01 12:56:26,954 patching runtime data at 583808
2023-12-01 12:56:26,955 patch runtime file OK
2023-12-01 12:56:26,955 pyarmor-auth importing "pydkdcnqpnelmijp.pyarmor_runtime"
2023-12-01 12:56:26,975 pyarmor-auth exception: /tmp/pyarmor_dockerh5du_zla/pydkdcnqpnelmijp/pyarmor_runtime.so: cannot apply additional memory protection after relocation: Cannot allocate memory
2023-12-01 12:56:26,976 unknown error, please check pyarmor.error.log
2023-12-01 12:56:26,979 invalid license token, try to run `pyarmor reg` to register license again
```

**Comment by goraje** [comment]
Sorry it was actually part of the INFO log so I'm pasting the last lines here
```
INFO     pyarmor-auth importing "pydkdcnqpnelmijp.pyarmor_runtime"
INFO     pyarmor-auth exception: /tmp/pyarmor_dockerh5du_zla/pydkdcnqpnelmijp/pyarmor_runtime.so: cannot apply additional memory protection after relocation: Cannot allocate memory
DEBUG    unknown error, please check pyarmor.error.log
ERROR    invalid license token, try to run `pyarmor reg` to register license again
```

**Comment by jondy** [comment]
This is the problem, thanks.

It need re-design the algorithm for pyarmor-auth.

**Comment by goraje** [comment]
Looking forward to it. Glad I could be of assistance.

**Comment by jondy** [comment]
Try this pre-release version
http://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.4.5.zip    
                                                                     
Reinstall it in both docker container and docker host
