### ISSUE TITLE
[BUG] link bcc code failed

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#1607]
```
pyarmor -d gen \
        ./storage/modules \
        --output . \
        --use-runtime obfuscation/runtime_package \
        --recursive \
        --enable-jit \
        --enable-bcc \
        --private \
        -a 

INFO     Python 3.11.4
INFO     Pyarmor 8.4.4 (pro), myVAX, myNAME
INFO     Platform windows.x86
```

Windows 11 Pro - 22H2 - 22621.2213
Physical Device, not VM.

ERROR:

```
INFO     write C:/Users/Paulo/Desktop/MONTADOR/modules\routes\ordem_montagem.py
INFO     obfuscating file routes.py
DEBUG    process inline marker
DEBUG    parse script
INFO     start to generate bcc code ...
DEBUG    ignore function "descartar_account"
DEBUG    name 'tracelog' is not defined
DEBUG    c sources has been patched by plugin
DEBUG    CC: clang.exe
DEBUG    cflags: --target=i686-elf-linux -O3 -Wno-unsequenced -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-stack-protector -fPIC -mno-sse -std=c99 -c
Unsupport relocation type
DEBUG    unknown error, please check pyarmor.error.log
ERROR    link bcc code failed
```

pyarmor.error.log

```
13696 MainProcess 2023-11-26 11:47:36,684
Traceback (most recent call last):
  File "C:\Users\Paulo\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pyarmor\cli\__main__.py", line 718, in main
    main_entry(sys.argv[1:])
  File "C:\Users\Paulo\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pyarmor\cli\__main__.py", line 706, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pyarmor\cli\__main__.py", line 236, in cmd_gen
    builder.process(options)
  File "C:\Users\Paulo\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pyarmor\cli\generate.py", line 157, in process
    self._obfuscate_scripts()
  File "C:\Users\Paulo\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pyarmor\cli\generate.py", line 120, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Paulo\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pyarmor\cli\core\__init__.py", line 103, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 675, in generate_obfuscated_script
  File "C:\Users\Paulo\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 496, in process
  File "<maker>", line 496, in <listcomp>
  File "<bccmaker>", line 297, in process
RuntimeError: link bcc code failed
```

**Comment by jondy** [comment]
> DEBUG    c sources has been patched by plugin  

This log means you may write plugin to modify the c sources.

Please remove your plugin and test it again.

If it stll failed, please also provide a script which could reproduce this issue.
