### ISSUE TITLE
Obfuscation not done in a pyinstaller executable.

### ISSUE THREAD

**Issue by alexdesion** [dashingsoft/pyarmor#1626]
Hello.

I generated an executable of my python project using pyinstaller.

Then I followed the [documentation](https://pyarmor.readthedocs.io/en/stable/tutorial/obfuscation.html#packing-obfuscated-scripts) and I tried to obfuscate the pack scripts with 

`
pyarmor gen -O obfdist --pack dist_obs/main main.py
`

I ran both versions of the executable, the plain and the obfuscated. And for both, the output when an error occurs is almost the same:

**Output plain:**
user1@pc:~/projects/test_binary/dist$ ./main 
...
Traceback (most recent call last):
  File "main.py", line 219, in <module>
  File "main.py", line 82, in prepare_predictors
  File "src/predictor/d2_predictor.py", line 61, in __init__
  File "detectron2/model_zoo/model_zoo.py", line 143, in get_config_file
RuntimeError: COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml not available in Model Zoo!
[999699] Failed to execute script 'main' due to unhandled exception!

**Output obfuscated:**
user1@pc:~/projects/test_binary/dist_obs$ ./main 
...
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen main>", line 219, in <module>
  File "<frozen main>", line 82, in prepare_predictors
  File "src/predictor/d2_predictor.py", line 61, in __init__
  File "detectron2/model_zoo/model_zoo.py", line 143, in get_config_file
RuntimeError: COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml not available in Model Zoo!
[1000777] Failed to execute script 'main' due to unhandled exception!

If you take a look into the outputs, you can easily see that there was no obfuscation in any script, functions has the same names, errors occur exactly in the same lines of the scripts...

Am i missing something? Is this the expected behaviour?

**Comment by jondy** [comment]
Please check FAQ in the online documentation to find the common solution for packing issue

**Comment by alexdesion** [comment]
Could you please be more specific? I checked the online documentation, as I said in my post. The link I shared indicates:
`pyarmor gen -O obfdist --pack dist/foo foo.py`

_This command will obfuscate foo.py first, then repack dist/foo, replace the original foo.py with obfdist/foo.py, and append all the runtime files to bundle._

But this is not obfuscating anything, because when an error occurs, all number of lines matches with the non obfuscated scripts.

**Comment by Lampe2020** [comment]
I think you need to do `pyarmor gen foo.py` and then pack the obfuscated script with PyInstaller. I don't think pyarmor can replace the script packed inside an executable. But if you packed obfuscated code of course the packed code will be obfuscated.
