### ISSUE TITLE
[BUG] `RuntimeError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (1:10930)`

### ISSUE THREAD

**Issue by jakernel** [dashingsoft/pyarmor#1641]
加密后脚本，执行有时会报连接错误，有时又可以正常执行

加密脚本
```
$ pyarmor gen -O dist0 --outer run.py uiauto/
INFO     Python 3.8.10
INFO     Pyarmor 8.4.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find script run.py
INFO     find package at uiauto
INFO     find 2 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write dist0\pyarmor_runtime_000000\pyarmor_runtime.pyd
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "run"
INFO     obfuscating file run.py
INFO     write dist0\run.py
INFO     process resource "uiauto"
...
```

执行脚本报错
```
$ python dist0\run.py
Traceback (most recent call last):
  File "dist0\run.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "C:\Users\29811\workspace\uiautomator2\quick\dist0\pyarmor_runtime_000000\__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (1:10930)
```
再执行报错
```
$ python dist0\run.py
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
RuntimeError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (1:10930)
```
再执行又正常运行
```
$ python dist0\run.py
2023-12-26 11:33:13,003 - INFO - MainThread - adb设备数量=0, adb_list=[]
```

**Comment by jondy** [comment]
请查看文档中关于选项 `-e` 的用法
