### ISSUE TITLE
[BUG] Encryption fails if the second or later lines of comments at the beginning of the file contain some multibyte characters

### ISSUE THREAD

**Issue by irreg** [dashingsoft/pyarmor#1658]
### Environment
Python 3.8.9
Pyarmor 8.4.6
Windows 10/11 x64

#### File Structure
root
|- a.py

#### a.py
```py
#
# 円

# any code...
```

Execute: pyarmor gen a.py

### Result
```
>pyarmor gen a.py
INFO     Python 3.8.9
INFO     Pyarmor 8.4.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find script a.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write dist\pyarmor_runtime_000000\pyarmor_runtime.pyd
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "a"
INFO     obfuscating file a.py
ERROR    'cp932' codec can't decode byte 0x86 in position 10: illegal multibyte sequence
```

#### a.py
```py
# 円

# any code...
```

#### a.py
```py
#

# 円

# any code...
```

**Comment by jondy** [comment]
Could you run it with debug option `-d` and share the content `pyarmor.error.log`?

```
pyarmor -d gen a.py 
```

**Comment by irreg** [comment]
I tried with debug option

### console
```
pyarmor -d gen a.py
INFO     Python 3.8.9
INFO     Pyarmor 8.4.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
DEBUG    native platform windows.amd64
DEBUG    home path: C:\Users\Admin\.pyarmor
DEBUG    command options: {'no_runtime': False, 'inputs': ['a.py']}
DEBUG    install plugin: CodesignPlugin
DEBUG    install plugin: DarwinUniversalPlugin
INFO     search inputs ...
INFO     find script a.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
DEBUG    got c:\works\test1\.venv\lib\site-packages\pyarmor\cli\core\pyarmor_runtime.pyd
INFO     write dist\pyarmor_runtime_000000\pyarmor_runtime.pyd
DEBUG    patching runtime data at 517152
DEBUG    patch runtime file OK
DEBUG    call post runtime plugin <class 'pyarmor.cli.plugin.CodesignPlugin'>
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "a"
INFO     obfuscating file a.py
DEBUG    unknown error, please check pyarmor.error.log
ERROR    'cp932' codec can't decode byte 0x86 in position 7: illegal multibyte sequence
```

### pyarmor.error.log
```
17512 MainProcess 2024-01-16 18:46:42,346
Traceback (most recent call last):
  File "c:\works\test1\.venv\lib\site-packages\pyarmor\cli\__main__.py", line 718, in main
    main_entry(sys.argv[1:])
  File "c:\works\test1\.venv\lib\site-packages\pyarmor\cli\__main__.py", line 706, in main_entry
    return args.func(ctx, args)
  File "c:\works\test1\.venv\lib\site-packages\pyarmor\cli\__main__.py", line 236, in cmd_gen
    builder.process(options)
  File "c:\works\test1\.venv\lib\site-packages\pyarmor\cli\generate.py", line 157, in process
    self._obfuscate_scripts()
  File "c:\works\test1\.venv\lib\site-packages\pyarmor\cli\generate.py", line 120, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "c:\works\test1\.venv\lib\site-packages\pyarmor\cli\core\__init__.py", line 103, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 675, in generate_obfuscated_script
  File "c:\works\test1\.venv\lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 471, in process
  File "c:\works\test1\.venv\lib\site-packages\pyarmor\cli\resource.py", line 136, in readlines
    lines = f.readlines()
UnicodeDecodeError: 'cp932' codec can't decode byte 0x86 in position 7: illegal multibyte sequence
```

**Comment by jondy** [comment]
Please check encoding settings
```
pyarmor cfg encoding
```

Also search `encoding` in the online documentation to fix this issue
