### ISSUE TITLE
[BUG] RuntimeError: No error (1:10181) 绑定设备运行时报错

### ISSUE THREAD

**Issue by jakernel** [dashingsoft/pyarmor#1668]
使用如下命令获取硬件信息
```
$ python -m pyarmor.cli.hdinfo
Machine ID: 'mc2b13cf3a44d388e30bd66ca70f57321'
Default Harddisk Serial Number: 'WFL2HK96'
Default Mac address: 
Default IPv4 address:
Multiple Mac addresses: Unsupported hardware type with name
```
使用硬盘序列号加密报错，似乎少于10个字符就会报错
```
$ pyarmor gen -O dist0 -e 1 -b WFL2HK96 run.py uiauto/
INFO     Python 3.8.10
INFO     Pyarmor 8.4.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find script run.py
INFO     find package at uiauto
INFO     find 2 top resources
ERROR    invalid device info "WFL2HK96"
```
本机实际有两块硬盘，使用 `wmic` 命令查看序列号
```
$ wmic diskdrive get serialnumber
SerialNumber
WFL2HK96
001B_448B_4941_F342.
```
使用另一个硬盘序列号可以正常加密，但运行时也报错
```
$ pyarmor gen -O dist0 -e 1 -b 001B_448B_4941_F342. run.py uiauto/
INFO     Python 3.8.10
INFO     Pyarmor 8.4.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     search inputs ...
...

$ python dist0\run.py
Traceback (most recent call last):
  File "dist0\run.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "C:\Users\29811\workspace\uiautomator2\quick\dist0\pyarmor_runtime_000000\__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: 脚本许可证不可用于当前设备 (1:10147)
```

使用其它命令获取MAC地址，并加密，但是运行时报错
```
$ getmac -v

连接名          网络适配器      物理地址            传输名称
=============== =============== =================== ==========================================================
以太网          Realtek PCIe Gb 98-EE-CB-C8-4C-88   \Device\Tcpip_{35215B48-A064-498E-B100-A41868EA0F5E}
WLAN            Intel(R) Wi-Fi  78-2B-46-07-9A-2D   媒体已断开连接
蓝牙网络连接    Bluetooth Devic 78-2B-46-07-9A-21   媒体已断开连接

$ pyarmor gen -O dist0 -e 1 -b 98:ee:cb:c8:4c:88 run.py uiauto/
INFO     Python 3.8.10
INFO     Pyarmor 8.4.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     search inputs ...
...

$ python dist0\run.py
Traceback (most recent call last):
  File "dist0\run.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "C:\Users\29811\workspace\uiautomator2\quick\dist0\pyarmor_runtime_000000\__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: No error (1:10181)
```

**Comment by jondy** [comment]
硬盘序列号的长度检查问题在下一个版本会修正，请使用下面的预发布版本验证

https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.4.7.zip

请重新运行 `python -m pyarmor.cli.hdinfo` 查看硬件信息，使用其他方式获取的硬件信息可能和 Pyarmor 不匹配，关于选项 `-b` 的用法和格式说明，请参考文档以及命令选项手册中的说明。

**Comment by jakernel** [comment]
> 我的解决办法是，可以通过 `pyarmor-7 hdinfo` 去查询所有的硬盘，然后再选择性绑定另一块，所以你命令应该改成：`pyarmor gen -O dist0 -e 1 -b "/1:001B_448B_4941_F342" run.py uiauto/`
> 
> 需要注意的是磁盘最后的 `.` 这个字符串是不能写的

我测试还是不行~
```
$ pyarmor-7 hdinfo
INFO     Create trial license file: C:\Users\29811\.pyarmor\license.lic
INFO     PyArmor Trial Version 8.4.6
INFO     Python 3.8.10

Hardware informations got by PyArmor:

Serial number of default harddisk: "WFL2HK96"

Serial number with disk name:
        "/0:            WFL2HK96"
        "/1:001B_448B_4941_F342."

Failed to get mac address.

Multiple Mac addresses: "<

$ pyarmor gen -O dist0 -e 1 -b "/1:001B_448B_4941_F342" run.py uiauto/
INFO     Python 3.8.10
INFO     Pyarmor 8.4.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     search inputs ...
...

$ python dist0\run.py
Traceback (most recent call last):
  File "dist0\run.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "C:\Users\29811\workspace\uiautomator2\quick\dist0\pyarmor_runtime_000000\__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: 脚本许可证不可用于当前设备 (1:10147)
```

**Comment by jakernel** [comment]
> 硬盘序列号的长度检查问题在下一个版本会修正，请使用下面的预发布版本验证
> 
> https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.4.7.zip
> 
> 请重新运行 `python -m pyarmor.cli.hdinfo` 查看硬件信息，使用其他方式获取的硬件信息可能和 Pyarmor 不匹配，关于选项 `-b` 的用法和格式说明，请参考文档以及命令选项手册中的说明。

这个预发布包，解压后使用命令 `python setup.py install` 安装后，执行会报错
```
$ python -m pyarmor.cli.hdinfo
Traceback (most recent call last):
  File "C:\Users\Jake\scoop\apps\python38\current\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jake\scoop\apps\python38\current\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jake\scoop\apps\python38\current\lib\site-packages\pyarmor-8.4.7-py3.8.egg\pyarmor\cli\hdinfo.py", line 25, in <module>
    from pyarmor.cli.core import Pytransform3
ModuleNotFoundError: No module named 'pyarmor.cli.core'
```
依赖是在的
```
$ pip install pyarmor
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pyarmor in c:\users\29811\scoop\persist\python38\lib\site-packages\pyarmor-8.4.7-py3.8.egg (8.4.7)
Requirement already satisfied: pyarmor.cli.core~=5.4.3 in c:\users\29811\scoop\persist\python38\lib\site-packages\pyarmor.cli.core-5.4.3-py3.8-win-amd64.egg (from pyarmor) (5.4.3)
```
如果只建议用`python -m pyarmor.cli.hdinfo` 获取硬件信息，有没有单独打包好的小工具，避免在客户机上安装 `python` 环境

**Comment by jakernel** [comment]
> `pyarmor gen -O dist0 -e 1 -b "/1:001B_448B_4941_F342." run.py uiauto/` 把 `.` 加上再试试

嗯，加上 `.` 就可以，谢谢哈

**Comment by jondy** [comment]
@jakernel

目前硬件信息是直接使用 Pyarmor 7 的功能的，所以以前使用的获取硬件信息的方式都是可用的，`pyarmor.cli.hdinfo` 只是 Pyarmor 8 中额外提供的一种方式。

**Comment by jondy** [comment]
Fixed in v8.4.7
