### ISSUE TITLE
[BUG] `ImportError: libdl.so: cannot open shared object file` on Android 13, built w/ --platform android.aarch64

### ISSUE THREAD

**Issue by mcharvat90** [dashingsoft/pyarmor#1674]
Dear developer,
I am facing an issue when using cross-platform obfuscation.

When obfuscating files on Linux x86-64 with the --platform android.aarch64 and then porting it to an Android 13-based phone running Ubuntu 22 under Termux, the obfuscated program gives me the error: "ImportError: libdl.so: cannot open shared object file: No such file or directory"

It seems to me that building with --platform android.aarch64 uses an old libdl.so that was replaced by libdl.so.2 in modern distributions on aarch64. When I obfuscate directly on the Android device (within Ubuntu 22 under Termux} the obfuscated code works. Could you update your code to use libdl.so.2 when obfuscating the program with --platform android.aarch64, please?

**Full error - running obfuscated code on Android device:** 
```
root@localhost:~/program/android.aarch64# uname -a
Linux localhost 5.10.136-android12-9-00021-g821df8f5bd36-ab9585204 #1 SMP PREEMPT Thu Feb 9 13:08:46 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
root@localhost:~/program/android.aarch64# uname -p
aarch64
root@localhost:~/program/android.aarch64# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@localhost:~/program/android.aarch64# ./run.py
Traceback (most recent call last):
  File "/root/program/android.aarch64/run.py", line 3, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "/root/program/android.aarch64/pyarmor_runtime_000000/__init__.py", line 3, in <module>
    __pyarmor__ = __import__("py%d%d.pyarmor_runtime" % py_version[:2], globals(), locals(), ["__pyarmor__"], 1).__pyarmor__
ImportError: libdl.so: cannot open shared object file: No such file or directory
```

**Build on linux.x86_64:**
```
mcharvat@NTBK:~$ pyarmor gen -O dist --platform android.aarch64 --assert-call run.py
INFO     Python 3.11.7
INFO     Pyarmor 8.4.6 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     use runtime platforms: ['android.aarch64']
INFO     search inputs ...
INFO     find script run.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'android.aarch64'}
INFO     write dist/pyarmor_runtime_000000/pyarmor_runtime.so
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "run"
INFO     obfuscating file run.py
INFO     write dist/run.py
INFO     obfuscate scripts OK
```

**Comment by jondy** [comment]
First it should use same `android.aarch64/pyarmor_runtime.so` both cross-platform and native platform, make sure they're same version, or reinstall package `pyarmor.cli.core.android`

Second, in termux please use command `patchelf` to fix dll dependencies issue, just write a plugin to patch the output `pyarmor_runtime.so`

Refer to
https://pyarmor.readthedocs.io/en/latest/tutorial/installation.html#termux-issues

It's not for this case, but show how to use patchelf to fix dll issue

**Comment by mcharvat90** [comment]
Hello,

Thank you for your reply and provided hints. I have reinstalled/ipgraded PyArmor on a "build" Linux x86-64 machine. Then I obfuscated the file with --platform android.aarch64 and transferred it to an Android device running Termux with Ubuntu 22 (aarch64).

After, I tried to patch only libdl.so using the following commands within Termux:
```
patchelf --remove-needed libm.so pyarmor_runtime.so
patchelf --add-needed libdl.so.2 pyarmor_runtime.so
```

This resulted in the following error:
```
Traceback (most recent call last):
  File "/root/program/android.aarch64/run.py", line 3, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "/root/program/android.aarch64/pyarmor_runtime_000000/__init__.py", line 3, in <module>
    __pyarmor__ = __import__("py%d%d.pyarmor_runtime" % py_version[:2], globals(), locals(), ["__pyarmor__"], 1).__pyarmor__
ImportError: /lib/aarch64-linux-gnu/libc.so: invalid ELF header
```

As a second step, I attempted to fully patch all libraries within Termux:
```
patchelf --remove-needed libdl.so pyarmor_runtime.so
patchelf --remove-needed libm.so pyarmor_runtime.so
patchelf --remove-needed libc.so pyarmor_runtime.so
patchelf --add-needed libcrypt.so.1 pyarmor_runtime.so
patchelf --add-needed libpthread.so.0 pyarmor_runtime.so
patchelf --add-needed libdl.so.2 pyarmor_runtime.so
patchelf --add-needed libutil.so.1 pyarmor_runtime.so
patchelf --add-needed libm.so.6 pyarmor_runtime.so
patchelf --add-needed libc.so.6 pyarmor_runtime.so
```

Unfortunatelly, that resulted in following error:
```
./run.py
Inconsistency detected by ld.so: dl-version.c: 204: _dl_check_map_versions: Assertion `needed != NULL' failed!
```

Any further tips or suggestions would be greatly appreciated.

Thanks,
Michal

**Comment by jondy** [comment]
Use `ldd /path/to/pyarmor_runtime.so` in Termux to check dependencies.

Since native building works, compare the output `ldd pyarmor_runtime.so` by native building with cross-platform building

**Comment by mcharvat90** [comment]
Hello,
crossplatform build (on linux.x86_64 w/ --platform android.aarch64, then ported to Termux):
```
root@localhost:~ ldd pyarmor_runtime.so
./pyarmor_runtime.so: error while loading shared libraries: /lib/aarch64-linux-gnu/libc.so: invalid ELF header

```
**native build / obfuscation in Termux:**
```
root@localhost:~ ldd pyarmor_runtime.so
        linux-vdso.so.1 (0x0000007e30b0d000)
        libcrypt.so.1 => /lib/aarch64-linux-gnu/libcrypt.so.1 (0x0000007e30a10000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007e309f0000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007e309d0000)
        libutil.so.1 => /lib/aarch64-linux-gnu/libutil.so.1 (0x0000007e309b0000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007e30910000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007e30760000)
        /lib/ld-linux-aarch64.so.1 (0x0000003000000000)
```

**crossplatform build (on linux.x86_64 w/ --platform linux.aarch64, then ported to Termux):**
```
root@localhost:~ ldd pyarmor_runtime.so
        linux-vdso.so.1 (0x000000746502a000)                             
        libcrypt.so.1 => /lib/aarch64-linux-gnu/libcrypt.so.1 (0x0000007464f30000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007464f10000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007464ef0000)                                                                
        libutil.so.1 => /lib/aarch64-linux-gnu/libutil.so.1 (0x0000007464ed0000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007464e30000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007464c80000)
        /lib/ld-linux-aarch64.so.1 (0x0000003000000000) 
```

This build works, so assuming to use linux.aarch64 and not android (--platform) for our case within Termux.

Closing the ticket, not a bug. I suggest to add this info to FAQ.

Thanks,
Michal
