### ISSUE TITLE
[BUG] `File ".pyarmor\pack\dist\main.py", line 2, in <module>`  Doesn't run the program.

### ISSUE THREAD

**Issue by sspark92** [dashingsoft/pyarmor#1704]
I'm currently developing a program with Python and using the PyArmor library for obfuscation. However, the program intermittently fails to run after obfuscation, producing an error. How can I resolve this issue?

Environment:

OS: Windows 11
Python version: 3.9
PyArmor version: 8.4.6   license : basic 
PyInstaller version: 5.4.1

Error Message:
Traceback (most recent call last):
 File ".pyarmor\pack\dist\main.py", line 2, in <module>
File "<frozen importlib._boostrap>", line 1007, in _find_and_load
File "<frozen importlib._boostrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._boostrap>", line 680, in _load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 2, in <module>
RuntimeError: [WinError 0] 작업을 완료했습니다(1:10930)

**Comment by jondy** [comment]
Try to upgrade Pyarmor to 8.5.0, and test it again.
