### ISSUE TITLE
[BUG] `ERROR    request license token failed (3): <h1>Server Error (500)</h1>`

### ISSUE THREAD

**Issue by smart0313** [dashingsoft/pyarmor#1706]
pyarmor信息
Package                 Version
'''
----------------------- -------
pyarmor                   8.5.0
pyarmor.cli.core          6.5.0
'''

执行>pyarmor reg -g 1
'''
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86
INFO     generating device file ".pyarmor\group\pyarmor-group-device.1"
INFO     current machine id is "abd23d6c7de1eab05bebf9753f7ceae5e"
INFO     device file has been generated successfully
'''

执行>pyarmor reg -g 1 pyarmor-regfile-6219.zip
'''
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86
INFO     register device file ".pyarmor\group\pyarmor-group-device.1"
INFO     use group license "pyarmor-regfile-6219.zip"
INFO     send request to server
INFO     write registration file "pyarmor-device-regfile-6219.1.zip"
INFO     please copy deivce regfile to offline device and run
INFO         pyarmor reg pyarmor-device-regfile-6219.1.zip
INFO     The device regfile has been generated successfully
'''

执行>C:\workspace\rpa-workwechat>pyarmor reg pyarmor-device-regfile-6219.1.zip
'''
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86
INFO     register "pyarmor-device-regfile-6219.1.zip"
INFO     machine id in group license: abd23d6c7de1eab05bebf9753f7ceae5e
INFO     got machine id: abd23d6c7de1eab05bebf9753f7ceae5e
INFO     this machine id matchs group license
INFO     This license registration information:

License Type    : pyarmor-group
License No.     : pyarmor-vax-006219
License To      : xxx公司
License Product : jcszfwRPA

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Offline obfuscation
'''

执行>C:\workspace\rpa-workwechat>pyarmor gen foo.py
'''
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (group), 006219, jcszfwRPA
INFO     Platform windows.x86
INFO     search inputs ...
INFO     find script foo.py
INFO     find 1 top resources
ERROR    request license token failed (3): <h1>Server Error (500)</h1>
ERROR    somthing is wrong
*===========================================================*
*  Please check                                             *
*    https://pyarmor.readthedocs.io/en/latest/questions.html*
*  or run `pyarmor man` to find solutions quickly           *
*                                                           *
*  It's recommand to report issue by `pyarmor man` in order *
*  to provide necessary information, and avoid dupcliated   *
*  issues or unclear question.                              *
*===========================================================*
'''

pyarmor.error.log
'''
4532 MainProcess 2024-03-13 16:05:53,721
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 786, in main
    main_entry(sys.argv[1:])
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 744, in main_entry
    return args.func(ctx, args)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 236, in cmd_gen
    builder.process(options)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\generate.py", line 155, in process
    Pytransform3.pre_build(self.ctx)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\core\__init__.py", line 120, in pre_build
    m = Pytransform3.init(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\core\__init__.py", line 100, in init
    m.init_ctx(ctx)
RuntimeError: request license token failed (3): <h1>Server Error (500)</h1>
'''

请问这种该如何解决？

**Comment by smart0313** [comment]
再次查看注册信息:
C:\workspace\rpa-workwechat>pyarmor -v
Pyarmor 8.5.0 (trial), 000000, non-profits

License Type    : pyarmor-trial
License No.     : pyarmor-vax-000000
License To      :
License Product : non-profits

BCC Mode        : No
RFT Mode        : No

Notes
* Can't obfuscate big script and mix str

得到的还是未注册的返回，希望帮助解决这个问题

**Comment by smart0313** [comment]
# win10 x64正常
## 生产组设备文件
```
(workwechat) D:\project\rpa-workwechat\jcszfwRobot\Mass_messaging_Project>pyarmor reg -g 2
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     generating device file ".pyarmor\group\pyarmor-group-device.2"
INFO     current machine id is "mb391ca193ea260e9926d8ac6cc602a2c"
INFO     device file has been generated successfully
```
## 生成离线设备注册文件
```
(workwechat) D:\project\rpa-workwechat\jcszfwRobot\Mass_messaging_Project>pyarmor reg -g 2 pyarmor-regfile-6219.zip
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     register device file ".pyarmor\group\pyarmor-group-device.2"
INFO     use group license "pyarmor-regfile-6219.zip"
INFO     send request to server
INFO     write registration file "pyarmor-device-regfile-6219.2.zip"
INFO     please copy deivce regfile to offline device and run
INFO         pyarmor reg pyarmor-device-regfile-6219.2.zip
INFO     The device regfile has been generated successfully
```
## 离线设备注册
```
(workwechat) D:\project\rpa-workwechat\jcszfwRobot\Mass_messaging_Project>pyarmor reg pyarmor-device-regfile-6219.2.zip
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     register "pyarmor-device-regfile-6219.2.zip"
INFO     machine id in group license: mb391ca193ea260e9926d8ac6cc602a2c
INFO     got machine id: mb391ca193ea260e9926d8ac6cc602a2c
INFO     this machine id matchs group license
INFO     This license registration information:

License Type    : pyarmor-group
License No.     : pyarmor-vax-006219
License To      :xxx有限公司
License Product :yyy

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Offline obfuscation

```
## 查看注册信息
```
(workwechat) D:\project\rpa-workwechat\jcszfwRobot\Mass_messaging_Project>pyarmor -v
Pyarmor 8.5.0 (group), 006219, jcszfwRPA

License Type    : pyarmor-group
License No.     : pyarmor-vax-006219
License To      : xxx有限公司
License Product : yyy

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Offline obfuscation

```
## 加密脚本
```
(workwechat) D:\project\rpa-workwechat\jcszfwRobot\Mass_messaging_Project>cd ..

(workwechat) D:\project\rpa-workwechat\jcszfwRobot>cd demo

(workwechat) D:\project\rpa-workwechat\jcszfwRobot\demo>pyarmor gen foo.py
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (group), 006219, jcszfwRPA
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find script foo.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write dist\pyarmor_runtime_006219\pyarmor_runtime.pyd
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "foo"
INFO     obfuscating file foo.py
INFO     write dist\foo.py
INFO     obfuscate scripts OK
```
> 以上在win10x64物理机正常，在win7sp1_x86却始终无法注册，希望尽快帮助我解决这个问题

**Comment by jondy** [comment]
windows.x86 上面的这条日志有问题
```
INFO     current machine id is "abd23d6c7de1eab05bebf9753f7ceae5e" 
```

最新版本的 machine id 应该是 `m` 开头的，而不是 `a` ，以 `a` 开头的 machine id 是无法在集团版中使用的。

查看一下是否修改了默认配置
```
pyarmor cfg group_device_flag
```
如果不是 22 就有问题，恢复默认设置应该就没有问题

**Comment by smart0313** [comment]
# 查看了配置，group_device_flag = 22
```
C:\workspace\pyarmor_demo>pyarmor cfg group_device_flag
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86

------------------------------------------------------------
Section: builder

Current settings
  group_device_flag = 22

Global settings

Local settings

C:\workspace\pyarmor_demo>
```
配置为22，接下来该如何处理？

**Comment by jondy** [comment]
我的看代码是怎么回事了，:(

**Comment by smart0313** [comment]
此前由于出现问题，参考  修改了
### pyarmor.cli.register.Register#_get_machine_id:234，的devflag=10，会 machine id 是 a 开头的，现在我恢复了 11 后已经变回了 m 开头
```
    def _get_machine_id(self, devflag=11):
        from .core import Pytransform3
        # devflag = 10
        return Pytransform3.get_hd_info(devflag)
  ```

**Comment by smart0313** [comment]
好的，期待你的回复!

**Comment by jondy** [comment]
我刚刚测试了一下，是好着的呢，在我的虚拟机上打印的是 `m`
```
$ c:/Python37-32/python -m pyarmor.cli reg -g 1
INFO     Python 3.7.7
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86
INFO     generating device file ".pyarmor\group\pyarmor-group-device.1"
INFO     current machine id is "m3275bb1a8e9376d969c494a7f4ede3fb"
INFO     device file has been generated successfully
```

请确认一下安装的 `pyarmor.cli.core` 中扩展模块是正确的? 
```
$ md5sum pyarmor/cli/core/pytransform3.pyd 
104141837788ee7578d880005559cf72 *pyarmor/cli/core/pytransform3.pyd
```

**Comment by smart0313** [comment]
# 重装了pyarmor
```
Installing collected packages: pyarmor.cli.core, pyarmor
Successfully installed pyarmor-8.5.0 pyarmor.cli.core-6.5.0
```
# 重新生成组设备文件，按照**1e1c7748d44ab8c7588e3b57cfeac3243bf4aa07**已解决不支持x86
```
C:\workspace\rpa-workwechat>pyarmor reg -g 5
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
ERROR    unsupported arch "x86"
ERROR    somthing is wrong
*===========================================================*
*  Please check                                             *
*    https://pyarmor.readthedocs.io/en/latest/questions.html*
*  or run `pyarmor man` to find solutions quickly           *
*                                                           *
*  It's recommand to report issue by `pyarmor man` in order *
*  to provide necessary information, and avoid dupcliated   *
*  issues or unclear question.                              *
*===========================================================*
```
# 再次重新生成组设备文件，**成功**。且machine id 是以 **m** 开头
```
C:\workspace\rpa-workwechat>pyarmor reg -g 5
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86
INFO     generating device file ".pyarmor\group\pyarmor-group-device.5"
INFO     current machine id is "mc155626e5573034e100d736d58983c1e"
INFO     device file has been generated successfully
```
# 生成离线设备注册注册文件
C:\workspace\rpa-workwechat>pyarmor reg -g 5 pyarmor-regfile-6219.zip
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86
INFO     register device file ".pyarmor\group\pyarmor-group-device.5"
INFO     use group license "pyarmor-regfile-6219.zip"
INFO     send request to server
INFO     write registration file "pyarmor-device-regfile-6219.5.zip"
INFO     please copy deivce regfile to offline device and run
INFO         pyarmor reg pyarmor-device-regfile-6219.5.zip
INFO     The device regfile has been generated successfully
```
#  离线设备注册
```
C:\workspace\rpa-workwechat>pyarmor reg pyarmor-device-regfile-6219.5.zip
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86
INFO     register "pyarmor-device-regfile-6219.5.zip"
INFO     machine id in group license: mc155626e5573034e100d736d58983c1e
INFO     got machine id: mc155626e5573034e100d736d58983c1e
INFO     this machine id matchs group license
INFO     This license registration information:

License Type    : pyarmor-group
License No.     : pyarmor-vax-006219
License To      : 广州金财数字服务有限公司
License Product : jcszfwRPA

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Offline obfuscation
```
# 查看注册信息
C:\workspace\rpa-workwechat>pyarmor -v
Pyarmor 8.5.0 (group), 006219, jcszfwRPA

License Type    : pyarmor-group
License No.     : pyarmor-vax-006219
License To      : 广州金财数字服务有限公司
License Product : jcszfwRPA

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Offline obfuscation
* ```
# 加密脚本
```
C:\workspace\rpa-workwechat>cd ..

C:\workspace>cd pyarmor_demo

C:\workspace\pyarmor_demo>pyarmor gen foo.py
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (group), 006219, jcszfwRPA
INFO     Platform windows.x86
INFO     search inputs ...
INFO     find script foo.py
INFO     find 1 top resources
ERROR    request license token failed (3): <h1>Server Error (500)</h1>
ERROR    somthing is wrong
*===========================================================*
*  Please check                                             *
*    https://pyarmor.readthedocs.io/en/latest/questions.html*
*  or run `pyarmor man` to find solutions quickly           *
*                                                           *
*  It's recommand to report issue by `pyarmor man` in order *
*  to provide necessary information, and avoid dupcliated   *
*  issues or unclear question.                              *
*===========================================================*
```
# 依然还是报错
```
request license token failed (3): <h1>Server Error (500)</h1>

C:\workspace\pyarmor_demo>python -m pyarmor.cli reg -g 5
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86
INFO     generating device file ".pyarmor\group\pyarmor-group-device.5"
INFO     current machine id is "mc155626e5573034e100d736d58983c1e"
INFO     device file has been generated successfully


C:\workspace\pyarmor_demo>pyarmor cfg group_device_flag
INFO     Python 3.7.4
INFO     Pyarmor 8.5.0 (trial), 000000, non-profits
INFO     Platform windows.x86

------------------------------------------------------------
Section: builder

Current settings
  group_device_flag = 22

Global settings

Local settings


```
问题还是存在
