### ISSUE TITLE
[BUG] `upon pip install pyarmor triggers a new error: ModuleNotFoundError: No module named 'distutils'`

### ISSUE THREAD

**Issue by KlubJoony** [dashingsoft/pyarmor#1710]
Steps to reproduce:

Python@3.12.2
pip3 or pip
then install pyarmor or run pyarmor in cmd

`pip install pyarmor` or `pyarmor`

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\joon\AppData\Local\Programs\Python\Python312\Scripts\pyarmor.exe\__main__.py", line 4, in <module>
  File "C:\Users\joon\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\pyarmor.py", line 59, in <module>
    import packer
  File "C:\Users\joon\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\packer.py", line 47, in <module>
    from distutils.util import get_platform
ModuleNotFoundError: No module named 'distutils'

```

Tried to install the module as well and failed to do so. Have tried reproducing on multiple computers and had the same issue.

**Comment by spsdamn** [comment]
https://github.com/pypa/distutils/tree/pypy move in C:\Users\joon\AppData\Local\Programs\Python\Python312\Lib\site-packages\

**Comment by jondy** [comment]
Got it, thanks. It will be fixed in next release.

As a quick workaround, only install `pip install pyarmor.cli` for Python 3.12

**Comment by KlubJoony** [comment]
Thank you, I'll be awaiting for the fix. I really appreciate the contributions!

**Comment by jondy** [comment]
v8.5.1 has been released just for this issue.

**Comment by KlubJoony** [comment]
Wow cool, will see if its fixed later <3
