### ISSUE TITLE
PyInstaller 6.5.0 isn't supported

### ISSUE THREAD

**Issue by Snegovik777** [dashingsoft/pyarmor#1714]
### Discussed in https://github.com/dashingsoft/pyarmor/discussions/1713

<div type='discussions-op-text'>

<sup>Originally posted by **Snegovik777** March 19, 2024</sup>
Good day.

[Bug] NotImplementedError: PyInstaller 6.5.0 isn't supported

### Full command options and console output
C:\Users\val\PycharmProjects\new_tract_report\venv\Scripts\pyarmor -d gen --pack ./dist/main.exe main.py ./utils

2024-03-19 15:35:08,743 Python 3.11.2
2024-03-19 15:35:08,743 Pyarmor 8.5.1 (trial), 000000, non-profits
2024-03-19 15:35:08,744 Platform windows.x86_64
2024-03-19 15:35:08,745 native platform windows.amd64
2024-03-19 15:35:08,745 home path: C:\Users\val\.pyarmor
2024-03-19 15:35:08,745 implicitly set output to ".pyarmor\pack\dist"
2024-03-19 15:35:08,745 command options: {'no_runtime': False, 'inputs': ['main.py', 'utils'], 'output': '.pyarmor\\pack\\dist'}
2024-03-19 15:35:08,746 install plugin: CodesignPlugin
2024-03-19 15:35:08,746 install plugin: DarwinUniversalPlugin
2024-03-19 15:35:08,793 Loaded ctypes backend
2024-03-19 15:35:08,834 extracting bundle "./dist/main.exe"
2024-03-19 15:35:08,842 pylib_name is "python311.dll"
2024-03-19 15:35:08,842 extract struct
2024-03-19 15:35:08,842 extract pyimod01_archive
2024-03-19 15:35:08,843 extract pyimod02_importers
2024-03-19 15:35:08,843 extract pyimod03_ctypes
2024-03-19 15:35:08,843 extract pyimod04_pywin32
2024-03-19 15:35:08,844 extract pyiboot01_bootstrap
2024-03-19 15:35:08,844 extract pyi_rth_inspect
2024-03-19 15:35:08,844 extract pyi_rth_pywintypes
2024-03-19 15:35:08,844 extract pyi_rth_pythoncom
2024-03-19 15:35:08,845 extract pyi_rth_pkgutil
2024-03-19 15:35:08,845 extract pyi_rth_multiprocessing
2024-03-19 15:35:08,845 extract pyi_rth__tkinter
2024-03-19 15:35:08,845 extract main
2024-03-19 15:35:08,845 extract Pythonwin\mfc140u.dll
2024-03-19 15:35:08,846 extract Pythonwin\win32ui.pyd
2024-03-19 15:35:08,846 extract VCRUNTIME140.dll
2024-03-19 15:35:08,846 extract VCRUNTIME140_1.dll
2024-03-19 15:35:08,846 extract _asyncio.pyd
2024-03-19 15:35:08,846 extract _bz2.pyd
2024-03-19 15:35:08,847 extract _ctypes.pyd
2024-03-19 15:35:08,847 extract _decimal.pyd
2024-03-19 15:35:08,847 extract _hashlib.pyd
2024-03-19 15:35:08,847 extract _lzma.pyd
2024-03-19 15:35:08,847 extract _multiprocessing.pyd
2024-03-19 15:35:08,848 extract _overlapped.pyd
2024-03-19 15:35:08,848 extract _queue.pyd
2024-03-19 15:35:08,848 extract _socket.pyd
2024-03-19 15:35:08,848 extract _ssl.pyd
2024-03-19 15:35:08,848 extract _tkinter.pyd
2024-03-19 15:35:08,849 extract _uuid.pyd
2024-03-19 15:35:08,849 extract _zoneinfo.pyd
2024-03-19 15:35:08,849 extract babel\global.dat
2024-03-19 15:35:08,849 extract babel\locale-data\aa.dat
2024-03-19 15:35:08,849 extract babel\locale-data\aa_DJ.dat
2024-03-19 15:35:08,850 extract babel\locale-data\aa_ER.dat
2024-03-19 15:35:08,850 extract babel\locale-data\aa_ET.dat
2024-03-19 15:35:08,850 extract babel\locale-data\ab.dat
2024-03-19 15:35:08,850 extract babel\locale-data\ab_GE.dat
2024-03-19 15:35:08,850 extract babel\locale-data\af.dat
2024-03-19 15:35:08,851 extract babel\locale-data\af_NA.dat
2024-03-19 15:35:08,851 extract babel\locale-data\af_ZA.dat
2024-03-19 15:35:08,851 extract babel\locale-data\agq.dat
2024-03-19 15:35:08,851 extract babel\locale-data\agq_CM.dat
2024-03-19 15:35:08,851 extract babel\locale-data\ak.dat
2024-03-19 15:35:08,852 extract babel\locale-data\ak_GH.dat
2024-03-19 15:35:08,852 extract babel\locale-data\am.dat
2024-03-19 15:35:08,852 extract babel\locale-data\am_ET.dat
2024-03-19 15:35:08,852 extract babel\locale-data\an.dat
2024-03-19 15:35:08,852 extract babel\locale-data\an_ES.dat
2024-03-19 15:35:08,853 extract babel\locale-data\ann.dat
2024-03-19 15:35:08,853 extract babel\locale-data\ann_NG.dat
2024-03-19 15:35:08,853 extract babel\locale-data\apc.dat
2024-03-19 15:35:08,853 extract babel\locale-data\apc_SY.dat
2024-03-19 15:35:08,853 extract babel\locale-data\ar.dat
2024-03-19 15:35:08,854 extract babel\locale-data\ar_001.dat
2024-03-19 15:35:08,854 extract babel\locale-data\ar_AE.dat
2024-03-19 15:35:08,854 extract babel\locale-data\ar_BH.dat
2024-03-19 15:35:08,854 extract babel\locale-data\ar_DJ.dat
2024-03-19 15:35:08,854 extract babel\locale-data\ar_DZ.dat
2024-03-19 15:35:08,854 extract babel\locale-data\ar_EG.dat
2024-03-19 15:35:08,855 extract babel\locale-data\ar_EH.dat
2024-03-19 15:35:08,855 extract babel\locale-data\ar_ER.dat
2024-03-19 15:35:08,855 extract babel\locale-data\ar_IL.dat
2024-03-19 15:35:08,855 extract babel\locale-data\ar_IQ.dat
2024-03-19 15:35:08,855 extract babel\locale-data\ar_JO.dat
2024-03-19 15:35:08,856 extract babel\locale-data\ar_KM.dat
2024-03-19 15:35:08,856 extract babel\locale-data\ar_KW.dat
2024-03-19 15:35:08,856 extract babel\locale-data\ar_LB.dat
2024-03-19 15:35:08,857 extract babel\locale-data\ar_LY.dat
2024-03-19 15:35:08,857 extract babel\locale-data\ar_MA.dat
2024-03-19 15:35:08,857 extract babel\locale-data\ar_MR.dat
2024-03-19 15:35:08,857 extract babel\locale-data\ar_OM.dat
2024-03-19 15:35:08,857 extract babel\locale-data\ar_PS.dat
2024-03-19 15:35:08,858 extract babel\locale-data\ar_QA.dat
2024-03-19 15:35:08,858 extract babel\locale-data\ar_SA.dat
2024-03-19 15:35:08,858 extract babel\locale-data\ar_SD.dat
2024-03-19 15:35:08,858 extract babel\locale-data\ar_SO.dat
2024-03-19 15:35:08,858 extract babel\locale-data\ar_SS.dat
2024-03-19 15:35:08,858 extract babel\locale-data\ar_SY.dat
2024-03-19 15:35:08,859 extract babel\locale-data\ar_TD.dat
2024-03-19 15:35:08,859 extract babel\locale-data\ar_TN.dat
2024-03-19 15:35:08,859 extract babel\locale-data\ar_YE.dat
2024-03-19 15:35:08,859 extract babel\locale-data\arn.dat
2024-03-19 15:35:08,860 extract babel\locale-data\arn_CL.dat
2024-03-19 15:35:08,860 extract babel\locale-data\as.dat
2024-03-19 15:35:08,860 extract babel\locale-data\as_IN.dat
2024-03-19 15:35:08,860 extract babel\locale-data\asa.dat
2024-03-19 15:35:08,861 extract babel\locale-data\asa_TZ.dat
...
2024-03-19 15:35:09,231 extract tk\ttk\utils.tcl
2024-03-19 15:35:09,231 extract tk\ttk\vistaTheme.tcl
2024-03-19 15:35:09,232 extract tk\ttk\winTheme.tcl
2024-03-19 15:35:09,232 extract tk\ttk\xpTheme.tcl
2024-03-19 15:35:09,232 extract tk\unsupported.tcl
2024-03-19 15:35:09,232 extract tk\xmfbox.tcl
2024-03-19 15:35:09,232 extract unicodedata.pyd
2024-03-19 15:35:09,233 extract win32\_win32sysloader.pyd
2024-03-19 15:35:09,233 extract win32\win32api.pyd
2024-03-19 15:35:09,233 extract win32\win32event.pyd
2024-03-19 15:35:09,233 extract win32\win32gui.pyd
2024-03-19 15:35:09,233 extract win32\win32process.pyd
2024-03-19 15:35:09,234 extract win32\win32trace.pyd
2024-03-19 15:35:09,234 extract winsound.pyd
2024-03-19 15:35:09,235 extract xlwings\xlwingslib.cp311-win_amd64.pyd
2024-03-19 15:35:09,235 extract PYZ-00.pyz
2024-03-19 15:35:09,673 one file mode is True
2024-03-19 15:35:09,674 Please check documentation `insight into pack command`to find solutions or downgrade PyInstaller to version 5
2024-03-19 15:35:09,674 unknown error, please check pyarmor.error.log
2024-03-19 15:35:09,676 PyInstaller 6.5.0 isn't supported

### Traceback
Traceback (most recent call last):
  File "C:\Users\val\PycharmProjects\new_tract_report\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 757, in main
    main_entry(sys.argv[1:])
  File "C:\Users\val\PycharmProjects\new_tract_report\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 745, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\val\PycharmProjects\new_tract_report\venv\Lib\site-packages\pyarmor\cli\__main__.py", line 233, in cmd_gen
    packer.check()
  File "C:\Users\val\PycharmProjects\new_tract_report\venv\Lib\site-packages\pyarmor\cli\repack.py", line 329, in check
    raise NotImplementedError(
NotImplementedError: PyInstaller 6.5.0 isn't supported

</div>

**Comment by LQQB** [comment]
Same question

**Comment by thetypingpuppy** [comment]
Any solution to this?
