### ISSUE TITLE
项目中使用到了 celery，如何执行混淆后的代码。

### ISSUE THREAD

**Issue by virezox** [dashingsoft/pyarmor#1716]
你好，当前项目中用到了 celery 去执行一些异步任务类似 celery -A celery_app.celery_worker worker ，混淆后的代码无法直接运行，是否有方法可以解决这个问题，当前用的是 Pyarmor 的 group license，版本是最新的 8.5.1。

我在生成加密脚本的时候是通过如下方式生成：

`pyarmor gen --platform linux.x86_64 --enable-jit --mix-str --assert-call --private -O obfuscated -r src`

当我在运行时会遇到如下问题：

```
[2024-03-20 23:37:58,927: ERROR/ForkPoolWorker-3] Task celery_app.celery_worker.process_task[f10eff90-0cf7-443d-99cb-8198096e3489] raised unexpected: RuntimeError('protection exception (16777934)')
Traceback (most recent call last):
  File "/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen src.celery_app.celery_worker>", line 69, in process_task
RuntimeError: protection exception (16777934)
```

**Comment by jondy** [comment]
尝试使用下面的配置，然后在进行加密
```
pyarmor cfg restrict_module=0 
```

请首先查看在线文档，这种类型的问题文档中已经有说明
