### ISSUE TITLE
[BUG] `There is no item named 'license.lic' in the archive`

### ISSUE THREAD

**Issue by DarkyAmagai** [dashingsoft/pyarmor#1735]
This is happening to me when trying to register my pyarmor license.

My environment.:

- Apple Silicon M3 Pro
- 18gb ram
- MacOS 14.4.1

```
AntispamBot % pyarmor reg pyarmor-regfile-4041.zip
INFO     Python 3.10.13
INFO     Pyarmor 8.5.2 (trial), 000000, non-profits
INFO     Platform darwin.aarch64
INFO     register "pyarmor-regfile-4041.zip"
ERROR    "There is no item named 'license.lic' in the archive"
ERROR    somthing is wrong
```

`pyarmor.error.log`
```
36312 MainProcess 2024-04-14 13:05:04,945
Traceback (most recent call last):
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 757, in main
    main_entry(sys.argv[1:])
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 745, in main_entry
    return args.func(ctx, args)
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 306, in cmd_reg
    reg.register_regfile(regfile)
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyarmor/cli/register.py", line 158, in register_regfile
    f.extract(item, path=path)
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/zipfile.py", line 1630, in extract
    return self._extract_member(member, path, pwd)
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/zipfile.py", line 1669, in _extract_member
    member = self.getinfo(member)
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/zipfile.py", line 1443, in getinfo
    raise KeyError(
KeyError: "There is no item named 'license.lic' in the archive"
```

`pyarmor.report.bug`
```
[Bug] KeyError: "There is no item named 'license.lic' in the archive"

### Full command options and console output
/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/bin/pyarmor -d reg pyarmor-regfile-4041.zip

2024-04-14 13:01:36,072 Python 3.10.13
2024-04-14 13:01:36,072 Pyarmor 8.5.2 (trial), 000000, non-profits
2024-04-14 13:01:36,073 Platform darwin.aarch64
2024-04-14 13:01:36,073 native platform darwin.arm64
2024-04-14 13:01:36,073 home path: /Users/oscarfernandodavisflores/.pyarmor
2024-04-14 13:01:36,073 register "pyarmor-regfile-4041.zip"
2024-04-14 13:01:36,074 extracting license.lic
2024-04-14 13:01:36,074 unknown error, please check pyarmor.error.log
2024-04-14 13:01:36,076 "There is no item named 'license.lic' in the archive"


### Traceback
Traceback (most recent call last):
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 757, in main
    main_entry(sys.argv[1:])
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 745, in main_entry
    return args.func(ctx, args)
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 306, in cmd_reg
    reg.register_regfile(regfile)
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pyarmor/cli/register.py", line 158, in register_regfile
    f.extract(item, path=path)
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/zipfile.py", line 1630, in extract
    return self._extract_member(member, path, pwd)
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/zipfile.py", line 1669, in _extract_member
    member = self.getinfo(member)
  File "/Users/oscarfernandodavisflores/.pyenv/versions/3.10.13/lib/python3.10/zipfile.py", line 1443, in getinfo
    raise KeyError(
KeyError: "There is no item named 'license.lic' in the archive"
```

**Comment by jondy** [comment]
First of all, unzip `pyarmor-regfile-xxxx.zip`, is there `license.lic` in it?

**Comment by jondy** [comment]
Though I'm not sure, but I think the most possible is that the regfile is not correct or broken, make sure get the right and complete refile `pyarmor-regfile-xxxx.zip`

**Comment by DarkyAmagai** [comment]
> First of all, unzip `pyarmor-regfile-xxxx.zip`, is there `license.lic` in it?
> 

Yeah, the licence.zip file is into the file, as I have been seen, other people have the same problem on mac m1
