### ISSUE TITLE
[BUG] `pydantic.errors.PydanticUserError: TaskList is not fully defined; you should define Task, then call TaskList.model_rebuild(). `

### ISSUE THREAD

**Issue by tchalupnik** [dashingsoft/pyarmor#1740]
Hello! 
I found a bug that is related to anyio and pydantic
Let's consider the code:

```
from __future__ import annotations

import anyio

from pydantic import BaseModel

async def get_tasks() -> None:
    class Task(BaseModel):
        name: str

    class TaskList(BaseModel):
        data: list[Task]

    TaskList.model_validate({"data": [{"name": "test"}]})

if __name__ == "__main__":
    anyio.run(get_tasks) 
```

First 4 lines of the pyarmor output:
```
INFO     Python 3.10.13
INFO     Pyarmor 8.5.2 (trial), 000000, non-profits
INFO     Platform darwin.aarch64
INFO     use runtime platforms: ['darwin.arm64']
```

Running the script results with:
```

Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen testpyda>", line 17, in <module>
  File "/Users/x/.pyenv/versions/y/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 73, in run
    return async_backend.run(func, args, {}, backend_options)
  File "/Users/x/.pyenv/versions/y/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1991, in run
    return runner.run(wrapper())
  File "/Users/x/.pyenv/versions/y/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 193, in run
    return self._loop.run_until_complete(task)
  File "/Users/x/.pyenv/versions/y/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/x/.pyenv/versions/y/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1979, in wrapper
    return await func(*args)
  File "<frozen testpyda>", line 14, in get_tasks
  File "/Users/x/.pyenv/versions/y/lib/python3.10/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
  File "/Users/x/.pyenv/versions/y/lib/python3.10/site-packages/pydantic/_internal/_mock_val_ser.py", line 47, in __getattr__
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `TaskList` is not fully defined; you should define `Task`, then call `TaskList.model_rebuild()`.

For further information visit https://errors.pydantic.dev/2.5/u/class-not-fully-defined
```

I found two ways they serve me as a work-around and they may help you with the debugging, however the initial code should run as-is.
1) is to move classes to the top level of the file, as in the example below:
```
from __future__ import annotations

import anyio
from pydantic import BaseModel


class Task(BaseModel):
    name: str


class TaskList(BaseModel):
    data: list[Task]


async def get_tasks() -> None:
    TaskList.model_validate({"data": [{"name": "test"}]})


if __name__ == "__main__":
    anyio.run(get_tasks)
```
2) Is to remove first line of the code which is: 
```
from __future__ import annotations
```

**Comment by jondy** [comment]
Got it, i think it's related to annotations.

What're options to obfuscate the code?

**Comment by tchalupnik** [comment]
```
> python -m pyarmor.cli gen -e .2024-07-16 --obf-code 0 --platform darwin.arm64 --enable-jit -O armored/ -i testpyda.py
```

**Comment by jonathanslenders** [comment]
I think the problem here is that Pydantic resolves the annotations at runtime when `from __future__ import annotations` is being used. In that case, the annotations are strings.

If pyarmor is renaming the local classes to something like `_var_var_2`, then the locals no longer match the corresponding portion of the annotations.

**Comment by jondy** [comment]
If the problem is local variable is renamed, try to disable it by
```
pyarmor cfg mix_localnames=0
```

should fix this issue
