### ISSUE TITLE
[BUG] `ModuleNotFoundError: No module named 'urllib.request'`

### ISSUE THREAD

**Issue by ner00** [dashingsoft/pyarmor#1746]
**Exception**
```
C:\Users\ner0\AppData\Roaming\Python\Python39\Scripts\dist>dist\obfuscated.exe
Traceback (most recent call last):
  File "<frozen __main__>", line 4, in <module>
  File "<frozen obfuscated>", line 173, in <module>
ModuleNotFoundError: No module named 'urllib.request'
[23496] Failed to execute script 'obfuscated' due to unhandled exception!
```

**.py**
```py
from urllib.request import urlopen
```

**Console log**
```
C:\Users\ner0\AppData\Roaming\Python\Python39\Scripts\dist>pyarmor gen --pack onefile obfuscated.py
INFO     Python 3.9.4
INFO     Pyarmor 8.5.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     implicitly save obfuscated scripts to ".pyarmor\pack\dist"
INFO     search inputs ...
INFO     find script obfuscated.py
INFO     find 1 top resources
INFO     call PyInstaller to generate specfile
INFO     call PyInstaller to analysis, it may take several minutes ...
INFO     find extra resources: []
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write .pyarmor\pack\dist\pyarmor_runtime_000000\pyarmor_runtime.pyd
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "obfuscated"
INFO     obfuscating file obfuscated.py
INFO     write .pyarmor\pack\dist\obfuscated.py
INFO     obfuscate scripts OK
INFO     call PyInstaller to generate final bundle ...

591 INFO: PyInstaller: 6.6.0, contrib hooks: 2024.4
591 INFO: Python: 3.9.4
593 INFO: Platform: Windows-10-10.0.19041-SP0
595 INFO: wrote .pyarmor\pack\obfuscated.spec
604 INFO: Removing temporary files and cleaning cache in C:\Users\ner0\AppData\Local\pyinstaller
614 INFO: Extending PYTHONPATH with paths
['C:\\Users\\ner0\\AppData\\Roaming\\Python\\Python39\\Scripts\\dist\\.pyarmor\\pack\\dist']
897 INFO: checking Analysis
897 INFO: Building Analysis because Analysis-00.toc is non existent
899 INFO: Running Analysis Analysis-00.toc
900 INFO: Target bytecode optimization level: 0
900 INFO: Initializing module dependency graph...
903 INFO: Caching module graph hooks...
927 INFO: Analyzing base_library.zip ...
2178 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\ner0\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
3706 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\ner0\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
4634 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\ner0\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
4986 INFO: Caching module dependency graph...
5153 INFO: Looking for Python shared library...
5167 INFO: Using Python shared library: C:\Python39\python39.dll
5167 INFO: Analyzing C:\Users\ner0\AppData\Roaming\Python\Python39\Scripts\dist\.pyarmor\pack\dist\obfuscated.py
5193 INFO: Loading module hook 'hook-pyarmor_runtime_000000.py' from 'C:\\Users\\ner0\\AppData\\Roaming\\Python\\Python39\\Scripts\\dist\\.pyarmor\\pack'...
5205 INFO: Processing module hooks...
5249 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\ner0\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
5388 INFO: Performing binary vs. data reclassification (2 entries)
5405 INFO: Looking for ctypes DLLs
5409 INFO: Analyzing run-time hooks ...
5414 INFO: Looking for dynamic libraries
5544 INFO: Extra DLL search directories (AddDllDirectory): []
5544 INFO: Extra DLL search directories (PATH): []
6053 INFO: Warnings written to C:\Users\ner0\AppData\Roaming\Python\Python39\Scripts\dist\.pyarmor\pack\build\obfuscated\warn-obfuscated.txt
6087 INFO: Graph cross-reference written to C:\Users\ner0\AppData\Roaming\Python\Python39\Scripts\dist\.pyarmor\pack\build\obfuscated\xref-obfuscated.html
6118 INFO: checking PYZ
6118 INFO: Building PYZ because PYZ-00.toc is non existent
6120 INFO: Building PYZ (ZlibArchive) C:\Users\ner0\AppData\Roaming\Python\Python39\Scripts\dist\.pyarmor\pack\build\obfuscated\PYZ-00.pyz
6425 INFO: Building PYZ (ZlibArchive) C:\Users\ner0\AppData\Roaming\Python\Python39\Scripts\dist\.pyarmor\pack\build\obfuscated\PYZ-00.pyz completed successfully.
6450 INFO: checking PKG
6451 INFO: Building PKG because PKG-00.toc is non existent
6451 INFO: Building PKG (CArchive) obfuscated.pkg
8233 INFO: Building PKG (CArchive) obfuscated.pkg completed successfully.
8236 INFO: Bootloader C:\Users\ner0\AppData\Roaming\Python\Python39\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
8236 INFO: checking EXE
8237 INFO: Building EXE because EXE-00.toc is non existent
8238 INFO: Building EXE from EXE-00.toc
8240 INFO: Copying bootloader EXE to C:\Users\ner0\AppData\Roaming\Python\Python39\Scripts\dist\dist\obfuscated.exe
8325 INFO: Copying icon to EXE
8401 INFO: Copying 0 resources to EXE
8401 INFO: Embedding manifest in EXE
8480 INFO: Appending PKG archive to EXE
8496 INFO: Fixing EXE headers
10478 INFO: Building EXE from EXE-00.toc completed successfully.
INFO
INFO     the final bundle "dist" has been generate successfully
```

**Assert-call**
```
C:\Users\ner0\AppData\Roaming\Python\Python39\Scripts\dist\pyarmor gen -O dist --assert-call obfuscated.py
INFO     Python 3.9.4
INFO     Pyarmor 8.5.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find script obfuscated.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write dist\pyarmor_runtime_000000\pyarmor_runtime.pyd
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "obfuscated"
INFO     obfuscating file obfuscated.py
INFO     write dist\obfuscated.py
INFO     obfuscate scripts OK
```

**Comment by ner00** [comment]
> Do not pack obfuscated script, but plain script.

@jondy 
The console log is from a plain script packing, no errors, but produces the exception mentioned. How is it wrong usage?

I just included the assert-call log because the issue template implied that ut was needed.

What's the wrong usage then?
