### ISSUE TITLE
[BUG] `ModuleNotFoundError: No module named 'urllib.request'`

### ISSUE THREAD

**Issue by ner00** [dashingsoft/pyarmor#1747]
**Exception**
```
C:\Python39>dist\myscript.exe
Traceback (most recent call last):
  File "<frozen __main__>", line 4, in <module>
  File "<frozen myscript>", line 173, in <module>
ModuleNotFoundError: No module named 'urllib.request'
[8208] Failed to execute script 'myscript' due to unhandled exception!
```

**.py**
```py
from urllib.request import urlopen
```

**Console log**
```
C:\Python39>pyarmor gen --pack onefile myscript.py
INFO     Python 3.9.4
INFO     Pyarmor 8.5.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
INFO     implicitly save obfuscated scripts to ".pyarmor\pack\dist"
INFO     search inputs ...
INFO     find script myscript.py
INFO     find 1 top resources
INFO     call PyInstaller to generate specfile
INFO     call PyInstaller to analysis, it may take several minutes ...
INFO     find extra resources: []
INFO     start to generate runtime files
INFO     target platforms {'windows.amd64'}
INFO     write .pyarmor\pack\dist\pyarmor_runtime_000000\pyarmor_runtime.pyd
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "myscript"
INFO     obfuscating file myscript.py
INFO     write .pyarmor\pack\dist\myscript.py
INFO     obfuscate scripts OK
INFO     call PyInstaller to generate final bundle ...

479 INFO: PyInstaller: 6.6.0, contrib hooks: 2024.4
479 INFO: Python: 3.9.4
480 INFO: Platform: Windows-10-10.0.19041-SP0
481 INFO: wrote .pyarmor\pack\myscript.spec
490 INFO: Removing temporary files and cleaning cache in C:\Users\ner0\AppData\Local\pyinstaller
499 INFO: Extending PYTHONPATH with paths
['C:\\Python39\\.pyarmor\\pack\\dist']
761 INFO: checking Analysis
761 INFO: Building Analysis because Analysis-00.toc is non existent
762 INFO: Running Analysis Analysis-00.toc
763 INFO: Target bytecode optimization level: 0
763 INFO: Initializing module dependency graph...
766 INFO: Caching module graph hooks...
789 INFO: Analyzing base_library.zip ...
1989 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\ner0\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
3482 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\ner0\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
4390 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\ner0\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
4830 INFO: Caching module dependency graph...
5001 INFO: Looking for Python shared library...
5015 INFO: Using Python shared library: C:\Python39\python39.dll
5016 INFO: Analyzing C:\Python39\.pyarmor\pack\dist\myscript.py
5041 INFO: Loading module hook 'hook-pyarmor_runtime_000000.py' from 'C:\\Python39\\.pyarmor\\pack'...
5052 INFO: Processing module hooks...
5084 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\ner0\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
5238 INFO: Performing binary vs. data reclassification (2 entries)
5255 INFO: Looking for ctypes DLLs
5258 INFO: Analyzing run-time hooks ...
5264 INFO: Looking for dynamic libraries
5403 INFO: Extra DLL search directories (AddDllDirectory): []
5403 INFO: Extra DLL search directories (PATH): []
5929 INFO: Warnings written to C:\Python39\.pyarmor\pack\build\myscript\warn-myscript.txt
5961 INFO: Graph cross-reference written to C:\Python39\.pyarmor\pack\build\myscript\xref-myscript.html
6020 INFO: checking PYZ
6021 INFO: Building PYZ because PYZ-00.toc is non existent
6022 INFO: Building PYZ (ZlibArchive) C:\Python39\.pyarmor\pack\build\myscript\PYZ-00.pyz
6331 INFO: Building PYZ (ZlibArchive) C:\Python39\.pyarmor\pack\build\myscript\PYZ-00.pyz completed successfully.
6369 INFO: checking PKG
6369 INFO: Building PKG because PKG-00.toc is non existent
6370 INFO: Building PKG (CArchive) myscript.pkg
8152 INFO: Building PKG (CArchive) myscript.pkg completed successfully.
8155 INFO: Bootloader C:\Users\ner0\AppData\Roaming\Python\Python39\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
8155 INFO: checking EXE
8155 INFO: Building EXE because EXE-00.toc is non existent
8156 INFO: Building EXE from EXE-00.toc
8157 INFO: Copying bootloader EXE to C:\Python39\dist\myscript.exe
8310 INFO: Copying icon to EXE
8390 INFO: Copying 0 resources to EXE
8390 INFO: Embedding manifest in EXE
8465 INFO: Appending PKG archive to EXE
8480 INFO: Fixing EXE headers
10345 INFO: Building EXE from EXE-00.toc completed successfully.
INFO
INFO     the final bundle "dist" has been generate successfully
```

**Comment by jondy** [comment]
Sorry, fixed in this pre-release version

https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-8.5.7.zip
