### ISSUE TITLE
[BUG] `FileNotFoundError: [Errno 2] No such file or directory: '.pyarmor\\pack\\PYZ-00.pyz_extracted\\pyarmor_runtime_005640\\__init__.pyc'

### ISSUE THREAD

**Issue by hayingbs** [dashingsoft/pyarmor#1790]
运行加密脚本：
pyarmor -d  gen --pack dist/yihaozitie/yihaozitie.exe --enable-bcc -r components/ configs/ query_tools/ UI/ utils/ views/ work_tools/ yihaozitie.py

加密时找不到文件：
.pyarmor\\pack\\PYZ-00.pyz_extracted\\pyarmor_runtime_005640\\__init__.pyc

版本信息：
PS D:\wfl> pyarmor -v
Pyarmor 8.5.8 (pro), 005640, 一号字帖                
                                                     
License Type    : pyarmor-pro                        
License No.     : pyarmor-vax-005640                 
License To      : 高海英                             
License Product : 一号字帖                           
                                                     
BCC Mode        : Yes                                
RFT Mode        : Yes   
Notes                                                
* Need verify license online when obfuscating scripts

日志：
### Traceback
Traceback (most recent call last):
  File "D:\wfl\venv\lib\site-packages\pyarmor\cli\__main__.py", line 764, in main
    main_entry(sys.argv[1:])
  File "D:\wfl\venv\lib\site-packages\pyarmor\cli\__main__.py", line 752, in main_entry
    return args.func(ctx, args)
  File "D:\wfl\venv\lib\site-packages\pyarmor\cli\__main__.py", line 241, in cmd_gen
    packer.build()
  File "D:\wfl\venv\lib\site-packages\pyarmor\cli\repack.py", line 714, in build
    self.repack(self.output, self.ctx.runtime_package_name)
  File "D:\wfl\venv\lib\site-packages\pyarmor\cli\repack.py", line 735, in repack
    repack_pyzarchive(pyzpath, self.pyztoc, obfpath, rtname)
  File "D:\wfl\venv\lib\site-packages\pyarmor\cli\repack.py", line 569, in repack_pyzarchive
    compile_item(rtname, os.path.join(rtname, '__init__.py'))
  File "D:\wfl\venv\lib\site-packages\pyarmor\cli\repack.py", line 562, in compile_item
    with open(fullpath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '.pyarmor\\pack\\PYZ-00.pyz_extracted\\pyarmor_runtime_005640\\__init__.pyc'

**Comment by jondy** [comment]
这个 bug 会在下一个版本中修正。

请参考 #1764

**Comment by jondy** [comment]
Fixed in v8.5.9
