### ISSUE TITLE
[BUG] `加密报错gbk`

### ISSUE THREAD

**Issue by hayingbs** [dashingsoft/pyarmor#1796]
Pyarmor 8.5.9 (pro), 005640, 一号字帖

License Type    : pyarmor-pro
License No.     : pyarmor-vax-005640
License To      : 高海英
License Product : 一号字帖

BCC Mode        : Yes
RFT Mode        : Yes

**pyinstaller版本**
pyinstaller    5.13.2 

**django版本**
django=3.9

所有.py文件都确认是utf-8, 并且头部也加了  # -*- coding: utf-8 -*-

**操作：**
pyarmor -d  gen --pack dist/yihaozitie/yihaozitie.exe --enable-bcc -r components/ configs/ query_tools/ UI/ utils/ views/ work_tools/ yihaozitie.py

**报错：**
INFO     replace item "pyarmor_runtime_005640"
INFO     replace item "UI.en"
DEBUG    unknown error, please check pyarmor.error.log
ERROR    'gbk' codec can't decode byte 0x80 in position 33: illegal multibyte sequence
Traceback (most recent call last):
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\__main__.py", line 764, in main
    main_entry(sys.argv[1:])
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\__main__.py", line 752, in main_entry
    return args.func(ctx, args)
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\__main__.py", line 241, in cmd_gen
    packer.build()
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\repack.py", line 715, in build
    self.repack(obfpath, self.ctx.runtime_package_name)
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\repack.py", line 736, in repack
    repack_pyzarchive(pyzpath, self.pyztoc, obfpath, rtname)
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\repack.py", line 577, in repack_pyzarchive
    fullpath = compile_item(name, ptname + '.py')
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\repack.py", line 558, in compile_item
    co = compile(f.read(), '<frozen %s>' % name, 'exec')
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 33: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\textwfl\env\Scripts\pyarmor.exe\__main__.py", line 7, in <module>
  File "F:\textwfl\env\lib\site-packages\pyarmor\pyarmor.py", line 1643, in main_entry_8
    call_pyarmor_cli()
  File "F:\textwfl\env\lib\site-packages\pyarmor\pyarmor.py", line 1617, in call_pyarmor_cli
    main()
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\__main__.py", line 772, in main
    find_solutions(e)
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\bug.py", line 114, in find_solutions
    generate_bug_report(e)
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\bug.py", line 73, in generate_bug_report
    lines = f.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 94: illegal multibyte sequence

**error.log:**
3380 MainProcess 2024-06-02 00:44:38,813
Traceback (most recent call last):
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\__main__.py", line 764, in main
    main_entry(sys.argv[1:])
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\__main__.py", line 752, in main_entry
    return args.func(ctx, args)
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\__main__.py", line 241, in cmd_gen
    packer.build()
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\repack.py", line 715, in build
    self.repack(obfpath, self.ctx.runtime_package_name)
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\repack.py", line 736, in repack
    repack_pyzarchive(pyzpath, self.pyztoc, obfpath, rtname)
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\repack.py", line 577, in repack_pyzarchive
    fullpath = compile_item(name, ptname + '.py')
  File "F:\textwfl\env\lib\site-packages\pyarmor\cli\repack.py", line 558, in compile_item
    co = compile(f.read(), '<frozen %s>' % name, 'exec')
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 33: illegal multibyte sequence

**Comment by jondy** [comment]
抱歉，这是个 Bug，应用下面这个补丁可以解决这个问题
```patch
--- a/pyarmor/cli/repack.py
+++ b/pyarmor/cli/repack.py
@@ -554,7 +554,7 @@ def repack_pyzarchive(pyzpath, pyztoc, obfpath, rtname, cipher=None):
             fullpath = fullpath + 'c'
         if os.path.exists(fullpath):
             logger.info('replace item "%s"', name)
-            with open(fullpath, 'r') as f:
+            with open(fullpath, 'r', encoding='utf-8') as f:
                 co = compile(f.read(), '<frozen %s>' % name, 'exec')
                 code_dict[name] = co
         else:
```

**Comment by hayingbs** [comment]
可以了谢谢
