### ISSUE TITLE
[BUG] `Error invalid license token, try to run `pyarmor reg` to register license again` Can't run group license in Kubernetes

### ISSUE THREAD

**Issue by noahmuney** [dashingsoft/pyarmor#1804]
Trying to use group license in Kubernetes cluster as in https://pyarmor.readthedocs.io/en/v8.5.8/how-to/register.html#run-unlimited-dockers-in-offline-device
Successfully setup `pyarmor-auth` server in kubernetes host machine
Create pod (like container) with host.docker.internal:host-gateway 
I can ping host.docker.internal from within the container and I can successfully register pyarmor against the host machine auth server.

From within container:
```
xxx@xxx:~xxx$ pyarmor -d reg pyarmor-device-regfile-xxxx.1.zip
INFO     Python 3.11.0
INFO     Pyarmor 8.5.8 (trial), 000000, non-profits
INFO     Platform linux.x86_64
DEBUG    native platform linux.x86_64
DEBUG    home path: xxxx
INFO     register "pyarmor-device-regfile-xxxx.1.zip"
DEBUG    extracting license.lic
DEBUG    extracting .pyarmor_capsule.zip
INFO     machine id in group license: mbec6391f5308372dc4821930af4702b7
INFO     got machine id: mb356c293560839b7076a751ada07f658
INFO     got machine id: lb356c293560839b7076a751ada07f658
INFO     got machine id: i2831768ef28971ff2bfe9ac369422992
INFO     got machine id: k18d7ff30ba50c9416dfb0b55cbb31f02
INFO     got machine id: g18d7ff30ba50c9416dfb0b55cbb31f02
INFO     got machine id: bac059f4cee673c5ca33280f6dc2bd0ed
INFO     no machine id matchs this group license
INFO     take this machine as docker container, and connect to docker host for authentication...
INFO     got docker host machine id: mbec6391f5308372dc4821930af4702b7
INFO     got docker host machine id: lbec6391f5308372dc4821930af4702b7
INFO     got docker host machine id: ibec6391f5308372dc4821930af4702b7
INFO     got docker host machine id: k78f28019b68cf3aa90581f0f71f6e2fb
INFO     got docker host machine id: g9dc1b63f8b29c891bb374f953ce7b0fa
INFO     got docker host machine id: bce1337927e80405dd923b433081cc1f6
DEBUG    extracting tokens/mbec6391f5308372dc4821930af4702b7
INFO     This license registration information:

License Type    : pyarmor-group
License No.     : pyarmor-vax-00xxxx
License To      : XXXX
License Product : XXXX

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Offline obfuscation
```

From pyarmor-auth: (10.42.3.19 is container address, host has address in same network) 
```
root@xxxx:xxx# pyarmor-auth pyarmor-device-regfile-xxxx.1.zip
2024-06-03 20:25:15,700: work path: /root/.pyarmor/docker
2024-06-03 20:25:15,701: register "pyarmor-device-regfile-xxxx.1.zip"
2024-06-03 20:25:15,704: machine id in group license: mbec6391f5308372dc4821930af4702b7
2024-06-03 20:25:15,704: got machine id: mbec6391f5308372dc4821930af4702b7
2024-06-03 20:25:15,704: this machine id matchs group license
2024-06-03 20:25:15,705: listen container auth request on 0.0.0.0:29092
2024-06-03 20:25:52,206: receive request from ('10.42.3.19', 44410)
2024-06-03 20:25:52,206: send auth result to ('10.42.3.19', 44410)
```

So far all good, but when I run `pyarmor gen foo.py` I get the following error:
```
INFO     Python 3.11.0
INFO     Pyarmor 8.5.8 (group), 00xxxx, xxxx
INFO     Platform linux.x86_64
DEBUG    native platform linux.x86_64
DEBUG    home path: /xxxx/.pyarmor
DEBUG    command options: {'no_runtime': False, 'inputs': ['foo.py']}
DEBUG    install plugin: CodesignPlugin
DEBUG    install plugin: DarwinUniversalPlugin
INFO     search inputs ...
INFO     find script foo.py
INFO     find 1 top resources
DEBUG    unknown error, please check pyarmor.error.log
ERROR    invalid license token, try to run `pyarmor reg` to register license again
ERROR    something is wrong
*=============================================================*
*  Please check                                               *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*  or run `pyarmor man` to find solutions quickly             *
*                                                             *
*  It's recommand to report issue by `pyarmor man` in order   *
*  to provide necessary information, and avoid dupcliated     *
*  issues or unclear question.                                *
*=============================================================*
```

pyarmor.error.log:
```
800348 MainProcess 2024-06-03 20:25:59,880
Traceback (most recent call last):
  File "/home/air/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 764, in main
    main_entry(sys.argv[1:])
  File "/home/air/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 752, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/air/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 244, in cmd_gen
    builder.process(options)
  File "/home/air/.local/lib/python3.11/site-packages/pyarmor/cli/generate.py", line 164, in process
    Pytransform3.pre_build(self.ctx)
  File "/home/air/.local/lib/python3.11/site-packages/pyarmor/cli/core/__init__.py", line 103, in pre_build
    m = Pytransform3.init(ctx)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/air/.local/lib/python3.11/site-packages/pyarmor/cli/core/__init__.py", line 83, in init
    m.init_ctx(ctx)
RuntimeError: invalid license token, try to run `pyarmor reg` to register license again
```

On host machine:
```
2024-06-03 20:25:59,876: receive request from ('10.42.3.19', 44414)
2024-06-03 20:25:59,876: unknown packet b''

```

**Comment by jondy** [comment]
How about specify host when start pyarmor-auth. Suppose docker host ip is 10.42.3.1
``` 
root@xxxx:xxx# pyarmor-auth --host 10.42.3.1 pyarmor-device-regfile-xxxx.1.zip   
```

Please use latest Pyarmor 8.5.9, because 8.5.8 still doesn't support `--host` for pyarmor-auth

**Comment by jondy** [comment]
I also uploaded a temporay test tool `a.out`, if possible, try to run it in docker container to check network connection to docker host

Just download
https://pyarmor.dashingsoft.com/downloads/temp/td.tar.gz

and `tar xzf td.tar.gz` to get `a.out`

Paste the console output here

**Comment by rmrmg** [comment]
It seems to me counterintuitive but add --host to pyarmor-auth, on host:
```
$ pyarmor-auth -d --host 172.18.0.1 /home/rmrmg/allchemyrepo/pyarmor-device-regfile-6290.2.zip
2024-06-12 11:38:37,188: work path: /home/rmrmg/.pyarmor/docker
2024-06-12 11:38:37,189: register "/home/rmrmg/allchemyrepo/pyarmor-device-regfile-6290.2.zip"
2024-06-12 11:38:37,230: extracting license.lic
2024-06-12 11:38:37,231: extracting .pyarmor_capsule.zip
2024-06-12 11:38:37,231: machine id in group license: m2dee6f44faf48854b6791574981434b2
2024-06-12 11:38:37,256: got machine id: m2dee6f44faf48854b6791574981434b2
2024-06-12 11:38:37,256: this machine id matchs group license
2024-06-12 11:38:37,256: extracting tokens/m2dee6f44faf48854b6791574981434b2
2024-06-12 11:38:37,258: machine id: [b'm2dee6f44faf48854b6791574981434b2', b'l2dee6f44faf48854b6791574981434b2', b'i2dee6f44faf48854b6791574981434b2', b'kc921b4c9ccdc5c16f4e314a75f00dffe', b'gbe433c70c6de394c1a963db845740e71', b'b2475160ff2c3451c90ed0ded1179fe19']
2024-06-12 11:38:37,258: listen container auth request on 172.18.0.1:29092`
```
In docker container:
```
# pip install pyarmor
Collecting pyarmor
  Downloading pyarmor-8.5.9-py3-none-any.whl.metadata (2.5 kB)
Collecting pyarmor.cli.core~=6.5.2 (from pyarmor)
  Downloading pyarmor.cli.core-6.5.2-cp39-none-manylinux1_x86_64.whl.metadata (3.0 kB)
Downloading pyarmor-8.5.9-py3-none-any.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 8.7 MB/s eta 0:00:00
Downloading pyarmor.cli.core-6.5.2-cp39-none-manylinux1_x86_64.whl (459 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 459.0/459.0 kB 8.4 MB/s eta 0:00:00
Installing collected packages: pyarmor.cli.core, pyarmor
Successfully installed pyarmor-8.5.9 pyarmor.cli.core-6.5.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv               
root@c88a4f825fe5:/code# pyarmor reg pyarmor-device-regfile-6290.2.zip
INFO     Python 3.9.2
INFO     Pyarmor 8.5.9 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "pyarmor-device-regfile-6290.2.zip"
INFO     machine id in group license: m2dee6f44faf48854b6791574981434b2
INFO     got machine id: m6adbf6eb902740e237f3279b498b547b
INFO     got machine id: l6adbf6eb902740e237f3279b498b547b
INFO     got machine id: i8902c0daf2fae127957b7a88b3064093
INFO     got machine id: k25c42d670e40ddbd271b561fc95daaa6
INFO     got machine id: g25c42d670e40ddbd271b561fc95daaa6
INFO     got machine id: b030b3cce291a32d3060145bee7df018d
INFO     no machine id matchs this group license
INFO     take this machine as docker container, and connect to docker host for authentication...
INFO     could not get docker host machine id

if this machine is docker container, please run command `pyarmor-auth` in docker host, and try it again

otherwise please generate new group device license for this machine

more information please check section "using group license" in documentation "how-to register" guide

ERROR    this group device license is not for this machine
ERROR    something is wrong
*=============================================================*
*  Please enable debug option `-d` to run it again            *
*    pyarmor -d gen options ...                               *
*                                                             *
*  Then check console log to find more information            *
*                                                             *
*  Please also check                                          *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*  or run `pyarmor man` to find solutions quickly             *
*=============================================================*
```
```
root@c88a4f825fe5:/code# ./a.out
check in container: 1
connect: Connection refused
```
Without --host options seems connections works:
```
 pyarmor-auth -d  /home/rmrmg/allchemyrepo/pyarmor-device-regfile-6290.2.zip                                                                                                                              
2024-06-12 11:54:44,234: work path: /home/rmrmg/.pyarmor/docker
2024-06-12 11:54:44,235: register "/home/rmrmg/allchemyrepo/pyarmor-device-regfile-6290.2.zip"
2024-06-12 11:54:44,240: extracting license.lic
2024-06-12 11:54:44,240: extracting .pyarmor_capsule.zip
2024-06-12 11:54:44,240: machine id in group license: m2dee6f44faf48854b6791574981434b2
2024-06-12 11:54:44,241: got machine id: m2dee6f44faf48854b6791574981434b2
2024-06-12 11:54:44,241: this machine id matchs group license
2024-06-12 11:54:44,241: extracting tokens/m2dee6f44faf48854b6791574981434b2
2024-06-12 11:54:44,243: machine id: [b'm2dee6f44faf48854b6791574981434b2', b'l2dee6f44faf48854b6791574981434b2', b'i2dee6f44faf48854b6791574981434b2', b'kc921b4c9ccdc5c16f4e314a75f00dffe', b'gbe433c70c6de394c1a963db845740e71', b'b2475160ff2c3451c90ed0ded1179fe19']
2024-06-12 11:54:44,244: listen container auth request on 0.0.0.0:29092
2024-06-12 11:54:48,394: receive request from ('172.18.0.7', 37458)
2024-06-12 11:54:48,394: request data (0): b''
2024-06-12 11:54:48,394: unknown packet b''
```
and in container:

```
root@c88a4f825fe5:/code# ./a.out
check in container: 1
dst addr is 10011ac
mask is ffff, src addr is 70012ac
```
then registration in container:
```
root@c88a4f825fe5:/code# pyarmor reg pyarmor-device-regfile-6290.2.zip
INFO     Python 3.9.2
INFO     Pyarmor 8.5.9 (trial), 000000, non-profits
INFO     Platform linux.x86_64
INFO     register "pyarmor-device-regfile-6290.2.zip"
INFO     machine id in group license: m2dee6f44faf48854b6791574981434b2
INFO     got machine id: mebc0fd1480ae98245450e50280a7a17e
INFO     got machine id: lebc0fd1480ae98245450e50280a7a17e
INFO     got machine id: i4fd76143e1cd7d4bdba03a6525fffa43
INFO     got machine id: k20d49b39cc2ec4b56d0345a2f83c24a7
INFO     got machine id: g20d49b39cc2ec4b56d0345a2f83c24a7
INFO     got machine id: b030b3cce291a32d3060145bee7df018d
INFO     no machine id matchs this group license
INFO     take this machine as docker container, and connect to docker host for authentication...
INFO     got docker host machine id: m2dee6f44faf48854b6791574981434b2
INFO     got docker host machine id: l2dee6f44faf48854b6791574981434b2
INFO     got docker host machine id: i2dee6f44faf48854b6791574981434b2
INFO     got docker host machine id: kc921b4c9ccdc5c16f4e314a75f00dffe
INFO     got docker host machine id: gbe433c70c6de394c1a963db845740e71
INFO     got docker host machine id: b2475160ff2c3451c90ed0ded1179fe19
INFO     This license registration information:

License Type    : pyarmor-group
License No.     : pyarmor-vax-006290
License To      : ALLCHEMY INC
License Product : allchemy

BCC Mode        : Yes
RFT Mode        : Yes

Notes
* Offline obfuscation

root@c88a4f825fe5:/
```

and log on host in pyarmor-auth console
```
2024-06-12 11:58:22,473: receive request from ('172.18.0.7', 58518)
2024-06-12 11:58:22,473: request data (64): b'PADHxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
2024-06-12 11:58:22,473: send auth result to ('172.18.0.7', 58518)
2024-06-12 11:58:22,473: response data (204): b'm2dee6f44faf48854b6791574981434b2\nl2dee6f44faf48854b6791574981434b2\ni2dee6f44faf48854b6791574981434b2\nkc921b4c9ccdc5c16f4e314a75f00dffe\ngbe433c70c6de394c1a963db845740e71\nb2475160ff2c3451c90ed0ded1179fe19\x00'
```

but then the same:
```
root@c88a4f825fe5:/code# pyarmor -d gen  --mix-str --private --obf-code 2  --enable-bcc --enable-rft  -r astDeadcodeRemover.py                                                                                                              
INFO     Python 3.9.2
INFO     Pyarmor 8.5.9 (group), 006290, allchemy
INFO     Platform linux.x86_64
DEBUG    native platform linux.x86_64
DEBUG    home path: /root/.pyarmor
DEBUG    command options: {'recursive': True, 'no_runtime': False, 'enable_bcc': True, 'enable_rft': True, 'obf_code': 2, 'mix_str': True, 'restrict_module': 2, 'inputs': ['astDeadcodeRemover.py']}                                       
DEBUG    install plugin: CodesignPlugin
DEBUG    install plugin: DarwinUniversalPlugin
INFO     search inputs ...
INFO     find script astDeadcodeRemover.py
INFO     find 1 top resources
DEBUG    unknown error, please check pyarmor.error.log
ERROR    invalid license token, try to run `pyarmor reg` to register license again
ERROR    something is wrong
*=============================================================*
*  Please check                                               *
*    https://pyarmor.readthedocs.io/en/latest/questions.html  *
*  or run `pyarmor man` to find solutions quickly             *
*                                                             *
*  It's recommand to report issue by `pyarmor man` in order   *
*  to provide necessary information, and avoid dupcliated     *
*  issues or unclear question.                                *
*=============================================================*
```
and log on host in pyarmor-auth console:
```
2024-06-12 12:01:39,999: receive request from ('172.18.0.7', 39178)
2024-06-12 12:01:39,999: request data (0): b''
2024-06-12 12:01:39,999: unknown packet b''
```

**Comment by jondy** [comment]
The reason is that host and container is not in same network.

host:      172.17.0.1
container: 172.18.0.7

mask is 0xffff, after mask  

host is       172.17.x.x
container is  172.18.x.x 

It's different.

Please configure the network to make sure both host and container is in the same network

**Comment by rmrmg** [comment]
Ok, when all is in the same subnetwork it works. However in most cases  --add-host=host.docker.internal:host-gateway (as sugested on https://pyarmor.readthedocs.io/en/latest/how-to/register.html#run-unlimited-dockers-in-offline-device) will not works.
So suggest to update documentation.

**Comment by jondy** [comment]
Got it.

**Comment by Benjamin-T** [comment]
> Ok, when all is in the same subnetwork it works. However in most cases --add-host=host.docker.internal:host-gateway (as sugested on https://pyarmor.readthedocs.io/en/latest/how-to/register.html#run-unlimited-dockers-in-offline-device) will not works. So suggest to update documentation.

Could you maybe share you step by step process to get you docker setup working? I cant seem to get my docker on the same subnet? I get a docker deamon error “address pool overlaps” when i setup the network:

```
version: '3.8'

services:
  app:
    image: your_image_name
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
```
