### ISSUE TITLE
[BUG] `ImportError: pyarmor_runtime_000000/pyarmor_runtime.so: undefined symbol: _PyFloat_Pack8`

### ISSUE THREAD

**Issue by stefanpejcic** [dashingsoft/pyarmor#1805]
Report runtime issue with:

- A clear title: [BUG] `ImportError: pyarmor_runtime_000000/pyarmor_runtime.so: undefined symbol: _PyFloat_Pack8`

- Full command options to obfuscate scripts
```bash
pip install pyarmor
pyarmor gen folder-name
```

- Full command to run the obfuscated scripts and traceback (if any)
```bash
gunicorn -c /usr/local/panel/conf/service.config.py app:app
```

- Necessary supplements and explanations

I am obfuscating the script for python311 on `CloudLinux 8.9` and it works on other Cloudlinux, Ubuntu, CentOS, but not on Debian.
On debian when I run the obfuscated script I get error:

```
[2024-06-03 22:11:09 +0000] [19034] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/admin/app.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "/usr/local/admin/pyarmor_runtime_000000/__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
ImportError: /usr/local/admin/pyarmor_runtime_000000/pyarmor_runtime.so: undefined symbol: _PyFloat_Pack8
[2024-06-03 22:11:09 +0000] [19035] [INFO] Worker exiting (pid: 19035)
[2024-06-03 22:11:09 +0000] [19034] [INFO] Worker exiting (pid: 19034)
[2024-06-03 22:11:09 +0000] [19033] [WARNING] Worker with pid 19035 was terminated due to signal 15
[2024-06-03 22:11:09 +0000] [19033] [INFO] Shutting down: Master
[2024-06-03 22:11:09 +0000] [19033] [INFO] Reason: Worker failed to boot.

```

When I perform the obfuscation on Debian and then run the script on Debian it works. 

I'm currently obfuscating separately for both

**Comment by stefanpejcic** [comment]
Do you mind sharing the actual link from https://pyarmor.readthedocs.io/ where i can find this "documented" problem  ??

**Comment by jondy** [comment]
This is the common solution in the FAQ:

If obfuscated scripts don’t work as expected, make sure you have read Understanding Obfuscated Script
https://pyarmor.readthedocs.io/en/latest/topic/obfuscated-script.html

**Comment by y-carl0s** [comment]
I faced to the same problem.
My case was mismatch of Python version between obfuscating env and executing env.
Obfuscated with Python 3.10 env but actually used in the Python 3.11 environment resulted in the error `pyarmor_runtime.so: undefined symbol: _PyFloat_Pack8`.

**Comment by hanswang73** [comment]
> This is the common solution in the FAQ:
> 
> If obfuscated scripts don’t work as expected, make sure you have read Understanding Obfuscated Script https://pyarmor.readthedocs.io/en/latest/topic/obfuscated-script.html

The understanding is that the Python version used with pyarmor should be consistent with the one at runtime. I encountered a situation where using sudo to execute Python led to a different Python version being used because the PATH variable under sudo differs from that without sudo, resulting in the same issue mentioned above.
