### ISSUE TITLE
[BUG] PyArmor 8.5.9 on Windows 11 VM: RuntimeError in generate_runtime_key

### ISSUE THREAD

**Issue by Kevin-Faeh** [dashingsoft/pyarmor#1807]
When calling the pyarmor 8.5.9 gen command on a Windows 11 VM a RuntimeError is raised. Following is the content of the pyarmor.report.bug file.
(License ID replaced)
```
[Bug] RuntimeError: Incorrect function.


### Full command options and console output
C:\BA\_work\_tool\Python\3.10.10\x64\Scripts\pyarmor -d gen --mix-str --output cython_build src\x1.py src\x2.py src\x3.py src\x4.py src\x5.py src\x6.py

2024-06-04 10:53:13,942 Python 3.10.10
2024-06-04 10:53:13,942 Pyarmor 8.5.9 (pro), XXXXX, name
2024-06-04 10:53:13,942 Platform windows.x86_64
2024-06-04 10:53:13,942 native platform windows.amd64
2024-06-04 10:53:13,942 home path: C:\Users\LabAdmin\.pyarmor
2024-06-04 10:53:13,942 command options: {'output': 'cython_build', 'no_runtime': False, 'mix_str': True, 'inputs': ['src\\x1.py', 'src\\x2.py', 'src\\x3.py', 'src\\x4.py', 'src\\x5.py', 'src\\x6.py']}
2024-06-04 10:53:13,942 install plugin: CodesignPlugin
2024-06-04 10:53:13,942 install plugin: DarwinUniversalPlugin
2024-06-04 10:53:13,942 search inputs ...
2024-06-04 10:53:13,942 find script src\mixture_analysis_no_ui.py
2024-06-04 10:53:13,942 find script src\mixture_analysis_report_writer_main.py
2024-06-04 10:53:13,942 find script src\ixture_analysis_report_writer.py
2024-06-04 10:53:13,942 find script src\mixture_analysis_result_viewer_main.py
2024-06-04 10:53:13,942 find script src\mixture_analysis_result_viewer.py
2024-06-04 10:53:13,942 find script src\mixture_analysis_ui.py
2024-06-04 10:53:13,942 find 6 top resources
2024-06-04 10:53:13,989 unknown error, please check pyarmor.error.log
2024-06-04 10:53:13,989 Incorrect function.




### Traceback
Traceback (most recent call last):
  File "C:\BA\_work\_tool\Python\3.10.10\x64\lib\site-packages\pyarmor\cli\__main__.py", line 764, in main
    main_entry(sys.argv[1:])
  File "C:\BA\_work\_tool\Python\3.10.10\x64\lib\site-packages\pyarmor\cli\__main__.py", line 752, in main_entry
    return args.func(ctx, args)
  File "C:\BA\_work\_tool\Python\3.10.10\x64\lib\site-packages\pyarmor\cli\__main__.py", line 244, in cmd_gen
    builder.process(options)
  File "C:\BA\_work\_tool\Python\3.10.10\x64\lib\site-packages\pyarmor\cli\generate.py", line 184, in process
    self.ctx.runtime_key = self.generate_runtime_key()
  File "C:\BA\_work\_tool\Python\3.10.10\x64\lib\site-packages\pyarmor\cli\generate.py", line 95, in generate_runtime_key
    return Pytransform3.generate_runtime_key(self.ctx, outer)
  File "C:\BA\_work\_tool\Python\3.10.10\x64\lib\site-packages\pyarmor\cli\core\__init__.py", line 99, in generate_runtime_key
    return m.generate_runtime_key(ctx, outer)
  File "<maker>", line 723, in generate_runtime_key
  File "<maker>", line 258, in build
  File "<maker>", line 175, in _pack_runtime_key
RuntimeError: Incorrect function.
```

**Comment by jondy** [comment]
I build new one at                                                          
https://pyarmor.dashingsoft.com/downloads/temp/windows/x86_64/py310/pytransform3.pyd 

Replace VM  `venv\Lib\site-packages\pyarmor\cli\core\pytransform3.pyd` with this one                                                                    
                                                                              
And try it again.

**Comment by Kevin-Faeh** [comment]
Hi Jondy this works, thank you!

**Comment by abbottbd** [comment]
@jondy - looks like this same/similar bug applies to Python 3.12.3, Pyarmor 8.5.9 and Windows Server 2022, although the error message is different.   I tested using PYthon 3.10.10 Pyarmor 8.5.9, and your patch above on server  2022 and the error goes away. 

#1810 

https://github.com/dashingsoft/pyarmor/issues/1810
