### ISSUE TITLE
[BUG] PyArmor 8.5.9 on Windows Server 2022 VM: RuntimeError: The request could not be performed because of an I/O device error.

### ISSUE THREAD

**Issue by abbottbd** [dashingsoft/pyarmor#1810]
When Calling pyarmor 8.5.9 gen command on Windows Server 2022 a runtimeerror occurs. Content of the bug file is below.  Noticed this is similar to a bug filed for windows 11.  Test that version (py3.10.10 and pyarmor 8.5.9) and this same error (I/O device error) happens with those versions on server 2022.  Tested the patch created for the windows 11 bug and it seems to resolve the issue on server 2022, however it is only good for python 3.10.10 - given patch doesn't work with python 3.12.3.  

Cross link to the closed bug: https://github.com/dashingsoft/pyarmor/issues/1807

[Bug] RuntimeError: The request could not be performed because of an I/O device error.

### Full command options and console output
./pyarmor -d gen C:\Users\abbottbr\Downloads\197\s\TorqUI\bin\Release\net6.0-windows\scripts\unobfuscated\torqui_compensate.py

2024-06-05 14:55:27,709 Python 3.12.3
2024-06-05 14:55:27,709 Pyarmor 8.5.9 (basic), 004506, TorqUI
2024-06-05 14:55:27,756 Platform windows.x86_64
2024-06-05 14:55:27,756 native platform windows.amd64
2024-06-05 14:55:27,756 home path: C:\Users\abbottbr\.pyarmor
2024-06-05 14:55:27,756 command options: {'no_runtime': False, 'inputs': ['C:\\Users\\abbottbr\\Downloads\\197\\s\\TorqUI\\bin\\Release\\net6.0-windows\\scripts\\unobfuscated\\torqui_compensate.py']}
2024-06-05 14:55:27,756 install plugin: CodesignPlugin
2024-06-05 14:55:27,756 install plugin: DarwinUniversalPlugin
2024-06-05 14:55:27,756 search inputs ...
2024-06-05 14:55:27,756 find script C:\Users\abbottbr\Downloads\197\s\TorqUI\bin\Release\net6.0-windows\scripts\unobfuscated\torqui_compensate.py
2024-06-05 14:55:27,756 find 1 top resources
2024-06-05 14:55:27,865 unknown error, please check pyarmor.error.log
2024-06-05 14:55:27,881 The request could not be performed because of an I/O device error.

### Traceback
Traceback (most recent call last):
  File "C:\Users\abbottbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\__main__.py", line 764, in main
    main_entry(sys.argv[1:])
  File "C:\Users\abbottbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\__main__.py", line 752, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abbottbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\__main__.py", line 244, in cmd_gen
    builder.process(options)
  File "C:\Users\abbottbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\generate.py", line 184, in process
    self.ctx.runtime_key = self.generate_runtime_key()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abbottbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\generate.py", line 95, in generate_runtime_key
    return Pytransform3.generate_runtime_key(self.ctx, outer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abbottbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyarmor\cli\core\__init__.py", line 99, in generate_runtime_key
    return m.generate_runtime_key(ctx, outer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 723, in generate_runtime_key
  File "<maker>", line 258, in build
  File "<maker>", line 175, in _pack_runtime_key
RuntimeError: The request could not be performed because of an I/O device error.

**Comment by jondy** [comment]
I have uploaded pre-release core
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor.cli.core.windows-6.5.3-cp310-none-any.whl

Download this wheel and unzip it, pick up `x86_64/pytransform3.pyd`

Replace `cp310` with other python version to download other wheel

**Comment by abbottbd** [comment]
thanks, using this resolved our issue!

**Comment by jondy** [comment]
Fixed in 8.5.10
