### ISSUE TITLE
[BUG] `Can't change error message`

### ISSUE THREAD

**Issue by ChangjunDAI** [dashingsoft/pyarmor#1829]
I followed the steps in the doc(v.8.5.3) 1.3.8: 
`mkdir .pyarmor`
`vim .pyarmor/message.cfg`

write new error messages in message.cfg:
```
[runtime.message]

  error_1 = e1
  error_2 = e2
  error_3 = e3
  error_4 = e4
  error_5 = e5
  error_6 = e6
  error_7 = e7
  error_8 = e8
```

Then, I tried to obfuscate the script
```
(software) mac@macdeMacBook-Pro encryption % pyarmor gen -e 2023-12-12 test.py
INFO     Python 3.10.14
INFO     Pyarmor 8.5.3 (group), 1111111, xxx
INFO     Platform darwin.x86_64
INFO     search inputs ...
INFO     find script test.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'darwin.x86_64'}
INFO     write dist/xx/xx.so
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "test"
INFO     obfuscating file test.py
INFO     write dist/test.py
INFO     obfuscate scripts OK
```
In this case, the error message should be: **e1**. However, I got the origin error message:
```
(software) mac@macdeMacBook-Pro encryption % python dist/test.py              
Traceback (most recent call last):
  File "/Users/mac/PycharmProjects/encryption/dist/test.py", line 2, in <module>
    from xxx import __pyarmor__
  File "/Users/mac/PycharmProjects/encryption/dist/HDTech2024/__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: 脚本许可证已经过期 (1:11086)
```

**Comment by jondy** [comment]
在仔细看看文档，缺少语言设置，检查一下环境变了 LANG

**Comment by ChangjunDAI** [comment]
按照1.4.7节增加语言设置：
```
(test_env) mac@macdeMacBook-Pro encryption % vim .pyarmor/message.cfg         

[runtime.message]

languages = zh_CN zh_TW

error_1 = invalid license
error_2 = invalid license

[runtime.message.zh_CN]

error_1 = 脚本超期
error_2 = 未授权设备

[runtime.message.zh_TW]

error_1 = 腳本許可證已經過期
error_2 = 腳本許可證不可用於當前設備
                                          
```

重新生成加密脚本并运行：
```
(test_env) mac@macdeMacBook-Pro encryption % pyarmor gen -e 2023-12-12 test.py
INFO     Python 3.10.13
INFO     Pyarmor 8.4.7 (group), 111111, xx
INFO     search inputs ...
INFO     find script test.py
INFO     find 1 top resources
INFO     start to generate runtime files
INFO     target platforms {'darwin.x86_64'}
INFO     write dist/xxx/pyarmor_runtime.so
INFO     generate runtime files OK
INFO     start to obfuscate scripts
INFO     process resource "test"
INFO     obfuscating file test.py
INFO     write dist/test.py
INFO     obfuscate scripts OK
(test_env) mac@macdeMacBook-Pro encryption % python dist/test.py              
Traceback (most recent call last):
  File "/Users/mac/PycharmProjects/encryption/dist/test.py", line 2, in <module>
    from xxx import __pyarmor__
  File "/Users/mac/PycharmProjects/encryption/dist/xxx/__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
RuntimeError: 脚本许可证已经过期 (1:10933)
```
仍然不对。
请告知文档哪个部分有更详细的说明
