### ISSUE TITLE
[BUG] `TypeError: can only concatenate str (not "int") to str`

### ISSUE THREAD

**Issue by HouKai999** [dashingsoft/pyarmor#1836]
**加密命令:**
`    pyarmor gen -O dist -r  stamp-model
`
**混淆版本:**
`pyarmor 8.5.9
`

**未加密的效果：**
```
104               101  1   4720640  seg.models.yolo.Conv                    [512, 1024, 3, 1]             
nc: 2, type: <class 'int'>
anchors: [[12, 16, 19, 36, 40, 28], [36, 75, 76, 55, 72, 146], [142, 110, 192, 243, 459, 401]], type: <class 'list'>
ch: [256, 512, 1024], type: <class 'list'>
2024-06-16 11:34:17,006 - yolov5:parse_model:525 - INFO:  105   [102, 103, 104]  1   1400798  seg.models.yolo.ISegment                [2, [[12, 16, 19, 36, 40, 28], [36, 75, 76, 55, 72, 146], [142, 110, 192, 243, 459, 401]], 32, 256, [256, 512, 1024]]
105   [102, 103, 104]  1   1400798  seg.models.yolo.ISegment                [2, [[12, 16, 19, 36, 40, 28], [36, 75, 76, 55, 72, 146], [142, 110, 192, 243, 459, 401]], 32, 256, [256, 512, 1024]]
2024-06-16 11:34:17,174 - yolov5:model_info:50 - INFO:  yolov7-seg summary: 417 layers, 37871486 parameters, 37871486 gradients
yolov7-seg summary: 417 layers, 37871486 parameters, 37871486 gradients
2024-06-16 11:34:17,174 - yolov5:__init__:383 - INFO:  
2024-06-16 11:34:20,306 - root:load:92 - INFO:  load successful
load successful
```

**加密后的报错：**
```
104               101  1   4720640  seg.models.yolo.Conv                    [512, 1024, 3, 1]             
[nc: nc, type: <class 'str'>
anchors: anchors, type: <class 'str'>
ch: [256, 512, 1024], type: <class 'list'>
[2024-06-16 11:30:15 +0000] [74] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/dist-packages/seldon_core/gunicorn_utils.py", line 107, in load
    self.user_object.load()
  File "<frozen ..Onlinestamp>", line 77, in load
  File "<frozen config>", line 3, in <module>
  File "<frozen ..config>", line 33, in <module>
  File "<frozen yolo>", line 449, in __init__
  File "<frozen yolo>", line 364, in __init__
  File "<frozen yolo>", line 521, in parse_model
  File "<frozen yolo>", line 257, in __init__
  File "<frozen yolo>", line 189, in __init__
TypeError: can only concatenate str (not "int") to str
[2024-06-16 11:30:15 +0000] [74] [INFO] Worker exiting (pid: 74)
Exception ignored in atexit callback: <function _exit_function at 0x7fcb589fb640>
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 147, in join
[2024-06-16 11:30:15 +0000] [70] [INFO] Handling signal: term
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process]
```

**源文件部分代码：**
```
class IDetect(nn.Module):
    # YOLOR Detect head for detection models
    stride = None  # strides computed during build
    dynamic = False  # force grid reconstruction
    export = False  # export mode

    def __init__(self, nc=80, anchors=(), ch=(), inplace=True):  # detection layer
        super().__init__()
        print(f"nc: {nc}, type: {type(nc)}")  # 调试信息
        print(f"anchors: {anchors}, type: {type(anchors)}")  # 调试信息
        print(f"ch: {ch}, type: {type(ch)}")  # 调试信息

        self.nc = nc  # number of classes
        self.no = nc + 5  # number of outputs per anchor
        self.nl = len(anchors)  # number of detection layers
        self.na = len(anchors[0]) // 2  # number of anchors
        self.grid = [torch.empty(1)] * self.nl  # init grid
        self.anchor_grid = [torch.empty(1)] * self.nl  # init anchor grid
        self.register_buffer('anchors', torch.tensor(anchors).float().view(self.nl, -1, 2))  # shape(nl,na,2)
        self.m = nn.ModuleList(nn.Conv2d(x, self.no * self.na, 1) for x in ch)  # output conv
        self.inplace = inplace  # use inplace ops (e.g. slice assignment)
        
        self.ia = nn.ModuleList(ImplicitA(x) for x in ch)
        self.im = nn.ModuleList(ImplicitM(self.no * self.na) for _ in ch)

    def forward(self, x):
        z = []  # inference output
        for i in range(self.nl):
            x[i] = self.m[i](self.ia[i](x[i]))  # conv
            bs, _, ny, nx = x[i].shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
            x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()

            if not self.training:  # inference
                if self.dynamic or self.grid[i].shape[2:4] != x[i].shape[2:4]:
                    self.grid[i], self.anchor_grid[i] = self._make_grid(nx, ny, i)

                y = x[i].clone()
                y[..., :5 + self.nc].sigmoid_()
                if self.inplace:
                    y[..., 0:2] = (y[..., 0:2] * 2 + self.grid[i]) * self.stride[i]  # xy
                    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
                else:  # for YOLOv5 on AWS Inferentia https://github.com/ultralytics/yolov5/pull/2953
                    xy, wh, etc = y.split((2, 2, self.no - 4), 4)  # tensor_split((2, 4, 5), 4) if torch 1.8.0
                    xy = (xy * 2 + self.grid[i]) * self.stride[i]  # xy
                    wh = (wh * 2) ** 2 * self.anchor_grid[i]  # wh
                    y = torch.cat((xy, wh, etc), 4)
                z.append(y.view(bs, -1, self.no))

        return x if self.training else (torch.cat(z, 1),) if self.export else (torch.cat(z, 1), x)

    def _make_grid(self, nx=20, ny=20, i=0, torch_1_10=check_version(torch.__version__, '1.10.0')):
        d = self.anchors[i].device
        t = self.anchors[i].dtype
        shape = 1, self.na, ny, nx, 2  # grid shape
        y, x = torch.arange(ny, device=d, dtype=t), torch.arange(nx, device=d, dtype=t)
        yv, xv = torch.meshgrid(y, x, indexing='ij') if torch_1_10 else torch.meshgrid(y, x)  # torch>=0.7 compatibility
        grid = torch.stack((xv, yv), 2).expand(shape) - 0.5  # add grid offset, i.e. y = 2.0 * x - 0.5
        anchor_grid = (self.anchors[i] * self.stride[i]).view((1, self.na, 1, 1, 2)).expand(shape)
        return grid, anchor_grid
```
从现象上看，混淆后的代码修改了nc，anchors变量的类型和内容

**Comment by jondy** [comment]
最好能提交一个简单的可以重现的脚本, 不需要使用第三方库

只通过这个脚本，看不出什么。nc 的type 发生了变化，给 nc 赋值的代码在那里
