### ISSUE TITLE
[BUG] docker外部密钥启动报错ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by brandy-xu** [dashingsoft/pyarmor#1839]
Traceback (most recent call last):
  File "/app/main.py", line 2, in <module>
    from usrlib import __pyarmor__
  File "/app/usrlib/__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
ValueError: bad marshal data (unknown type code)
docker启动容器报错信息，这个是什么原因导致的？

**Comment by jondy** [comment]
一般是 Python 版本不一致导致的，请参考文档中的常见问题以及通用解决方案
