### ISSUE TITLE
[BUG] HTTP 500 Server Error when Registering Pyarmor

### ISSUE THREAD

**Issue by gino2013** [dashingsoft/pyarmor#1856]
Dear Pyarmor Support Team,

I hope this email finds you well. I'm reaching out because I've encountered an issue while attempting to register my recently purchased Pyarmor license. I would greatly appreciate your assistance in resolving this matter.

Here are the specific details of the problem I'm experiencing:

1. I'm using Pyarmor version 8.5.10 on Python 3.9.18.

2. I attempted to register using the following command:
   pyarmor -d reg -p TBD pyarmor-regcode-5769-mail.txt

3. However, I received an HTTP 500 server error. Here's a summary of the error log:

   2024-07-01 11:44:13,011 url: https://api.dashingsoft.com/product/key/enter/xR7pL9mNqS3fA8bC1dE6gH2iJ4kO5tU0wX9yZ7vF2nM4qP6rT8uW1aD3cG5hB7jL9mN0pQ2sV4xY6zE8fH1iK3oR5tU/?&prepare=1 (modified to protect privacy)
   2024-07-01 11:44:13,011 query key file from server
   2024-07-01 11:44:15,296 HTTP Error 500
   2024-07-01 11:44:15,299 <h1>Server Error (500)</h1>

4. The full error traceback is as follows:

   Traceback (most recent call last):
     File "/Users/cfh00892977/anaconda3/envs/py39/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 764, in main
       main_entry(sys.argv[1:])
     File "/Users/cfh00892977/anaconda3/envs/py39/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 752, in main_entry
       return args.func(ctx, args)
     File "/Users/cfh00892977/anaconda3/envs/py39/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 318, in cmd_reg
       info, msg = regsvr.prepare(regfile, args.product, upgrade=upgrade)
     File "/Users/cfh00892977/anaconda3/envs/py39/lib/python3.9/site-packages/pyarmor/cli/register.py", line 403, in prepare
       raise CliError(res.read().decode('utf-8'))
   pyarmor.cli.CliError: <h1>Server Error (500)</h1>

I've tried running the command multiple times, but the issue persists. Could you please advise on how to proceed or provide any insights into what might be causing this server error?

Thank you for your time and assistance. I look forward to your response.

Best regards,
Lucian

![image](https://github.com/dashingsoft/pyarmor/assets/5793569/0c723516-601d-43be-b84f-4b0864e6c798)
![image](https://github.com/dashingsoft/pyarmor/assets/5793569/a3e14e86-1261-4af7-a8e8-5a2c62dc2446)

**Comment by jondy** [comment]
Please first check this
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#registration-failed
