### ISSUE TITLE
[BUG] `URLError: <urlopen error [Errno 104] Connection reset by peer>`

### ISSUE THREAD

**Issue by Zhaoxuyu** [dashingsoft/pyarmor#1861]
I am trying to register Pyarmor to our product, I use "pyarmor reg -p "Our product name" pyarmor-regcode-4575.txt".

but meet error "Connection reset by peer".

Below is detail information in <pyarmor.report.bug>:

Could you teach me how to solve this issue?

[Bug] URLError: <urlopen error [Errno 104] Connection reset by peer>

### Full command options and console output
/home/oem/.local/bin/pyarmor -d reg -p CIP ./pyarmor-regcode-4575.txt

2024-07-05 11:10:06,063 Python 3.10.12
2024-07-05 11:10:06,064 Pyarmor 8.5.8 (trial), 000000, non-profits
2024-07-05 11:10:06,067 Platform linux.x86_64
2024-07-05 11:10:06,067 native platform linux.x86_64
2024-07-05 11:10:06,067 home path: /home/oem/.pyarmor
2024-07-05 11:10:06,067 prepare "./pyarmor-regcode-4575.txt"
2024-07-05 11:10:06,068 url: https://api.dashingsoft.com/product/key/enter/lDyYD7qiMxjq9gyPCZRhtByamyY1V5dQN8kDcDaRemWiPxVbo8Aw3YP07H6jd_AU87oot2Jg4_w_PXvzDW_Pdo7TK4woQ3mpYdSuXPvLZ1V4O6MjcNdfhwW8Itwda2ZeRg6hREdTCyWDnYCxlU1A5Nm5pBt9UlTH8YQEpYWDQn8exh05FzpG7dPWwoqlhYYe/?&prepare=1
2024-07-05 11:10:06,068 query key file from server
2024-07-05 11:10:06,146 direct request failed "[Errno 104] Connection reset by peer"
2024-07-05 11:10:06,191 unknown error, please check pyarmor.error.log
2024-07-05 11:10:06,201 <urlopen error [Errno 104] Connection reset by peer>

### Traceback
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oem/.local/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 764, in main
    main_entry(sys.argv[1:])
  File "/home/oem/.local/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 752, in main_entry
    return args.func(ctx, args)
  File "/home/oem/.local/lib/python3.10/site-packages/pyarmor/cli/__main__.py", line 318, in cmd_reg
    info, msg = regsvr.prepare(regfile, args.product, upgrade=upgrade)
  File "/home/oem/.local/lib/python3.10/site-packages/pyarmor/cli/register.py", line 395, in prepare
    with self._send_request(url) as res:
  File "/home/oem/.local/lib/python3.10/site-packages/pyarmor/cli/register.py", line 367, in _send_request
    return urlopen(url, None, timeout, context=context)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

**Comment by Zhaoxuyu** [comment]
It is network issue, now solved.

**Comment by Zhaoxuyu** [comment]
It is network issue, now solved.
