### ISSUE TITLE
[BUG] `Traceback (most recent call last):   File "C:\Users\Administrator\Downloads\Compressed\dist\dist\main.py", line 2, in <module>     from pyarmor_runtime_000000 import __pyarmor__   File "C:\Users\Administrator\Downloads\Compressed\dist\dist\pyarmor_runtime_000000\__init__.py", line 2, in <module>     from .pyarmor_runtime import __pyarmor__ ImportError: DLL load failed while importing pyarmor_runtime: The specified module could not be found`

### ISSUE THREAD

**Issue by darkz0823** [dashingsoft/pyarmor#1862]
I Send File To My Friend And He Can't Open But Have Runtime Folder

**Comment by jondy** [comment]
Please first check FAQ in the online document and report bug following the guide
