### ISSUE TITLE
[BUG] ERROR    invalid license token, try to run `pyarmor reg` to register license again

### ISSUE THREAD

**Issue by geekblack22** [dashingsoft/pyarmor#1872]
Hello I have a pyarmor group license and what I find is that  I cannot run the obfuscation command in a jenkins build(Jenkins is running on on windows 10 64 bit server). I however can run it if I remote desktop into the device and run it manually from a terminal. Here is the error I get when I try to run pyarmor from the Jenkins build I am on the latest version(8.5.10):
27428 MainProcess 2024-07-16 08:58:54,112
Traceback (most recent call last):
  File "C:\Users\jenkins.service\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 764, in main
    main_entry(sys.argv[1:])
  File "C:\Users\jenkins.service\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 752, in main_entry
    return args.func(ctx, args)
  File "C:\Users\jenkins.service\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\__main__.py", line 240, in cmd_gen
    builder.process(options, packer=packer)
  File "C:\Users\jenkins.service\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\generate.py", line 179, in process
    Pytransform3.pre_build(self.ctx)
  File "C:\Users\jenkins.service\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\core\__init__.py", line 107, in pre_build
    m = Pytransform3.init(ctx)
  File "C:\Users\jenkins.service\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\cli\core\__init__.py", line 87, in init
    m.init_ctx(ctx)
RuntimeError: invalid license token, try to run `pyarmor reg` to register license again

**Comment by jondy** [comment]
Please first do this check list about Group license
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#registration-failed

**Comment by jondy** [comment]
I have no idea about Jenkins, but If Jenkins is one vm or docker container running in Windows, pyarmor group license for Windows doesn't work for it.

In Pyarmor world, VM and docker container is one standalone system.
