### ISSUE TITLE
[BUG] `request license token failed (4): NO:timeout/`

### ISSUE THREAD

**Issue by printpal-io** [dashingsoft/pyarmor#1885]
I am trying to register my license on another raspberry pi using the following code:
`pyarmor -d reg pyarmor-regfile-5695.zip`

 and get this error:

```
INFO     Python 3.9.2
INFO     Pyarmor 8.5.10 (trial), 000000, non-profits
INFO     Platform linux.aarch64
DEBUG    native platform linux.aarch64
DEBUG    home path: /home/pi/.pyarmor
INFO     register "pyarmor-regfile-5695.zip"
DEBUG    extracting license.lic
DEBUG    extracting .pyarmor_capsule.zip
INFO     update license token
DEBUG    unknown error, please check pyarmor.error.log
ERROR    request license token failed (4): NO:timeout/?ukey=<hidden_for_security_reasons>
INFO     generate bug file "pyarmor.report.bug"
ERROR    something is wrong

```

Content of `Pyarmor.report.bug`:

```

### Traceback
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 764, in main
    main_entry(sys.argv[1:])
  File "/home/pi/.local/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 752, in main_entry
    return args.func(ctx, args)
  File "/home/pi/.local/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 313, in cmd_reg
    reg.register_regfile(regfile)
  File "/home/pi/.local/lib/python3.9/site-packages/pyarmor/cli/register.py", line 210, in register_regfile
    self.update_token()
  File "/home/pi/.local/lib/python3.9/site-packages/pyarmor/cli/register.py", line 117, in update_token
    Pytransform3.init(self.ctx)
  File "/home/pi/.local/lib/python3.9/site-packages/pyarmor/cli/core/__init__.py", line 87, in init
    m.init_ctx(ctx)
RuntimeError: request license token failed (4): NO:timeout/?ukey=
```

**Comment by jondy** [comment]
Yesterday pyarmor license server is out of server about 1 hour.

How about now?

**Comment by printpal-io** [comment]
still receiving this issue @jondy

**Comment by jondy** [comment]
Check machine time is correct.

Also take this check list
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html
