### ISSUE TITLE
[BUG] Failure to register `HTTP Error 503: Service Temporarily Unavailable` 

### ISSUE THREAD

**Issue by PeteOnTheGitHub** [dashingsoft/pyarmor#1914]
**Reproduced steps**

pip install pyarmor==7.*
pyarmor register "%PyArmorRegCode%"

**Actual results**

INFO     PyArmor Trial Version 7.7.4
INFO     Python 3.8.10
INFO     Start to activate this code
ERROR    HTTP Error 503: Service Temporarily Unavailable

**With -d:**

INFO     PyArmor Trial Version 7.7.4
INFO     Python 3.8.10
INFO     Start to activate this code
Traceback (most recent call last):
  File "/home/user/.virtualenvs/draftable/lib/python3.8/site-packages/pyarmor/utils.py", line 1685, in _urlopen
    return urlopen(*args, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.virtualenvs/draftable/bin/pyarmor", line 8, in <module>
    sys.exit(main_entry())
  File "/home/user/.virtualenvs/draftable/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1612, in main_entry
    main(sys.argv[1:])
  File "/home/user/.virtualenvs/draftable/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1604, in main
    args.func(args)
  File "/home/user/.virtualenvs/draftable/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 866, in _register
    filename = activate_regcode(ucode)
  File "/home/user/.virtualenvs/draftable/lib/python3.8/site-packages/pyarmor/register.py", line 74, in activate_regcode
    res = _urlopen(reg_url % ucode, timeout=6.0)
  File "/home/user/.virtualenvs/draftable/lib/python3.8/site-packages/pyarmor/utils.py", line 1689, in _urlopen
    return urlopen(*args, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

**Expected results**

It works....

**Comment by jondy** [comment]
Please check the registration file `pyarmor-xxxx.txt`, use the second method to download .zip file, and register pyarmor with .zip file.

The `pyarmor-xxx.txt` file can't be used more than 100 times.

And do not run this command more than 3 times in one minutes, the server will reject too frequent reuqests.
