### ISSUE TITLE
[BUG] `_pickle.PicklingError: Can't pickle <function func1 at 0x0000016DA005BEC0>: attribute lookup func1 on func failed`

### ISSUE THREAD

**Issue by pnthai88** [dashingsoft/pyarmor#1920]
I'm working in multiple processing but it seem not able to start the child process function from another py file.

main.py
```
import multiprocessing
from func import func1

def main():
    print("this is main")

if __name__ == "__main__": 
    main()

    multiprocessing.freeze_support() #try this
    func = multiprocessing.Process(target=func1, name="USB Barcode manager")

    __spec__ = None #try this
    func.start()
```

func.py
```
def func1():
    print("hello world")
```

build.cmd
```
pyarmor reg
pyarmor cfg enable_trace=1
pyarmor cfg optimize 2
pyarmor cfg restrict_module=0
pyarmor cfg package_name_format "RT"
pyarmor cfg outer_keyname=RT.license
pyarmor gen key -O dist -e "2025-12-18"
pyarmor gen runtime --outer -O  dist

pyarmor gen --outer --use-runtime dist --platform windows.x86_64 --enable-themida --private --enable-jit --mix-str --assert-import --obf-module 1 --obf-code 2 main.py
pyarmor gen --outer --use-runtime dist --platform windows.x86_64 --enable-themida --private --enable-jit --mix-str --assert-import --obf-module 1 --obf-code 2 func.py
```

RESULT AFTER ENCODE WITH PYARMOR and before encode with PYARMOR
```
E:\test\mp\dist>py main.py
this is main
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen main>", line 14, in <module>
  File "C:\Users\thaip\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\thaip\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thaip\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\thaip\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\popen_spawn_win32.py", line 95, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\thaip\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function func1 at 0x000002433C8D8540>: attribute lookup func1 on func failed

E:\test\mp\dist>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\thaip\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 113, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thaip\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
           ^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied







E:\test\mp\dist>
E:\test\mp\dist>cd ..

E:\test\mp>py main.py
this is main
hello world
```

**Comment by jondy** [comment]
I suggest you first use the simplest options to test, and find which option results in this problem.

This is test script I used which it's pass

```python
from multiprocessing import Process
import os

def info(title):
    print(title)
    print('module name:', __name__)
    print('parent process:', os.getppid())
    print('process id:', os.getpid())

def f(name):
    info('function f')
    print('hello', name)

if __name__ == '__main__':
    info('main line')
    p = Process(target=f, args=('bob',))
    p.start()
    p.join()
```

**Comment by pnthai88** [comment]
> I suggest you first use the simplest options to test, and find which option results in this problem.
> 
> This is test script I used which it's pass
> 
> ```python
> from multiprocessing import Process
> import os
> 
> def info(title):
>     print(title)
>     print('module name:', __name__)
>     print('parent process:', os.getppid())
>     print('process id:', os.getpid())
> 
> def f(name):
>     info('function f')
>     print('hello', name)
> 
> if __name__ == '__main__':
>     info('main line')
>     p = Process(target=f, args=('bob',))
>     p.start()
>     p.join()
> ```

yea this one is good. But when i try to separate the "f" to something another py file like "another_function.py" then it starting problem. 

oh yea, i found the way to run it , i have to create another clone in main.py

```
import multiprocessing
from func import func1

def main():
    print("this is main")

def _clone_func1():
    func1()

if __name__ == "__main__": 
    main()

    multiprocessing.freeze_support() #try this
    func = multiprocessing.Process(target=_clone_func1, name="USB Barcode manager")

    __spec__ = None #try this
    func.start()
```
