### ISSUE TITLE
[BUG] `ImportError: __import__ not found` while using RTF mode

### ISSUE THREAD

**Issue by JiaPai12138** [dashingsoft/pyarmor#1962]
```
Microsoft Windows [Version 10.0.19044.5011]
(c) Microsoft Corporation. All rights reserved.

INFO     Python 3.12.7
INFO     Pyarmor 9.0.2 (pro), 00XXXX, XX
INFO     Platform windows.x86_64
usage: pyarmor [-h] [-v] [-q] [-d]  ...
```

Command:
```
pyarmor cfg enable_trace=1
pyarmor cfg trace_rft 1
::pyarmor cfg optimize 2
pyarmor gen --mix-str --exclude "./dist" --enable-jit --enable-rft --obf-code 2 .
```

origin script1.py:
```
# -*- coding: utf-8 -*-

import os
import signal
from ctypes import (CFUNCTYPE, POINTER, GetLastError, Structure, Union, WinDLL,
                    byref, c_bool, c_int, c_int32, c_short, c_size_t, c_uint8,
                    c_uint32, sizeof, windll, wintypes, pointer, memset)
...
...
...
```

..script1.py:
```
pyarmor__10 = __assert_armored__(b'\x83\xd5;')
pyarmor__11 = __assert_armored__(b'\x83\xc9!M\xdd\x14:')
pyarmor__12, pyarmor__13, pyarmor__14, pyarmor__15, pyarmor__16, pyarmor__17, pyarmor__18, pyarmor__19, pyarmor__20, pyarmor__21, pyarmor__22, pyarmor__23, pyarmor__24, pyarmor__25, pyarmor__26, pyarmor__27, pyarmor__28, pyarmor__29, pyarmor__30 = __assert_armored__(b'\x84\x13K\xf0\xb5\x16"\xe8@\xf4[=\x83f\x8a[d\x06\xdf\xd6et\x02\xf0\x14\x82\xb9;\x8a\xf0\x1a^"&\xe6p\\\x19"\xc3\x0eN\xa3S+\\$b\xec\x19Q\x97\x1b\xce\x0f\xe2S\x85\xb7\x1e\x84.}\xe3~+\xc5\x1e\x07\x99\x95oQ\xcb\x1e*\r\x13|\x19r\xb0p\xe1K@J\x81]\xc8_\x83]\x94\xc3\xbc\x03\xb3\xea\x9b\xc8\x12s\xd7\x1fR\xe4[\x1e\x84\xa0\x08B\xcf+\x1b\x89\xc4h6\xa5\xdd\xb9$\xff\t~j\xa1/\xb7h\xacA\xae\xbd\xb7I\xfd(\xc3\x1dNy\x9b~n7wY\xc2f\xd2L\x17\x9a\x11\xff\x12G\x10\x94\xfd3\x87\xc6\x84\xfa\xf8_\x07\xd1\xe2\x0eJ8\xc2\x11nl\xd5A\x1d\x8c\x86\xcb\xa4\xd1\xce9')
...
...
...
```

pyarmor.trace.log
```
trace.rft            ..script1:3 (import os as pyarmor__10)
trace.rft            ..script1:4 (import signal as pyarmor__11)
trace.rft            ..script1:5 (from ctypes import CFUNCTYPE as pyarmor__12, POINTER as pyarmor__13, GetLastError as pyarmor__14, Structure as pyarmor__15, Union as pyarmor__16, WinDLL as pyarmor__17, byref as pyarmor__18, c_bool as pyarmor__19, c_int as pyarmor__20, c_int32 as pyarmor__21, c_short as pyarmor__22, c_size_t as pyarmor__23, c_uint8 as pyarmor__24, c_uint32 as pyarmor__25, sizeof as pyarmor__26, windll as pyarmor__27, wintypes as pyarmor__28, pointer as pyarmor__29, memset as pyarmor__30)
...
...
...
```

ERROR:
```
python script1.py
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen ..script1>", line 1, in <module>
ImportError: __import__ not found
```

**Comment by jondy** [comment]
Please first check
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#failed-to-run-obfuscated-scripts

And report with clear description

**Comment by jondy** [comment]
I test this script by Python 3.12 in darwin.x86_64

`t1962.py`
```python
import os                                                            
import signal                                                        
from ctypes import (CFUNCTYPE, POINTER, Structure, Union, byref, c_bool, c_int, c_int32, c_short, c_size_t, c_uint8, c_uint32, sizeof, pointer, memset) 
# from ctypes import (CFUNCTYPE, POINTER, GetLastError, Structure, Union, WinDLL, byref, c_bool, c_int, c_int32, c_short, c_size_t, c_uint8, c_uint32, sizeof, windll, wintypes, pointer, memset) 
```

I removed some functions because they're only for Windows.

What I test is
```
pyarmor gen --enable-rft t1962.py
python3.12 dist/t1962.py
```

No exception raised.

If you have problem, please report like this with one scritpt could reproduce this issue

**Comment by Apprisco** [comment]
@jondy Issue replicated in python3.12 vs python 3.11 on pyarmor 8.5.12. pyarmor 9 just fails entirely

**Comment by jondy** [comment]
`__import__` is python builtin function, please check your python configuration, find solutions by any search engine

**Comment by jondy** [comment]
Please upgrade Pyarmor to latest version (v9.1.7) which is released just now to handle this case if there is no `__import__` in Python builtins names

**Comment by Warfront1** [comment]
For anyone having this issue on `pyarmor==8.5.12`, try to run your pyarmor gen on version `3.12.6` of Python.
It seems to work for me when I downgrade it.
