### ISSUE TITLE
[License Issue] Unable to get the registration file

### ISSUE THREAD

**Issue by StefanScoarta** [dashingsoft/pyarmor#1978]
Hello, We recently bought a CI license and I think that there is an issue on our side with the company firewall and I'm not able to get an registration file using the following command: pyarmor reg -p XXX pyarmor-regcode-8004.txt

Is there an alternative to do this?
We have an PyArmor 7 license too and things worked smoothly for that one.

Here is the error log file.

40756 MainProcess 2024-11-06 09:12:20,603
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Program Files\Python310\lib\http\client.py", line 1447, in connect
    super().connect()
  File "C:\Program Files\Python310\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "C:\Program Files\Python310\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Program Files\Python310\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\stefscoa\AppData\Roaming\Python\Python310\site-packages\pyarmor\cli\__main__.py", line 767, in main
    main_entry(sys.argv[1:])
  File "C:\Users\stefscoa\AppData\Roaming\Python\Python310\site-packages\pyarmor\cli\__main__.py", line 755, in main_entry
    return args.func(ctx, args)
  File "C:\Users\stefscoa\AppData\Roaming\Python\Python310\site-packages\pyarmor\cli\__main__.py", line 327, in cmd_reg
    info, msg = regsvr.prepare(regfile, args.product, upgrade=upgrade)
  File "C:\Users\stefscoa\AppData\Roaming\Python\Python310\site-packages\pyarmor\cli\register.py", line 538, in prepare
    with self._send_request(url) as res:
  File "C:\Users\stefscoa\AppData\Roaming\Python\Python310\site-packages\pyarmor\cli\register.py", line 510, in _send_request
    return urlopen(url, None, timeout, context=context)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

**Comment by StefanScoarta** [comment]
If I try to do this manually as I did for pyarmor 7 using this link: https://api.dashingsoft.com/product/key/enter/ and my new key I also get a connection timeout error

**Comment by StefanScoarta** [comment]
Hello again, I managed to fix if, it was an firewall/network issue.
