### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 188: illegal multibyte sequence

### ISSUE THREAD

**Issue by JLU-WY** [dashingsoft/pyarmor#1982]
## Traceback
Traceback (most recent call last):
  File "E:\Program\Python\evns\tem\lib\site-packages\pyarmor\cli\__main__.py", line 785, in main
    main_entry(sys.argv[1:])
  File "E:\Program\Python\evns\tem\lib\site-packages\pyarmor\cli\__main__.py", line 778, in main_entry
    return args.func(ctx, args)
  File "E:\Program\Python\evns\tem\lib\site-packages\pyarmor\cli\__main__.py", line 241, in cmd_gen
    builder.process(options, packer=packer)
  File "E:\Program\Python\evns\tem\lib\site-packages\pyarmor\cli\generate.py", line 179, in process
    Pytransform3.pre_build(self.ctx)
  File "E:\Program\Python\evns\tem\lib\site-packages\pyarmor\cli\core\__init__.py", line 110, in pre_build
    return m.pre_build(ctx)
  File "<maker>", line 731, in pre_build
  File "<maker>", line 658, in build
  File "<maker>", line 3431, in process
  File "E:\Program\Python\evns\tem\lib\site-packages\pyarmor\cli\resource.py", line 143, in reparse
    lines = self.readlines(encoding=encoding)
  File "E:\Program\Python\evns\tem\lib\site-packages\pyarmor\cli\resource.py", line 136, in readlines
    lines = f.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 188: illegal multibyte sequence

**Comment by JLU-WY** [comment]
Section: builder

Current settings
  encoding = gbk

Global settings

Local settings
  encoding = gbk

**Comment by JLU-WY** [comment]
This exception still occurs after setting up like this. How to solve it? This is true for versions 9 and 8.5.

**Comment by JLU-WY** [comment]
pyarmor gen -O obfdist --enable-rft --obf-code 0 --mix-str --assert-import --assert-call --pack ./funManger.exe -r funManger.py
 mulThreadCalDC.py ioPatch.py mergeFile.py

**Comment by jondy** [comment]
提示明明是 gbk 解码错误，为什么还要使用配置 encoding 为 gbk 呢?

首先检查文件头部是否有 --coding-- 设定，其次使用 

pyarmor cfg encoding utf-8

如果还有问题，请升级到 pyarmor v9.0.4，并使用 `pyarmor man` 提交问题
