### ISSUE TITLE
Pyarmor 3.13 Freethreading 9.0.5 DLL Load failed while importing pytransform3

### ISSUE THREAD

**Issue by Apprisco** [dashingsoft/pyarmor#1983]
No clue what's causing this.
```
Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\envs\trove13\Lib\site-packages\pyarmor\cli\__main__.py", line 785, in main
    main_entry(sys.argv[1:])
    ~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Anaconda3\envs\trove13\Lib\site-packages\pyarmor\cli\__main__.py", line 778, in main_entry
    return args.func(ctx, args)
           ~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Andrew\Anaconda3\envs\trove13\Lib\site-packages\pyarmor\cli\__main__.py", line 241, in cmd_gen
    builder.process(options, packer=packer)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\Anaconda3\envs\trove13\Lib\site-packages\pyarmor\cli\generate.py", line 179, in process
    Pytransform3.pre_build(self.ctx)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Andrew\Anaconda3\envs\trove13\Lib\site-packages\pyarmor\cli\core\__init__.py", line 109, in pre_build
    m = Pytransform3.init(ctx)
  File "C:\Users\Andrew\Anaconda3\envs\trove13\Lib\site-packages\pyarmor\cli\core\__init__.py", line 87, in init
    Pytransform3._pytransform3 = m = _import_pytransform3()
                                     ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Andrew\Anaconda3\envs\trove13\Lib\site-packages\pyarmor\cli\core\__init__.py", line 67, in _import_pytransform3
    return __import__(
        'pytransform3', globals=globals(), locals=locals(),
        fromlist=('__pyarmor__',), level=1
    )
ImportError: DLL load failed while importing pytransform3: The specified module could not be found.


```

**Comment by jondy** [comment]
Please first following this check list
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#bootstrap-failed

And report bug with `pyarmor man` to provide necessary information

**Comment by Apprisco** [comment]
![image](https://github.com/user-attachments/assets/250c72e9-7c39-4a4d-bd2a-e86c731220ce)
working script in python 3.11 and 3.12, when compiled in 3.13 causes above issue. With BCC/RFT

**Comment by jondy** [comment]
python-freethreading isn't supported by Pyarmor now.

`pyarmor man` could provide more information about the full command line options, and the build logs to help finding the problem.

If the report only includes traceback, in most of cases it can't help to fix the problem.
