### ISSUE TITLE
专家版9.06：

### ISSUE THREAD

**Issue by wac81** [dashingsoft/pyarmor#1998]
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen ..interface_1_second_frames_one_ws>", line 1, in <module>
ImportError: cannot import name 'pyarmor__882' from 'classifer.big_five_predictor' (/root/emotion_hr/classifer/big_five_predictor.py)
(env) root@wacbook:~/emotion_hr# tail logs/onews.log

为什么会出现pyarmor__882，确定没有使用这个作为prefix
直接执行  python classifer/big_five_predictor.py  结果正确

pyarmor命令：

```
pyarmor gen --exclude "./test/*" --exclude "./dist/*" --exclude "./settings.py" \
 --exclude "./emotion/fer.py" --exclude "./fatigue/models/*"  --outer --private  --assert-import --enable-rft --enable-bcc --mix-str ./ --prefix pyarmor2
```

**Comment by wac81** [comment]
Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen ..interface_1_second_frames_one_ws>", line 1, in <module>
  File "<frozen hr_hrv.inference_every_second_frames_onnx>", line 3, in <module>
  File "<frozen ..hr_hrv.inference_every_second_frames_onnx>", line 1, in <module>
  File "<frozen utils>", line 3, in <module>
  File "<frozen ..hr_hrv.utils>", line 1, in <module>
ImportError: cannot import name 'buy_url' from 'config' (/root/emotion_hr/dist/hr_hrv/config.py)

我都项目里都搜索不到buy_url ，这是pyarmor的吧？


不使用--assert-import --enable-rft --enable-bcc 就没事

**Comment by jondy** [comment]
请参考 https://pyarmor.readthedocs.io/zh/latest/reference/solutions.html#target-device

如果存在 Bug，请使用 `pyarmor man` 提供规范的问题报告
