### ISSUE TITLE
[BUG] `Error when running obfuscated code in conda env`

### ISSUE THREAD

**Issue by nothiin** [dashingsoft/pyarmor#1999]
Pyarmor works fine when using it outside the conda env. But gives an error when obfuscating it outside the env and using it through the conda env -
`Pyarmor 9.0.6 (pro)`
Here is the file structure, the codes used -
`pyarmor gen run.py
`

**Steps to Reproduce:**

1. I have a Python application protected with Pyarmor. The file structure looks like this:

    ```
    project_folder/
    ├── start.bat
    ├── run.py
    ├── pyarmor_runtime_007126/
    │   ├── __init__.py
    │   └── pyarmor_runtime.pyd
    ├── ffmpeg/ (contains ffmpeg binaries)
    ├── python/ (contains Python distribution)
    ├── models/ (contains application models)
    └── tmp/    (temporary directory)

    ```

2. My `start.bat` file is as follows:

    ```batch
    @echo off
    set pypath=home=%~dp0python
    set appdata=%~dp0tmp
    set userprofile=%~dp0tmp
    set temp=%~dp0tmp
    set PATH=%PATH%;ffmpeg;python\Lib\site-packages\torch\lib;models

    set CUDA_MODULE_LOADING=LAZY
    set CUDA_PATH=python\Lib\site-packages\torch\lib

    .\python\python.exe run.py
    pause
    ```

3. `run.py` - _obfuscated outside of conda env_ starts like this:

    ```python
    #!/usr/bin/env python3
    from pyarmor_runtime_007126 import __pyarmor__
    __pyarmor__(__name__, __file__, b'PY007126\x00\x0....')  # obfuscated part
    ```

4. `pyarmor_runtime_007126/__init__.py`:

    ```python
    # Pyarmor 9.0.6 (pro)
    from .pyarmor_runtime import __pyarmor__
    ```

5. `pyarmor_runtime_007126/pyarmor_runtime.pyd` is present in the directory.

6. When I execute `start.bat`, I get the following error:

    ```
    Traceback (most recent call last):
      File "run.py", line 3, in <module>
        from pyarmor_runtime_007126 import __pyarmor__
      File "pyarmor_runtime_007126\__init__.py", line 2, in <module>
        from .pyarmor_runtime import __pyarmor__
    ImportError: DLL load failed while importing pyarmor_runtime: The specified module could not be found.
    ```

**Comment by jondy** [comment]
Please following this check list to make sure the extension is right for this platform
https://pyarmor.readthedocs.io/en/latest/reference/solutions.html#target-device

**Comment by nothiin** [comment]
Is there a documentation/tutorial for obfuscating code outside of a conda env (where the pro license is registered)... and use the obfuscated code inside a conda env.

**Comment by jondy** [comment]
In Pyarmor view, it's cross platform.

Please search cross platform in pyarmor online doc.
