### ISSUE TITLE
Load _pytransfrom failed in linux x86_64 by subprocess.Popen

### ISSUE THREAD

**Issue by jondy** [dashingsoft/pyarmor#2]
I am two projects that will be using the pyArmor soon.  I have run tests in the past without problems.  I am now building my project on an AWS server.  When the app starts it reports "Cound not load library _pytransform."    I assume the "Cound" should be "Could"  
```
Traceback:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pytransform.py", line 183, in <module>
    _pytransform = _load_library()
  File "pytransform.py", line 175, in _load_library
    raise PytransformError('Cound not load library _pytransform.')
pytransform.PytransformError: Cound not load library _pytransform.
```

NOTES:
pyarmor 3.1.3

AWS uname -a: Linux ip-172-31-36-76 4.4.0-1035-aws #44-Ubuntu SMP Tue Sep 12 17:27:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 
The App:
```
------------------------------------------------------------------------
#! /usr/bin/env python
import time
import subprocess
import pyimcore

Arg = ['import pytransform\npytransform.exec_file("Main.pye")']
NewApplication = subprocess.Popen(['python','-c']+Arg)

try:
        while(True):
                time.sleep(1.0)
finally:
        NewApplication.terminate()
        StartTime = time.time()
        while (NewApplication.poll() is None):
                if (time.time()-StartTime>10):
                        break
-------------------------------------------------------------------------
```

**Comment by jondy** [comment]
Fixed in version 3.1.4.
