### ISSUE TITLE
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0x96 in position 0: invalid start byte

### ISSUE THREAD

**Issue by nekotaroneko** [dashingsoft/pyarmor#217]
hello i have this error
C:\Users\TEST\Desktop>pyarmor pack C:\Users\TEST\Desktop\あ.py
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0x96 in position 0: invalid start byte

I think the cause is path contains multi byte.
I can fix it by modifying pyarmor\packer.py.
line 312
`with open(patched_file, 'w') as f:` 
-->
 ` with open(patched_file, 'w', encoding='utf-8') as f:`
sorry for my bad English

**Comment by jondy** [comment]
The other way is specify the right source encoding at the beginning of the script, for example,
```
# -*- coding: utf-8 -*-
```

Refer to https://docs.python.org/2.7/tutorial/interpreter.html#source-code-encoding

**Comment by nekotaroneko** [comment]
a.py
```
#!/usr/bin/env python3
#coding: utf-8

print('OK')
```
b.py
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

print('OK')
```
but
C:\Users\TESTあ>pyarmor -d  pack C:\Users\TESTあ\a.py failed
C:\Users\TESTあ>pyarmor -d  pack C:\Users\TESTあ\b.py failed

and after modifying pyarmor\packer.py it works well
Also line 257
`with open(specfile) as f:`
-->
`with open(specfile, encoding='utf-8') as f:`

I forgot to say I use Windows python.

**Comment by nekotaroneko** [comment]
Detail error log
C:\Users\TESTあ>pyarmor -d  pack C:\Users\TESTあ\a.py
```
DEBUG    PyArmor installation path: c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor
DEBUG    PyArmor data path: C:\Users\aa\.pyarmor
DEBUG    Native platform is windows.x86
DEBUG    Search dynamic library in the path: c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\platforms
DEBUG    Loaded dynamic library: c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\platforms\windows\x86\_pytransform.dll
DEBUG    The version of core library is (16, 10, 7)
INFO     PyArmor Trial Version 5.9.6
INFO     Prepare to pack obfuscated scripts with PyInstaller...
INFO     entry script: a.py
INFO     src for searching scripts: .
INFO     build path: dist\obf
INFO     Run PyArmor to obfuscate scripts...
INFO

c:\users\aa\appdata\local\programs\python\python37-32\python.exe c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\pyarmor.py obfuscate -r -O dist\obf --exclude dist --package-runtime 0 .\a.py


INFO     Generate hook script: dist\obf\temp\hook-pytransform.py
INFO     Run PyInstaller to generate .spec file...
INFO

pyi-makespec -p dist\obf\temp --hidden-import pytransform --additional-hooks-dir dist\obf\temp .\a.py


INFO     Save .spec file to a.spec
INFO     Patching .spec file...
Traceback (most recent call last):
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\aa\AppData\Local\Programs\Python\Python37-32\Scripts\pyarmor.exe\__main__.py", line 7, in <module>
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\pyarmor.py", line 1241, in main_entry
    main(sys.argv[1:])
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\pyarmor.py", line 1233, in main
    args.func(args)
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\packer.py", line 472, in packer
    _pyinstaller(src, entry, output, extra_options, xoptions, args)
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\packer.py", line 389, in _pyinstaller
    patched_spec = _patch_specfile(obfdist, src, specfile, hookpath)
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\packer.py", line 258, in _patch_specfile
    lines = f.readlines()
UnicodeDecodeError: 'cp932' codec can't decode byte 0x82 in position 154: illegal multibyte sequence

```

**Comment by jondy** [comment]
I got it, I'll fix it in next version.

**Comment by nekotaroneko** [comment]
Thank you!!

**Comment by jondy** [comment]
Fixed in v5.9.7

**Comment by nekotaroneko** [comment]
I still got error.....
```
cd あ
pyarmor pack a.py
```
-->ok
But
`pyarmor pack あ\a.py`
-->error
so when  "path" contains muti -byte , error occurs.

after I modified function _make_hook_pytransform in packer.py , it works well.
`with open(hookfile, 'w') as f:`
-->
`with open(hookfile, 'w', encoding='utf-8') as f:`

LOG
```
C:\Users\aa\TEST>pyarmor pack あ\a.py
INFO     PyArmor Trial Version 5.9.7
INFO     Prepare to pack obfuscated scripts with PyInstaller...
INFO     entry script: a.py
INFO     src for searching scripts: あ
INFO     build path: あ\dist\obf
INFO     Run PyArmor to obfuscate scripts...
INFO

c:\users\aa\appdata\local\programs\python\python37-32\python.exe c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\pyarmor.py obfuscate -r -O あ\dist\obf --exclude あ\dist --package-runtime 0 あ\a.py


INFO     ==================== Run command ====================
INFO     PyArmor Trial Version 5.9.7
INFO     Source path is "C:\Users\aa\TEST\あ"
INFO     Entry scripts are ['あ\\a.py']
INFO     Use cached capsule C:\Users\aa\.pyarmor_capsule.zip
INFO     Recursive mode is on
INFO     Exclude path "あ\dist"
INFO     Auto exclude output path "dist\obf"
no previously-included directories found matching 'あ\dist'
INFO     Save obfuscated scripts to "あ\dist\obf"
INFO     Read public key from capsule
INFO     Obfuscate scripts with default mode
INFO     Advanced mode is 0
INFO     Restrict mode is 1
INFO            a.py -> あ\dist\obf\a.py
INFO     Insert shell line: #!/usr/bin/env python3
INFO     Insert bootstrap code to entry script あ\dist\obf\a.py
INFO     1 scripts have been obfuscated
INFO     Generating runtime files to あ\dist\obf
INFO     Extract pytransform.key
INFO     Extract license.lic
INFO     Copying c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\platforms\windows\x86\_pytransform.dll
INFO     Generate runtime files OK
INFO     Obfuscate scripts with restrict mode on
INFO     Obfuscate 1 scripts OK.
INFO     ==================== End command ====================

INFO     Generate hook script: あ\dist\obf\temp\hook-pytransform.py
INFO     Run PyInstaller to generate .spec file...
INFO

pyi-makespec -p あ\dist\obf\temp --hidden-import pytransform --additional-hooks-dir あ\dist\obf\temp あ\a.py


INFO     ==================== Run command ====================
wrote C:\Users\aa\TEST\a.spec
now run pyinstaller.py to build the executable
INFO     ==================== End command ====================

INFO     Save .spec file to a.spec
INFO     Patching .spec file...
INFO     Save patched .spec file to a-patched.spec
INFO     Run PyInstaller with patched .spec file...
INFO

c:\users\aa\appdata\local\programs\python\python37-32\python.exe -m PyInstaller --distpath あ\dist -y a-patched.spec


INFO     ==================== Run command ====================
82 INFO: PyInstaller: 3.6
83 INFO: Python: 3.7.1
84 INFO: Platform: Windows-10-10.0.18362-SP0
87 INFO: UPX is not available.
88 INFO: Extending PYTHONPATH with paths
['C:\\Users\\aa\\TEST\\あ',
 'C:\\Users\\aa\\TEST\\あ\\dist\\obf\\temp',
 'C:\\Users\\aa\\TEST']
89 INFO: checking Analysis
95 INFO: Building because inputs changed
95 INFO: Initializing module dependency graph...
99 INFO: Caching module graph hooks...
112 INFO: Analyzing base_library.zip ...
4901 INFO: Caching module dependency graph...
5054 INFO: running Analysis Analysis-00.toc
5084 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\aa\appdata\local\programs\python\python37-32\python.exe
5385 INFO: Analyzing あ\a.py
5387 INFO: Analyzing hidden import 'pytransform'
5488 INFO: Processing module hooks...
5488 INFO: Loading module hook "hook-encodings.py"...
5611 INFO: Loading module hook "hook-pydoc.py"...
5613 INFO: Loading module hook "hook-xml.py"...
5983 INFO: Loading module hook "hook-pytransform.py"...
Traceback (most recent call last):
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\__main__.py", line 121, in <module>
    run()
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "a-patched.spec", line 17, in <module>
    noarchive=False)
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 244, in __init__
    self.__postinit__()
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 422, in assemble
    self.graph.process_post_graph_hooks()
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\analysis.py", line 311, in process_post_graph_hooks
    module_hook.post_graph()
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\imphook.py", line 417, in post_graph
    self._load_hook_module()
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\depend\imphook.py", line 384, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\users\aa\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\compat.py", line 797, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\aa\TEST\あ\dist\obf\temp\hook-pytransform.py", line 2
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0x82 in position 0: invalid start byte
INFO     ==================== End command ====================

ERROR    Run command failed
```

**Comment by nekotaroneko** [comment]
Uhh I got another error.
I know the reason.It is patched.spec.
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['dist\\obf\\temp', 'C:\\Users\\aa\\Desktop\\Qt\\テスト'],
.....


<<<Different encoding>>>

# Patched by PyArmor
_src = 'C:\\Users\\aa\\Desktop\\Qt\\?e?X?g' <-- THIS
for i in range(len(a.scripts)):
.....
```

so would you change function _patch_specfile
encoding = None
-->
encoding = 'utf-8'

**Comment by jondy** [comment]
Thanks, got it, I'll check all the other `open` functions.

> so would you change function _patch_specfile
> encoding = None
> -->
> encoding = 'utf-8'

Because I also need make it works for python2.7, and other python3.x versions, and in different platforms. At least `utf-8` encoding doesn't work for Python3.4 in Windows, so I cann't  set encoding to `utf-8` simply. Anyway I'll refine the code and make it work for all the cases.

**Comment by nekotaroneko** [comment]
Thank you for quick replay.

**Comment by jondy** [comment]
@nekotaroneko 
Would you try this `packer.py` work or not? Just download it and overwrite the old one
https://github.com/dashingsoft/pyarmor/raw/master/src/packer.py

Now it will get encoding from the first comment line in the `.spec` file

**Comment by nekotaroneko** [comment]
It works perfectly!!.Thank you!!

**Comment by alikaz3mi** [comment]
I am facing this issue in pyarmor 8.3.1. What should I do?
