### ISSUE TITLE
win32ctypes.pywin32.pywintypes.error: (2, 'LoadLibraryExW', '系统找不到指定的文件。')

### ISSUE THREAD

**Issue by spectrumAI** [dashingsoft/pyarmor#226]
Hi Jondy,

I am using Pyarmor 3.6 and run on Win10 under conda python=3.6 environment. when I run 

pyinstaller my_python.py 

everything is good. I can successfully build and successfully run the exe. 

But, when I run

pyarmor pack my_pathon.py, I constantly get the following error. I have tried to used both Pyinstaller 3.6 and Pyinstaller 4.0. Both with the same error, as blow. I was wondering whether this is caused by something innate to pyarmor, because it runs well using pyinstaller alone. Thank you for your help!

39726 INFO: Loading module hook 'hook-pytransform.py' from 'C:\\Users\\ali\\spectrumAI\\dist\\obf\\temp'...
39730 INFO: Loading module hook 'hook-imageio.py' from 'c:\\users\\ali\\anaconda3\\envs\\py36\\lib\\site-packages\\PyInstaller\\hooks'...
39841 INFO: Looking for ctypes DLLs
39932 INFO: Analyzing run-time hooks ...
39943 INFO: Including run-time hook 'c:\\users\\ali\\anaconda3\\envs\\py36\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
39946 INFO: Including run-time hook 'c:\\users\\ali\\anaconda3\\envs\\py36\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
39948 INFO: Including run-time hook 'c:\\users\\ali\\anaconda3\\envs\\py36\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32comgenpy.py'
39950 INFO: Including run-time hook 'c:\\users\\ali\\anaconda3\\envs\\py36\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
39952 INFO: Including run-time hook 'c:\\users\\ali\\anaconda3\\envs\\py36\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyqt5.py'
39953 INFO: Including run-time hook 'c:\\users\\ali\\anaconda3\\envs\\py36\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_mplconfig.py'
39955 INFO: Including run-time hook 'c:\\users\\ali\\anaconda3\\envs\\py36\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_mpldata.py'
39980 INFO: Looking for dynamic libraries
40057 WARNING: lib not found: impi.dll dependency of c:\users\ali\anaconda3\envs\py36\Library\bin\mkl_blacs_intelmpi_ilp64.dll
Traceback (most recent call last):
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\win32ctypes\core\ctypes\_util.py", line 42, in check_null
    raise make_error(function, function_name)
OSError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ali\anaconda3\envs\py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ali\anaconda3\envs\py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\__main__.py", line 121, in <module>
    run()
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\building\build_main.py", line 735, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\building\build_main.py", line 682, in build
    exec(code, spec_namespace)
  File "spectrumVision-patched.spec", line 17, in <module>
    noarchive=False)
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\building\build_main.py", line 247, in __init__
    self.__postinit__()
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\building\build_main.py", line 472, in assemble
    redirects=self.binding_redirects))
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\depend\bindepend.py", line 228, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\depend\bindepend.py", line 407, in getAssemblyFiles
    for assembly in getAssemblies(pth):
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\depend\bindepend.py", line 358, in getAssemblies
    res = GetManifestResources(pth)
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1000, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 170, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "c:\users\ali\anaconda3\envs\py36\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\ali\anaconda3\envs\py36\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (2, 'LoadLibraryExW', '系统找不到指定的文件。')
INFO     ==================== End command ====================

**Comment by jondy** [comment]
If there is virtual venv in the current path, try to exclude them, for example
`pyarmor -x " --exclude venv" mypython.py`

**Comment by jondy** [comment]
Besides there is another way to location errors:

1. First run `pack` with `--debug`, for example, `pyarmor pack --debug my_python.py`

2. Make sure `Pyinstaller` with no patched `.spec` works
    pyinstaller -y --clean my_python.spec

3. Then run `pyinstaller` with `my_python-patched.spec`
    pyinstaller -y --clean my_python-patched.spec

If something is wrong, try to edit the `my_python-patched.spec` with some other options, and run it again.

**Comment by spectrumAI** [comment]
What is the difference between my_python.spec and my_python-patched.spec?

**Comment by jondy** [comment]
The latter is patched by `pack` command in order to replace the plain scripts with the obfuscated ones.
