### ISSUE TITLE
FileNotFoundError: [WinError 2] - The file can not be found

### ISSUE THREAD

**Issue by BarryThrill** [dashingsoft/pyarmor#241]
Hello!

So I have been trying to use pyarmor with license which worked fine a month ago and I havent really touched since then. What I did was I upgraded to 3.8 and I installed pyarmor with license and pyinstaller. 

When I try to do a simple 

`pyarmor pack --debug my_python.py`

that returns:

```
INFO     40 scripts have been obfuscated
INFO     Generating runtime files to dist\obf
INFO     Extract pytransform.key
INFO     Generate default license.lic
INFO     Copying c:\users\barry-pc\appdata\local\programs\python\python38\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Generate runtime files OK
INFO     Obfuscate 40 scripts OK.
INFO     ==================== End command ====================

INFO     Create temp path: dist\obf\temp
INFO     Run PyInstaller to generate .spec file...
INFO

pyi-makespec -p dist\obf\temp --hidden-import pytransform --additional-hooks-dir dist\obf\temp .\autoraffle.py

INFO     ==================== Run command ====================
Traceback (most recent call last):
  File "c:\users\barry-pc\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\barry-pc\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Barry-PC\AppData\Local\Programs\Python\Python38\Scripts\pyarmor.exe\__main__.py", line 7, in <module>
  File "c:\users\barry-pc\appdata\local\programs\python\python38\lib\site-packages\pyarmor\pyarmor.py", line 1245, in main_entry
    main(sys.argv[1:])
  File "c:\users\barry-pc\appdata\local\programs\python\python38\lib\site-packages\pyarmor\pyarmor.py", line 1237, in main
    args.func(args)
  File "c:\users\barry-pc\appdata\local\programs\python\python38\lib\site-packages\pyarmor\packer.py", line 507, in packer
    _pyinstaller(src, entry, output, extra_options, xoptions, args)
  File "c:\users\barry-pc\appdata\local\programs\python\python38\lib\site-packages\pyarmor\packer.py", line 407, in _pyinstaller
    _pyi_makespec(obftemp, src, entry, packcmd)
  File "c:\users\barry-pc\appdata\local\programs\python\python38\lib\site-packages\pyarmor\packer.py", line 263, in _pyi_makespec
    run_command(cmdlist)
  File "c:\users\barry-pc\appdata\local\programs\python\python38\lib\site-packages\pyarmor\packer.py", line 83, in run_command
    p = Popen(cmdlist)
  File "c:\users\barry-pc\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\barry-pc\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The file can not be found
```

I can't find out where the issue is by the code so I am here to ask what am I doing actually wrong :(

Appreciate the help!

**Comment by jondy** [comment]
Try to run `pyarmor pack` with extra option `--clean`, if still not work, check this command work or not?
```
pyi-makespec autoraffle.py
```

**Comment by BarryThrill** [comment]
Oh! That worked! I also reinstalled pyarmor aswell to be sure :)
