### ISSUE TITLE
Bindkey example does not work in python 3.7

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#250]
https://pyarmor.readthedocs.io/en/latest/advanced.html#binding-obfuscated-scripts-to-python-interpreter

```python
import sys

from ctypes import CFUNCTYPE, cdll, pythonapi, string_at, c_void_p, c_char_p


def get_bind_key():
    c = cdll.LoadLibrary(None)

    if sys.platform.startswith('win'):
        from ctypes import windll
        dlsym = windll.kernel32.GetProcAddressA
    else:
        prototype = CFUNCTYPE(c_void_p, c_void_p, c_char_p)
        dlsym = prototype(('dlsym', c))

    refunc1 = dlsym(pythonapi._handle, 'PyEval_EvalCode')
    refunc2 = dlsym(pythonapi._handle, 'PyEval_GetFrame')

    size = refunc2 - refunc1
    code = string_at(refunc1, size)

    checksum = 0
    for c in code:
        checksum += ord(c)
    print('Get bind key: %s' % checksum)


if __name__ == '__main__':
    get_bind_key()
```

```
Traceback (most recent call last):
  File "./bindkey.py", line 30, in <module>
    get_bind_key()
  File "./bindkey.py", line 17, in get_bind_key
    refunc1 = dlsym(pythonapi._handle, 'PyEval_EvalCode')
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

It works in python 2.7, but fails in python 3.7

**Comment by jondy** [comment]
Fixed version
```python
  import sys

  from ctypes import CFUNCTYPE, cdll, pythonapi, string_at, c_void_p, c_char_p


  def get_bind_key():
      c = cdll.LoadLibrary(None)

      if sys.platform.startswith('win'):
          from ctypes import windll
          dlsym = windll.kernel32.GetProcAddressA
      else:
          prototype = CFUNCTYPE(c_void_p, c_void_p, c_char_p)
          dlsym = prototype(('dlsym', c))

      refunc1 = dlsym(pythonapi._handle, b'PyEval_EvalCode')
      refunc2 = dlsym(pythonapi._handle, b'PyEval_GetFrame')

      size = refunc2 - refunc1
      code = string_at(refunc1, size)

      checksum = 0
      for c in bytearray(code):
          checksum += c
      print('Get bind key: %s' % checksum)


  if __name__ == '__main__':
      get_bind_key()
```

**Comment by dror-weiss** [comment]
@jondy , 
I've tested your fixed version above on a python 3.7.5 docker and I'm getting the following error:
```
root@30cab2e771fc:/opt/app# python fixed_version.py 
Traceback (most recent call last):
  File "fixed_version.py", line 26, in <module>
    get_bind_key()
  File "fixed_version.py", line 20, in get_bind_key
    code = string_at(refunc1, size)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 505, in string_at
    return _string_at(ptr, size)
SystemError: Negative size passed to PyBytes_FromStringAndSize
```
So I tried setting the absolute value `size = abs(refunc2 - refunc1)` and then I get a response: 

> Get bind key: 5383802

However, this key used while generating a license to my project apparently is wrong and I get:
```
Traceback (most recent call last):
  File "/opt/app/manage.py", line 2, in <module>
    pyarmor(__name__, __file__, b'\x50\x59\x41\x52\x4d ... \x4e\xa9\xa7\x5b', 2)
RuntimeError: License is not for this machine
```
, where `manage.py` is the entry script.

Why it appears to provide the wrong key?

**Comment by jondy** [comment]
@dror-weiss I think fix-key license mayn't work with this python. The alternative is to use plugin to extend license type. 

First define plugin script `check_fixed_key.py`

``` python
from ctypes import CFUNCTYPE, cdll, pythonapi, py_object, string_at, c_void_p, c_char_p

def get_bind_key():
    c = cdll.LoadLibrary(None)

    prototype = CFUNCTYPE(c_void_p, c_void_p, c_char_p)
    dlsym = prototype(('dlsym', c))

    refunc1 = dlsym(pythonapi._handle, b'_PyEval_EvalFrameDefault')
    refunc2 = dlsym(pythonapi._handle, b'PyEval_EvalCodeEx')

    # print('refunc1 at %x, refunc2 at %x' % (refunc1, refunc2))

    size = refunc2 - refunc1
    code = string_at(refunc1, size)

    return sum(bytearray(code))


def _get_license_data():
    from pytransform import _pytransform
    prototype = PYFUNCTYPE(py_object)
    dlfunc = prototype(('get_registration_code', _pytransform))
    rcode = dlfunc().decode()
    index = rcode.find(';', rcode.find('*CODE:'))
    return rcode[index+1:]


def check_fixed_key():
    excepted = _get_license_data()
    value = _get_bind_key()

    # print('Get bind key: %s' % value)

    if excepted != value:
        raise RuntimeError('License is not for this machine')    
```

The key is that get the code sum of python library in this machine, and check it by plugin, about how to use plugin, refer to
https://github.com/dashingsoft/pyarmor/tree/master/plugins

**Comment by dror-weiss** [comment]
@jondy , your script above does seem to produce a workable solution, however, I kept getting a different value from your `get_bind_key` method every time I ran the plugin in my main platform. It wasn't stable. It appears the solution was to calculate the interpreter id using `reffunc2` rather than the other.

This is my working solution for producing the interpreter id:

**pyarmor/extract_interpreter_id.py**:
```python
from __future__ import print_function
from __future__ import absolute_import
from __future__ import division

# 3rd party
import argparse
from ctypes import CFUNCTYPE, cdll, pythonapi, string_at, c_void_p, c_char_p


def get_interpreter_id() -> int:
    prototype = CFUNCTYPE(c_void_p, c_void_p, c_char_p)
    dlsym = prototype(("dlsym", cdll.LoadLibrary(None)))
    refunc1 = dlsym(pythonapi._handle, b'_PyEval_EvalFrameDefault')
    refunc2 = dlsym(pythonapi._handle, b'PyEval_EvalCodeEx')
    size = abs(refunc2 - refunc1)
    code = string_at(refunc2, size)
    return sum(bytearray(code))


def _write_to_file(filename: str, interpreter_id: int) -> None:
    with open(filename, "w+") as file:
        file_content = str(interpreter_id)
        file.write(file_content)


def _parse_arguments() -> dict:
    parser = argparse.ArgumentParser(
        description="Detect the bind key for binding obfuscated scripts to Python interpreter")
    parser.add_argument("-o", "--output", help="The name of the output file", required=True)
    args = parser.parse_args()
    return args


if __name__ == '__main__':
    args = _parse_arguments()
    interpreter_id = get_interpreter_id()
    _write_to_file(args.output, interpreter_id)

```

**pyarmor/plugins/verify_interpreter.py**:
```python

# app
from pyarmor.extract_interpreter_id import get_interpreter_id as get_interpreter_id_from_platform


def _get_interpreter_id_from_license() -> int:
    from pytransform import get_user_data
    user_data = get_user_data()
    interpreter_id = int(user_data)
    return interpreter_id


def verify_interpreter():
    interpreted_id = get_interpreter_id_from_platform()
    expected_interpreted_id = _get_interpreter_id_from_license()
    if interpreted_id != expected_interpreted_id:
        raise RuntimeError(
            f"License is not for this machine; expecting id '{expected_interpreted_id}', got '{interpreted_id}'")
```

```Dockerfile
FROM base AS interpreter_id_extractor

# cd
WORKDIR /pyarmor

COPY pyarmor/extract_interpreter_id.py .
RUN python extract_interpreter_id.py -o interpreter_id

FROM python:3.7 AS obfuscator

# cd
WORKDIR /pyarmor

# Copy the target bind key from the target platform.
COPY --from=interpreter_id_extractor /pyarmor/interpreter_id .

# Register pyarmor...

# Copy the source files...

# Generate a license for the application, bound to interpreter and expiration date.
RUN pyarmor licenses \
    --bind-data $(cat interpreter_id) \
    --enable-period-mode \
    runtime_licence

# Copy PyArmor's plugins and configuration.
COPY .pyarmor_config .
RUN pyarmor config \
    --with-license licenses/runtime_licence/license.lic \
    --plugin /app/pyarmor/plugins/verify_interpreter

# Obfuscate the source files according to the configurations and remove docstring as well.
RUN PYTHONOPTIMIZE=2 && pyarmor build -B
```

**Entry script**:
```python
from __future__ import print_function
from __future__ import absolute_import
from __future__ import division

# {PyArmor Plugins}
# PyArmor Plugin: verify_interpreter()

# 3rd party
from flask import request
...
```

**Comment by jondy** [comment]
@dror-weiss It seems this python is not build with `-fPIC`, the code segment of python interpreter isn't position independent. 

Anyway for your case, checking code segment doesn't work. You can check the content of `libpython3.7.so`, verify this file is same as expected.

**Comment by dror-weiss** [comment]
@jondy ,

**Is there any way to bind the code to the python in my docker's image only?**

I have a docker image with python installed from the `ppa:deadsnakes/ppa` repository.
As far as I can tell it's is PIE enabled.

```bash
root@d45d681b05e9:/# apt-get update && apt-get install -y file

root@d45d681b05e9:/# file /usr/bin/python3.7
/usr/bin/python3.7: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=d3f6a0f5892175a0e3625f84408f117b64dc44de, stripped

root@d45d681b05e9:/# file /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0 
/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=10adaafee4408936c998a277511730125eae3a15, stripped
```
```unix
root@d45d681b05e9:/# pip install pwntools
root@d45d681b05e9:/# python
Python 3.7.9 (default, Aug 18 2020, 06:22:45) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pwn import *
>>> e = ELF("/usr/bin/python3.7")
[*] '/usr/bin/python3.7'
    Arch:     amd64-64-little
    RELRO:    Full RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
    FORTIFY:  Enabled
>>> e = ELF("/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0")
[*] '/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    Canary found
    NX:       NX enabled
    PIE:      PIE enabled
    FORTIFY:  Enabled
```

I tried to run the code from another and different docker container with installed python and it worked, meaning my interpreter verification passed.

**Comment by jondy** [comment]
@dror-weiss binding to fix key is used to protect python interpreter doesn't built with some extra code.

Here is an example to check docker id
https://github.com/dashingsoft/pyarmor/tree/master/plugins#example-2-check-docker-container-id

You can base this example, add your private check points to make sure the docker is expected.
