### ISSUE TITLE
Super-Mode aka `--advanced 2`

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#251]
I don't know if i'm using super-mode wrong, when i use it,  two files are generated 

```
__init__.py
pytransform.pyd
```

However, when i try import the module the exact same way I do in `--advanced 1`

I get the following error...

```
Traceback (most recent call last):
  File "./inject-example.py", line 3, in <module>
    from xxxxxx import xxxxxx
  File "/Project/xxxxxx/dist/xxxxxx/__init__.py", line 2, in <module>
    from .pytransform import pyarmor
ModuleNotFoundError: No module named 'xxxxxx.pytransform'

```

**Comment by VeNoMouS** [comment]
Ah ok, so i had my platform set to windows.x86_64 but was building on linux... how ever removing the platform it copeid the `pytransform.cpython-37m-x86_64-linux-gnu.so` to build..

**Comment by VeNoMouS** [comment]
ah am i being retarded, is the .pyd for windows?!

**Comment by VeNoMouS** [comment]
![image](https://user-images.githubusercontent.com/597545/83465799-33a42a80-a4c9-11ea-86a2-5ca97e2080e4.png)
