### ISSUE TITLE
Super mode no module named pytransform

### ISSUE THREAD

**Issue by martyur** [dashingsoft/pyarmor#277]
```
Traceback (most recent call last):
  File "<main.py>", line 2, in <module>
  File "<frozen s.s.s_api>", line 7, in <module>
  File "C:\Git\hi\dist\Modules\mod_name\__init__.py", line 1, in <module>
    from .pytransform import pyarmor
ModuleNotFoundError: No module named 'Modules.mod_name.pytransform'
```

Only getting this when i build with super mode

**Comment by martyur** [comment]
pytransform.pyd is located in C:\Git\hi\dist\

**Comment by jondy** [comment]
Set bootstrap mode to 2, it could make always absolute import without leading dot, for example,
```
pyarmor config --bootstrap 2
```

**Comment by martyur** [comment]
thanks, any idea why ``pyarmor download`` doesn't do anything for me ?

**Comment by jondy** [comment]
How about run download with `-d`, for example, `pyarmor -d download`

**Comment by martyur** [comment]
Yah that basically lets me use it by outputting DEBUG and INFO logs

**Comment by jondy** [comment]
It's strange, `download` is a very simple command, just print platform informations and download remote files. It works fine in my machine.

**Comment by martyur** [comment]
it's also the same with some other commands like ``benchmark`` no idea what it could be. Tried reinstalling, different terminals.

**Comment by jondy** [comment]
try to set environment variable `PYTHONINSPECT=x`

**Comment by martyur** [comment]
```
C:\Users\marty>pyarmor download
ERROR:root:
Error in sys.excepthook:
Traceback (most recent call last):
  File "c:\users\marty\appdata\local\programs\python\python37\lib\site-packages\pyarmor\pyarmor.py", line 1277, in excepthook
    sys.exit(1)
SystemExit: 1

Original exception was:
Traceback (most recent call last):
  File "c:\users\marty\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\marty\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\marty\AppData\Local\Programs\Python\Python37\Scripts\pyarmor.exe\__main__.py", line 7, in <module>
SystemExit
>>>
ERROR:root:
```

**Comment by jondy** [comment]
It seems something is wrong with module `logging`, how about `pyarmor -d download`? And what's the content of `C:\Users\marty\AppData\Local\Programs\Python\Python37\Scripts\pyarmor.exe\__main__.py`?
