### ISSUE TITLE
Error relocating /root/.pyarmor/platforms/linux/aarch64/3/_pytransform.so: __strdup: symbol not found

### ISSUE THREAD

**Issue by lucabianchi91** [dashingsoft/pyarmor#286]
Hi,
I am trying to use pyarmor on a OpenWrt device (`Linux OpenWrt 5.4.31 #0 SMP Fri Apr 10 13:22:26 2020 aarch64 GNU/Linux
`) but I run into the following issue:
```
root@OpenWrt:~/humanitas/heaven_py3_copy# pyarmor -d obfuscate heaven.py
DEBUG    PyArmor installation path: /usr/lib/python3.8/site-packages/pyarmor
DEBUG    PyArmor home path: /root/.pyarmor
DEBUG    Native platform is linux.aarch64
DEBUG    Search dynamic library in the path: /usr/lib/python3.8/site-packages/pyarmor/platforms
DEBUG    Search dynamic library in the path: /root/.pyarmor/platforms
DEBUG    Found available dynamic library linux/aarch64/3
Traceback (most recent call last):
  File "/usr/bin/pyarmor", line 8, in <module>
    sys.exit(main_entry())
  File "/usr/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1330, in main_entry
    main(sys.argv[1:])
  File "/usr/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1315, in main
    pytransform_bootstrap(capsule=DEFAULT_CAPSULE, force=args.boot)
  File "/usr/lib/python3.8/site-packages/pyarmor/utils.py", line 146, in pytransform_bootstrap
    pytransform.pyarmor_init(platid=platid)
  File "/usr/lib/python3.8/site-packages/pyarmor/pytransform.py", line 336, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid, suffix)
  File "/usr/lib/python3.8/site-packages/pyarmor/pytransform.py", line 304, in _load_library
    m = cdll.LoadLibrary(filename)
  File "/__init__.py", line 451, in LoadLibrary
  File "/__init__.py", line 373, in __init__
OSError: Error relocating /root/.pyarmor/platforms/linux/aarch64/3/_pytransform.so: __strdup: symbol not found
```
I tried to follow [readthedocs](https://pyarmor.readthedocs.io/en/latest/questions.html#could-not-find-pytransform) and I can verify that the file `/root/.pyarmor/platforms/linux/aarch64/3/_pytransform.so` exists but I cannot import `pytransform` in a python3 interactive shell, hence the issue report.

Any idea of what could be the problem?

**Comment by jondy** [comment]
What's the output of this command?
```
ldd root/.pyarmor/platforms/linux/aarch64/3/_pytransform.so
```

It seems it's not glibc in this platform.

**Comment by lucabianchi91** [comment]
```
root@OpenWrt:~# ldd /root/.pyarmor/platforms/linux/aarch64/3/_pytransform.so
	ldd (0x7fb484e000)
	libc.so.6 => ldd (0x7fb484e000)
Error relocating /root/.pyarmor/platforms/linux/aarch64/3/_pytransform.so: __strdup: symbol not found

root@OpenWrt:~# ldd --version
musl libc (aarch64)
Version 1.1.24
Dynamic Program Loader
Usage: ldd [options] [--] pathname
```

**Comment by jondy** [comment]
This platform is built with must, but `_pytransform.so` is built with glibc. One solution is rebuild this platform with glibc.
