### ISSUE TITLE
Could not find _pytransform.dll

### ISSUE THREAD

**Issue by devlop7** [dashingsoft/pyarmor#291]
i have issue with the pytransform when i was make it as exe file first i make the command PYARMOR obfuscate file.py the output file work 100% but when i convert the file to exe by the command

pyinstaller --onefile file.py

the file.exe show this message when i run it

Traceback (most recent call last):
  File "wineaccess_main.py", line 2, in <module>
  File "pytransform\__init__.py", line 341, in pyarmor_runtime
  File "pytransform\__init__.py", line 336, in pyarmor_init
  File "pytransform\__init__.py", line 301, in _load_library
pytransform.PytransformError: Could not find "C:\Users\USER\AppData\Local\Temp\_MEI79242\pytransform\platforms\windows\x86\_pytransform.dll"

**Comment by jondy** [comment]
Please use command [pack](https://pyarmor.readthedocs.io/en/latest/man.html#pack) for this, for example,
```
pyarmor pack -e " --onefile" file.py
```
