### ISSUE TITLE
ModuleNotFoundError: No module named 'pyarmor2'

### ISSUE THREAD

**Issue by yanjieee** [dashingsoft/pyarmor#30]
I had trid "pip install pyarmor; pyarmor" in windows10 and ubuntu 16.04 server, it show the errors below:
win10:
`Traceback (most recent call last):
  File "c:\users\yanjie\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\yanjie\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yanjie\AppData\Local\Programs\Python\Python36\Scripts\pyarmor.exe\__main__.py", line 9, in <module>
  File "c:\users\yanjie\appdata\local\programs\python\python36\lib\site-packages\pyarmor\__init__.py", line 7, in main
    from pyarmor2 import main as main_entry
ModuleNotFoundError: No module named 'pyarmor2'`
ubuntu:
`Traceback (most recent call last):
  File "/home/usr01/yanjie/pyarmor/venv/bin/pyarmor", line 11, in <module>
    sys.exit(main())
  File "/home/usr01/yanjie/pyarmor/venv/lib/python3.5/site-packages/pyarmor/__init__.py", line 7, in main
    from pyarmor2 import main as main_entry
ImportError: No module named 'pyarmor2'`

**Comment by jondy** [comment]
Fixed it in v4.1.1. Please run `pip install pyarmor` again.

**Comment by jondy** [comment]
It works in Python 3 other python 2. i'll fix it soon. 

Quick workaround,  just replace this line with `from pyarmor import main` in `/usr/local/lib/python2.7/site-packages/pyarmor/__init__.py`

To support both python 2 and 3, replace it with
```
try:
    from pyarmor import main
except ImportError:
    from .pyarmor import main
```
