### ISSUE TITLE
ValueError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by chwba** [dashingsoft/pyarmor#301]
I am using Project for packing my application, On start I get the error mentioned in the subject.
Using Python 3.8.5, on Windows 10.

Here is the structure of my project:
![ImageGlass_lx4yMXAE8J](https://user-images.githubusercontent.com/22568014/89047492-c2f57f00-d34e-11ea-9720-1297955cd9d5.png)

EDIT: Ok I think I fixed it. I made use of pyarmor-webui and set Bootstrap Code to absolute import. Will the gui make use of the private algorithm (I bought a license)

Here are my settings, please let me know if thats the highest complexity I can configure :D.

![image](https://user-images.githubusercontent.com/22568014/89049820-1ae1b500-d352-11ea-88d2-db16d1e63448.png)
![image](https://user-images.githubusercontent.com/22568014/89049830-1f0dd280-d352-11ea-9d50-7d880b2b5e47.png)
![image](https://user-images.githubusercontent.com/22568014/89050304-dc002f00-d352-11ea-86a1-0ae784a79877.png)

EDIT2: One thing I noticed, when I activate Windows in platforms the build fails for some reason.

**Comment by jondy** [comment]
Yes, that's the highest security.

And if vm protection is enable, do not select the platform. In this version, there is no platform for vm protection, the cross platform is not support. It will be added in next version 1.2.3.

**Comment by chwba** [comment]
Ah, alright, thanks. Another question. One of my projects I pack with these additional commands:
'--hidden-import=brotli', '--hidden-import=pkg_resources.py2_warn', '--icon=C:\\Users\\me\\my_projects\\project\\my_icon.ico', '--noupx'

Then it failes with
```
35750 INFO: Copying icons from C:\Users\me\my_projects\project\my_icon.ico,
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "C:\Program Files\Python38\lib\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Program Files\Python38\lib\site-packages\win32ctypes\core\ctypes\_util.py", line 42, in check_null
    raise make_error(function, function_name)
OSError: [WinError 2] The system cannot find the file specified.
```
How do I have to write the path, so it can find it?

**Comment by chwba** [comment]
And another project I am trying to obfuscate using pyarmor-webui as well without pyinstaller fails with this traceback:

```
127.0.0.1 - - [02/Aug/2020 01:38:11] Post-Data: {'title': 'mrt', 'src': 'C:\\Users\\chwba/PycharmProjects/mrt', 'entry': ['MRT.py'], 'include': 'all', 'exclude': ['CHANGELOG.txt', 'config-sample.json', 'config.json', 'exceptions.log', 'README.txt', 'requirements.txt', 'requirements_linux.txt', 'setup_linux_dev.py', 'setup_windows_dev.py', 'start.bat', 'usernames.txt', '__pycache__', 'admin', 'archive', 'externals', 'proxies', 'python', 'resources', 'tmp', 'tokens', 'venv'], 'buildTarget': 0, 'output': '', 'bundleName': '', 'packageRuntime': True, 'noRuntime': False, 'enableSuffix': True, 'crossProtection': True, 'bootstrapCode': 2, 'platforms': [], 'pack': [], 'restrictMode': 1, 'obfMod': True, 'obfCode': 2, 'wrapMode': True, 'advancedMode': 4, 'licenseFile': 'true', 'plugins': [], 'id': 4, 'name': 'project-4', 'path': 'C:\\Users\\chwba\\.pyarmor\\projects\\project-4'}
DEBUG    PyArmor installation path: C:\Program Files\Python38\lib\site-packages\pyarmor
DEBUG    PyArmor home path: C:\Users\chwba\.pyarmor
DEBUG    Native platform is windows.x86_64
DEBUG    Search dynamic library in the path: C:\Program Files\Python38\lib\site-packages\pyarmor\platforms
DEBUG    Loaded dynamic library: C:\Program Files\Python38\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
DEBUG    The version of core library is (30, 4, 7)
INFO     PyArmor Version 6.3.4
INFO     Build project C:\Users\chwba\.pyarmor\projects\project-4 ...
INFO     Check project
INFO     Use capsule: C:\Users\chwba\.pyarmor\.pyarmor_capsule.zip
INFO     Output path is: C:\Users\chwba\PycharmProjects\mrt\dist
INFO     Taget platforms: []
DEBUG    Load platform list from C:\Program Files\Python38\lib\site-packages\pyarmor\platforms\index.json
INFO     Update target platforms to: ['windows.x86_64.25.py38']
INFO     ====================================================
INFO     Reload PyArmor with platform: windows.x86_64.21
INFO     ====================================================
DEBUG    PyArmor installation path: C:\Program Files\Python38\lib\site-packages\pyarmor
DEBUG    PyArmor home path: C:\Users\chwba\.pyarmor
DEBUG    Native platform is windows.x86_64
INFO     PYARMOR_PLATFORM is windows.x86_64.21
DEBUG    Build platform is windows.x86_64.21
DEBUG    Search dynamic library in the path: C:\Program Files\Python38\lib\site-packages\pyarmor\platforms
DEBUG    Search dynamic library in the path: C:\Users\chwba\.pyarmor\platforms
DEBUG    Loaded dynamic library: C:\Users\chwba\.pyarmor\platforms\windows\x86_64\21\_pytransform.dll
DEBUG    The version of core library is (30, 4, 21)
INFO     Generating super runtime library to PycharmProjects\mrt\dist
DEBUG    Load platform list from C:\Program Files\Python38\lib\site-packages\pyarmor\platforms\index.json
DEBUG    Target dynamic library: ['C:\\Users\\chwba\\.pyarmor\\platforms\\windows\\x86_64\\25\\py38\\pytransform.pyd']
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Copying C:\Users\chwba\.pyarmor\platforms\windows\x86_64\25\py38\pytransform.pyd
INFO     Rename extension to pytransform_vax_000139.pyd
INFO     Patch extension C:\Users\chwba\PycharmProjects\mrt\dist\pytransform_vax_000139.pyd
DEBUG    Patching PycharmProjects\mrt\dist\pytransform_vax_000139.pyd
DEBUG    Found pattern at 5a964
DEBUG    Patch 261 bytes from 5a984
DEBUG    Patch 270 bytes from 5aa89
DEBUG    Patch 404 bytes from 5ab97
INFO     Patch library file OK
DEBUG    Found marker at 5c4b5
DEBUG    Found marker at 7b071
DEBUG    Found marker at 7e85d
INFO     Generate runtime files OK
INFO     Use protection template: C:\Program Files\Python38\lib\site-packages\pyarmor\protect_code2.pt
no previously-included directories found matching 'CHANGELOG.txt'
no previously-included directories found matching 'config-sample.json'
no previously-included directories found matching 'config.json'
no previously-included directories found matching 'exceptions.log'
no previously-included directories found matching 'README.txt'
no previously-included directories found matching 'requirements.txt'
no previously-included directories found matching 'requirements_linux.txt'
no previously-included directories found matching 'start.bat'
no previously-included directories found matching 'usernames.txt'
no previously-included directories found matching '__pycache__'
no previously-included directories found matching 'admin'
no previously-included directories found matching 'externals'
no previously-included directories found matching 'proxies'
no previously-included directories found matching 'resources'
no previously-included directories found matching 'tokens'
no previously-included directories found matching 'dist'
INFO     Save obfuscated scripts to "C:\Users\chwba\PycharmProjects\mrt\dist"
INFO     Read public key from capsule
INFO     Enable increment build
INFO     Search scripts from C:\Users\chwba\PycharmProjects\mrt
INFO     Obfuscate scripts with mode:
INFO     Obfuscating the whole module is on
INFO     Obfuscating each function is on
INFO     Autowrap each code object mode is on
INFO     Restrict mode is 1
INFO     Advanced value is 4
INFO     Super mode is on
INFO            MRT.py -> PycharmProjects\mrt\dist\MRT.py
INFO     Patch this entry script with protection code
INFO     Write patched script for debugging: C:\Users\chwba\PycharmProjects\mrt\MRT.py.pyarmor-patched
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\pyarmor.py", line 1357, in <module>
    main_entry()
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\pyarmor.py", line 1353, in main_entry
    main(sys.argv[1:])
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\pyarmor.py", line 1345, in main
    args.func(args)
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\pyarmor.py", line 341, in _build
    encrypt_script(prokey, a, b, obf_code=obf_code, obf_mod=obf_mod,
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\utils.py", line 875, in encrypt_script
    f.write(''.join(lines))
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 72202-72204: character maps to <undefined>
ERROR    Failed to handle request
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\webui\server.py", line 65, in do_POST
    result['data'] = self.root_handler.dispatch(self.path[1:], args)
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\webui\handler.py", line 62, in dispatch
    return handler.dispatch(path[i+1:], args)
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\webui\handler.py", line 56, in dispatch
    return getattr(self, 'do_' + path)(args)
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\webui\handler.py", line 468, in do_diagnose
    return self.do_build(args, debug=True)
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\webui\handler.py", line 465, in do_build
    return self._build_target(path, args, debug=debug)
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\webui\handler.py", line 365, in _build_target
    run_pyarmor(cmd_args, debug=debug)
  File "C:\Program Files\Python38\lib\site-packages\pyarmor\webui\handler.py", line 41, in run_pyarmor
    raise RuntimeError('Build project failed (%s)' % p.returncode)
RuntimeError: Build project failed (1)
127.0.0.1 - - [02/Aug/2020 01:38:16] "POST /project/diagnose HTTP/1.1" 200 -
```

**Comment by jondy** [comment]
How about replacing `\` with `/` in the icon path? Or copy icon to current path.

About the encoding issue, please add the source encoding in the script `MRT.py`, refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#xxx-codec-can-t-decode-byte-0xxx

**Comment by chwba** [comment]
> How about replacing \ with / in the icon path? Or copy icon to current path.

Question is what is the current path if I compile from within the pyarmor-webui? Ill try replacing \ with /

> About the encoding issue, please add the source encoding in the script MRT.py, refer to
https://pyarmor.readthedocs.io/en/latest/questions.html#xxx-codec-can-t-decode-byte-0xxx

Yes, thats exactly what fixed it, 👍 Thanks

**Comment by jondy** [comment]
The current path of pyarmor-webui is where to run `pyarmor-webui`

And one slash is enough I think, `C:/Users/me/projects/project_one/icon.ico`

**Comment by chwba** [comment]
> And one slash is enough I think, `C:/Users/me/projects/project_one/icon.ico
I had tried this, then it will not recognize the path, it will print `CUsersmeprojectsproject_oneicon.cio` in the debug log as well. Tried running pyarmor-webui from within the project root, it tried to copy from `C:\Users\me\.pyarmor\projects\project-3\icon.ico`, ill try to put it there but its weird still

**Comment by jondy** [comment]
Sorry, I made a mistake. All the path in pyinstaller extra options, for example, `--icon`, `-p`, the current path is `Src` of the project. That is, if it's relative path, it will be prefixed with `Src`

**Comment by chwba** [comment]
Yeah but wherever I put the icon it wont find it, so in case it is relative to the src of the project which would be `C:\Users\me\my_projects\project\` it should find icon.ico, if I pass `'--icon=my_icon.ico' but it doesnt, what can I try?

**Comment by jondy** [comment]
In `pyarmor-webui`, pass `--icon=my_icon.ico`, and put `my_icon.ico` in the `src` path which is the same path of entry script, it should be different from project path. Does it work? 

If not, upgrade `pyarmor-webui` to v1.2.4, then pass absolute path, for example, `--icon=C:/Users/me/my_projects/project/my_icon.ico`. 

If it still doesn't work, please find all the options of command `pyi-makespec` and `pyinstaller` in the console log and show here.

**Comment by jondy** [comment]
Hi guy, it may be not icon path issue, please check command `pyi-makespec` in the environment PATH, make sure this command could be run in the command line directly.

**Comment by chwba** [comment]
pyi-makespec works and I can call it from the environment path. I have installed pyarmor-webui from pypi, its at version 1.2.2, would I get the newest version if i install from the repo directly?
![587-139-max](https://user-images.githubusercontent.com/22568014/89126924-12bc7d80-d4ea-11ea-9b35-275bc8fe13c6.png)

**Comment by jondy** [comment]
if `pip install --upgrade pyarmor-webui` doesn't work, install from this link
https://files.pythonhosted.org/packages/cb/4f/39235674b07cfd979c5def013d610a822cc14cd0010c52b667e373e1171d/pyarmor-webui-1.2.5.zip

**Comment by chwba** [comment]
I updated, now when I start I get:
```
INFO     Data path: C:\Users\me\.pyarmor
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\pyarmor-webui.exe\__main__.py", line 7, in <module>
  File "c:\program files\python38\lib\site-packages\pyarmor\webui\server.py", line 231, in main
    server = socketserver.TCPServer((args.host, args.port), HelperHandler)
  File "c:\program files\python38\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "c:\program files\python38\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

**Comment by jondy** [comment]
Please kill the old pyarmor-webui process, it's still running in backend. Or start pyarmor-webui with another port
```
pyarmor-webui -p 9098
```

**Comment by chwba** [comment]
Indeed, you were right, there was a process still running in the background, after killing it it started up fine and with the new version it also found the ico, perfect, thanks for the quick replies!
