### ISSUE TITLE
Segmentation fault when running script on MacOS

### ISSUE THREAD

**Issue by norbertcyran** [dashingsoft/pyarmor#322]
Hi,

I'm trying to run the script obfuscated with super mode (using pyarmor projects). Running `python manage.py runserver` ends up with segmentation fault:
```
[1]    57735 segmentation fault  python manage.py runserver
```
Issue happens on MacOS, Darwin i386 64bit. Everything works as expected on dockerized linux environment.

Tried workaround mentioned in the documentation, unfortunately didn't work for me:
```python
# Disable advanced mode if required
m.set_option(5, c_char_p(1))
```

**Comment by jondy** [comment]
Is there any error message with -d?
```
python -d manage.py runserver
```

**Comment by norbertcyran** [comment]
Same output with `-d`. With `-dvv` (paths cut out):
```
Python 3.7.6 (default, Jan 16 2020, 18:10:01) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
# trying xxx/dist/pytransform.cpython-37m-darwin.so
[1]    63338 segmentation fault  python -dvv manage.py runserver
```

**Comment by jondy** [comment]
What's the output of this command in this machine?
```
python-config --ldflags
```
It will print where the python installed. If it's not installed in the `/System/Library` or `/Library` or `/usr/local/opt/python`, for example,
```
-L/home/jondy/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin
```
Try to adjust rpath by this command
```
install_name_tool -delete_rpath /usr/local/opt/python -add_rpath /home/jondy/python ~/.pyarmor/platforms/darwin/x86_64/11/py37/pytransform.cpython-37m-darwin.so
```

**Comment by norbertcyran** [comment]
```
-L/Users/cyran/.pyenv/versions/3.7.6/lib/python3.7/config-3.7m-darwin -lpython3.7m -lintl -ldl -framework CoreFoundation
```
Tried:
```
install_name_tool -delete_rpath /usr/local/opt/python -add_rpath /Users/cyran/.pyenv ~/.pyarmor/...
```
Didn't work

**Comment by jondy** [comment]
`pytransform.cpython-37m-darwin.so` is linked to `Frameworks/Python.framework`, here are shared libraries used: (the output of `otool -L`)
```
	@rpath/Frameworks/Python.framework/Versions/3.7/Python (compatibility version 3.7.0, current version 3.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1575.17.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 946.0.0)
```
But in this machine, `python` is not in a framework, I think it may be the problem.

**Comment by norbertcyran** [comment]
Yes, my output is exactly the same. Do you have any workaround for the issue? pyenv is a pretty common tool, it'd be great to have it fixed

**Comment by jondy** [comment]
Refer to
https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with-framework-support-on-os-x

**Comment by norbertcyran** [comment]
Reinstalling python with `--enable-framework` and running `install_name_tool` again didn't work either unfortunately

**Comment by jondy** [comment]
First make sure `rpath` is correct, what's the output of  `python-config --ldflags` and `otool -l pytransform.cpython-37m-darwin.so`?

**Comment by norbertcyran** [comment]
`python-config --ldflags`:
```
-L/Users/cyran/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -lintl -ldl -framework CoreFoundation
```
`otool -l ~/.pyarmor/.../pytransform.cpython-37m-darwin.so`:
```
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           6    20       2272 0x00100085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x00000000000d9000
  fileoff 0
 filesize 888832
  maxprot 0x00000005
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x00000000000011b0
      size 0x00000000000baf23
    offset 4528
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x00000000000bc0d4
      size 0x0000000000000552
    offset 770260
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x00000000000bc628
      size 0x00000000000008ee
    offset 771624
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x00000000000bcf20
      size 0x0000000000017f2c
    offset 773920
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000000000d4e4c
      size 0x00000000000028c8
    offset 872012
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x00000000000d7714
      size 0x0000000000000678
    offset 882452
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __eh_frame
   segname __TEXT
      addr 0x00000000000d7d90
      size 0x0000000000001270
    offset 884112
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 712
  segname __DATA
   vmaddr 0x00000000000d9000
   vmsize 0x0000000000066000
  fileoff 888832
 filesize 401408
  maxprot 0x00000003
 initprot 0x00000003
   nsects 8
    flags 0x0
Section
  sectname __nl_symbol_ptr
   segname __DATA
      addr 0x00000000000d9000
      size 0x0000000000000008
    offset 888832
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 227 (index into indirect symbol table)
 reserved2 0
Section
  sectname __got
   segname __DATA
      addr 0x00000000000d9008
      size 0x0000000000000180
    offset 888840
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 228 (index into indirect symbol table)
 reserved2 0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x00000000000d9188
      size 0x0000000000000718
    offset 889224
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 276 (index into indirect symbol table)
 reserved2 0
Section
  sectname __const
   segname __DATA
      addr 0x00000000000d98a0
      size 0x0000000000000748
    offset 891040
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cfstring
   segname __DATA
      addr 0x00000000000d9fe8
      size 0x00000000000000a0
    offset 892904
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x00000000000da090
      size 0x00000000000604f0
    offset 893072
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x000000000013a580
      size 0x00000000000009c0
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x000000000013af40
      size 0x0000000000003da8
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x000000000013f000
   vmsize 0x0000000000004ab4
  fileoff 1290240
 filesize 19124
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
          cmd LC_ID_DYLIB
      cmdsize 64
         name pytransform.cpython-37m-darwin.so (offset 24)
   time stamp 1 Thu Jan  1 01:00:01 1970
      current version 31.5.0
compatibility version 0.0.0
Load command 4
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 1290240
    rebase_size 112
       bind_off 1290352
      bind_size 1056
  weak_bind_off 0
 weak_bind_size 0
  lazy_bind_off 1291408
 lazy_bind_size 5568
     export_off 1296976
    export_size 56
Load command 5
     cmd LC_SYMTAB
 cmdsize 24
  symoff 1298048
   nsyms 276
  stroff 1304476
 strsize 4888
Load command 6
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 1
     iextdefsym 1
     nextdefsym 2
      iundefsym 3
      nundefsym 273
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 1302464
  nindirectsyms 503
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 7
     cmd LC_UUID
 cmdsize 24
    uuid C8825D02-AFB4-36E2-B9DD-D73BE2B2EA09
Load command 8
       cmd LC_BUILD_VERSION
   cmdsize 32
  platform 1
       sdk 10.14
     minos 10.14
    ntools 1
      tool 3
   version 530.0
Load command 9
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 80
         name @rpath/Frameworks/Python.framework/Versions/3.7/Python (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 3.7.0
compatibility version 3.7.0
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1252.250.1
compatibility version 1.0.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 104
         name /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1575.17.0
compatibility version 150.0.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 275.0.0
compatibility version 1.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 104
         name /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 946.0.0
compatibility version 1.0.0
Load command 15
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 1297032
 datasize 904
Load command 16
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 1297936
 datasize 112
Load command 17
          cmd LC_RPATH
      cmdsize 32
         path /System/Library (offset 12)
Load command 18
          cmd LC_RPATH
      cmdsize 24
         path /Library (offset 12)
Load command 19
          cmd LC_RPATH
      cmdsize 48
         path /Users/cyran/.pyenv/versions/3.7.6/ (offset 12)
```

**Comment by jondy** [comment]
How about adapting the python library by this way?
```
install_name_tool -change @rpath/Frameworks/Python.framework/Versions/3.7/Python  /Users/cyran/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
```

Make sure `/Users/cyran/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/libpython3.7m.dylib` exists.

**Comment by norbertcyran** [comment]
Didn't work also

I tried `install_name_tool` also with local pytransform in `dist` directory, fixed the segmentation fault with `install_name_tool -change @rpath/Frameworks/Python.framework/Versions/3.7/Python  /Users/cyran/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/libpython3.7m.dylib pytransform.cpython-37m-darwin.so `, but now I have:
```python
Traceback (most recent call last):
  File "<manage.py>", line 3, in <module>
  File "<frozen manage>", line 53, in <module>
  File "<frozen manage>", line 48, in protect_pytransform
  File "<frozen manage>", line 41, in check_lib_pytransform
RuntimeError: unexpected /Users/cyran/repo/dist/pytransform.cpython-37m-darwin.so
```

**Comment by jondy** [comment]
Try to obfuscate the scripts with `--no-cross-protection`, for example,
```
pyarmor obfuscate --advanced 2 --no-cross-protection foo.py
```

**Comment by norbertcyran** [comment]
I managed to fix it. Problem disappeared after setting `is_package` option to `1`. Everything ran without problem, didn't even have to run `install_name_tool`.

Can be closed
