### ISSUE TITLE
Function does not end with "):" when SUPER MODE is enabled

### ISSUE THREAD

**Issue by aboganas** [dashingsoft/pyarmor#326]
Dears
When I enable the super mode I get the following error bellow.
note that in any other mode, it runs fine
The line in the code that cause this error, I found it to be [here](https://github.com/apache/incubator-superset/blob/9a6697141dd0e7fae4317c244e3c0047ac5f5985/superset/datasets/dao.py#L170) which seems fine (similar error is also caused by this line [here](https://github.com/apache/incubator-superset/blob/9a6697141dd0e7fae4317c244e3c0047ac5f5985/superset/connectors/druid/models.py#L1222))

```
127.0.0.1 - - [09/Sep/2020 11:01:44] Content-Type: application/x-www-form-urlencoded
127.0.0.1 - - [09/Sep/2020 11:01:44] Post-Data: {'title': 'incubator-superset', 'src': '/Users/username/incubator-superset', 'entry': ['superset/__init__.py'], 'include': 'all', 'exclude': ['setup.py', 'superset/bin/__init__.py'], 'buildTarget': 0, 'output': '', 'bundleName': 'incubator-superset', 'packageRuntime': False, 'noRuntime': False, 'enableSuffix': False, 'crossProtection': True, 'bootstrapCode': 1, 'platforms': [], 'pack': [], 'restrictMode': 0, 'obfMod': True, 'obfCode': 2, 'wrapMode': True, 'advancedMode': 2, 'licenseFile': 'true', 'plugins': [], 'id': 6, 'name': 'project-6', 'path': '/Users/username/.pyarmor/projects/project-6'}
DEBUG    PyArmor installation path: /Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor
DEBUG    PyArmor home path: /Users/username/.pyarmor
DEBUG    Native platform is darwin.x86_64
DEBUG    Search dynamic library in the path: /Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/platforms
DEBUG    Loaded dynamic library: /Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/platforms/darwin/x86_64/_pytransform.dylib
DEBUG    The version of core library is (32, 6, 7)
INFO     PyArmor Version 6.4.0
INFO     Build project /Users/username/.pyarmor/projects/project-6 ...
INFO     Check project
INFO     Use capsule: /Users/username/.pyarmor/.pyarmor_capsule.zip
INFO     Output path is: /Users/username/incubator-superset/dist/incubator-superset
INFO     Taget platforms: []
DEBUG    Load platform list from /Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/platforms/index.json
INFO     Update target platforms to: ['darwin.x86_64.11.py37']
INFO     Generating super runtime library to ../dist/incubator-superset
DEBUG    Load platform list from /Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/platforms/index.json
DEBUG    Target dynamic library: ['/Users/username/.pyarmor/platforms/darwin/x86_64/11/py37/pytransform.cpython-37m-darwin.so']
INFO     Extract pytransform.key
INFO     Generate no restrict mode license file
INFO     Copying /Users/username/.pyarmor/platforms/darwin/x86_64/11/py37/pytransform.cpython-37m-darwin.so
INFO     Patch extension /Users/username/incubator-superset/dist/incubator-superset/pytransform.cpython-37m-darwin.so
DEBUG    Patching ../dist/incubator-superset/pytransform.cpython-37m-darwin.so
DEBUG    Found pattern at dc0bc
DEBUG    Patch 261 bytes from dc0dc
DEBUG    Patch 270 bytes from dc1e1
DEBUG    Patch 424 bytes from dc2ef
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Use protection template: /Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/protect_code2.pt
INFO     Save obfuscated scripts to "/Users/username/incubator-superset/dist/incubator-superset"
INFO     Read public key from capsule
INFO     Enable increment build
INFO     Search scripts from /Users/username/incubator-superset
INFO     Obfuscate scripts with mode:
INFO     Obfuscating the whole module is on
INFO     Obfuscating each function is on
INFO     Autowrap each code object mode is on
INFO     Restrict mode is 0
INFO     Advanced value is 2
INFO     Super mode is on
INFO            superset/datasets/dao.py -> ../dist/incubator-superset/superset/datasets/dao.py
ERROR    Function does not end with "):"
Traceback (most recent call last):
  File "/Users/username/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/username/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/pyarmor.py", line 1452, in <module>
    main_entry()
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/pyarmor.py", line 1448, in main_entry
    main(sys.argv[1:])
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/pyarmor.py", line 1440, in main
    args.func(args)
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/pyarmor.py", line 353, in _build
    suffix=suffix)
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/utils.py", line 937, in encrypt_script
    co = _check_code_object_for_super_mode(co, lines, modname)
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/utils.py", line 1432, in _check_code_object_for_super_mode
    raise RuntimeError('Patch function "%s" failed' % c.co_name)
RuntimeError: Patch function "update" failed
ERROR    Failed to handle request
Traceback (most recent call last):
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/webui/server.py", line 78, in do_POST
    result['data'] = self.root_handler.dispatch(self.path[1:], args)
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/webui/handler.py", line 49, in dispatch
    return handler.dispatch(path[i+1:], args)
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/webui/handler.py", line 43, in dispatch
    return getattr(self, 'do_' + path)(args)
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/webui/handler.py", line 468, in do_diagnose
    return self.do_build(args, debug=True)
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/webui/handler.py", line 465, in do_build
    return self._build_target(path, args, debug=debug)
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/webui/handler.py", line 365, in _build_target
    run_pyarmor(cmd_args, debug=debug)
  File "/Users/username/.pyenv/versions/3.7.7/envs/pyarmor/lib/python3.7/site-packages/pyarmor/webui/handler.py", line 28, in run_pyarmor
    raise RuntimeError('Build project failed (%s)' % p.returncode)
RuntimeError: Build project failed (1)
127.0.0.1 - - [09/Sep/2020 11:01:44] "POST /project/diagnose HTTP/1.1" 200 -

```

**Comment by jondy** [comment]
Add extra line at the beginning of these functions to fix this issue
```
    [None, None]
```

Refer to https://pyarmor.readthedocs.io/en/latest/questions.html#code-object-could-not-be-obufscated-with-advanced-mode-2

**Comment by jondy** [comment]
It also works to apply this patch 1c46de6148e19e52b1ccaf82c2f27f5a970f91e2  in the source of pyarmor

**Comment by aboganas** [comment]
Thanks for your quick response and help. it works now
