### ISSUE TITLE
problem when using tortoise orm

### ISSUE THREAD

**Issue by evstratbg** [dashingsoft/pyarmor#330]
Hi! Thanks for the great soft

I've faced the problem, using tortoise-orm as async orm for postgresql.

As a run obfuscation like so:
`pyarmor obfuscate -r run.py`

the app doesnt start, throwing following traceback:

```
Traceback (most recent call last):
  File "<dist/run.py>", line 3, in <module>
  File "<frozen run>", line 15, in <module>
  File "</app/dist/app/app.py>", line 1, in <module>
  File "<frozen app.app>", line 5, in <module>
  File "</app/dist/app/routes/__init__.py>", line 1, in <module>
  File "<frozen app.routes>", line 7, in <module>
  File "</app/dist/app/routes/v1/app.py>", line 1, in <module>
  File "<frozen app.routes.v1.app>", line 6, in <module>
  File "</app/dist/app/routes/v1/handlers/file.py>", line 1, in <module>
  File "<frozen app.routes.v1.handlers.file>", line 15, in <module>
  File "</app/dist/app/database/models.py>", line 3, in <module>
  File "<frozen app.database.models>", line 45, in <module>
  File "/app/.venv/lib/python3.8/site-packages/tortoise/models.py", line 596, in __new__
    for fname, comment in _get_comments(new_class).items():
  File "/app/.venv/lib/python3.8/site-packages/tortoise/models.py", line 140, in _get_comments
    source = inspect.getsource(cls)
  File "/usr/local/lib/python3.8/inspect.py", line 985, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/local/lib/python3.8/inspect.py", line 967, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/local/lib/python3.8/inspect.py", line 824, in findsource
    raise OSError('could not find class definition')
OSError: could not find class definition

```

if I add app.database, where models.py is, to --exclude arg, everything works great.

 As far, as I understood, the problem is in `source = inspect.getsource(cls)`, because interpreter can't get the text of the source code for an object. 

Is there is any way to bypass it?

**Comment by jondy** [comment]
There is no way to bypass it. But it should work to obfuscate `models.py` with `--obf-code=0` separately, for example,
```
pyarmor obfuscate --exact --obf-code 0 models.py
```

**Comment by evstratbg** [comment]
ye, that's ok

btw, made a PR to tortoise-orm to make it work under pyarmor

Thank's!
