### ISSUE TITLE
Tensorflow error - (ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.)

### ISSUE THREAD

**Issue by ApurvaDani** [dashingsoft/pyarmor#334]
Description:

I have installed tensorflow using conda and it works fine in the conda environment. I converted my app into binary file using pyarmor. While running .exe file, it throws ImportError

Exact Steps Followed:

Used pyarmor pack command to convert my flask app to .exe file
First issue encountered: No module named tensorflow
Copied the tensorflow folder from the conda environment and pasted it in directory where app.exe is located. (Is there a better way to solve the import tensorflow issue?)
Now facing the Import Error
Is there something else, I need to copy to the working directory or a path to set?

Stack Trace:

Traceback (most recent call last):
  File "<dist\obf\app.py>", line 3, in <module>
  File "<frozen app>", line 16, in <module>
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\pywrap_tensorflow.py", line 59, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\pywrap_tensorflow_internal.py", line 35, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 242, in load_module
  File "imp.py", line 342, in load_dynamic
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.
[9200] Failed to execute script app

**Comment by jondy** [comment]
First make sure the scripts could be packed by PyInstaller directly and the final bundle works, for example,
```
pyinstaller --hidden-import tensorflow  app.py
```
You could also google how to use pyinstaller to pack tensoflow app, it may use some extra options, for example, `--hidden-import`, `--add-data` etc.

If it works, pass any pyinstaller options by `-e`, for example,
```
pyarmor pack -e " --hidden-import tensorflow" app.py
```

 Also refer to 
https://pyarmor.readthedocs.io/en/latest/questions.html#the-final-bundle-does-not-work

**Comment by ApurvaDani** [comment]
It was using pyinstaller installed in the base environment which did not have tensorflow installed.
This solved the issue

conda activate your_env_name
conda install -c conda-forge pyinstaller
