### ISSUE TITLE
pytransform error

### ISSUE THREAD

**Issue by omarm-aiy** [dashingsoft/pyarmor#35]
I'm using Python 3.6.4
I used to the web ui  to obfuscate my project
I then opened the dist folder and tried to run my entry point python file and i for this error:

`
Traceback (most recent call last):
  File ".\test.py", line 1, in <module>
    from pytransform import pyarmor_runtime
ModuleNotFoundError: No module named 'pytransform'
`
I tried to install pytransform using pip install pytransform but it failed. so i tried to get it directly from the repo using pip install git+https://github.com/rock-learning/pytransform.git and then i got the following error:

`
Traceback (most recent call last):
  File ".\test.py", line 1, in <module>
    from pytransform import pyarmor_runtime
ImportError: cannot import name 'pyarmor_runtime'
`
PS: I'm not sure if this is related to https://github.com/dashingsoft/pyarmor/issues/29 or not

**Comment by Rattle-15236** [comment]
I found those files in C:\ even tho my project isn't directly in C:\
I tried to re-reproduce the problem so i can show you the output console but the latest 4.2.2 version is not letting me open pyarmor-webui. it's throwing the following error:

`
C:\>pyarmor-webui
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\user\appdata\local\programs\python\python36-32\scripts\pyarmor-webui.exe\__main__.py", line 9, in <module>
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pyarmor\webui\__init__.py", line 7, in main
    from server import main as main_entry
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pyarmor\webui\server.py", line 24, in <module>
    import _project
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pyarmor\webui\_project.py", line 18, in <module>
    from pyarmor import main as _pyarmor
ImportError: cannot import name 'main'
`
I was able to use pyarmor-webui in 4.2.1

**Comment by jondy** [comment]
I have found this issue but not released,  Quick workaround:
Edit file `c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pyarmor\webui\_project.py`, replace line 18 `from pyarmor import main as _pyarmor` with 
```
from pyarmor.pyarmor import main as _pyarmor
```

It's very strange that those files are found in the `c:\`, I'll check the source to find what happens.

**Comment by Rattle-15236** [comment]
@jondy thanks the quick workaround worked. i'll be waiting for the release.
But since i got the webui running now, here's a step-by-step walk-through to reproduce my result
1- Create a hello_world.py in _c:\Users\<your_user>\pyarmor-test\_ which only has print("hello world!")
2- open cmd and change directory to c:\ (**cd /**)
3- open pyarmor-webui (i used the direct command **pyarmor-webui** and hit enter)
4- create a new project
the default settings will look something like this
![default](https://user-images.githubusercontent.com/29326892/47951565-10bb3880-df6b-11e8-963f-e231ee6664d7.png)

i changed them to this
![image](https://user-images.githubusercontent.com/29326892/47951658-56c4cc00-df6c-11e8-9cd5-4eaf9f0ffcdc.png)


5- click save
6- click build

webui console will show the following:

> Request /newProject: {}
> Request /updateProject: {"version":"1.0.1","name":"project-1","title":"test-helloworld","src":"C:\\Users\\User\\pyarmor-test","is_package":null,"manifest":"global-include *.py","entry":"hello_world.py","output":"C:\\Users\\User\\pyarmor-test\\dist","capsule":".pyarmor_capsule.zip","runtime_path":"","disable_restrict_mode":0,"obf_module_mode":"des","obf_code_mode":"des","build_time":0}
> Update project OK
> Request /buildProject: {"version":"1.0.1","name":"project-1","title":"test-helloworld","src":"C:\\Users\\User\\pyarmor-test","is_package":null,"manifest":"global-include *.py","entry":"hello_world.py","output":"C:\\Users\\User\\pyarmor-test\\dist","capsule":".pyarmor_capsule.zip","runtime_path":"","disable_restrict_mode":0,"obf_module_mode":"des","obf_code_mode":"des","build_time":0}
> Build project OK.

_C:\Users\User\pyarmor-test_ will have the "dist" folder created which will _only_ contain the obfuscated hello_world.py file. (this time nothing was created in C:\)
![image](https://user-images.githubusercontent.com/29326892/47951727-537e1000-df6d-11e8-9881-dd69af492b35.png)

to make the obfuscated file run, go to 
**C:\Users\User\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\pyarmor\webui\projects\project-1\runtimes**

(i have no idea why it's called project one even tho i changed the name.. doesn't matter tho)

and copy all the files there and paste them in the obfuscated file directory

if i do that, the hello_world.py runs now

BUT if i do the same steps on my project, i get the following error when trying to run it:

NameError: name '__pyarmor__' is not defined

**Comment by jondy** [comment]
@Rattle-15236 
Download the attached file `build.bat`, edit in any text editor, change line 4 and line 7 as your actual setting.

Then double click `build.bat`, check if there is any error in the console window.
[build.zip](https://github.com/dashingsoft/pyarmor/files/2545043/build.zip)

**Comment by jondy** [comment]
One solution is to copy these files after `build`, add an extra line after `./pyarmor.bat build` in `build.bat`:
```
copy dist/_pytransform.dll dist/pytransform.py dist/*.lic dist/*.key dist/myapp
```
