### ISSUE TITLE
pyarmor pack error when running bundled app that uses gpio on raspberry pi 4

### ISSUE THREAD

**Issue by momendez** [dashingsoft/pyarmor#351]
I have an application that runs on raspberry pi 4 and uses gpio (gpiozero). The app runs fine.

I'm trying to pack the app  using "pyarmor pack" but when I try to run the bundled application I received the following error:

`Traceback (most recent call last):
  File "<dist/obf/htoob.py>", line 4, in <module>
  File "<frozen htoob>", line 541, in <module>
  File "<frozen htoob>", line 472, in main
  File "<frozen htoob>", line 122, in __init__
  File "gpiozero/devices.py", line 124, in __call__
  File "gpiozero/boards.py", line 244, in __init__
  File "gpiozero/boards.py", line 244, in <dictcomp>
  File "gpiozero/devices.py", line 124, in __call__
  File "gpiozero/input_devices.py", line 432, in __init__
  File "gpiozero/mixins.py", line 383, in __init__
  File "gpiozero/input_devices.py", line 182, in __init__
  File "gpiozero/mixins.py", line 197, in __init__
  File "gpiozero/input_devices.py", line 98, in __init__
  File "gpiozero/devices.py", line 512, in __init__
  File "gpiozero/devices.py", line 243, in __init__
  File "gpiozero/devices.py", line 280, in _default_pin_factory
gpiozero.exc.BadPinFactory: Unable to load any default pin factory!
[6171] Failed to execute script htoob
Exception ignored in: <function GPIOBase.__del__ at 0xb2c81348>
Traceback (most recent call last):
  File "gpiozero/devices.py", line 151, in __del__
  File "gpiozero/mixins.py", line 391, in close
  File "gpiozero/devices.py", line 426, in __getattr__
AttributeError: no such attribute _hold_thread
`

**Comment by jondy** [comment]
It seems some hidden modules in the package `gpiozero` aren't packed into the final bundle, try to create hook script `hook-gpiozero.py` in the current path:
```
from PyInstaller.utils.hooks import collect_all
datas, binaries, hiddenimports = collect_all('gpiozero')
```
Then pack it
```
pyarmor pack -e " --additional-hooks-dir ." main.py
```

Also refer to https://pyarmor.readthedocs.io/en/latest/questions.html#the-final-bundle-does-not-work

**Comment by momendez** [comment]
It worked perfectly. Thank you!
