### ISSUE TITLE
NameError: name '__armor_wrap__' is not defined

### ISSUE THREAD

**Issue by matanfiddler** [dashingsoft/pyarmor#352]
My obfuscated Flask app running on Python 3.7 is crashing on Docker with the error:
`NameError: name '__armor_wrap__' is not defined`

It was running in a previous build, now this error pops up and I can't tell what's causing it...

Would appreciate any help very much, thanks!

**Comment by jondy** [comment]
Do you obfuscate any python system library? If python virtual environment is in the source path, exclude this path by option `--exclude`.

**Comment by matanfiddler** [comment]
I don't think I'm obfuscating any system library. The error is being thrown by Flask when trying to execute my server:
`Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/venv/lib/python3.7/site-packages/flask_restx/api.py", line 600, in error_router
    return original_handler(e)
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 1878, in handle_exception
    server_error = handler(server_error)
  File "<frozen data.service>", line 125, in handle_invalid_usage`

**Comment by jondy** [comment]
If the scripts are obfuscated by `restrict=3 or 4`, it could not be imported from plain script. Refer to [restrict mode](https://pyarmor.readthedocs.io/en/latest/mode.html#restrict-mode)

In this traceback, `site-packages/flask/app.py` is plain script, but `src/data/service.py` is obfuscated by restrict mode 3 or 4, so it raises exception.

One solution is to obfuscate `site-packages/flask/app.py` and all the other plain scripts which import any obfuscated module with `restrict=1` separately.

**Comment by matanfiddler** [comment]
Thank you @jondy, this is super helpful 👍
