### ISSUE TITLE
Pyarmor "ModuleNotFoundError" error issue

### ISSUE THREAD

**Issue by basavarajmouli** [dashingsoft/pyarmor#383]
Below is the our project structure,

![Capture10](https://user-images.githubusercontent.com/13089211/98682940-80e6cb00-238a-11eb-8ecf-7808467ba324.JPG)

Our objective is to obfuscate the whole project and run pyinstaller command to wrap and finally we are bundling the files to obtain the EXE from the third party software. 

To achieve the first objective I’m following the below commands:
1.	Pyarmor  obfuscate -r /catcher/libexec/test/__main__.py – which will add bootstrap code to the main file.
2.	Pyarmor  obfuscate -r /catcher/lib/test_folder/test_folder_1/other_folders_contains_py_files.
From these two commands most of the code will be obfuscated.

To achieve the second objective we wrap around the code using the custom .spec file:
1.	I run pyinstaller pyinstaller.spec file – we will get the wrapped obfuscated source code. 

While trying to test the obfuscate package, we observe few folders not found and we get the errors shown below:
1.	We were getting some folders, that used to get generated while we are running the .spec file. Now with the obfuscated code I’m not able to get those folders
2.	Because of the above issue, I’m getting “ModuleNotFoundError:” for the Python inbuild libraries.

**Comment by jondy** [comment]
After the scripts are obfuscated, pyinstaller could not find any imported module, that's problem.

I suggest you create a project to configure the scripts need to be obfuscated, and pack them by `pyarmor pack`, for example,
```
cd catcher
pyarmor init --entry libexec/test/__main__.py .
pyarmor config --manifest "recursive-include lib/test_folder/test_folder1 *.py,  recursive-include libexec/test *.py"
pyarmor pack .
```
About the usage of `--manifest`, refer to https://pyarmor.readthedocs.io/en/latest/project.html#project-configuration-file

**Comment by basavarajmouli** [comment]
@jondy  i have followed your steps as mentioned, I didn't get any error. It generated its own spec file and it ran fine. But when i did the reverse engineering i can able to read my code. Basically the code wasn't  obfuscated at all. Can you suggest where i'm going wrong.

**Comment by jondy** [comment]
If you use other options to pack the scripts, please show all your options here.

If not, first run `pack` with `--debug`
```
pyarmor pack --debug .
```

Then check the path `dist/obf`, make sure there are obfuscated scripts in the corresponding child folders.

**Comment by basavarajmouli** [comment]
@jondy  i have not followed the pack method, instead i have used the recursive method below are the steps
`pyarmor obfuscate --recursive --output dist/obf/catcher/lib/test_folder/ catcher/lib/test_folder/`
`pyarmor obfuscate --recursive --output dist/obf/catcher/libexec/ese /catcher/libexec/test/main.py` 

and then i'm running our own custom spec file by this command
`pyinstaller -y --clean pyinstaller_main.spec`

although it gave me obfuscated exe, when i'm running the exe i get the following error
`Traceback (most recent call last):
  File "<C:\Users\basavaraj_chandramou\ESE-1958\ese\dist\obf\catcher\libexec\test\__main__.py>", line 3, in <module>
  File "<frozen libexec.test.__main__>", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\basavaraj_chandramou\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    #
  File "<catcher\lib\test_folder\esework.py>", line 1, in <module>
  File "<frozen catcher\lib\test_folder.esework>", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\basavaraj_chandramou\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    #
  File "<catcher\lib\test_folderthreads\upgrade.py>", line 1, in <module>
  File "<frozen catcher.lib.test_folder.threads.upgrade>", line 673, in <module>
  File "<frozen catcher.lib.test_folder.threads.threads.upgrade>", line 98, in UpgradeOrchestrator
  File "site-packages\automat\_methodical.py", line 378, in decorator
  File "<attrs generated init automat._methodical.MethodicalInput>", line 11, in __init__
  File "site-packages\automat\_methodical.py", line 166, in assertNoCode
ValueError: function body must be empty
[7524] Failed to execute script __main__`


any idea on this.

**Comment by jondy** [comment]
Check function `assertNoCode` in File "site-packages\automat\_methodical.py", line 166

After the empty function is obfuscated, it's not empty, so ignore this assert if possible.

**Comment by basavarajmouli** [comment]
this is a Python inbuild library- any idea how to do this.

**Comment by jondy** [comment]
It's also a common Python script, is there this file `c:\users\basavaraj_chandramou\appdata\local\programs\python\python36\lib\site-packages\automat\_methodical.py`?
