### ISSUE TITLE
How can I display nicely if license is invalid?

### ISSUE THREAD

**Issue by fieu** [dashingsoft/pyarmor#385]
I would like to inject this code at the beginning to check license and log information if non valid and stuff.

I have this at the moment:

```python
# license_information.py
import logging
import sys
from pytransform import pyarmor_init, get_license_info

pyarmor_init(is_runtime=1)
from rich.logging import RichHandler

logging.basicConfig(level=logging.INFO, format="%(message)s", datefmt="[%X]", handlers=[RichHandler(show_path=False, markup=False)])
log = logging.getLogger('license_information')


def print_license_info():
    try:
        license_info = get_license_info()
        log.info('License Information:')
        log.info('* Expiration Date: {0} (Will expire in {1} days)'.format(license_info['EXPIRED'], get_expired_days()))
    except Exception:
        log.error('License invalid!')
        sys.exit(0)


print_license_info()

if __name__ == '__main__':
    print_license_info()
```

```python
# main.py
import json
import logging
import os
import sys

import click
from dotenv import load_dotenv
from rich.logging import RichHandler

import utils.decorators
import utils.steam as steam
from utils.config import validate, is_steam_guarded

logging.basicConfig(level=logging.INFO, format="%(message)s", datefmt="[%X]", handlers=[RichHandler(show_path=False, markup=False)])
log = logging.getLogger('main.main')

if os.path.isfile('.env'):
    try:
        load_dotenv()
        log.info('(dev) Loaded .env')
    except Exception:
        pass


def dev_log(message: str, in_dev: bool):
    if in_dev:
        log.info(f'(dev) {message}')


@click.command()
@click.option('--setup-login', is_flag=True, help='Login with Steam (RUN THIS BEFORE USING THIS TOOL)')
@click.option('--config', type=click.Path(), help='Specify config file', default='config.json')
@utils.decorators.coro
async def main(setup_login: bool, config: str):
    log.info('Started SteamEventPoster')
    if os.getenv('DEV') == 'SEP':
        in_dev = True
    else:
        in_dev = False
    cfg = {}
    try:
        with open(config, 'r') as config:
            cfg = json.loads(config.read())
    except FileNotFoundError:
        log.error('No config file found. Make sure you have one of the following below:')
    if setup_login:  # login to steam
        await steam.login(cfg)
    elif is_steam_guarded(cfg):  # post event in steam guarded mode
        await steam.post_event_steam_guarded(cfg)
    else:
        await steam.post_event_non_steam_guarded(cfg)


if __name__ == '__main__':
    # print_license_info()
    main()

```

My command:
```
pyarmor pack --clean -x " --exclude license_information.py --exclude pytransform.py --exclude venv\\Lib\\site-packages\\PyInstaller --plugin license_information" -e " --onefile" --with-license outer main.py
```

When I launch `main.exe` I get:
```
Traceback (most recent call last):
  File "dist\obf\main.py", line 2, in <module>
  File "pytransform.py", line 344, in pyarmor_runtime
  File "pytransform.py", line 340, in pyarmor_init
  File "pytransform.py", line 57, in wrap
  File "pytransform.py", line 75, in init_pytransform
RuntimeError: Read file license.lic failed, No such file or directory
[2152] Failed to execute script main
```

But I want the nice error I made. How?

**Comment by jondy** [comment]
First patch `license_information.py`, it's not required to run `pyarmor_init` for obfuscated scripts
```python
# license_information.py
import logging
import sys
# from pytransform import pyarmor_init, get_license_info
from pytransform import  get_license_info

# pyarmor_init(is_runtime=1)
from rich.logging import RichHandler
```

Second patch `main.py`, the plugin mark should be like this
```
# {PyArmor Plugins}
if __name__ == '__main__':
    # PyArmor Plugin: print_license_info()

```

And if you pack scripts with outer license, you need generate a license and copy it within the final bundle.

**Comment by fieu** [comment]
How do I pack it though?

This is the command I am using:
`pyarmor pack --clean -x " --exclude venv\\Lib\\site-packages\\PyInstaller --exclude pytransform.py" -e " --onefile" --with-license outer main.py`

I am still getting this error when I run `main.exe`:
```
Traceback (most recent call last):
  File "dist\obf\main.py", line 2, in <module>
  File "pytransform.py", line 344, in pyarmor_runtime
  File "pytransform.py", line 340, in pyarmor_init
  File "pytransform.py", line 57, in wrap
  File "pytransform.py", line 75, in init_pytransform
RuntimeError: Read file license.lic failed, No such file or directory
[28656] Failed to execute script main
```

**Comment by jondy** [comment]
Is there `license.lic` in the same path of `main.exe`? If you don't know what if the usage of `--with-license outer`, pack it
```
pyarmor pack --clean -x " --exclude venv" -e " --onefile"  main.py
```

**Comment by fieu** [comment]
I'm sorry, I don't think you understand what I want to do. I would like to display a better message when there is no license in the path.

Instead of:
```
Traceback (most recent call last):
  File "dist\obf\main.py", line 2, in <module>
  File "pytransform.py", line 344, in pyarmor_runtime
  File "pytransform.py", line 340, in pyarmor_init
  File "pytransform.py", line 57, in wrap
  File "pytransform.py", line 75, in init_pytransform
RuntimeError: Read file license.lic failed, No such file or directory
[3564] Failed to execute script main
```
I would like to say:
```
INFO: Please put the license.lic inside the same path
```

And when I do put my `license.lic` file in the same path and launch `main.exe`, my app works but does not display any license info, like the plugin is not even loaded.

**Comment by ChaochCN** [comment]
I think your idea is: catch the exception and handle it yourself, in a friendly interactive way.
it`s realy an awesome plan.
I also hope that my project can be perfectly combined with pyarmor， just like this.

**Comment by fieu** [comment]
@ChaochCN Yes that's what I want to do.

**Comment by jondy** [comment]
@fieu try to use runtime hook of pyinstaller to catch unhandled exception, first create a script `myhandle.py`
```
import sys
import logging

def excepthook(type, value, traceback):
    logging.error('%s', value)
    sys.exit(0)

sys.excepthook = excepthook
```

then pack it
```
pyarmor pack --clean -x " --exclude venv --exclude myhandle.py" -e " --onefile --runtime-hook myhandle.py"  main.py
```

**Comment by fieu** [comment]
@jondy I guess that works, how can I catch a license not found error. `except RuntimeError:` doesn't work

**Comment by jondy** [comment]
There is another way is to edit `pytransform.py`, refine `dllmethod`
```python
def dllmethod(func):
    def wrap(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            if sys.flags.debug:
                raise
            print(e)
            sys.exit(1)
    return wrap
```
You can try this.

**Comment by fieu** [comment]
Hello, I am using the exact same code, is there a reason this doesn't work in the newest update?

**Comment by jondy** [comment]
It should work with the latest version (v6.6.2) for non-super mode. It doesn't work for super mode.

**Comment by jondy** [comment]
If you have upgraded pyarmor, please remove all the old obfuscated files, and obfuscate them again.

**Comment by fieu** [comment]
I ended up fixing it some other way. Thanks.

**Comment by LuisHenri** [comment]
Hi @fieu, would you mind sharing the way you fixed it? :)
