### ISSUE TITLE
Function does not end with "):"

### ISSUE THREAD

**Issue by aguiot** [dashingsoft/pyarmor#387]
Hi,

We're facing an issue when obfuscating some scripts.
It says that the function doesn't end with "):", but it does.

**file:**
``` python

def check_other_conditions(obj):  # noqa C901
    """Check other conditions associated to the trigger."""
    # Get all Fields to check in one query
    all_fields_to_check = ["code"]
    for attr_to_check in obj.other_checks.keys():
        attr_split = attr_to_check.split(".")
        # handle usual fields
        if len(attr_split) == 1:
            all_fields_to_check.append(attr_to_check)
        # handle bubbled fields
        elif len(attr_split) == 2:
            all_fields_to_check.append(attr_split[0])
        else:
            message = "Unhandled field {}".format(attr_to_check)
            obj._fail_message(message)
            return False

    # Update entity
    sg_filter = [["id", "is", obj.trigger_entity["id"]]]
    update_entity = obj.sg.find_one(
        obj.trigger_entity["type"], sg_filter, all_fields_to_check
    )
    obj.logger.debug("all_fields_to_check {}".format(all_fields_to_check))
    obj.logger.debug("updated entity {}".format(update_entity))

    for attr, value in obj.other_checks.items():
        attr_split = attr.split(".")
        fail_flag = False

        # Check value is a list
        value_list = [value] if not isinstance(value, list) else value

        # Update entity when dealing with bubbled fields
        if len(attr_split) == 2:
            sg_fields = [key for val in value_list for key in val.keys()]
            for ent in update_entity[attr_split[0]]:
                sg_filter = [["id", "is", ent["id"]]]
                ent.update(obj.sg.find_one(ent["type"], sg_filter, sg_fields))

        obj.logger.debug("updated entity {}".format(update_entity))

        # Handle entity or multi-entity fields
        try:
            # handle usual fields
            if len(attr_split) == 1:
                curr_attr_list = [ent["name"] for ent in update_entity[attr]]

                if any([elmt not in curr_attr_list for elmt in value_list]):
                    fail_flag = True

            # handle bubbled fields
            elif len(attr_split) == 2:
                # reformat value_list
                value_list = [it for val in value_list for it in val.items()]

                # get all tasks
                for ent in update_entity[attr_split[0]]:
                    # refine to the deisred task only
                    if ent["name"] == attr_split[1]:
                        obj.logger.debug("entity {}".format(ent))

                        curr_attr_list = ent.items()

                        if any([elmt not in curr_attr_list for elmt in value_list]):
                            fail_flag = True

        # Handle simple value fields
        except Exception:
            curr_attr_list = update_entity[attr]
            if curr_attr_list not in value_list:
                fail_flag = True

        if fail_flag:
            message = "Prerequisite Field {} is {} and not {}".format(
                attr, curr_attr_list, value_list
            )
            print(message)
            obj._fail_message(message)
            return False

    return True

```

**command:**
``` bash
$ pyarmor -d obfuscate --advanced 2 --no-runtime /tmp/reproduce_encrypt_error.py
```

**output:**
``` bash
DEBUG    PyArmor installation path: /app/user/aguiot/package/pyarmor/6.4.2/88a70aca30cb79a278872594adf043dc6c40af99/python/pyarmor
DEBUG    PyArmor home path: /home/aguiot/.pyarmor
DEBUG    Native platform is linux.x86_64
DEBUG    Search dynamic library in the path: /app/user/aguiot/package/pyarmor/6.4.2/88a70aca30cb79a278872594adf043dc6c40af99/python/pyarmor/platforms
DEBUG    Loaded dynamic library: /app/user/aguiot/package/pyarmor/6.4.2/88a70aca30cb79a278872594adf043dc6c40af99/python/pyarmor/platforms/linux/x86_64/_pytransform.so
DEBUG    The version of core library is (34, 8, 7)
INFO     PyArmor Version 6.4.2
INFO     Target platforms: Native
DEBUG    Load platform list from /app/user/aguiot/package/pyarmor/6.4.2/88a70aca30cb79a278872594adf043dc6c40af99/python/pyarmor/platforms/index.json
INFO     Update target platforms to: ['linux.x86_64.11.py37']
INFO     Source path is "/tmp"
INFO     Entry scripts are ['/tmp/reproduce_encrypt_error.py']
INFO     Use cached capsule /home/aguiot/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read public key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 2
INFO     Super mode is True
WARNING  No cross protection because no runtime generated
INFO     Start obfuscating the scripts...
INFO     	reproduce_encrypt_error.py -> dist/reproduce_encrypt_error.py
ERROR    Function does not end with "):"
Traceback (most recent call last):
  File "/app/user/aguiot/package/pyarmor/6.4.2/88a70aca30cb79a278872594adf043dc6c40af99/bin/pyarmor", line 10, in <module>
    sys.exit(main_entry())
  File "/app/user/aguiot/package/pyarmor/6.4.2/88a70aca30cb79a278872594adf043dc6c40af99/python/pyarmor/pyarmor.py", line 1447, in main_entry
    main(sys.argv[1:])
  File "/app/user/aguiot/package/pyarmor/6.4.2/88a70aca30cb79a278872594adf043dc6c40af99/python/pyarmor/pyarmor.py", line 1439, in main
    args.func(args)
  File "/app/user/aguiot/package/pyarmor/6.4.2/88a70aca30cb79a278872594adf043dc6c40af99/python/pyarmor/pyarmor.py", line 698, in _obfuscate
    plugins=plugins, suffix=suffix)
  File "/app/user/aguiot/package/pyarmor/6.4.2/88a70aca30cb79a278872594adf043dc6c40af99/python/pyarmor/utils.py", line 939, in encrypt_script
    co = _check_code_object_for_super_mode(co, lines, modname)
  File "/app/user/aguiot/package/pyarmor/6.4.2/88a70aca30cb79a278872594adf043dc6c40af99/python/pyarmor/utils.py", line 1457, in _check_code_object_for_super_mode
    raise RuntimeError('Patch function "%s" failed' % c.co_name)
RuntimeError: Patch function "check_other_conditions" failed
```

I thought it was because of the comment on the line of the function definition.
But obfuscating a basic function such as:
``` python
def foo():  # bar
    pass
```
is not failing.

Thanks for your help,
Anthony

**Comment by jondy** [comment]
Yes, the problem is the trailing comment in the line of function definition. `check_other_conditions` need to be patched,  but `foo` need not, so `foo` works.

Refer to #380

**Comment by aguiot** [comment]
Unfortunately, the comment can't be moved that's a comment needed to disable a flake8 warning, and should be on the definition line.

In that case, your advice is to add `[None, None]`  at the beginning of the function?
Such as:
``` python
def check_other_conditions(obj):
    [None, None]
    ...
```

**Comment by jondy** [comment]
Yes, it should work by this redundant line.

But I have fixed this issue in develop version, you also can apply this patch b7a4f6566a0cb568b4242f33c7b3c7832a41022d

**Comment by aguiot** [comment]
Nice, thanks!
I'll wait for it to be released.

**Comment by jondy** [comment]
Please upgrade to v6.5.3

**Comment by aguiot** [comment]
Thanks for the fix, but I think there is a mistake in that patch.
It no longer supports methods defined on multiple lines.
example:
``` python
def foo(
    a,
    b,
):
    pass
```

I think that's because of variable "k" on your patch, shadowing a previously defined "k":
``` python
            i = c.co_firstlineno - 1
            k = i + c.co_lnotab[1]
            while i < k:
                s = lines[i].strip()
                k = s.find('#')
                if k > 0 and s[k:].find('"') == -1 and s[k:].find("'") == -1:
                    s = s[:k].strip()
                if s.endswith('):') or (s.endswith(':') and s.find('->') > -1):
                    break
                i += 1
            else:
                logging.error('Function does not end with "):"')
                raise RuntimeError('Patch function "%s" failed' % c.co_name)
```

It may be:
``` python
            i = c.co_firstlineno - 1
            k = i + c.co_lnotab[1]
            while i < k:
                s = lines[i].strip()
                f = s.find('#')
                if f > 0 and s[f:].find('"') == -1 and s[f:].find("'") == -1:
                    s = s[:f].strip()
                if s.endswith('):') or (s.endswith(':') and s.find('->') > -1):
                    break
                i += 1
            else:
                logging.error('Function does not end with "):"')
                raise RuntimeError('Patch function "%s" failed' % c.co_name)
```

**Comment by jondy** [comment]
Yes, you're right. Sorry for this mistake, :(

**Comment by aguiot** [comment]
No problem, sorry to spot that after you released, and not before ^^'

**Comment by aguiot** [comment]
Tested with pyarmor-6.5.4, that's working now, thanks!
