### ISSUE TITLE
SyntaxError in linux

### ISSUE THREAD

**Issue by choojw** [dashingsoft/pyarmor#398]
My `__init__.py` file cannot be obfuscate. Attach the error code below.

```
INFO     Start obfuscating the scripts...
INFO            __init__.py -> dist/__init__.py
INFO     Write patched script for debugging: /usr/src/app/dl_rest/app/__init__.py.pyarmor-patched
Traceback (most recent call last):
  File "/usr/local/bin/pyarmor", line 11, in <module>
    sys.exit(main_entry())
  File "/usr/local/lib/python2.7/dist-packages/pyarmor/pyarmor.py", line 1518, in main_entry
    main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pyarmor/pyarmor.py", line 1510, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/pyarmor/pyarmor.py", line 714, in _obfuscate
    plugins=plugins, suffix=suffix)
  File "/usr/local/lib/python2.7/dist-packages/pyarmor/utils.py", line 954, in encrypt_script
    co = compile(''.join(lines), modname, 'exec')
  File "<frozen app>", line 27
    for resource_name, *url in _state.URL:
                       ^
SyntaxError: invalid syntax
```

**Comment by jondy** [comment]
Before obfuscating, make sure python could execute the script correctly. You're using Python 2.7 to obfuscate this script, but this script `/usr/src/app/dl_rest/app/__init__.py` doesn't  work for Python2, please obfuscate this script by Python3.

Refer to https://pyarmor.readthedocs.io/en/latest/advanced.html#obfuscating-scripts-by-other-python-version

**Comment by choojw** [comment]
Thank you for your information.
