### ISSUE TITLE
No library _pytransform.so found after update to 4.5.0

### ISSUE THREAD

**Issue by Zippersk** [dashingsoft/pyarmor#41]
After update to version 4.5.0 a get error when building:
`RuntimeError: No library /usr/lib/python3.6/site-packages/pyarmor/platforms/linux_x86_64/_pytransform.so found`

Downgrade to 4.4.3 helps.

Whole error message is here:
```
$ pyarmor build

Traceback (most recent call last):
  File "/usr/bin/pyarmor", line 7, in <module>
    from pyarmor.pyarmor import main_entry
  File "/usr/lib/python3.6/site-packages/pyarmor/pyarmor.py", line 49, in <module>
    from utils import make_capsule, obfuscate_scripts, make_runtime, \
  File "/usr/lib/python3.6/site-packages/pyarmor/utils.py", line 50, in <module>
    search_pytransform(PYARMOR_PATH)
  File "/usr/lib/python3.6/site-packages/pyarmor/utils.py", line 48, in search_pytransform
    raise RuntimeError('No library %s found' % src)
RuntimeError: No library /usr/lib/python3.6/site-packages/pyarmor/platforms/linux_x86_64/_pytransform.so found
```

**Comment by jondy** [comment]
Fixed in 4.5.1
