### ISSUE TITLE
Error after obfuscation.

### ISSUE THREAD

**Issue by GoekhanA** [dashingsoft/pyarmor#410]
```
Traceback (most recent call last):
  File "dist\obf\Automation.py", line 2, in <module>
  File "dist\obf\temp\pytransform.py", line 314, in pyarmor_runtime
  File "dist\obf\temp\pytransform.py", line 310, in pyarmor_init
  File "dist\obf\temp\pytransform.py", line 55, in wrap
  File "dist\obf\temp\pytransform.py", line 73, in init_pytransform
OSError: exception: access violation reading 0x0000000000000000
[20528] Failed to execute script Automation
```
Python version 3.8.6

Using following modules:

```
import random, time, os, sys, ctypes, threading, re, requests, json, subprocess, configparser

from getpass import getpass
from time import strftime
from threading import Lock
from colorama import Back, Fore, Style, init
from discord_webhook import DiscordWebhook

import undetected_chromedriver as uc
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.support.ui import Select, WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import (NoSuchElementException, TimeoutException, WebDriverException)
```

**Comment by jondy** [comment]
How about obfuscating the scripts with super mode by passing option `--advanced 2`?

**Comment by GoekhanA** [comment]
Fixed the issue, I was using a old version of pyarmor.
