### ISSUE TITLE
pyarmor benchmark 是否支持指定文件进行测试

### ISSUE THREAD

**Issue by xingwenchao** [dashingsoft/pyarmor#411]
我想指定我的代码进行测试，这个是否支持呢

**Comment by jondy** [comment]
不支持，测试自己的代码需要自己加入打印时间戳的语句

**Comment by xingwenchao** [comment]
好的，pyarmor的模式中哪一种加密模式的性能是最优的呢

**Comment by jondy** [comment]
普通模式/高级模式/超级模式这三种模式性能都差不多，安全性超级模式最高，VM模式性能上明显慢一些，但是安全性更高。

**Comment by xingwenchao** [comment]
好的，我们这边有一个业务是对静态资源文件读取，然后进行数据进行处理，然后发现同一份代码，随着静态资源文件资源的增多，加密代码比同一份非加密代码额外消耗的时间也在增长，这一点我很疑惑，加密解密的过程不是只有消耗在代码加载的过程中吗？

**Comment by jondy** [comment]
默认情况下是动态加密的，即函数开始执行前才解密，执行完成会重新加密。请参考文档中 模式 章节中包裹模式的说明，如何切换不同模式请参考文档中的说明和各个命令的 man 手册中选项说明。

**Comment by yq1320** [comment]
@jondy 加密的脚本是否支持使用cProfile性能测试工具进行测试，我们使用cProfile对加密文件测试，出现了如下的错误。
```
gradients/logistic_loss/Log1p_grad/add/x: (Const): /job:localhost/replica:0/task:0/cpu:0
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/cProfile.py", line 200, in <module>
    main()
  File "/usr/lib64/python2.7/cProfile.py", line 193, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/usr/lib64/python2.7/cProfile.py", line 56, in runctx
    result = prof.print_stats(sort)
  File "/usr/lib64/python2.7/cProfile.py", line 81, in print_stats
    pstats.Stats(self).strip_dirs().sort_stats(sort).print_stats()
  File "/usr/lib64/python2.7/pstats.py", line 81, in __init__
    self.init(arg)
  File "/usr/lib64/python2.7/pstats.py", line 95, in init
    self.load_stats(arg)
  File "/usr/lib64/python2.7/pstats.py", line 119, in load_stats
    arg.create_stats()
  File "/usr/lib64/python2.7/cProfile.py", line 92, in create_stats
    self.snapshot_stats()
  File "/usr/lib64/python2.7/cProfile.py", line 100, in snapshot_stats
    func = label(entry.code)
TypeError: 'NoneType' object is not callable
```
您这边有类似cProfile对加密脚本进行测试的方法或工具嘛？

**Comment by jondy** [comment]
pyarmor 不支持 cProfile 的，它用到了和调试相关的功能，所以被禁掉了。如果对个别模块测试，可以参考 pyarmor 包里面的 `benchmark.py` 里面有个 decorator `metricmethod` 可以用来测试一个函数的执行时间。

**Comment by yq1320** [comment]
如何调用 decorator metricmethod ？
我一下文档没有说明  decorator metricmethod 的调用方式。
https://pyarmor.readthedocs.io/zh/latest/man.html#banchmark

**Comment by yq1320** [comment]
@jondy 我现在要测试整个业务代码模块的整体消耗的性能，不是单一的方式。除了metricmethod  这个方式，还有其他的性能测试方式嘛？

**Comment by jondy** [comment]
你是怎么使用 cProfile 的，我使用下面的方式运行 cProfile 测试加密脚本都没有问题：
```
python -m cProfile -s filename dist/foo.py
```

你尝试一下修改 cProfile 的源码，在出现异常的行加一些代码，忽略出现异常的被测试函数，然后使用 cProfile 测试性能。

**Comment by yq1320** [comment]
我对不加密的代码使用cProfile进行测试，没有问题，正常输出的，对加密的代码进行测试就报错了。
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/cProfile.py", line 200, in <module>
    main()
  File "/usr/lib64/python2.7/cProfile.py", line 193, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/usr/lib64/python2.7/cProfile.py", line 56, in runctx
    result = prof.print_stats(sort)
  File "/usr/lib64/python2.7/cProfile.py", line 81, in print_stats
    pstats.Stats(self).strip_dirs().sort_stats(sort).print_stats()
  File "/usr/lib64/python2.7/pstats.py", line 81, in __init__
    self.init(arg)
  File "/usr/lib64/python2.7/pstats.py", line 95, in init
    self.load_stats(arg)
  File "/usr/lib64/python2.7/pstats.py", line 119, in load_stats
    arg.create_stats()
  File "/usr/lib64/python2.7/cProfile.py", line 92, in create_stats
    self.snapshot_stats()
  File "/usr/lib64/python2.7/cProfile.py", line 100, in snapshot_stats
    func = label(entry.code)
TypeError: 'NoneType' object is not callable
```

**Comment by xingwenchao** [comment]
@jondy 在一个单进程的常规读写+数据处理的程序中，使用的命令是
 
pyarmor config  --wrap-mode 0 --cross-protection=0 --advanced 2 --restrict 0   --manifest "global-include *.py, global-exclude dvrtranslator.py, prune lib/Python-2.7/site-packages " 

加密完成后使用cProfile测试，得到了如下数据，但是根据文档，如果使用wrap-mode=0的情况下，加密解密的消耗时间应该是常量才对，但是根据我们的测试结果得到的数据是，根据我们读写+数据处理数据量的增加，armor_wrap模块的耗时也在增加，我想是不是wrap-mode没有生效呢？

程序处理  74M的IO数据 armor_wrap耗时 57s
程序处理147M的IO数据 armor_wrap耗时115s

**Comment by jondy** [comment]
超级模式下面 wrap-mode 总是生效的，因为超级模式是后来增加的，文档里面有点地方可能存在不一致。

要想禁用 wrap-mode，就不能使用超级模式，这样应该能提升重新执行函数的性能。

**Comment by xingwenchao** [comment]
@jondy  好的，谢谢你的解答，此问题已经得到解决。再不使用超级模式后，性能提升很大。
