### ISSUE TITLE
Error with ray

### ISSUE THREAD

**Issue by galmegy** [dashingsoft/pyarmor#412]
I am a beginner at pyarmor and want to use ray with pyarmor, but I have an error like below.

Environment:
- windows 10 - 64bit/ python 3.8/ anaconda

pyarmor obfuscate test_main.py:
```python
import ray
ray.init()

@ray.remote
def f(x):
    return x * x

futures = [f.remote(i) for i in range(4)]
print(ray.get(futures)) # [0, 1, 4, 9]
```

I got the following error:
```
Traceback (most recent call last):
  File "<test_main.py>", line 3, in <module>
  File "<frozen dist.test_main>", line 17, in <module>
  File "<frozen dist.test_main>", line 16, in <listcomp>
  File "D:\Anaconda3\envs\py38\lib\site-packages\ray\remote_function.py", line 101, in _remote_proxy
    return self._remote(args=args, kwargs=kwargs)
  File "D:\Anaconda3\envs\py38\lib\site-packages\ray\remote_function.py", line 201, in _remote
    self._pickled_function = pickle.dumps(self._function)
  File "D:\Anaconda3\envs\py38\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "D:\Anaconda3\envs\py38\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "D:\Anaconda3\envs\py38\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 658, in reducer_override
    return self._function_reduce(obj)
  File "D:\Anaconda3\envs\py38\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 526, in _function_reduce
    return self._dynamic_function_reduce(obj)
  File "D:\Anaconda3\envs\py38\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 507, in _dynamic_function_reduce
    state = _function_getstate(func)
  File "D:\Anaconda3\envs\py38\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 157, in _function_getstate
    f_globals_ref = _extract_code_globals(func.__code__)
  File "D:\Anaconda3\envs\py38\lib\site-packages\ray\cloudpickle\cloudpickle.py", line 236, in _extract_code_globals
    out_names = {names[oparg] for _, oparg in _walk_global_ops(co)}
  File "D:\Anaconda3\envs\py38\lib\site-packages\ray\cloudpickle\cloudpickle.py", line 236, in <setcomp>
    out_names = {names[oparg] for _, oparg in _walk_global_ops(co)}
  File "D:\Anaconda3\envs\py38\lib\site-packages\ray\cloudpickle\cloudpickle.py", line 425, in _walk_global_ops
    for instr in dis.get_instructions(code):
  File "D:\Anaconda3\envs\py38\lib\dis.py", line 350, in _get_instructions_bytes
    argval, argrepr = _get_name_info(arg, cells)
  File "D:\Anaconda3\envs\py38\lib\dis.py", line 304, in _get_name_info
    argval = name_list[name_index]
IndexError: tuple index out of range
```

**Comment by jondy** [comment]
It seems it tries to get byte codes of the obfuscated scripts  by `dis.get_instructions`, but the byte codes are protected by pyarmor.

Also refer to
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts
