### ISSUE TITLE
Support for 64bit embedded platform

### ISSUE THREAD

**Issue by hankso** [dashingsoft/pyarmor#42]
Pyarmor now only support 32bit embedded platform include Raspberry Pi and Banana Pi.
I'd like to use it on a 64bit Orange Pi Zero Plus 2. Could you please compile the aarch64 _pytransform.so lib? I believe It will also work on 64bit RaspPi & BananaPi

**Comment by jondy** [comment]
No problem. I'll build it with this toolchain `https://codeload.github.com/orangepi-xunlong/OrangePiH5_toolchain/zip/master`.

**Comment by jondy** [comment]
Here it is

http://pyarmor.dashingsoft.com/downloads/platforms/orangepi/_pytransform.so

Cross compile by `gcc-linaro-aarch/bin/aarch64-linux-gnu-gcc`

**Comment by hankso** [comment]
Thanks for your work, Jondy. But there's error msssage:
```bash
$ # On Orange Pi Zero Plus 2 running Armbian 5.60
$ cd /usr/local/lib/python2.7/dist-packages/pyarmor
$ wget http://url/to/lib -O platforms/linux64/_pytransform.so
$ pyarmor -h
Invalid input packet.
Verify rsa key failed
Invalid trial license file, size is 202 != 256
Check pyshield license failed
Check trial license failed
Verify license failed
Initialize pytransform failed
$ # Running cmd `pyarmor` failed
$ # Here's output when I trying to run codes that 
$ # obfuscated on computer linux x86_64 after
$ # replace old _pytransforms.so with your new one.
$ python queens.py
Traceback (most recent call last):
  File "queens.py", line 2, in <module>
    pyarmor_runtime()
  File "/usr/local/lib/python2.7/dist-packages/pyarmor/examples/dist/pytransform.py", line 274, in pyarmor_runtime
    pyarmor_init(path)
  File "/usr/local/lib/python2.7/dist-packages/pyarmor/examples/dist/pytransform.py", line 271, in pyarmor_init
    init_pytransform()
  File "/usr/local/lib/python2.7/dist-packages/pyarmor/examples/dist/pytransform.py", line 72, in wrap
    raise PytransformError(format_message(errmsg, *args, **kwargs))
pytransform.PytransformError: Invalid input packet.
Verify rsa key failed
Invalid trial license file, size is 212 != 256
Check trial license failed
Verify license failed
Initialize pytransform failed
$ file _pytransform.so
_pytransform.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=cfb28ccd17afe160898b3fbe3a831fedb0e6a1ac, not stripped
```
Don't know what is wrong but I'd suggest compiling on a real embedded device,

**Comment by hankso** [comment]
You are right, I can successfully load new `_pytransform.so` by `ctypes.dll`.
But after I pip uninstall & install pyarmor, it reports the same bug:
> Invalid input packet.
Verify rsa key failed
Invalid trial license file, size is 202 != 256
Check pyshield license failed
Check trial license failed
Verify license failed
Initialize pytransform failed

I manually download `license.lic` from this repo and it's exactly replace old one but still got same error `202 != 256`.
Result of `stat license.lic`:
>  File: 'license.lic'
  Size: 256       	Blocks: 8          IO Block: 4096   regular file
Device: b301h/45825d	Inode: 32136      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (   50/   staff)
Access: 2018-12-10 20:08:55.119672030 +0800
Modify: 2018-12-10 20:08:45.006960000 +0800
Change: 2018-12-10 20:08:45.807017476 +0800
 Birth: -

**Comment by hankso** [comment]
You are right, I can successfully load new _pytransform.so by ctypes.dll.
But after I pip uninstall & install pyarmor, it reports the same bug:
>Invalid input packet.
Verify rsa key failed
Invalid trial license file, size is 202 != 256
Check pyshield license failed
Check trial license failed
Verify license failed
Initialize pytransform failed

Here's the most wired thing: when I update `license.lic` with a new one generated on my computer, I still get exactly same error `202 != 256`.
```
hansko@DELL:~$ pyarmor license test_orangepi

hankso@orangepizeroplus2:~# cd /usr/local/lib/python2.7/dist-packages/pyarmor
hankso@orangepizeroplus2:~# scp hankso@DELL:/path/to/test_orangepi/license.lic ./

hankso@orangepizeroplus2:~# pyarmor -h
Invalid input packet.
Verify rsa key failed
Invalid trial license file, size is 202 != 256
Check pyshield license failed
Check trial license failed
Verify license failed
Initialize pytransform failed

hankso@orangepizeroplus2:~# stat license.lic
  File: 'license.lic'
  Size: 204       	Blocks: 8          IO Block: 4096   regular file
Device: b301h/45825d	Inode: 30113      Links: 1
Access: (0664/-rw-rw-r--)  Uid: (     0/    root)   Gid: (   50/    staff)
Access: 2018-12-10 20:17:54.863127612 +0800
Modify: 2018-12-10 20:17:40.843516686 +0800
Change: 2018-12-10 20:17:40.843516686 +0800
 Birth: -
```

**Comment by jondy** [comment]
It's not the right way:
* Generate a license on your DELL
* Run pyarmor on Orange Zero Plus2 with this license

Something need to be clear:
The license generated on your DELL is only used to run obfuscated scripts.

And you need not install pyarmor on Orange Zero Plus2 if you only run obfuscated scripts on it.

The right steps
1. Obfuscate python scripts on DELL: `pyarmor obfuscate foo.py`
2. Copy all the files in `dist` path to Orange Zero Plus2 `/home/user/test`
    In the `dist` path, there are obfuscated scripts `foo.py` and all the other runtime files which are required to run obfuscated scripts, include `license.lic`.
3.  On Orange Zero Plus2, download `_pytransform.so` for Orange Zero Plus2
4.  Run obfuscated script
```
    cd /home/user/test
    python foo.py
    python --version     # It should be same as version of Python in the DELL
```

On Orange Zero Plus2, could you edit `/usr/local/lib/python2.7/dist-packages/pyarmor/pytransform.py`, uncomment this line
```
    # m.set_option('enable_trace_log'.encode(), c_char_p(1))
```
Then run `pyarmor -h`, it will create a log file `_pytransform.log`, then show me this log.

**Comment by hankso** [comment]
Obfuscate `queen.py` on my computer:
```
hankso@DELL:~$ # first uninstall and reinstall pyarmor
hankso@DELL:~$ pyarmor obfuscate -r simple/queen.py
hankso@DELL:~$ wget http://url/to/lib -O dist/_pytransform.so
hankso@DELL:~$ python -V
Python 2.7.12
```
Then transfer all files in `dist/` to orangepi
```
hankso@orangepizeroplus2:~/dist# ls -lh
-rw-r--r-- 1 root staff   212 Dec 12  2018 license.lic
-rw-r--r-- 1 root staff   140 Dec 12  2018 product.key
-rw-r--r-- 1 root staff   140 Dec 12  2018 pyshield.key
-rw-r--r-- 1 root staff   288 Dec 12  2018 pyshield.lic
-rw-r--r-- 1 root staff  7.4K Dec 12  2018 pytransform.py
-rw-r--r-- 1 root staff  603K Dec  6  2018 _pytransform.so
-rw-r--r-- 1 root staff   14K Dec 12  2018 queens.py
```
It occurs the same error:
```
hankso@orangepizeroplus2:~/dist# python queen.py
Invalid input packet.
Verify rsa key failed
Invalid trial license file, size is 212 != 256
Check trial license failed
Verify license failed
Initialize pytransform failed
```
When dig in deeper I find that all codes is gonig well until `init_module(major, minor, pythonapi._handle)` in `pytransform.py`. This function return `1` and `_get_error_msg()` return the above error info. Because `_get_error_msg` is the function inside `_pytransform.so`, I guess a constent might be set to **256**.

Besides, on orangepi:
```
hankso@orangepizeroplus2:~/dist# python -V
Python 2.7.13
```
Could this be the reason for error?

**Comment by jondy** [comment]
It's not about Python version. Something is wrong with verify rsa key.  

On orangepi, download this test version:

http://pyarmor.dashingsoft.com/downloads/platforms/orangepi/test/_pytransform.so

Replace the old one, then run 'pyarmor -h'.

If it still doesn't work, send me "_pytransform.log"

**Comment by hankso** [comment]
The new `orangepi/test/_pytransform.so` and old one `orangepi/_pytransform.so` are exact same files, resulting in same traceback info. Here is [_pytransform.log](https://github.com/dashingsoft/pyarmor/files/2682693/_pytransform.log)

**Comment by jondy** [comment]
Last time I changed the type of parameter of verify rsa function from `int` to `unsigned long`, this has been resulted in license issues in 64-bit machine before. It seems this is not the root cause of orange pi. Now I build a new one to trace parameter, it will print data in stdout, show me the output

http://pyarmor.dashingsoft.com/downloads/platforms/orangepi/test/_pytransform.so
06581737e77ec73b841ec35569d427be *_pytransform.so

**Comment by hankso** [comment]
Here it is:
>Trace log mode enabled and log to '_pytransform.log'
30 81 89 02 81 81 00 f4 
70 b5 1b 0e ab aa 00 00 f0 59 cd 9b 
len is 149, sigsize is 128, msgsize is 20, lenoffset is 1, saltlen is 8
44 41 53 48 49 4e 47 53 4f 46 54 2d 50 59 53 48
>
>b9 83 e2 6a 87 f5 ab 68 12 34 cd 49 5f de fe fb
>
>30 81 89 02 81 81 00 f4 
70 b5 1b 0e ab aa 00 00 f0 59 cd 9b 
len is 149, sigsize is 128, msgsize is 20, lenoffset is 1, saltlen is 8
44 41 53 48 49 4e 47 53 4f 46 54 2d 50 59 53 48
>
>b9 83 e2 6a 87 f5 ab 68 12 34 cd 49 5f de fe fb

>Invalid input packet.
Verify rsa key failed
Invalid trial license file, size is 202 != 256
Check pyshield license failed
Check trial license failed
Verify license failed
Initialize pytransform failed

and the  [_pytransform.log](https://github.com/dashingsoft/pyarmor/files/2693038/_pytransform.log)

**Comment by jondy** [comment]
Something is wrong with `pyshield.lic`, check md5sum of /usr/local/lib/python2.7/dist-packages/pyarmor/pyshield.lic, it should be

    4e70cac2a862f28dd12d9e8497d7df8c

If it is, download this new one, run `pyarmor -h` again and show me the output

http://pyarmor.dashingsoft.com/downloads/platforms/orangepi/test/_pytransform.so

md5sum: 685b5f48ecb44ce5a01ef9e16e9f2369

**Comment by hankso** [comment]
`pyshield.lic` md5sum passed. Here's [CLI log](https://we.tl/t-DqCg4uAYga) and [_pytransform.log](https://we.tl/t-mqNjyhE8Is)

**Comment by jondy** [comment]
I rebuild new one with some extra `CFlags` to support 64bit machine, hope it works:

http://pyarmor.dashingsoft.com/downloads/platforms/orangepi/test/_pytransform.so

md5sum: 786966e94f24924df305c1a5d0e133bd

If it still doesn't work, send me the output.

**Comment by hankso** [comment]
Sorry for the late reply. I guess `pyshield.lic` is mistakenly decoded into 202bytes while the result should have been 256bytes. Both data type(`int` & `unsigned long`) or RSA verification function might be the reason. Check [20181219 logfile](https://ufile.io/z1q13) and [20181220 logfile](https://ufile.io/8921o)

**Comment by jondy** [comment]
The size is not problem. I think something is wrong with 64-bit machine. libtomcrypt fails to verify rsa key. 
Here I build new one to check all the data of parameters,  replace old one and show me the output (_pytransfrom.log is not required)

http://pyarmor.dashingsoft.com/downloads/platforms/orangepi/test/_pytransform.so

And there is another file `libtest` which used to verify libtomcrypt, just run it, check whether test cases passed:

http://pyarmor.dashingsoft.com/downloads/platforms/orangepi/test/libtest

fd335dfdf0813c373ae7f9e0e7f27435 *libtest
14b79e835ac432a2be98837f569a3fbc *_pytransform.so

**Comment by hankso** [comment]
You are right.

`libtest` encounter an error when testing `pkcs_1_pss` in function `rsa_sign_hash(buf, buflen, ...)`, see [libtest.log](https://github.com/dashingsoft/pyarmor/files/2708793/libtest.log) for details.

And output of `pyarmor -h` [pyarmor.log](https://github.com/dashingsoft/pyarmor/files/2708794/pyarmor.log).

Not an expert on encryption and verification, what else I can do to help you?

**Comment by jondy** [comment]
It's a good idea.

First install `tomsfastmath`, then download 

https://github.com/libtom/libtomcrypt/releases/download/v1.18.2/crypt-1.18.2.zip

Unzip it and build

make CFLAGS="-DUSE_TFM -DTFM_DESC" EXTRALIBS="libtfm.a" libtomcrypt.a test

Next, run `test`

If all tests pass, send me 2 files: `libtfm.a` and `libtomcrypt.a`

**Comment by hankso** [comment]
I use [tomsfastmath v0.13.1](https://github.com/libtom/libtomcrypt/releases/download/v1.18.2/crypt-1.18.2.zip) and [libtomcrypt v1.18.2](https://github.com/libtom/tomsfastmath/releases/download/v0.13.1/tfm-0.13.1.zip). 

Here's [libtfm.a.gz](https://github.com/dashingsoft/pyarmor/files/2710612/libtfm.a.gz), [libtomcrypt.a.gz](https://github.com/dashingsoft/pyarmor/files/2710613/libtomcrypt.a.gz) and [test.log](https://github.com/dashingsoft/pyarmor/files/2710614/test.log). All tests passed.

Hope this helps.

**Comment by jondy** [comment]
Thanks a lot. Here is the latest one linked with your static libraries

http://pyarmor.dashingsoft.com/downloads/platforms/orangepi/_pytransform.so
md5sum: b50205aabc1e07a69ccd8d5367b3e01d

It should work, :)
