### ISSUE TITLE
Target platform string ['linux.x86_64.11.py37'] being read as a list of characters

### ISSUE THREAD

**Issue by davidwynter** [dashingsoft/pyarmor#442]
I am using this method https://pyarmor.readthedocs.io/en/latest/advanced.html#distributing-obfuscated-package-with-pip

My script for obsfucation, run from project/shell directory:

```
#!/usr/bin/env bash
# Prepare the obsfucation, run from shell directory
rm -rf ../obsfucated
mkdir -p ../obsfucated
pyarmor  runtime -O obsfucated --enable-suffix 1 --advanced 2
pyarmor obfuscate  -r --with-runtime @obsfucated  --exclude package.py,setu*.py,test,test_data,dist,build ../
```

I am having this issue with the approach

```
l$ /bin/bash /home/david/projects/product/shell/obsfucate.sh
INFO     PyArmor Version 6.5.5
INFO     Update target platforms to: ['linux.x86_64.11.py37']
INFO     Generating super runtime library to obsfucated
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Copying /home/david/.pyarmor/platforms/linux/x86_64/11/py37/pytransform.cpython-37m-x86_64-linux-gnu.so
INFO     Rename extension to pytransform_vax_000925.cpython-37m-x86_64-linux-gnu.so
INFO     Patch extension obsfucated/pytransform_vax_000925.cpython-37m-x86_64-linux-gnu.so
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Generating protection script ...
INFO     Generating bootstrap script ...
INFO     Generating bootstrap script obsfucated/pytransform_bootstrap.py OK
INFO     PyArmor Version 6.5.5
INFO     Got settings from --runtime: obsfucated
INFO         Platforms: linux.x86_64.11.py37
INFO         Advanced: 2
INFO         Suffix: _vax_000925
INFO         License: embedded
INFO     Target platforms: ['l', 'i', 'n', 'u', 'x', '.', 'x', '8', '6', '_', '6', '4', '.', '1', '1', '.', 'p', 'y', '3', '7']
ERROR    No available dynamic library for l with features ['11']
```
Why is it detecting my Target platform and reading it as an array rather than a string?

**Comment by jondy** [comment]
It's a bug, please apply this patch in the source of pyarmor package: f445fb424e2f07eec226f1ee6f75bf93b34a48a8

**Comment by davidwynter** [comment]
I installed version 6.6.1 which has the change and now get this error

```
$ /bin/bash /home/david/fairxchange/horizon_data/shell/obsfucate.sh
INFO     PyArmor Version 6.6.1
INFO     Update target platforms to: ['linux.x86_64.11.py37']
INFO     Generating super runtime library to obsfucated
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Copying /home/david/.pyarmor/platforms/linux/x86_64/11/py37/pytransform.cpython-37m-x86_64-linux-gnu.so
INFO     Rename extension to pytransform_vax_000925.cpython-37m-x86_64-linux-gnu.so
INFO     Patch extension obsfucated/pytransform_vax_000925.cpython-37m-x86_64-linux-gnu.so
INFO     Patch library file OK
INFO     Generate runtime files OK
INFO     Generating protection script ...
INFO     Generating bootstrap script ...
INFO     Generating bootstrap script obsfucated/pytransform_bootstrap.py OK
INFO     PyArmor Version 6.6.1
INFO     Got settings from --runtime: obsfucated
INFO         Platforms: linux.x86_64.11.py37
INFO         Advanced: 2
INFO         Suffix: _vax_000925
INFO         License: embedded
INFO     Target platforms: ['linux.x86_64.11.py37']
INFO     Update target platforms to: ['linux.x86_64.11.py37']
INFO     Source path is "/home/david/fairxchange/horizon_data"
INFO     Entry scripts are []
INFO     Use cached capsule /home/david/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Exclude pattern "package.py"
INFO     Exclude pattern "setu*.py"
INFO     Exclude path "test"
INFO     Exclude path "testdata"
INFO     Exclude path "dist"
INFO     Exclude path "build"
INFO     Auto exclude output path "shell/dist"
no previously-included directories found matching 'dist'
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 2
INFO     Super mode is True
INFO     Copying runtime files from obsfucated
INFO     To dist
ERROR    Multiple runtime modules found
```

**Comment by jondy** [comment]
Remove the entire output path `dist`, make a clean obfuscation.

**Comment by davidwynter** [comment]
Thank you, that works. One issue is that now that I have switched to use `runtime` and `obsfucate` commands instead of `config` and `build`. I lost he ability to use a manifest to control which custom specific python files are excluded. I add my `pyarmor config --manifest ...` command to the shell script but it looks like it is ignored. Is there a way to use a manifest with the obsfucate command?

**Comment by jondy** [comment]
@davidwynter if you prefer to use project, pass prebuilt runtime in command `build`. For example
```
pyarmor build --runtime @obfuscate 
```

**Comment by davidwynter** [comment]
I have obfuscated, using Super mode, my 2 libraries and the product `etl` OK. But even with PYTHONPATH it still does not find the shared object file?

```
root@f378377cab94:/app# PYTHONPATH=./ python3 -m runtime.cust1.schedule_cust1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/runtime/__init__.py", line 1, in <module>
    from pytransform_vax_000925 import pyarmor
ImportError: dynamic module does not define module export function (PyInit_pytransform_vax_000925)
root@f378377cab94:/app# PYTHONPATH=./ python3 -m runtime.cust1.schedule_cust1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/runtime/__init__.py", line 1, in <module>
    from pytransform_vax_000925 import pyarmor
ImportError: dynamic module does not define module export function (PyInit_pytransform_vax_000925)
root@f378377cab94:/app# ls -l
total 1148
-rw-rw-r-- 1 root root     926 Jan 19 15:46 __init__.py
drwxr-xr-x 1 root root    4096 Jan 19 15:46 configfiles
drwxr-xr-x 2 root root    4096 Jan 19 15:46 core
drwxr-xr-x 1 root root    4096 Jan 19 15:46 customer
drwxr-xr-x 2 root root    4096 Jan 19 15:46 errorfiles
drwxr-xr-x 2 root root    4096 Jan 19 15:46 etl
drwxr-xr-x 2 root root    4096 Jan 19 15:46 logs
-rw-rw-r-- 1 root root 1132448 Jan 19 15:46 pytransform_vax_000925.cpython-37m-x86_64-linux-gnu.so
drwxr-xr-x 1 root root    4096 Jan 19 15:51 runtime
drwxr-xr-x 3 root root    4096 Jan 19 15:46 shell
drwxr-xr-x 2 root root    4096 Jan 19 15:46 utils
root@f378377cab94:/app# ls -l runtime/cust1
total 68
-rw-rw-r-- 1 root root 1374 Jan 19 15:46 __init__.py
-rw-rw-r-- 1 root root 5226 Jan 19 15:46 schedule_cust1.py
```
Further suggestions?

**Comment by jondy** [comment]
> ImportError: dynamic module does not define module export function (PyInit_pytransform_vax_000925)

In docker, the scripts should be obfuscate with `--platform musl.x86_64`.

Note that the obfuscated scripts are normal Python scripts, and `pytransform_vax_000925.cpython-37m-x86_64-linux-gnu.so` is a normal Python extension, you can use them as normal Python scripts, and fix import issue as in normal Python scripts. 

Check the python path by `print(sys.path)`, make sure this extension file is one of them. Or change Python Python to adapt it, you can check Python documentation to find how to set Python Path.

**Comment by davidwynter** [comment]
Changed my obfuscate.sh to:

```
#!/usr/bin/env bash
cd ../..
# Prepare the Cust1 etl obfuscation
rm -rf ./obfuscated
mkdir -p ./obfuscated
pyarmor init --src=../etl --entry run_workflow_cust1.py
pyarmor config --manifest "include app/etl/*.py, include app/*.py, include app/utils/*.py, include runtime/cust1/*.py, \
include app/core/*.py, include app/customer/*.py, include app/customer/cust1/*.py, include runtime/utils/*.py, \
include runtime/__init__.py, include __init__.py " --enable-suffix 1 --advanced 2
pyarmor build --platform musl.x86_64 -O ./obfuscated ./
```
The docker image uses debian-slim as the OS. 
I get this output inside the docker container:

```
root@3cc3a8dccc99:/# cd app
root@3cc3a8dccc99:/app# export PYTHONPATH=/app
root@3cc3a8dccc99:/app# python3 -m runtime.cust1.schedule_cust1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/runtime/__init__.py", line 1, in <module>
    from pytransform_vax_000925 import pyarmor
ImportError: /usr/lib/x86_64-linux-gnu/libc.so: invalid ELF header
```

**Comment by jondy** [comment]
Could you obfuscate a simple `foo.py` with `--platform musl.x86_64` and `--advanced 2`, and run it in docker?

**Comment by davidwynter** [comment]
Same result.

```
$ docker run --name foo -it fairxchange/foo:1.0.1 /bin/bash
root@61ad4b6b59a4:/# cd app
root@61ad4b6b59a4:/app# python3 -m app.foo
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/app/__init__.py", line 1, in <module>
    from pytransform_vax_000925 import pyarmor
ImportError: /usr/lib/x86_64-linux-gnu/libc.so: invalid ELF header
```

The shell script used:

```
#!/usr/bin/env bash
cd ../..
# Prepare the foo obfuscation
rm -rf ./obfuscated
mkdir -p ./obfuscated
pyarmor init --src=../etl --entry foo.py
pyarmor config --manifest "include app/*.py" --enable-suffix 1 --advanced 2
pyarmor build --platform musl.x86_64 -O ./obfuscated ./```

**Comment by jondy** [comment]
I mean 
```
echo "print('Hello')" > foo.py
rm -rf dist/
pyarmor obfuscate --advanced 2 --enable-suffix 1 --advanced 2 --platform musl.x86_64 --exact foo.py
```
Then run `python3 dist/foo.py` in docker.

Note that `pytransform.xxxx.so` is platform dependent, actually I don't know the right platform of your docker. This error `invalid ELF header` means the dynamic binary is not for this platform.

**Comment by davidwynter** [comment]
Not sure why pyarmor does not like you syntax, cut and pasted from your comment:

```
$ pyarmor obfuscate --advanced 2 --enable-suffix 1 --platform musl.x86_64 --exact foo.py
usage: pyarmor [-h] [-v] [-q] [-d] [--home HOME] [--boot BOOT]  ...
pyarmor: error: unrecognized arguments: foo.py
$ cat foo.py 
print('Hello')
```

**Comment by jondy** [comment]
Check the output `pyarmor -h`, and `pyarmor obfuscate -h` in your machine

**Comment by davidwynter** [comment]
Since 6.6.1 has the fix for platform input I cloned from github and build it.

```
david@david-desktop:~/PycharmProjects/pyarmor$ python3 setup.py bdist_wheel
```
Then install it 

```
david@david-desktop:~/PycharmProjects/pyarmor$ python3 install dist/pyarmor-6.6.1-py3-none-any.whl 
```
But there is something wrong with it

```
david@david-desktop:~/PycharmProjects/pyarmor$ pyarmor -h
usage: pyarmor [-h] [-v] [-q] [-d] [--home HOME] [--boot BOOT]  ...

PyArmor is a command line tool used to obfuscate python scripts,
bind obfuscated scripts to fixed machine or expire obfuscated scripts.
...
```

```
david@david-desktop:~/PycharmProjects/pyarmor$ pyarmor obsfuctate -h
usage: pyarmor [-h] [-v] [-q] [-d] [--home HOME] [--boot BOOT]  ...
pyarmor: error: argument : invalid choice: 'obsfuctate' (choose from 'obfuscate', 'o', 'licenses', 'l', 'pack', 'p', 'init', 'i', 'config', 'c', 'build', 'b', 'info', 'check', 'hdinfo', 'benchmark', 'capsule', 'register', 'download', 'runtime', 'help')
```

**Comment by jondy** [comment]
I find the problem. You're packing the scripts out of docker, but run the final executable in the docker.

You must pack the scripts in docker,  because docker is different platform, Alpine linux, in which libc is `musl`. In Ubuntu, it's `glibc`.

PyInstaller also doesn't support this cross platform packing.

**Comment by davidwynter** [comment]
Ok, this was a rework of my Docker file and supporting scripts, but pyarmor has a problem finding the license.lic file, even with explicit `export PYARMOR_LICENSE=/tmp/license.lic`. A minimal foo.py example will work, as it is under 32KB

Here is the relevant part of my Dockerfile

```
# Install pyarmor on image
COPY pyarmor/dist/pyarmor-6.6.1-py3-none-any.whl /tmp/
RUN pip install /tmp/pyarmor-6.6.1-py3-none-any.whl

# Copy app to obfuscate
COPY etl/app/customer/360t /tmp/app/customer/cust1/
COPY etl/app/core /tmp/app/core/
COPY etl/app/utils /tmp/app/utils/
COPY etl/app/etl /tmp/app/etl/
COPY etl/app/__init__.py /tmp/app/
COPY etl/app/customer/__init__.py /tmp/app/customer/
COPY etl/runtime/360t /tmp/runtime/cust1/
COPY etl/runtime/utils /tmp/runtime/utils/
COPY etl/runtime/__init__.py /tmp/runtime/
COPY etl/__init__.py /tmp/
COPY etl/shell/cust1/obfuscate_cust1.sh /tmp/
COPY etl/shell/license.lic /tmp
CMD ["export", "PYARMOR_LICENSE=/tmp/license.lic"]
RUN /tmp/obfuscate_cust1.sh
```

Here is my obfuscate_cust1.sh

```
#!/usr/bin/env bash
# Prepare the Cust1 etl obfuscation
rm -rf ./etl_obfuscated
mkdir -p ./etl_obfuscated
pyarmor init --src=../tmp --entry runtime/cust1/run_workflow_cust1.py
pyarmor config --manifest "include app/etl/*.py, include app/*.py, include app/utils/*.py, include runtime/cust1/*.py, \
include app/core/*.py, include app/customer/*.py, include app/customer/cust1/*.py, include runtime/utils/*.py, \
include runtime/__init__.py, include __init__.py" --enable-suffix 1 --advanced 2
pyarmor build --platform musl.x86_64 -O ./etl_obfuscated ./
```

Any ideas?

**Comment by davidwynter** [comment]
When I tried to obfuscate inside the image I got this:

```
Step 21/54 : RUN /tmp/obfuscate_cust1.sh
 ---> Running in bcc9d2e94471
INFO     Create cross platform libraries path /root/.pyarmor/platforms
INFO     Search library for platform: linux.x86_64
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r40.14/platforms/index.json
INFO     Write cached platform list file /root/.pyarmor/platforms/index.json
INFO     Found available libraries: ['linux.x86_64.7']
INFO     Target path for linux.x86_64.7: /root/.pyarmor/platforms/linux/x86_64/7
INFO     Downloading library file for linux.x86_64.7 ...
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r40.14/platforms/linux_x86_64/_pytransform.so
INFO     Writing target file: /root/.pyarmor/platforms/linux/x86_64/7/_pytransform.so
INFO     Download dynamic library linux.x86_64.7 OK
INFO     Generating public capsule ...
ERROR    The registered version would use private capsule.
         Please run `pyarmor register KEYFILE` to restore your private capsule.
ERROR    Could not generate private capsule.
INFO     Generating public capsule ...
ERROR    The registered version would use private capsule.
         Please run `pyarmor register KEYFILE` to restore your private capsule.
ERROR    Could not generate private capsule.
INFO     Generating public capsule ...
ERROR    The registered version would use private capsule.
         Please run `pyarmor register KEYFILE` to restore your private capsule.
ERROR    Could not generate private capsule.

```
So I need to generate the license file again. But that too had an issue

```
$ ls -la ~/.pyarmor/
total 20
drwxrwxr-x  3 david david 4096 Nov 23 15:39 .
drwxr-xr-x 53 david david 4096 Jan 14 15:35 ..
-rw-rw-r--  1 david david  380 Jan 22 18:00 license.lic
drwxrwxr-x  4 david david 4096 Jan 20 09:11 platforms
-rw-rw-r--  1 david david 2812 Nov 26 16:06 .pyarmor_capsule.zip
$ pyarmor register ~/.pyarmor/.pyarmor_capsule.zip 
$ pyarmor register ~/.pyarmor/.pyarmor_capsule.zip 
INFO     PyArmor Trial Version 6.6.1
INFO     Start to register keyfile: /home/david/.pyarmor/.pyarmor_capsule.zip
INFO     Save registration data to: /home/david/.pyarmor
INFO     Extracting license.lic
INFO     Extracting .pyarmor_capsule.zip
ERROR    There is no item named '.pyarmor_capsule.zip' in the archive
```
What am I missing?

**Comment by davidwynter** [comment]
I got this to work by installing pyarmor from a wheel file inside the container and using `pyarmor register tmp/pyrmor-regcode-1.txt` inside the docker container before obfuscating using the musl platform. Thx for you help.

**Comment by davidwynter** [comment]
I now have enerything obfuscated (product and 2 libraries used by the product) and have the export for PYTHONPATH set to locate the shared object. But it still cannot find it.

```
root@0242770cae19:/app# ls -l
total 1136
-rw-r--r-- 1 root root     926 Jan 25 18:06 __init__.py
drwxr-xr-x 6 root root    4096 Jan 25 18:06 app
drwxr-xr-x 1 root root    4096 Jan 25 18:06 configfiles
drwxr-xr-x 2 root root    4096 Jan 25 18:06 errorfiles
drwxr-xr-x 2 root root    4096 Jan 25 18:06 logs
-rw-r--r-- 1 root root 1132448 Jan 25 18:06 pytransform_vax_000925.cpython-37m-x86_64-linux-gnu.so
drwxr-xr-x 1 root root    4096 Jan 25 18:14 runtime
drwxr-xr-x 3 root root    4096 Jan 25 18:06 shell
root@0242770cae19:/app# export PYTHONPATH=/app
root@0242770cae19:/app# python3 -m runtime.360t.run_workflow
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/app/runtime/__init__.py", line 1, in <module>
    from pytransform_vax_000925 import pyarmor
ImportError: dynamic module does not define module export function (PyInit_pytransform_vax_000925)
```
Any ideas why PYTHONPATH is not working?

**Comment by VeNoMouS** [comment]
@davidwynter i came across this the other day, i had to remove `--enable-suffix`

**Comment by jondy** [comment]
It's a bug, I have reproduce it in Linux. As @VeNoMouS said, it works with remove `--enable-suffix` now. 
I'll fix it and release it with new version.

**Comment by davidwynter** [comment]
Same result for me after removing `--enable-suffix`:

```
root@e537bd3e77fd:/app# ls -l
total 1136
-rw-r--r-- 1 root root     871 Jan 26 08:06 __init__.py
drwxr-xr-x 1 root root    4096 Jan 26 08:29 app
drwxr-xr-x 1 root root    4096 Jan 26 08:06 configfiles
drwxr-xr-x 2 root root    4096 Jan 26 08:06 errorfiles
drwxr-xr-x 2 root root    4096 Jan 26 08:06 logs
-rw-r--r-- 1 root root 1132448 Jan 26 08:06 pytransform.cpython-37m-x86_64-linux-gnu.so
drwxr-xr-x 1 root root    4096 Jan 26 08:29 runtime
drwxr-xr-x 3 root root    4096 Jan 26 08:06 shell
root@e537bd3e77fd:/app# export PYTHONPATH=/app
root@e537bd3e77fd:/app# python3 -m runtime.cust1.run_workflow
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "</app/runtime/__init__.py>", line 2, in <module>
  File "<frozen runtime>", line 3, in <module>
ModuleNotFoundError: No module named 'app.pytransform'
```

**Comment by VeNoMouS** [comment]
should your `pytransform.cpython-37m-x86_64-linux-gnu.so` be in your `app` dir?

**Comment by davidwynter** [comment]
According to Jondy, so long as the PYHONPATH is set correctly it will find it. That is why I include the export in the above as proof it is set.

**Comment by davidwynter** [comment]
I tried to switch to the original mode, not Super. But it is not clear to me how this can be used with the 2 libraries I need to obfuscate. As there is no `--entry` function for a library. I could bundle the library code into the product, but that is a big change. At this point I have to use pyminifier as I have a deadline that I cannot meet with the pyarmor issues.

**Comment by davidwynter** [comment]
Nearly 2 weeks of trying to get this to work. Even simple foo.py example is not working. When we had a simple project with no libraries before Super mode with a v5 of pyarmor it worked, now there are repeated options across init, config, build and obfuscate, confusing and don't work in certain combinations.

Here is my latest attempt

```
#!/usr/bin/env bash
cd ../..
# Prepare the foo obfuscation
rm -rf ./obfuscated
mkdir -p ./obfuscated
pyarmor config --src=./test --entry foo.py --enable-suffix 0 --advanced 2
pyarmor build -O ./obfuscated ./
```

foo.py has `print('hello world')

Output
```
/obfuscated$ python3 foo.py
Traceback (most recent call last):
  File "foo.py", line 1, in <module>
    from pytransform_vax_000925 import pyarmor
ImportError: dynamic module does not define module export function (PyInit_pytransform_vax_000925)
```
Note that the enable-suffix has a bug, which is why I had to set it to 0. But the code still wants the suffix present! When I add it with `enable-suffix=1` I get the same error.

**Comment by jondy** [comment]
Hi Brother, I also spent a lot of time to support you, but most of time, what I told you is the basic knowledge of Python, not pyarmor.

Remember, every issue means something you don't know.

In the all of the issues you mentioned, only the `--enable-suffix=1` is pyarmor's bug. Because I don't know `elf` file how to search symbol by `.gnu.hash`, so yesterday I spend almost whole day to read the source of `glibc` to learn it.

For the other issues, it's you don't know
* Python how to import a module/package

So you need to learn what's Python PYTHON, how python imports a package, you can read the official document of Python or search engineer. I think it will not spent you more than one hour to understand it.

After you have this knowledge, you will find pyarmor has an option `--bootstrap` is useful for your case, and understand why I suggest you set PYTHONPATH. It's not my word, I just forward Python's word.

Anyway I'm sure now `--enable-suffix 0` works if you use pyarmor in right way.

It maybe helpful to read the description of command `obfuscate` in the man page
https://pyarmor.readthedocs.io/en/latest/man.html#obfuscate

It describe how `--enable-suffix` and `--bootstrap` work.

**Comment by VeNoMouS** [comment]
```
Anyway I'm sure now --enable-suffix 0 works if you use pyarmor in right way.

```

@jondy fwiw, i don't think you can do this, pyarmor errors if you try pass a argument with `--enable-suffix`

**Comment by jondy** [comment]
@VeNoMouS it's somewhat a bit confusing. In the command `obfuscate`, no argument for `--enable-suffix`. But for command `config`, it works. 

It's easy to get the hint by `pyarmor config -h`

**Comment by davidwynter** [comment]
You missed my point `pyarmor config` sets enable-suffix to 1 by default, `pyarmor obfuscate` sets it to 0. You documentation does not express the default settings, so people expect it to at least be consistent. I am not using docker and single python file to try to get it working. Also if you look closely at the output above it is trying to load `pytransform_vax_000925` after using `pyarmor config  --src=./test --entry foo.py --enable-suffix 0 --advanced 2` which looked like a bug to me.

**Comment by davidwynter** [comment]
To have a clear statement of the problem I will repeat my actions here:

```
(test) david@david-desktop:~/projects/etl$ echo $PYTHONPATH
/home/david/projects/etl/obfuscated
(test) david@david-desktop:~/projects/etl$ ls -l obfuscated/
total 1172
drwxrwxr-x 8 david david    4096 Jan 27 11:57 app
drwxrwxr-x 5 david david    4096 Jan 27 11:57 lib_data
drwxrwxr-x 8 david david    4096 Jan 27 11:57 math_lib
-rw-rw-r-- 1 david david     871 Jan 27 11:57 __init__.py
-rw-rw-r-- 1 david david 1132448 Jan 27 11:57 pytransform.cpython-37m-x86_64-linux-gnu.so
drwxrwxr-x 5 david david    4096 Jan 27 11:57 runtime
(test) david@david-desktop:~/projects/etl$ cd obfuscated/
(test) david@david-desktop:~/projects/etl/obfuscated$ python3 -m runtime.cust1.run_workflow_cust1
Traceback (most recent call last):
  File "/home/david/anaconda3/envs/test/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/david/anaconda3/envs/test/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "</home/david/projects/etl/obfuscated/runtime/__init__.py>", line 2, in <module>
  File "<frozen runtime>", line 3, in <module>
ModuleNotFoundError: No module named 'app.pytransform'

```

The environment variable PYTHONPATH is set so that the shared object can be located. Why is it looking for the package `app.pytransform`? I thought it would be `pytransform`.

**Comment by jondy** [comment]
Please check the content `/home/david/projects/etl/obfuscated/runtime/__init__.py`, it will tell you the answer.

**Comment by davidwynter** [comment]
It is trying to import from `pytransform`. So why does the build process put the shared object file in the base directory, in this case `
`obfuscated`?

**Comment by jondy** [comment]
The command `config` only changes the project options list in the command line, if you don't pass option `--advanced`, It will keep the last updated value.

The idea of `.pyarmor_config` is  used to save project settings, once project is created, then run `build` only.

> ImportError: cannot import name 'pyarmor' from 'pytransform' (unknown location)

This exception means you're run the super mode obfuscated scripts, but import the non-super mode runtime files `pytransform/__init__.py`

You need understand the runtime file of super model `--advanced 2` is different from non-super mode, please do a test in five minutes to understand super mode
```
mkdir learning-super-mode
cd learning-super-mode
echo 'print("hello")' > foo.py
pyarmor obfuscate --advanced 2 foo.py

ls dist/
cat dist/foo.py
python dist/foo.py
```
 
You can also do a test in 5 minutes to learn non-super mode
```
mkdir learning-non-super-mode
cd learning-non-super-mode
echo 'print("hello")' > foo.py
pyarmor obfuscate  foo.py

ls dist/
cat dist/foo.py
python dist/foo.py
```

Compare the file list in the `dist` and  the content in the `dist/foo.py` in different mode.

You also can add extra option `enable-suffix` and `bootstrap` to do another test, and compare the difference in different mode

And look through
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html

Especially section
https://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#key-points-to-use-obfuscated-scripts

**Comment by davidwynter** [comment]
I understand the difference. The issue here is that I remove the directory into which I output the obfuscated scripts every time I run to ensure there are no artefacts from the previous run. It should just work I understand, but the errors I am getting are seen in a fresh obfuscation.

Here is the output from your learning-super-mode script above

```
$ /bin/bash /home/david/fairxchange/etl/shell/360t/supermode.sh
INFO     PyArmor Version 6.6.1
INFO     Target platforms: Native
WARNING  The core library excepted version is r40.14, but got r39.13 from platform list file /home/david/anaconda3/envs/fairx/lib/python3.7/site-packages/pyarmor/platforms/index.json
INFO     Update target platforms to: ['linux.x86_64.11.py37']
INFO     Source path is "/home/david/fairxchange/etl/shell/360t/learning-super-mode"
INFO     Entry scripts are ['foo.py']
INFO     Use cached capsule /home/david/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 2
INFO     Super mode is True
INFO     Generating super runtime library to dist
WARNING  The core library excepted version is r40.14, but got r39.13 from platform list file /home/david/anaconda3/envs/fairx/lib/python3.7/site-packages/pyarmor/platforms/index.json
INFO     The platform linux.x86_64.11.py37 is out of date
INFO     Search library for platform: linux.x86_64.11.py37
WARNING  The core library excepted version is r40.14, but got r39.13 from platform list file /home/david/anaconda3/envs/fairx/lib/python3.7/site-packages/pyarmor/platforms/index.json
INFO     Found available libraries: ['linux.x86_64.11.py37']
INFO     Target path for linux.x86_64.11.py37: /home/david/.pyarmor/platforms/linux/x86_64/11/py37
INFO     Downloading library file for linux.x86_64.11.py37 ...
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r40.14/platforms/linux.x86_64.11.py37/pytransform.cpython-37m-x86_64-linux-gnu.so
ERROR    Verify dynamic library failed
cat: dist/foo.py: No such file or directory
python3: can't open file 'dist/foo.py': [Errno 2] No such file or directory
```

**Comment by davidwynter** [comment]
I found the issue. pyarmor has bug if the entry class/function is not in the base package. I found it through a process of experimentation. 

This works:

```
pyarmor init --src="." --entry run_workflow_cust1.py
```

This does not:

```
pyarmor init --src="." --entry runtime/cust1/run_workflow_cust1.py```
