### ISSUE TITLE
Support for Apple Silicon M1

### ISSUE THREAD

**Issue by tede12** [dashingsoft/pyarmor#470]
I tried to register my key with pyarmor and I got this error:
```bash
$pyarmor register /Users/user/Desktop/pyarmor-regfile-xxxx.zip 
INFO     Create pyarmor home path: /Users/user/.pyarmor
INFO     Create trial license file: /Users/user/.pyarmor/license.lic
INFO     Create cross platform libraries path /Users/user/.pyarmor/platforms
INFO     Search library for platform: darwin.aarch64
ERROR    Unsupport platform darwin.aarch64
ERROR    No available library for this platform
```

these are mine computer specifics
```
system name: Darwin
machine: arm64
processor: arm
aliased terse platform: macOS-11.2.1
```

Is it possible to add this platform?

**Comment by jondy** [comment]
Please upgrade pyarmor to the latest version v6.6.1

**Comment by tede12** [comment]
Thanks I thought I have the latest version.
But I can't register again. (pip says that I'm in v6.6.1)

```
pyarmor --version
INFO     Search library for platform: darwin.aarch64
INFO     Found available libraries: ['darwin.aarch64.3']
INFO     Target path for darwin.aarch64.3: /Users/user/.pyarmor/platforms/darwin/aarch64/3
INFO     Downloading library file for darwin.aarch64.3 ...
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r40.14/platforms/ios.arm64.3/_pytransform.dylib
INFO     Writing target file: /Users/user/.pyarmor/platforms/darwin/aarch64/3/_pytransform.dylib
INFO     Download dynamic library darwin.aarch64.3 OK
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/venvs/bin/pyarmor", line 8, in <module>
    sys.exit(main_entry())
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1562, in main_entry
    main(sys.argv[1:])
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1528, in main
    args = parser.parse_args(argv)
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/polyfills/argparse.py", line 1695, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/polyfills/argparse.py", line 1727, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/polyfills/argparse.py", line 1933, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/polyfills/argparse.py", line 1873, in consume_optional
    take_action(action, args, option_string)
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/polyfills/argparse.py", line 1801, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/polyfills/argparse.py", line 1018, in __call__
    version = version()
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/pyarmor.py", line 1023, in _version_action
    pytransform_bootstrap()
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/utils.py", line 148, in pytransform_bootstrap
    pytransform.pyarmor_init(platid=platid)
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/pytransform.py", line 343, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid, suffix, advanced)
  File "/Users/user/PycharmProjects/venvs/lib/python3.8/site-packages/pyarmor/pytransform.py", line 311, in _load_library
    m = cdll.LoadLibrary(filename)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/user/.pyarmor/platforms/darwin/aarch64/3/_pytransform.dylib, 6): no suitable image found.  Did find:
        /Users/user/.pyarmor/platforms/darwin/aarch64/3/_pytransform.dylib: mach-o, but not built for platform macOS
        /Users/user/.pyarmor/platforms/darwin/aarch64/3/_pytransform.dylib: mach-o, but not built for platform macOS
```

**Comment by jondy** [comment]
Does this command work?
`PYARMOR_PLATFORM=darwin.aarch64.0 pyarmor --version`

**Comment by jondy** [comment]
Here is pre-release version with new libraries for Apple Silicon, please check it works or not
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-6.6.2.zip
```

**Comment by tede12** [comment]
Thank you It seems work

**Comment by jondy** [comment]
Note that the pre-release version may be changed from time to time to fix new bugs, please update it if it doesn't work. And once the new version is released in PyPI, please remove the pre-release version, install the latest pyarmor from PyPi.
