### ISSUE TITLE
pyarmor django:  pyarmor pack -s wsgi.spec kfquantum/wsgi.py error

### ISSUE THREAD

**Issue by adamxy** [dashingsoft/pyarmor#477]
[dist]$ ./wsgi
Traceback (most recent call last):
  File "django/apps/config.py", line 178, in get_model
KeyError: 'userinfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "django/contrib/auth/__init__.py", line 165, in get_user_model
  File "django/apps/registry.py", line 210, in get_model
  File "django/apps/config.py", line 181, in get_model
LookupError: App 'users' doesn't have a 'UserInfo' model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<dist/obf/wsgi.py>", line 3, in <module>
  File "<frozen wsgi>", line 16, in <module>
  File "django/core/wsgi.py", line 12, in get_wsgi_application
  File "django/__init__.py", line 24, in setup
  File "django/apps/registry.py", line 122, in populate
  File "django/contrib/admin/apps.py", line 24, in ready
  File "django/contrib/admin/__init__.py", line 26, in autodiscover
  File "django/utils/module_loading.py", line 47, in autodiscover_modules
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "django/contrib/auth/admin.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "django/contrib/auth/forms.py", line 20, in <module>
  File "django/contrib/auth/__init__.py", line 170, in get_user_model
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'users.UserInfo' that has not been installed
[28597] Failed to execute script wsgi
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

settings config  AUTH_USER_MODEL=user.UserInfo
python3 manage.py runserver Ok

**Comment by jondy** [comment]
Please first refer to
https://pyarmor.readthedocs.io/en/latest/questions.html

Make sure Pyinstaller can pack the plain script and the final executable works.

**Comment by adamxy** [comment]
I've fixed it, not the PyArmor bug
