### ISSUE TITLE
Using obfuscated library inside obfuscated project

### ISSUE THREAD

**Issue by LamaramaLuisa** [dashingsoft/pyarmor#497]
Hey,

is there a way to use a obfuscated library inside obfuscated project with two diffent licesens?
We are obfuscating our libray with one license and our project with another license. When we try to run the project we run into an error message:

```
Traceback (most recent call last):
  File "<installer\bin\obf\main.py>", line 3, in <module>
  File "<frozen main>", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\develop\jnk\workspace\rvice_tools_config_editor_master\.nox\prod\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "<backend\mainhandler.py>", line 1, in <module>
  File "<frozen backend.mainhandler>", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\develop\jnk\workspace\rvice_tools_config_editor_master\.nox\prod\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "<rocket_rest_server\__init__.py>", line 3, in <module>
RuntimeError: Marshal loads failed
[1840] Failed to execute script main
```

The rocket_rest_server is our obfuscated library wich we use inside the other project.
If we use the same license for the library and the project it is working. So is there a way to use different licenses in one project?

**Comment by jondy** [comment]
The obfuscation option `--enable-suffix` is exact for this, refer to
https://pyarmor.readthedocs.io/en/latest/advanced.html#solve-conflicts-with-other-obfuscated-libraries

**Comment by LamaramaLuisa** [comment]
But this option is only available when using `pyarmor obfuscate` and not for `pyarmor pack` right?

**Comment by jondy** [comment]
Please refer to man page of command `pack` in the pyarmor documentation
