### ISSUE TITLE
pyarmor corrupts scripts using  cryptography.fernet module

### ISSUE THREAD

**Issue by dallascao** [dashingsoft/pyarmor#509]
When encrypting scripts containing cryptography.fernet module using the default parameters, the resulting program get corrupted with the following errors:

Traceback (most recent call last):
  File "<volcano.py>", line 3, in <module>
  File "<frozen volcano>", line 199, in <module>
  File "<frozen volcano>", line 120, in crypt
  File "C:\Users\Mac\Documents\GT4T_win\python_portable\GT4T_32\lib\site-packages\cryptography\fernet.py", line 32, in __init__
    key = base64.urlsafe_b64decode(key)
  File "base64.py", line 133, in urlsafe_b64decode
  File "base64.py", line 87, in b64decode
binascii.Error: Incorrect padding

To reproduce the error, use this pseudo code.:

class crypt:
    """
    all crypt related functions
    """
    from cryptography.fernet import Fernet
    fernet = Fernet(b'iMC2MSURpz9e8bCiKg9YMaI4Z26CSSU7sgW5NjE8Ito=')
    @staticmethod
    def encryptStr(theStr):
        return crypt.fernet.encrypt(theStr.encode())
    @staticmethod
    def decryptStr(bStr):
        return crypt.fernet.decrypt(bStr).decode()
#end of functions

print(crypt.encryptStr("I like this game."))

**Comment by jondy** [comment]
pyarmor 加密后的脚本基本不会改变原来的业务逻辑，请首先确认没有加密之前该脚本能运行吗？

如果可以的话，使用 `-d` 参数运行加密脚本，有什么提示吗？例如 `python -d dist/foo.py`

另外，务必确认运行加密脚本使用的 python 的版本和加密脚本使用的 python 版本是一样的
