### ISSUE TITLE
使用插件 check_ntp_time加密后，启动程序报错：'NoneType' object has no attribute '_handle'

### ISSUE THREAD

**Issue by tonglei100** [dashingsoft/pyarmor#534]
1. 使用插件加密
```shell
pyarmor obfuscate --recursive --plugin check_ntp_time --with-license outer --output code code/__init__.py
```
2. 生成license
```shell
pyarmor licenses -x 20211230 code-001
```
3. 拷贝license到dist
4. 执行代码，报错如下：

```python
D:\PyArmor\dist>python start.py
Traceback (most recent call last):
  File "start.py", line 1, in <module>
    from code import Test
  File "<D:\PyArmor\dist\code\__init__.py>", line 3, in <module>
  File "<frozen code>", line 510, in <module>
  File "<frozen code>", line 490, in check_ntp_time
  File "<frozen code>", line 483, in _get_license_data
AttributeError: 'NoneType' object has no attribute '_handle'
```

```shell
>pyarmor info
INFO     PyArmor Trial Version 6.7.2
INFO     Python 3.8.3
ERROR    [Errno 2] No such file or directory: '.pyarmor_config'
```

**Comment by jondy** [comment]
我加密了一个简单脚本 `foo.py` ，
```
# {PyArmor Plugins}
# PyArmor Plugin: check_ntp_time()
if __name__ == '__main__':
    print('Hello')
```

```
pyarmor obfuscate --with-license outer --plugin check_ntp_time foo.py
pyarmor licenses -x 20201230 code-001
cp licenses/code-001/license.lic dist
cd dist
python foo.py 
```
 这个插件是工作正常的

插件也是一个普通脚本，只不过是为了不影响原来代码的执行，在加密的时候才插入到脚本里面的。请参考
https://pyarmor.readthedocs.io/zh/latest/pytransform.html
这里对插件进行调试，报这个错误是因为插件使用了不正确的 `pytransform` ，至于哪里不正确，请参考上面的能够正常运行的例子，对比自己的代码去发现问题

**Comment by tonglei100** [comment]
单独的 foo.py 脚本是可以的，但是用包的就不行了

目录如下：
```
test\
    __init__.py
    foo.py
start.py
```
其中，__init__.py 中插入插件代码

然后加密，授权，执行
```shell
pyarmor obfuscate --with-license outer --plugin check_ntp_time --output dist/test test/__init__.py
pyarmor licenses -x 20201230 code-001
cp licenses/code-001/license.lic dist
cp start.py dist
cd dist
python start.py
```
start.py 只是导入foo
```python
from test import foo
```

还是报一样的错
```shell
D:\PyArmor\code\dist>python start.py
Traceback (most recent call last):
  File "start.py", line 1, in <module>
    from test import foo
  File "<D:\PyArmor\code\dist\test\__init__.py>", line 3, in <module>
  File "<frozen test>", line 484, in <module>
  File "<frozen test>", line 482, in check_ntp_time
  File "<frozen test>", line 475, in _get_license_data
AttributeError: 'NoneType' object has no attribute '_handle'
```

**Comment by jondy** [comment]
首先了解一下加密脚本，特别是运行辅助文件和使用加密脚本的基本原则
https://pyarmor.readthedocs.io/zh/latest/understand-obfuscated-scripts.html

然后需要基于 pyarmor 源码中提供 `check_ntp_time.py` 编写自己的插件，主要是需要导入正确的 `pytransform` 模块，因为默认的插件代码是导入的 `pytransform` 和你模块使用的不是同一个 `pytransform`，所以这个文件需要修改来适配你的加密代码。

你比较一下 `dist/foo.py` 和 `dist/test/__init__.py` 就知道区别所在了

**Comment by jondy** [comment]
需要明白下面几点
1. 加密脚本需要运行辅助模块 `pytransform`
2. 插件也需要导入这个运行辅助模块，并调用其中的功能

导致问题的原因是 加密脚本和插件导入的 `pytransform` 不是同一个，因为运行环境有多个

解决方案是定制自己的 `check_ntp_time.py`，pyarmor 自带的脚本不适用于加密包的这种情况

**Comment by tonglei100** [comment]
解决了
 在 check_ntp_time.py 中把

```python
from pytransform import
```
改为：
```python
from test.pytransform import
```
这样是正确的方式吗

**Comment by jondy** [comment]
脚本你自己随便写吧，只要能实现功能就行。不过，修改为 `from .pytransform import` 似乎更好一些
