### ISSUE TITLE
FileNotFoundError after "pyarmor pack"

### ISSUE THREAD

**Issue by rejjin** [dashingsoft/pyarmor#544]
Hello. I do not know if this is a pyarmor problem, or a pyinstaller problem, but the result is an error:

```
$ start.exe
Traceback (most recent call last):
  File "<dist\obf\start.py>", line 3, in <module>
  File "<frozen start>", line 81, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "orderedmultidict\__init__.py", line 19, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\AppData\\Local\\Temp\\_MEI100362\\orderedmultidict\\__version__.py'
[7684] Failed to execute script start
```

(I don't use orderedmultidict, it's some kind of third-party library dependency)

For build I use:
```
pyarmor pack --clean -e " --onefile " -x " --exact " "./start.py"
```
I try --debug option, all works fine with obfuscated script, but cant start from finish build, after pyinstaller works.

Thank you.

**Comment by rejjin** [comment]
I found the problem: https://github.com/gruns/orderedmultidict/issues/25

This does not apply to pyarmor.
