### ISSUE TITLE
Pi Zero W Illegal Instruction

### ISSUE THREAD

**Issue by gb160** [dashingsoft/pyarmor#576]
Hello Im receiving the following error on Pi Zero WH, running on DietPi, the same error occurs on Raspios Lite also, both the latest versions.

```
DEBUG    PyArmor installation path: /usr/local/lib/python3.9/dist-packages/pyarmor
DEBUG    PyArmor home path: /root/.pyarmor
DEBUG    Native platform is linux.armv6
DEBUG    Search dynamic library in the path: /usr/local/lib/python3.9/dist-packages/pyarmor/platforms
DEBUG    Search dynamic library in the path: /root/.pyarmor/platforms
DEBUG    Found available dynamic library linux/armv6/3
Illegal instruction
```
I searched the issues quickly and it seems this is a known issue, which is a real shame as I would be happy to purchase the full license if I can get this up and running.

I would be happy with just a workaround as long as I can get something working on the Pi Zero WH.

Any input would be greatly appreciated.

**Comment by jondy** [comment]
How about using `--platform linux.armv6.0`?

**Comment by gb160** [comment]
Hi buddy, thanks for getting back to me

```root@DietPi:~/g# pyarmor obfuscate g.py --platform linux.armv6.0
INFO     Create pyarmor home path: /root/.pyarmor
INFO     Create trial license file: /root/.pyarmor/license.lic
INFO     Create cross platform libraries path /root/.pyarmor/platforms
INFO     Search library for platform: linux.armv6
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/index.json
INFO     Write cached platform list file /root/.pyarmor/platforms/index.json
WARNING  The trial version could not download the latest core libraries, tag r41.15a is always used
WARNING  The core library excepted version is r45.19, but got r41.15a from platform list file /root/.pyarmor/platforms/index.json
INFO     Found available libraries: ['linux.armv6.3']
INFO     Target path for linux.armv6.3: /root/.pyarmor/platforms/linux/armv6/3
INFO     Downloading library file for linux.armv6.3 ...
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/linux.armv6.3/_pytransform.so
INFO     Writing target file: /root/.pyarmor/platforms/linux/armv6/3/_pytransform.so
INFO     Download dynamic library linux.armv6.3 OK
Illegal instruction
root@DietPi:~/g# ```

**Comment by jondy** [comment]
Run pyarmor by this way
```
export PYARMOR_PLATFORM=linux.armv6.0
pyarmor obfuscate foo.py
```

**Comment by gb160** [comment]
We have progress !

OK, I can successfully obfuscate on the Pi zero now, and execute the obfuscated scripts successfully.

However I have one last problem...I wish to execute the obfuscated scripts on very lite custom linux distribution.
So I obfuscated on Raspios lite, then copied the entire dist folder over to my custom linux distribution, but when executing the obfuscated script I get:

```
# python3 -d dist/test.py
Load /root/dist/pytransform/_pytransform.so failed:
File not found
Traceback (most recent call last):
  File "/root/dist/test.py", line 2, in <module>
    pyarmor_runtime()
  File "/root/dist/pytransform/__init__.py", line 370, in pyarmor_runtime
    pyarmor_init(path, is_runtime=1, suffix=suffix, advanced=advanced)
  File "/root/dist/pytransform/__init__.py", line 361, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid, suffix, advanced)
  File "/root/dist/pytransform/__init__.py", line 329, in _load_library
    m = cdll.LoadLibrary(filename)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
OSError: File not found
```

```
# ls -l /root/dist/pytransform
total 1535
-rw-------    1 root     root         13383 Jan  1 00:03 __init__.py
-rw-------    1 root     root         11648 Jan  1 00:04 __init__.pyc
drwxr-xr-x    2 root     root          1024 Jan  1 00:03 __pycache__
-rw-------    1 root     root       1543776 Jan  1 00:04 _pytransform.so
```


obviously I checked that the _unobfuscated_ script runs fine on my custom linux distribution, no problem there, so I guess there's some dependency that is not being met on my custom linux distribution.

Any idea what my custom linux distribution is missing? I appreciate that you might not be able to offer more support on this, but I just need to check that PyArmor is suitable for my needs so im testing with a tiny test script, my final script that I wish to run is much bigger so I will need the full license for that.

**Comment by jondy** [comment]
It seems the dynamic library has no `x` permission, try to `chmod +x _pytransform.so`
```
-rw-------    1 root     root       1543776 Jan  1 00:04 _pytransform.so
```

**Comment by gb160** [comment]
Yes I did try this yesterday, as a long shot but the result is the same :(

```
# chmod +x -R dist
# ls -l ./*
total 3
drwxr-xr-x    3 root     root          1024 Jan  1 00:06 pytransform
-rwx--x--x    1 root     root          1169 Jan  1 00:06 test.py
# ls -l ./*/*
-rwx--x--x    1 root     root          1169 Jan  1 00:06 ./dist/test.py

./dist/pytransform:
total 1523
-rwx--x--x    1 root     root         13383 Jan  1 00:06 __init__.py
drwxr-xr-x    2 root     root          1024 Jan  1 00:06 __pycache__
-rwx--x--x    1 root     root       1543776 Jan  1 00:06 _pytransform.so

```


```
# python3 -d dist/test.py
Load /root/dist/pytransform/_pytransform.so failed:
File not found
Traceback (most recent call last):
  File "/root/dist/test.py", line 2, in <module>
    pyarmor_runtime()
  File "/root/dist/pytransform/__init__.py", line 370, in pyarmor_runtime
    pyarmor_init(path, is_runtime=1, suffix=suffix, advanced=advanced)
  File "/root/dist/pytransform/__init__.py", line 361, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid, suffix, advanced)
  File "/root/dist/pytransform/__init__.py", line 329, in _load_library
    m = cdll.LoadLibrary(filename)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
OSError: File not found
```


Does the python version on the two systems have to match exactly?

**Comment by jondy** [comment]
Check it by `ldd`
```
ldd dist/_pytransform.so
```

**Comment by gb160** [comment]
OK mate, the `_pytransform.so` file is in the `pytransform` directory, and I get this:

```
# ldd dist/pytransform/_pytransform.so
checking sub-depends for 'not found'
	libc.so.6 => not found (0x00000000)
	not a dynamic executable

```

**Comment by jondy** [comment]
This is the problem. `_pytransform.so` requires `glibc`, but your system is not built with glibc. By default the embedded system uses `uclibc`. 

The solution is to rebuild your system with glibc, generally you can select which c is used when building your system.

**Comment by gb160** [comment]
Thanks buddy, I've built with glibc now and am getting the `RuntimeError: Marshal loads failed` error, which I think I read is caused by a python version mismatch.
I know the python version is different on my raspios install, so tomorrow I will upgrade that to python 3.9, and im hoping all will be working fine.

Thanks again for your support on this issue, I will be purchasing full license as my bigger scripts will require it 👍

**Comment by gb160** [comment]
Just for closure, after rebuilding the embedded build with crib,and matching the python versions, Pyarmor is working fine on my custom linux system.
