### ISSUE TITLE
Build charmap' codec can't decode byte ERROR 

### ISSUE THREAD

**Issue by emrecpp** [dashingsoft/pyarmor#587]
**Python version**: 3.9.7
**Pyarmor version**: Purchased 6.8.0
**Command**: pyarmor -d build C:\Users\Emre\.pyarmor\projects\project-3\\.pyarmor_config
Main file has: **# -*- coding: utf-8 -*-** on first line. 
**I know the problem is in my code.**
My code: 
`store = Storage(            b'\xa2|||||}\xa0\x9a\xb4\x8f\xac\xa0\x8c\xaa\x83\x86q\xb4ms~\xab\xa9\x95\x9f\xae\x86\x8b\x81\xa8h\x9a\x91\xa8\x94|\x9a\x92\xa8l\x8d\x80\x9c\x83\x8a\xa7l\xab\x9eq\xa8h\xb4\xa4')`
![image](https://user-images.githubusercontent.com/29755479/135588608-c777de7d-1173-42f0-a3c5-63d0fef1c53c.png)

**Interesting**: When I add **-B** argument ( pyarmor -d build C:\Users\Emre\.pyarmor\projects\project-3\\.pyarmor_config -B), pyarmor buildes successfully.

I have hardcoded bytes and own decrypt function. I need to use bytes like "\xab\xcd\x9e".
**Pyarmor Error**: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9e in position 3923: character maps to <undefined>
**Error Output:**
> INFO     Save obfuscated scripts to "C:\Users\Emre\Desktop\iProCafe\dist"
INFO     Read product key from capsule
INFO     Enable increment build
INFO     Search scripts from C:\Users\Emre\Desktop\iProCafe
INFO     Obfuscate scripts with mode:
INFO     Obfuscating the whole module is on
INFO     Obfuscating each function is on
INFO     Autowrap each code object mode is on
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is off
INFO     0 scripts has been obfuscated
INFO     Copy entry script C:\Users\Emre\Desktop\iProCafe\Main.py to C:\Users\Emre\Desktop\iProCafe\dist\Main.py
INFO     Insert bootstrap code to entry script C:\Users\Emre\Desktop\iProCafe\dist\Main.py
Traceback (most recent call last):
  File "C:\Users\Emre\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Emre\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Emre\AppData\Local\Programs\Python\Python39\Scripts\pyarmor.exe\__main__.py", line 7, in <module>
  File "C:\Users\Emre\AppData\Local\Programs\Python\Python39\lib\site-packages\pyarmor\pyarmor.py", line 1568, in main_entry
    main(sys.argv[1:])
  File "C:\Users\Emre\AppData\Local\Programs\Python\Python39\lib\site-packages\pyarmor\pyarmor.py", line 1560, in main
    args.func(args)
  File "C:\Users\Emre\AppData\Local\Programs\Python\Python39\lib\site-packages\pyarmor\pyarmor.py", line 382, in _build
    make_entry(project.entry, project.src, soutput,
  File "C:\Users\Emre\AppData\Local\Programs\Python\Python39\lib\site-packages\pyarmor\utils.py", line 441, in make_entry
    _make_entry(filename, rpath, relative=relative, shell=shell,
  File "C:\Users\Emre\AppData\Local\Programs\Python\Python39\lib\site-packages\pyarmor\utils.py", line 385, in _make_entry
    lines = f.readlines()
  File "C:\Users\Emre\AppData\Local\Programs\Python\Python39\lib\encodings\cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9e in position 3923: character maps to <undefined>

**Probably I need to use utf-8 instead cp1254. But I don't know how to do it.**

**Comment by jondy** [comment]
I don't think the following code will result in `UnicodeDecodeError`
```
store = Storage( b'\xa2|||||}\xa0\x9a\xb4\x8f\xac\xa0\x8c\xaa\x83\x86q\xb4ms~\xab\xa9\x95\x9f\xae\x86\x8b\x81\xa8h\x9a\x91\xa8\x94|\x9a\x92\xa8l\x8d\x80\x9c\x83\x8a\xa7l\xab\x9eq\xa8h\xb4\xa4')
```
pyarmor doesn't touch literal bytes.

**Comment by emrecpp** [comment]
When I rename UTF_8.py to CP1254.py, bug fixes. But I am looking other ways to fix.
Path: C:\Users\Username\AppData\Local\Programs\Python\Python39\Lib\encodings\UTF_8.py

**Comment by jondy** [comment]
Since encode of the script is `cp1254`, why not change encoding line to cp1254 in the main script?
```patch
- # -- coding: utf-8 --
- # -- coding: cp1254 --
```
