### ISSUE TITLE
--enable-suffix raises Failed to add symbol suffix ERROR for Non-Super Mode

### ISSUE THREAD

**Issue by tkornuta-nvidia** [dashingsoft/pyarmor#612]
**Description**
```
pyarmor runtime --enable-suffix --advanced 2 -O dist/shared
```

doesn't work for advanced mode < 2, e.g.:

```
(eff) tkornuta@tkornuta-desktop:~/workspace/eff$ pyarmor runtime --enable-suffix --advanced 0 -O dist/shared
INFO     PyArmor Version 6.8.1
INFO     Python 3.7.10
INFO     Generating runtime files to dist/shared/pytransform_vax_xxx
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying xxx
INFO     Rename it to _pytransform_vax_xxx.so
INFO     Patch library dist/shared/pytransform_vax_xxx/_pytransform_vax_xxx.so
INFO     Patch library file OK
ERROR    Failed to add symbol suffix for library dist/shared/pytransform_vax_xxx/_pytransform_vax_xxx.so
```

**Comment by jondy** [comment]
Please run pyarmor with `-d` and provide the full trace back log
```
pyarmor -d runtime --enable-suffix --advanced 0 -O dist/shared
```

**Comment by tkornuta-nvidia** [comment]
Here you go:

```
(eff) tkornuta@tkornuta-desktop:~/workspace/eff$ pyarmor -d runtime --enable-suffix --advanced 0 -O dist/shared
DEBUG    PyArmor installation path: xxx/lib/python3.7/site-packages/pyarmor
DEBUG    PyArmor home path: /home/tkornuta/.pyarmor
DEBUG    Native platform is linux.x86_64
DEBUG    Search dynamic library in the path: xxx/python3.7/site-packages/pyarmor/platforms
DEBUG    Loaded dynamic library: xxx/python3.7/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
DEBUG    The version of core library is (45, 19, 7)
INFO     PyArmor Version 6.8.1
INFO     Python 3.7.10
INFO     Generating runtime files to dist/shared/pytransform_vax_yyy
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying xxx/python3.7/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
INFO     Rename it to _pytransform_vax_yyy.so
INFO     Patch library dist/shared/pytransform_vax_yyy/_pytransform_vax_yyy.so
DEBUG    Patching dist/shared/pytransform_vax_yyy/_pytransform_vax_yyy.so
DEBUG    Found pattern at c4384
DEBUG    Patch 261 bytes from c43a4
DEBUG    Patch 270 bytes from c44a9
DEBUG    Patch 404 bytes from c45b7
INFO     Patch library file OK
Traceback (most recent call last):
  File "xxx/bin/pyarmor", line 33, in <module>
    sys.exit(load_entry_point('pyarmor', 'console_scripts', 'pyarmor')())
  File "xxx/python3.7/site-packages/pyarmor/pyarmor.py", line 1572, in main_entry
    main(sys.argv[1:])
  File "xxx/python3.7/site-packages/pyarmor/pyarmor.py", line 1564, in main
    args.func(args)
  File "xxx/python3.7/site-packages/pyarmor/pyarmor.py", line 930, in _runtime
    suffix=suffix, supermode=supermode)
  File "xxx/python3.7/site-packages/pyarmor/utils.py", line 620, in make_runtime
    copy3(libfile, output)
  File "xxx/python3.7/site-packages/pyarmor/utils.py", line 605, in copy3
    data = _patch_extension(target, keylist, suffix)
  File "xxx/python3.7/site-packages/pyarmor/utils.py", line 1470, in _patch_extension
    % filename)
RuntimeError: Failed to add symbol suffix for library dist/shared/pytransform_vax_001221/_pytransform_vax_001221.so
```

hope it helps

**Comment by jondy** [comment]
Please upgrade the latest version 7.0.1, it has been fixed in this version.
