### ISSUE TITLE
Application is not building

### ISSUE THREAD

**Issue by NeilRiver** [dashingsoft/pyarmor#618]
1. Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
2. Windows 10
3. PyArmor Trial Version 7.0.2

code 223 lines 

if i type "pyinstaller main.py" all be ok, and i will can launch .exe

if i type "pyarmor pack main.py" i got error 

```
Traceback (most recent call last):
  File "gspread\client.py", line 120, in open
  File "gspread\utils.py", line 88, in finditem
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<dist\obf\main.py>", line 3, in <module>
  File "<frozen main>", line 14, in <module>
  File "gspread\client.py", line 130, in open
gspread.exceptions.SpreadsheetNotFound
[5132] Failed to execute script 'main' due to unhandled exception!
```

**Comment by jondy** [comment]
Please find the solution here
https://pyarmor.readthedocs.io/en/latest/questions.html#the-final-bundle-does-not-work
