### ISSUE TITLE
混淆后执行报错

### ISSUE THREAD

**Issue by asasas234** [dashingsoft/pyarmor#624]
您好，我的是Mac系统，混淆后执行报如下错误
```
Traceback (most recent call last):
  File "/Users/lizhibo/PycharmProjects/dist/main.py", line 1, in <module>
    from pytransform import pyarmor
ImportError: dlopen(/Users/lizhibo/PycharmProjects/dist/pytransform.so, 0x0002): Library not loaded: @rpath/Frameworks/Python.framework/Versions/3.9/Python
  Referenced from: /Users/lizhibo/PycharmProjects/dist/pytransform.so
  Reason: tried: '/Users/lizhibo/PycharmProjects/dist/../Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/Users/lizhibo/PycharmProjects/dist/../Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/usr/local/lib/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/usr/local/lib/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.9/Python' (no such file)
```

我的混淆方式如下
`pyarmor obfuscate --no-cross-protection  --advanced 2 LearnPython`
请问该如何解决？

**Comment by asasas234** [comment]
我通过执行install_name_tool -add_rpath /usr/local/Cellar/python@3.9/3.9.7_1 ~/PycharmProjects/dist/pytransform.so 后，在执行python3 main.py 得到如下错误
```
Traceback (most recent call last):
  File "/Users/lizhibo/PycharmProjects/dist/main.py", line 1, in <module>
    from pytransform import pyarmor
RuntimeError: Check license failed, Invalid input packet.
```

**Comment by asasas234** [comment]
版本是7.0.2

**Comment by asasas234** [comment]
@jondy 有空麻烦帮忙看看谢谢

**Comment by jondy** [comment]
试用版本的问题，请参考 #623
