### ISSUE TITLE
Do not support numexpr.

### ISSUE THREAD

**Issue by ykk648** [dashingsoft/pyarmor#627]
[mirror question](https://github.com/pydata/numexpr/issues/389)

When I use pyarmor to encrypt my projects, any other package works fine, besides numexpr reports not for the name in expression:

`img = ne.evaluate('img_mask * (...)+(1 - img_mask) * ...')`

Traceback (most recent call last):                                                                                                                                                                                 
  File "/opt/anaconda3/envs/base_py38_torch18_tf2/lib/python3.8/threading.py", line 932, in _bootstrap_inner                                                                                                       
    self.run()                                                                                                                                                                                                     
	......                                                                                     
  File "/opt/anaconda3/envs/base_py38_torch18_tf2/lib/python3.8/site-packages/numexpr/necompiler.py", line 820, in evaluate                                                                                        
    arguments = getArguments(names, local_dict, global_dict)                                                                                                                                                       
  File "/opt/anaconda3/envs/base_py38_torch18_tf2/lib/python3.8/site-packages/numexpr/necompiler.py", line 748, in getArguments                                                                                    
    a = global_dict[name]                                                                                                                                                                                          
KeyError: 'img_mask'  

convert it to `img = img_mask * (...)+(1 - img_mask) * ... ` , It just work fine.

**Comment by jondy** [comment]
I don't know how `ne.evaluate` works, if possible, pass `globals` and `locals` to `ne.evaluate`.

Note that if the package uses any features changed by pyarmor, it will not work with pyarmor, refer to
http://pyarmor.readthedocs.io/en/latest/understand-obfuscated-scripts.html#the-differences-of-obfuscated-scripts

**Comment by ykk648** [comment]
Really thanks for the fast reply, I tried to pass the local_dict and the problem was solved:

`    local_dict = {
        'img_mask': img_mask,
        ......
    }
    img = ne.evaluate('img_mask *...+(1 - img_mask) * ...', local_dict=local_dict, global_dict=None)
`
