### ISSUE TITLE
ERROR    Expecting value: line 1 column 1 (char 0) in Super Mode

### ISSUE THREAD

**Issue by gohkokhan** [dashingsoft/pyarmor#640]
1) Create a script foo.py 
```
# -*- coding: utf-8 -*-

print('hello')
```
2) On Windows 10, pyarmor v7.1.1 run pyarmor to obfuscate the script with super mode
```
$ pyarmor -d obfuscate --advanced 2 foo.py
DEBUG    PyArmor installation path: c:\users\goh kok han\.conda\envs\python38fordm\lib\site-packages\pyarmor
DEBUG    PyArmor home path: C:\Users\Goh Kok Han\.pyarmor
DEBUG    Native platform is windows.x86_64
DEBUG    Search dynamic library in the path: c:\users\goh kok han\.conda\envs\python38fordm\lib\site-packages\pyarmor\platforms
DEBUG    Loaded dynamic library: c:\users\goh kok han\.conda\envs\python38fordm\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
DEBUG    The version of core library is (47, 21, 7)
INFO     PyArmor Version 7.1.1
INFO     Python 3.8.10
INFO     Target platforms: Native
DEBUG    Load platform list from C:\Users\Goh Kok Han\.pyarmor\platforms\index.json
Traceback (most recent call last):
  File "c:\users\goh kok han\.conda\envs\python38fordm\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\goh kok han\.conda\envs\python38fordm\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Goh Kok Han\.conda\envs\python38fordm\Scripts\pyarmor.exe\__main__.py", line 7, in <module>
  File "c:\users\goh kok han\.conda\envs\python38fordm\lib\site-packages\pyarmor\pyarmor.py", line 1594, in main_entry
    main(sys.argv[1:])
  File "c:\users\goh kok han\.conda\envs\python38fordm\lib\site-packages\pyarmor\pyarmor.py", line 1586, in main
    args.func(args)
  File "c:\users\goh kok han\.conda\envs\python38fordm\lib\site-packages\pyarmor\pyarmor.py", line 585, in _obfuscate
    platforms = check_cross_platform(platforms, supermode, vmenabled)
  File "c:\users\goh kok han\.conda\envs\python38fordm\lib\site-packages\pyarmor\utils.py", line 1244, in check_cross_platform
    platid = _get_preferred_platid(name, features=features)
  File "c:\users\goh kok han\.conda\envs\python38fordm\lib\site-packages\pyarmor\utils.py", line 1209, in _get_preferred_platid
    plist = [x['id'] for x in _get_platform_list() if x['name'] == name]
  File "c:\users\goh kok han\.conda\envs\python38fordm\lib\site-packages\pyarmor\utils.py", line 236, in _get_platform_list
    cfg = json_loads(f.read())
  File "c:\users\goh kok han\.conda\envs\python38fordm\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\users\goh kok han\.conda\envs\python38fordm\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\goh kok han\.conda\envs\python38fordm\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

The normal obfuscate works flawlessly. 
```
pyarmor obfuscate foo.py
```

**Comment by jondy** [comment]
How about remove this file `C:\Users\Goh Kok Han\.pyarmor\platforms\index.json` and try it again?

**Comment by gohkokhan** [comment]
Thanks, it's working!
