### ISSUE TITLE
Running merge: 'RuntimeError: Too many runtime files'

### ISSUE THREAD

**Issue by jack1902** [dashingsoft/pyarmor#663]
**Title**
Runtime detection with the merge command doesn't work as expected and results in detection of numerous files that are created by the runtime command itself.

**Description**
1. Run the following commands:
```bash
# PLATFORMS as a csv string
PLATFORMS=""

for PY_VERSION in "38" "39"; do
  # Generate runtime for version (assumes pyarmor is installed for the relevant version of python specified) [Uses pyenv and a venv to install the relevant version of pyarmor]

  # Using the `src` directory to output the pytransform package means that pytransform is included as part of the overall package and I use `package_data` to bundle the relevant .so / .pyd files
  pyarmor runtime -O "dist/src" --enable-suffix 1 --platform "${PLATFORMS}"
  
  # Generate the obfuscated scripts for the relevant version (using `--no-runtime` as I don't always need it for other packages that use a common base package which includes the runtime
  pyarmor obfuscate --enable-suffix --no-runtime --recursive --bootstrap 2  --output "${PY_VERSION}/src/myapp" src/myapp/__init__.py
done

# Merge the obfuscated scripts and runtimes into one (observe error)
python -m pyarmor.helper.merge -d py38 py39
```

Observe the error below (vax_xxxxxx contains my unique id for the registered version):

```python
INFO     Merging runtime files...
DEBUG    Found runtimes: ['src/pytransform_bootstrap.py', 'src/pytransform_protection.py', 'src/pytransform_vax_xxxxxx']
Traceback (most recent call last):
  File "PATH/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "PATH/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "PATH/.venv/lib/python3.8/site-packages/pyarmor/helper/merge.py", line 293, in <module>
    main()
  File "PATH/.venv/lib/python3.8/site-packages/pyarmor/helper/merge.py", line 282, in main
    merge_runtimes(args.path, output)
  File "PATH/.venv/lib/python3.8/site-packages/pyarmor/helper/merge.py", line 170, in merge_runtimes
    raise RuntimeError('Too many runtime files')
RuntimeError: Too many runtime files
```

2. This becomes an `sdist` and `bdist` using a `setup.py` with `python -m build merged_dist` and is then distributed as a normal python package. See my setup.py below:

<details>
  <summary>setup.py</summary>
  
  ```python
  from setuptools import find_namespace_packages, setup
from pathlib import Path

def getreadme():
    with open("README.md") as f:
        return f.read()

def get_package_data(path):
    # Returns a list of files excluding the `__init__` from the given path
    p = Path(path)
    return [
        str(f.relative_to(path))
        for f in p.glob("**/*")
        if f.is_file() and "__init__" not in str(f)
    ]

setup(
    name="myapp",
    version="1.0.0",
    description="description",
    long_description=getreadme(),
    author="author",
    author_email="author_email",
    packages=find_namespace_packages(where="src"),
    package_dir={"": "src"},
    install_requires=["jwt"],
    package_data={
        "pytransform_vax_xxxxxx": get_package_data("src/pytransform_vax_xxxxxx")
    },
    include_package_data=False,
    zip_safe=True,
)
  ```

</details>

The reason behind this is https://github.com/dashingsoft/pyarmor/blob/82ec16c69ee61b19c0a0c0fe34c815a0e89e770f/src/helper/merge.py#L148 as it simply checks if the given file includes a string but the output of `runtime` results in two files and a folder which match this. A simple hack I have done at the moment is to remove `pytransform_bootstrap.py` and `pytransform_protection.py` after generating the runtime within my script above. Ideally a licensed version of pyarmor would work with the merge command and not detect the other files that are created when creating a runtime with multiple versions of python.

**Comment by jondy** [comment]
Thanks, fixed by this patch 0de6904a4d066537c4cf2c7963d6d6dd6c43522f

**Comment by jack1902** [comment]
@jondy when can i expect this to be released as an updated version? Thanks for the quick fix :D!

**Comment by jondy** [comment]
Here it's a pre-release version
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-7.3.1.zip
