### ISSUE TITLE
Running merge: 'RuntimeError: No runtime files found'

### ISSUE THREAD

**Issue by jack1902** [dashingsoft/pyarmor#666]
relates_to: https://github.com/dashingsoft/pyarmor/issues/663

**Title**
When running the `merge` tool on a package with multiple versions of python obfuscated with `--no-runtime` I can't merge the output into one. I don't need a runtime for these packages as they use a common library which includes the `pytransform` library within.

**Description**
1. run `python -m pyarmor.helper.merge -d py38 py39 py310`

```python
INFO     Merge 'dist/3.8.12', 'dist/3.9.9', 'dist/3.10.0'...
INFO     Merging obfuscated scripts...
... REDACTED ...
INFO     Merging runtime files...
DEBUG    Found runtimes: []
Traceback (most recent call last):
  File "PATH/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "PATH/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/venv_3.10.0/lib/python3.10/site-packages/pyarmor/helper/merge.py", line 293, in <module>
    main()
  File "/tmp/venv_3.10.0/lib/python3.10/site-packages/pyarmor/helper/merge.py", line 282, in main
    merge_runtimes(args.path, output)
  File "/tmp/venv_3.10.0/lib/python3.10/site-packages/pyarmor/helper/merge.py", line 168, in merge_runtimes
    raise RuntimeError('No runtime files found')
RuntimeError: No runtime files found
```

Adding a new option which is defaulted to `true` so that 
https://github.com/dashingsoft/pyarmor/blob/89c4df8a6624bb89cb14f633aead7f8448f75b39/src/helper/merge.py#L284

is only run when this flag is enabled would ensure that i can pass `--no-runtime` or similar to this script and have it work as expected and is consistent with other flags that `pyarmor obfuscate` consumes

**Comment by jondy** [comment]
A new option `--no-runtime` has been added in the pre-release version v7.3.1
