### ISSUE TITLE
Building wheel using pyarmor fails with the below exception

### ISSUE THREAD

**Issue by murphp15** [dashingsoft/pyarmor#676]
**Description**
I am following instructions from here https://pyarmor.readthedocs.io/en/latest/build-wheel.html
I have setup my pyproject.toml like below: 
```
[build-system]
requires = ["setuptools", "wheel", "pyarmor>7.2.0"]
build-backend = "pyarmor.build_meta"
```
I then run
```
pip wheel .
```

I get the below stacktrace.

I have tried this on linux and mac, I've also tried python 3.8.1 and 3.8.12. It always produces the same stacktrace
Any idea how I might fix this? 

**Stacktrace**
```
 ERROR: Command errored out with exit status 1:
   command: /anaconda/envs/azureml_py38/bin/python /anaconda/envs/azureml_py38/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpdd0ocajh
       cwd: /tmp/pip-req-build-wwnjrv88
  Complete output (35 lines):
  running bdist_wheel
  /anaconda/envs/azureml_py38/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
    warnings.warn("Setuptools is replacing distutils.")
  Traceback (most recent call last):
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-6iq_h291/overlay/lib/python3.8/site-packages/pyarmor/build_meta.py", line 103, in build_wheel
      result_basename = setuptools_build_wheel(
    File "/tmp/pip-build-env-6iq_h291/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-6iq_h291/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-6iq_h291/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 26, in <module>
      setup(
    File "/tmp/pip-build-env-6iq_h291/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-6iq_h291/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-6iq_h291/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-6iq_h291/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-6iq_h291/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 984, in run_command
      cmd_obj = self.get_command_obj(command)
    File "/tmp/pip-build-env-6iq_h291/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 859, in get_command_obj
      cmd_obj = self.command_obj[command] = klass(self)
    File "/anaconda/envs/azureml_py38/lib/python3.8/distutils/cmd.py", line 57, in __init__
      raise TypeError("dist must be a Distribution instance")
  TypeError: dist must be a Distribution instance
  ----------------------------------------
```

**Comment by jondy** [comment]
First make sure `setuptools.build_meta` works.

**Comment by murphp15** [comment]
It definitely does

**Comment by jondy** [comment]
`build_meta.py` of pyarmor is a very simple script, it just call `setuptools.build_wheel` to build wheel first, then unpack the wheel and replace the original scripts with obfuscated ones.

In the traceback, `pyarmor.build_meta.setuptools_build_wheel` failed, it may be caused by `_distutils_hack`. But I have no more idea, because `setuptools_build_wheel` is same as `setuptools.build_wheel`.

If this script doesn't work, please refer to `pyarmor.build_meta.build_wheel` to do this manully by the following command:

pip wheel .
pip unpack xxx.wheel
pyarmor obfuscation ...
cp dist/* to wheel
pip pack /path/to/unpack_wheel
