### ISSUE TITLE
RuntimeError: No available dynamic library for linux.x86 with features ['11']

### ISSUE THREAD

**Issue by JKKSI** [dashingsoft/pyarmor#678]
$ Hello, i'm trying to obfuscate script with linux.x86 platform, i execute the next steps..

```
C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio>pyarmor download linux.x86
INFO     PyArmor Version 7.3.0
INFO     Python 3.10.1
INFO     Downloading dynamic library for linux.x86
INFO     Search library for platform: linux.x86
INFO     Found available libraries: ['linux.x86.7', 'linux.x86.0', 'linux.x86.11.py39', 'linux.x86.11.py38', 'linux.x86.11.py37', 'linux.x86.11.py27']
INFO     Target path for linux.x86.7: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\7
INFO     Downloading library file for linux.x86.7 ...
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r48.2/linux_i386/_pytransform.so
INFO     Writing target file: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\7\_pytransform.so
INFO     Download dynamic library linux.x86.7 OK
INFO     Target path for linux.x86.0: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\0
INFO     Downloading library file for linux.x86.0 ...
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r48.2/linux.x86.0/_pytransform.so
INFO     Writing target file: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\0\_pytransform.so
INFO     Download dynamic library linux.x86.0 OK
INFO     Target path for linux.x86.11.py39: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\11\py39
INFO     Downloading library file for linux.x86.11.py39 ...
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r48.2/linux.x86.11.py39/pytransform.cpython-39-i386-linux-gnu.so
INFO     Writing target file: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\11\py39\pytransform.cpython-39-i386-linux-gnu.so
INFO     Download dynamic library linux.x86.11.py39 OK
INFO     Target path for linux.x86.11.py38: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\11\py38
INFO     Downloading library file for linux.x86.11.py38 ...
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r48.2/linux.x86.11.py38/pytransform.cpython-38-i386-linux-gnu.so
INFO     Writing target file: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\11\py38\pytransform.cpython-38-i386-linux-gnu.so
INFO     Download dynamic library linux.x86.11.py38 OK
INFO     Target path for linux.x86.11.py37: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\11\py37
INFO     Downloading library file for linux.x86.11.py37 ...
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r48.2/linux.x86.11.py37/pytransform.cpython-37m-i386-linux-gnu.so
INFO     Writing target file: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\11\py37\pytransform.cpython-37m-i386-linux-gnu.so
INFO     Download dynamic library linux.x86.11.py37 OK
INFO     Target path for linux.x86.11.py27: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\11\py27
INFO     Downloading library file for linux.x86.11.py27 ...
INFO     Getting remote file: https://pyarmor.dashingsoft.com/files/r48.2/linux.x86.11.py27/pytransform.so
INFO     Writing target file: C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\11\py27\pytransform.so
INFO     Download dynamic library linux.x86.11.py27 OK
```
$ Later I Try Obfuscate with next command

```
C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio>pyarmor -d obfuscate --platform linux.x86_64 --platform linux.x86 --advanced 2 --no-runtime --exact berserker.py                                               
DEBUG    PyArmor installation path: C:\Python3\lib\site-packages\pyarmor                                                                                                                                           DEBUG    PyArmor home path: C:\Users\Daishinkan\.pyarmor                                                                                                                                                           DEBUG    Native platform is windows.x86_64                                                                                                                                                                         DEBUG    Search dynamic library in the path: C:\Python3\lib\site-packages\pyarmor\platforms                                                                                                                        DEBUG    Loaded dynamic library: C:\Python3\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll                                                                                                    DEBUG    The version of core library is (48, 2, 7)                                                                                                                                                                 INFO     PyArmor Version 7.3.0                                                                                                                                                                                     INFO     Python 3.10.1                                                                                                                                                                                             INFO     Target platforms: ['linux.x86_64', 'linux.x86']                                                                                                                                                           DEBUG    Load platform list from C:\Users\Daishinkan\.pyarmor\platforms\index.json                                                                                                                                 DEBUG    Load platform list from C:\Users\Daishinkan\.pyarmor\platforms\index.json                                                                                                                                 Traceback (most recent call last):                                                                                                                                                                                   File "C:\Python3\lib\runpy.py", line 196, in _run_module_as_main                                                                                                                                                     return _run_code(code, main_globals, None,                                                                                                                                                                       File "C:\Python3\lib\runpy.py", line 86, in _run_code                                                                                                                                                                exec(code, run_globals)                                                                                                                                                                                          File "C:\Python3\Scripts\pyarmor.exe\__main__.py", line 7, in <module>                                                                                                                                             File "C:\Python3\lib\site-packages\pyarmor\pyarmor.py", line 1599, in main_entry                                                                                                                                     main(sys.argv[1:])                                                                                                                                                                                               File "C:\Python3\lib\site-packages\pyarmor\pyarmor.py", line 1591, in main                                                                                                                                           args.func(args)                                                                                                                                                                                                  File "C:\Python3\lib\site-packages\pyarmor\pyarmor.py", line 585, in _obfuscate                                                                                                                                      platforms = check_cross_platform(platforms, supermode, vmenabled)                                                                                                                                                File "C:\Python3\lib\site-packages\pyarmor\utils.py", line 1246, in check_cross_platform                                                                                                                             raise RuntimeError('No available dynamic library for %s '                                                                                                                                                      RuntimeError: No available dynamic library for linux.x86 with features ['11'] 
```
$ I Tried removing from command the next lines ...
```
--platform linux.x86_64
--no-runtime
```
$ Later i tried 
```
C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio>pyarmor -d obfuscate --platform linux.x86 --advanced 2 --exact berserker.py
DEBUG    PyArmor installation path: C:\Python3\lib\site-packages\pyarmor
DEBUG    PyArmor home path: C:\Users\Daishinkan\.pyarmor
DEBUG    Native platform is windows.x86_64
DEBUG    Search dynamic library in the path: C:\Python3\lib\site-packages\pyarmor\platforms
DEBUG    Loaded dynamic library: C:\Python3\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
DEBUG    The version of core library is (48, 2, 7)
INFO     PyArmor Version 7.3.0
INFO     Python 3.10.1
INFO     Target platforms: ['linux.x86']
DEBUG    Load platform list from C:\Users\Daishinkan\.pyarmor\platforms\index.json
Traceback (most recent call last):
  File "C:\Python3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python3\Scripts\pyarmor.exe\__main__.py", line 7, in <module>
  File "C:\Python3\lib\site-packages\pyarmor\pyarmor.py", line 1599, in main_entry
    main(sys.argv[1:])
  File "C:\Python3\lib\site-packages\pyarmor\pyarmor.py", line 1591, in main
    args.func(args)
  File "C:\Python3\lib\site-packages\pyarmor\pyarmor.py", line 585, in _obfuscate
    platforms = check_cross_platform(platforms, supermode, vmenabled)
  File "C:\Python3\lib\site-packages\pyarmor\utils.py", line 1246, in check_cross_platform
    raise RuntimeError('No available dynamic library for %s '
RuntimeError: No available dynamic library for linux.x86 with features ['11']
```
$ Finally i tried again but with --no-runtime
```
C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio>pyarmor -d obfuscate --platform linux.x86 --advanced 2 --no-runtime --exact berserker.py
DEBUG    PyArmor installation path: C:\Python3\lib\site-packages\pyarmor
DEBUG    PyArmor home path: C:\Users\Daishinkan\.pyarmor
DEBUG    Native platform is windows.x86_64
DEBUG    Search dynamic library in the path: C:\Python3\lib\site-packages\pyarmor\platforms
DEBUG    Loaded dynamic library: C:\Python3\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
DEBUG    The version of core library is (48, 2, 7)
INFO     PyArmor Version 7.3.0
INFO     Python 3.10.1
INFO     Target platforms: ['linux.x86']
DEBUG    Load platform list from C:\Users\Daishinkan\.pyarmor\platforms\index.json
Traceback (most recent call last):
  File "C:\Python3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python3\Scripts\pyarmor.exe\__main__.py", line 7, in <module>
  File "C:\Python3\lib\site-packages\pyarmor\pyarmor.py", line 1599, in main_entry
    main(sys.argv[1:])
  File "C:\Python3\lib\site-packages\pyarmor\pyarmor.py", line 1591, in main
    args.func(args)
  File "C:\Python3\lib\site-packages\pyarmor\pyarmor.py", line 585, in _obfuscate
    platforms = check_cross_platform(platforms, supermode, vmenabled)
  File "C:\Python3\lib\site-packages\pyarmor\utils.py", line 1246, in check_cross_platform
    raise RuntimeError('No available dynamic library for %s '
RuntimeError: No available dynamic library for linux.x86 with features ['11']
```
$ I have Tried too removing --advanced 2
```
C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio>pyarmor -d obfuscate --platform linux.x86 --exact berserker.py
DEBUG    PyArmor installation path: C:\Python3\lib\site-packages\pyarmor
DEBUG    PyArmor home path: C:\Users\Daishinkan\.pyarmor
DEBUG    Native platform is windows.x86_64
DEBUG    Search dynamic library in the path: C:\Python3\lib\site-packages\pyarmor\platforms
DEBUG    Loaded dynamic library: C:\Python3\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
DEBUG    The version of core library is (48, 2, 7)
INFO     PyArmor Version 7.3.0
INFO     Python 3.10.1
INFO     Target platforms: ['linux.x86']
DEBUG    Load platform list from C:\Users\Daishinkan\.pyarmor\platforms\index.json
INFO     Update target platforms to: ['linux.x86.7']
INFO     Source path is "C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio"
INFO     Entry scripts are ['berserker.py']
INFO     Use cached capsule C:\Users\Daishinkan\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Exact
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
DEBUG    Load platform list from C:\Users\Daishinkan\.pyarmor\platforms\index.json
DEBUG    Target dynamic library: ['C:\\Users\\Daishinkan\\.pyarmor\\platforms\\linux\\x86\\7\\_pytransform.so']
INFO     Copying C:\Users\Daishinkan\.pyarmor\platforms\linux\x86\7\_pytransform.so
INFO     Patch library dist\pytransform\_pytransform.so
DEBUG    Patching dist\pytransform\_pytransform.so
DEBUG    Found pattern at fb264
DEBUG    Patch 261 bytes from fb284
DEBUG    Patch 270 bytes from fb389
DEBUG    Patch 412 bytes from fb497
INFO     Patch library file OK
INFO     Copying C:\Python3\lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio\berserker.py -> dist\berserker.py
INFO     Write patched script for debugging: C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio\berserker.py.pyarmor-patched
INFO     Insert bootstrap code to entry script dist\berserker.py
INFO     Obfuscate 1 scripts OK.
```
$ Finally i copy the whole dist folder to my Kali Linux System 
```
┌──(root💀kali)-[/home/kali/Desktop]
└─# cd dist 

┌──(root💀kali)-[/home/kali/Desktop/dist]
└─# ls
berserker.py  pytransform
                                                                                                      
┌──(root💀kali)-[/home/kali/Desktop/dist]
└─# chmod 777 *               
                                                                                                      
┌──(root💀kali)-[/home/kali/Desktop/dist]
└─# python3 berserker.py      
/home/kali/Desktop/dist/pytransform/_pytransform.so: wrong ELF class: ELFCLASS32
```
$ is Same error including if i add --no-runtime
```
C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio>pyarmor -d obfuscate --platform linux.x86 --no-runtime --exact berserker.py
DEBUG    PyArmor installation path: C:\Python3\lib\site-packages\pyarmor
DEBUG    PyArmor home path: C:\Users\Daishinkan\.pyarmor
DEBUG    Native platform is windows.x86_64
DEBUG    Search dynamic library in the path: C:\Python3\lib\site-packages\pyarmor\platforms
DEBUG    Loaded dynamic library: C:\Python3\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
DEBUG    The version of core library is (48, 2, 7)
INFO     PyArmor Version 7.3.0
INFO     Python 3.10.1
INFO     Target platforms: ['linux.x86']
DEBUG    Load platform list from C:\Users\Daishinkan\.pyarmor\platforms\index.json
INFO     Update target platforms to: ['linux.x86.7']
INFO     Source path is "C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio"
INFO     Entry scripts are ['berserker.py']
INFO     Use cached capsule C:\Users\Daishinkan\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Exact
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
WARNING  No cross protection because no runtime generated
INFO     Start obfuscating the scripts...
INFO            C:\Users\Daishinkan\Desktop\ransomcrypt\laboratorio\berserker.py -> dist\berserker.py
INFO     Insert bootstrap code to entry script dist\berserker.py
INFO     Obfuscate 1 scripts OK.
```
$ Copy again the whole dist folder to linux and give chmod 777 * && python3 berserker.py
```
──(root💀kali)-[/home/kali/Desktop/dist]
└─# python3 berserker.py      
/home/kali/Desktop/dist/pytransform/_pytransform.so: wrong ELF class: ELFCLASS32
```

**Comment by JKKSI** [comment]
> There is still no linux.x86.11.py310 at this time, it'll available in next version (v7.3.1) released. Or try the pre-release version here https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-7.3.1.zip

Hello Jondy, sadly the pre-release version dont solved my problem, will wait for the official version 7.3.1 come and hope bug be fixed , same thanks :)
