### ISSUE TITLE
UnboundLocalError: local variable 'sys' referenced before assignment

### ISSUE THREAD

**Issue by whiteowl3** [dashingsoft/pyarmor#688]
Since updating to latest version on Linux ARM this afternoon, every ADVANCED script is broken.
I am using 7.3.3 with Python 3.8.10 on ubuntu impish aarch64v8, previous version worked perfectly.
If I use ADVANCED 2, 
```
Traceback (most recent call last):
  File "<test.py>", line 2, in <module>
  File "<frozen test>", line 53, in <module>
  File "<frozen test>", line 48, in protect_pytransform
  File "<frozen test>", line 27, in check_lib_pytransform
UnboundLocalError: local variable 'sys' referenced before assignment
```
If I use ADVANCED 1:
```
XXX lineno: 74, opcode: 228
Traceback (most recent call last):
  File "<test.py>", line 3, in <module>
  File "<frozen test>", line 74, in <module>
SystemError: unknown opcode
```
These are the same errors no matter what the script.  Tested scripts of all different types, complex and simple.

Previous version worked flawlessly.

**Comment by jondy** [comment]
Please upgrade v7.3.4, it's just for fixing this issue

**Comment by whiteowl3** [comment]
appears to work perfectly thanks.
