### ISSUE TITLE
Check bootstrap restrict mode failed

### ISSUE THREAD

**Issue by octoma** [dashingsoft/pyarmor#696]
Purchased Copy*

I keep running into (Check bootstrap restrict mode failed) issue when trying to run the script after obfuscation. I'm only doing one file. Also, when I check the pytransform folder, I don't see pyarmor_runtime. 

I'm a total Python/programing newb. I am good at following directions. Please simplify.

```
Check bootstrap restrict mode failed
2022-02-10 15:12:21.136 Traceback (most recent call last):
  File "/home/sage/.local/share/Trash/files/dist/pytransform/__init__.py", line 365, in pyarmor_runtime
    init_runtime()
  File "/home/sage/.local/share/Trash/files/dist/pytransform/__init__.py", line 58, in wrap
    return func(*args, **kwargs)
  File "/home/sage/.local/share/Trash/files/dist/pytransform/__init__.py", line 87, in init_runtime
    return _init_runtime(0, 0, 0, 0)
RuntimeError: Check bootstrap restrict mode failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sage/.local/lib/python3.8/site-packages/streamlit/script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "/home/sage/.local/share/Trash/files/dist/SHIB.py", line 2, in <module>
    pyarmor_runtime()
  File "/home/sage/.local/share/Trash/files/dist/pytransform/__init__.py", line 370, in pyarmor_runtime
    sys.exit(1)
SystemExit: 1

```

**Comment by octoma** [comment]
After noticing that the script was looking in the trash folder for some reason, I cleared the trash folder, but now the issue changed to:

`Traceback (most recent call last):
  File "/home/sage/.local/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/home/sage/.local/lib/python3.8/site-packages/streamlit/__init__.py", line 46, in <module>
    from streamlit import logger as _logger
  File "/home/sage/.local/lib/python3.8/site-packages/streamlit/logger.py", line 21, in <module>
    from streamlit import config
  File "/home/sage/.local/lib/python3.8/site-packages/streamlit/config.py", line 956, in <module>
    file_util.get_project_streamlit_file_path("config.toml"),
  File "/home/sage/.local/lib/python3.8/site-packages/streamlit/file_util.py", line 148, in get_project_streamlit_file_path
    return os.path.join(os.getcwd(), CONFIG_FOLDER_NAME, *filepath)
FileNotFoundError: [Errno 2] No such file or directory
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 76, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "/home/sage/.local/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/home/sage/.local/lib/python3.8/site-packages/streamlit/__init__.py", line 46, in <module>
    from streamlit import logger as _logger
  File "/home/sage/.local/lib/python3.8/site-packages/streamlit/logger.py", line 21, in <module>
    from streamlit import config
  File "/home/sage/.local/lib/python3.8/site-packages/streamlit/config.py", line 956, in <module>
    file_util.get_project_streamlit_file_path("config.toml"),
  File "/home/sage/.local/lib/python3.8/site-packages/streamlit/file_util.py", line 148, in get_project_streamlit_file_path
    return os.path.join(os.getcwd(), CONFIG_FOLDER_NAME, *filepath)
FileNotFoundError: [Errno 2] No such file or directory`

**Comment by jondy** [comment]
As a test, try to obfuscate one simple print hello script in a fresh folder.
