### ISSUE TITLE
pyrarmor not working in termux

### ISSUE THREAD

**Issue by rmdlv** [dashingsoft/pyarmor#701]
trying to execute `pyarmor obfuscate main.py` in termux environment, everything goes without errors, but when I run it, I get the error `Check license failed, Invalid input packet.`
```
~ $ pyarmor obfuscate main.py
INFO     PyArmor Trial Version 7.3.6
INFO     Python 3.10.2
INFO     Target platforms: Native
INFO     Source path is "/data/data/com.termux/files/home"
INFO     Entry scripts are ['main.py']
INFO     Use cached capsule /data/data/com.termux/files/home/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying /data/data/com.termux/files/home/.pyarmor/platforms/android/aarch64/0/_pytransform.so
INFO     Patch library dist/pytransform/_pytransform.so
INFO     Patch library file OK
INFO     Copying /data/data/com.termux/files/usr/lib/python3.10/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            main.py -> dist/main.py
INFO     Insert bootstrap code to entry script dist/main.py
INFO     Obfuscate 1 scripts OK.
~ $ python dist/main.py
Check license failed, Invalid input packet.
```

**Comment by jondy** [comment]
Is there more information to run the obfuscated scripts with "-d"?

python -d dist/main.py

**Comment by rmdlv** [comment]
```
Initialize license failed

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/dist/main.py", line 2, in <module>
    pyarmor_runtime()
  File "/data/data/com.termux/files/home/dist/pytransform/__init__.py", line 364, in pyarmor_runtime
    pyarmor_init(path, is_runtime=1, suffix=suffix, advanced=advanced)
  File "/data/data/com.termux/files/home/dist/pytransform/__init__.py", line 356, in pyarmor_init
    return init_pytransform()
  File "/data/data/com.termux/files/home/dist/pytransform/__init__.py", line 58, in wrap
    return func(*args, **kwargs)
  File "/data/data/com.termux/files/home/dist/pytransform/__init__.py", line 76, in init_pytransform
    ret = init_module(major, minor, pythonapi._handle)
RuntimeError: Check license failed, Invalid input packet.
```

**Comment by KreizDev** [comment]
фатаграфирую закааат будта пару лет назад без тибяя

**Comment by jondy** [comment]
This issue has been fixed in the latest version, but not for trial version, it only works in purchased version, please check the change logs for more information.

**Comment by rmdlv** [comment]
I bought and activated a license, but nothing has changed
`INFO     PyArmor Version 7.3.7`
