### ISSUE TITLE
Is there a way to use different restrict modes with "pyarmor pack"?

### ISSUE THREAD

**Issue by saidelike** [dashingsoft/pyarmor#704]
NOTE: tested with PyArmor Version 6.6.2.

`pyarmor pack` allows to obfuscate with pyamor (options passed in `-x`) and pack with pyinstaller (options passed in `-e`):

```
$ pyarmor pack -h
usage: pyarmor pack [-h] [-v] [-s FILE] [-n NAME] [-O PATH] [-e EXTRA_OPTIONS]
                    [-x EXTRA_OPTIONS] [--with-license FILE] [--clean]
                    [--keep]
                    SCRIPT

positional arguments:
  SCRIPT                Entry script or project path

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  -s FILE, --setup FILE
                        Use external .spec file to pack the script
  -n NAME, --name NAME  Name to assign to the bundled app (default: first
                        script’s basename)
  -O PATH, --output PATH
                        Directory to put final built distributions in
  -e EXTRA_OPTIONS, --options EXTRA_OPTIONS
                        Pass these extra options to `pyinstaller`
  -x EXTRA_OPTIONS, --xoptions EXTRA_OPTIONS
                        Pass these extra options to `pyarmor obfuscate`
  --with-license FILE   Use this license file other than default one
  --clean               Remove cached .spec file before packing
  --keep, --debug       Do not remove build files after packing

Pack obfuscated scripts to one bundle, distribute the bundle as a
folder or file to other people, and they can execute your program
without Python installed.
```

So an example I've used is:

```
$ pyarmor pack -e "\--onefile" -x "--advanced 2 --restrict 1 --recursive" program.py 
```

This works fine. However, if I try to use a `--restrict 2` or above (a value of 2, 3, 4 or 5), I get the following when executing the resulting packed binary:

```
$ ./dist/program
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing/spawn.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing/util.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "subprocess.py", line 64, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "<msvcrt.py>", line 2, in <module>
RuntimeError: Check restrict mode of module failed
[120908] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!
```

I am not sure to understand why the above does not work. Any idea?

One idea I have to solve the problem would be to maybe have a restrict mode of 1 for the entry script and a restrict mode of 5 for all other files. But it means I have to run the command `pyamor obfuscate` twice:

To obfuscate the entry script:

```
pyarmor obfuscate --advanced 2 --restrict 1 --exact program.py
```

and to obfuscate all other files:

```
pyarmor obfuscate --advanced 2 --restrict 5 --recursive --exclude program.py program.py
```

Any idea how I can do that? Is it easy to modify `packer.py` (implementing the `pyarmor pack` command) to do so? Is it the right approach?

**Comment by jondy** [comment]
About the restrict modes, please refer to chapter modes in the online documentation.

**Comment by VeNoMouS** [comment]
> This works fine. However, if I try to use a --restrict 2 or above (a value of 2, 3, 4 or 5), I get the following when executing the resulting packed binary:

you can't do it with pyinstaller, each file you must specify the restrict level... and you need at least 1 file with restrict 1 as an entry point loader

then you must pack the resulting restrictions

It would be nice if there was some way to automatically map all this... but there isn't

**Comment by jondy** [comment]
But pyarmor doesn't know which script should be restricted by which mode.

**Comment by VeNoMouS** [comment]
thats why i said it would be cool if you could map that out via a mapping file or something... but as i also said... you can do it manually ... so its not like you can't do it....

**Comment by jondy** [comment]
Refer to advanced usage about `repack` helper script. First obfuscate the scripts with restrict modes, then repack the executable with them.
