### ISSUE TITLE
encrypt_script() got an unexpected keyword argument 'plugins'

### ISSUE THREAD

**Issue by ArendJanKramer** [dashingsoft/pyarmor#72]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/pyarmor/pyarmor.py", line 863, in <module>
    main_entry()
  File "/usr/local/lib/python3.6/dist-packages/pyarmor/pyarmor.py", line 854, in main_entry
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/pyarmor/pyarmor.py", line 844, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/pyarmor/pyarmor.py", line 494, in _obfuscate
    encrypt_script(prokey, a, b, protection=protection, plugins=plugins)
TypeError: encrypt_script() got an unexpected keyword argument 'plugins'

**Comment by jondy** [comment]
Try to run `pip install --upgrade pyarmor`, it seems that "/usr/local/lib/python3.6/dist-packages/pyarmor/utils.py" is not latest.

**Comment by ArendJanKramer** [comment]
Now I get this error message:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/pyarmor/pyarmor.py", line 863, in <module>
    main_entry()
  File "/usr/local/lib/python3.6/dist-packages/pyarmor/pyarmor.py", line 854, in main_entry
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/pyarmor/pyarmor.py", line 844, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/pyarmor/pyarmor.py", line 494, in _obfuscate
    encrypt_script(prokey, a, b, protection=protection, plugins=plugins)
  File "/usr/local/lib/python3.6/dist-packages/pyarmor/utils.py", line 356, in encrypt_script
    encoding = _guess_encoding(filename)
  File "/usr/local/lib/python3.6/dist-packages/pyarmor/utils.py", line 343, in _guess_encoding
    elif n < 60 and line[n+1] == 35:
IndexError: index out of range

**Comment by jondy** [comment]
The quick workaround to fix this problem is to replace line 343 in `utils.py` with
```
elif len(line) > n + 1 and n < 60 and line[n+1] == 35:
```
And it'll be fixed in next version.
