### ISSUE TITLE
Project build/obfuscation with (Ray)

### ISSUE THREAD

**Issue by Mamounx** [dashingsoft/pyarmor#724]
#### *TItle*

After successfully obfuscating all files in my project, I'm unable to run my main.py file but it gives the below error. The error is caused by Ray I was able to figure this out as I tried to exclude my RayActor from obfuscation and it worked fine. I'm not sure the bugs is related to ray or pyarmor. I checked previous issues in the repository and came through another issue with ray, but it's different I was getting that one but I was able to avioded by setting `--obf-code=0`, however, this issue was not solved by this.
#### *Description*:

1. Obfuscate files in the project by running:
```
$ pyarmor build --force
INFO     PyArmor Version 7.4.1
INFO     Python 3.8.0
INFO     Build project  ...
INFO     Check project
INFO     Use capsule: /home/azureuser/.pyarmor/.pyarmor_capsule.zip
INFO     Output path is: /home/azureuser/mamoun/funny-face-onprem/AI-Services/funny-face-cpu/dist
INFO     Taget platforms: []
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying /home/azureuser/mamoun/funny-face-onprem/AI-Services/funny-face-cpu/cpuenv/lib/python3.8/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
INFO     Patch library /home/azureuser/mamoun/funny-face-onprem/AI-Services/funny-face-cpu/dist/pytransform/_pytransform.so
INFO     Patch library file OK
INFO     Copying /home/azureuser/mamoun/funny-face-onprem/AI-Services/funny-face-cpu/cpuenv/lib/python3.8/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Save obfuscated scripts to "/home/azureuser/mamoun/funny-face-onprem/AI-Services/funny-face-cpu/dist"
INFO     Read product key from capsule
INFO     Disable increment build
INFO     Search scripts from /home/azureuser/mamoun/funny-face-onprem/AI-Services/funny-face-cpu/src
INFO     Obfuscate scripts with mode:
INFO     Obfuscating the whole module is off
INFO     Obfuscating each function is off
INFO     Autowrap each code object mode is on
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is off
INFO     Super plus mode is off
INFO     152 scripts has been obfuscated
INFO     Insert bootstrap code to entry script dist/main.py
INFO     Insert bootstrap code to entry script dist/ray_actor.py
INFO     Build project OK.
```
2. Copy the whole folder `dist/` to target machine Ubuntu
3. Failed to run the obfuscated script by Python 3.8 in Unbutu
```
$ cd dist/
$ python main.py
(TemporaryActor pid=154) 2022-03-30 10:41:51,381        ERROR worker.py:430 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::AsyncActor.__init__() (pid=154, ip=10.3.0.4, repr=<ray_actor.FunctionActorManager._create_fake_actor_class.<locals>.TemporaryActor object at 0x7f3716deca00>)
(TemporaryActor pid=154) RuntimeError: The actor with name AsyncActor failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
(TemporaryActor pid=154) 
(TemporaryActor pid=154) ray::AsyncActor.__init__() (pid=154, ip=10.3.0.4, repr=<ray_actor.FunctionActorManager._create_fake_actor_class.<locals>.TemporaryActor object at 0x7f3716deca00>)
(TemporaryActor pid=154)   File "/app/src/Swapping/__init__.py", line 1, in <module>
(TemporaryActor pid=154)     __pyarmor__(__name__, __file__, b'\x50\x59\x41\x52\x4d\x4f\x52\x00\x00\x03\x08\x00\x55\x0d\x0d\x0a\x09\x30\xe0\x02\x00\x00\x00\x00\x01\x00\x00\x00\x40\x00\x00\x00\x79\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x40\x00\x00\x00\x73\x10\x00\x00\x00\x64\x00\x64\x01\x6c\x00\x6d\x00\x5a\x00\x01\x00\x64\x02\x53\x00\x29\x03\xe9\x01\x00\x00\x00\xa9\x01\xda\x08\x53\x77\x61\x70\x70\x69\x6e\x67\x4e\x72\x02\x00\x00\x00\xa9\x00\x72\x04\x00\x00\x00\x72\x04\x00\x00\x00\xfa\x11\x3c\x66\x72\x6f\x7a\x65\x6e\x20\x53\x77\x61\x70\x70\x69\x6e\x67\x3e\xda\x08\x3c\x6d\x6f\x64\x75\x6c\x65\x3e\x01\x00\x00\x00\xf3\x00\x00\x00\x00', 0)
(TemporaryActor pid=154) NameError: name '__pyarmor__' is not defined
```

**Comment by jondy** [comment]
Try to use "--advanced 2" to obfuscate the scripts.

**Comment by Mamounx** [comment]
It didn't work, It's now not generating pytransform module for runtime but only pytransform.so. so It's giving this error now:

```
Traceback (most recent call last):
  File "<./main.py>", line 2, in <module>
  File "<frozen main>", line 3, in <module>
ImportError: cannot import name 'pyarmor_runtime' from 'pytransform' (/app/src/pytransform.so)
```

**Comment by jondy** [comment]
Please remove all the old obfuscated files and runtime files, then make a clean obfuscation.

And read the chapter "Understand the obfuscated scripts" in the online doc.

**Comment by Mamounx** [comment]
Thank you @jondy for your support, In my first try I don't remember If I removed obfuscated files or not, but now It's working fine.
