### ISSUE TITLE
pyproject.toml: pyarmor wheel error

### ISSUE THREAD

**Issue by little9999** [dashingsoft/pyarmor#735]
Not the same error as #641 

*Description*:
After modify the pyproject.toml, I run "pip wheel ."

`  ERROR: Command errored out with exit status 1:
   command: /home/tli/Code/fod/product_fod_detection/venv/bin/python /home/tli/Code//venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpevuxgjl_
       cwd: /home/tli/Code/submodules/fod_utils
  Complete output (12 lines):
  Traceback (most recent call last):
    File "/home/tli/Code/fod/product_fod_detection/venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/tli/Code/fod/product_fod_detection/venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/tli/Code/fod/product_fod_detection/venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-1inqdtmy/overlay/lib/python3.6/site-packages/pyarmor/build_meta.py", line 100, in build_wheel
      config_settings = _fix_config(config_settings, obf_options)
    File "/tmp/pip-build-env-1inqdtmy/overlay/lib/python3.6/site-packages/pyarmor/build_meta.py", line 72, in _fix_config
      from pip._internal.configuration import Configuration, ConfigurationError
  ModuleNotFoundError: No module named 'pip'
`

I'm using
Ubuntu 18.04
python 3.6
pyarmor 7.4.2
venv for project

**Comment by jondy** [comment]
Please check the last note in the documentation chapter "Build Pyarmor wheel", there is no more support for building wheel.
