### ISSUE TITLE
SyntaxError: invalid character in identifier

### ISSUE THREAD

**Issue by DeoLeung** [dashingsoft/pyarmor#80]
```bash
PYTHONDEBUG=y pyarmor obfuscate schemas/xxx.py
Trace log mode enabled and log to 'pytransform.log'
INFO     Capsule /xxx/.pyarmor_capsule.zip has been out of date
INFO     Rename it as /xxx/.pyarmor_capsule.zip.20190520180357
INFO     Generate global capsule /xxx/.pyarmor_capsule.zip
INFO     Generating project key ...
INFO     Generate project key OK.
INFO     Writing capsule to /xxx/.pyarmor_capsule.zip ...
INFO     Write capsule OK.
INFO     PyArmor Trial Version 5.3.9

INFO     Source path is "/xxx/pyproj/xxx/schemas"
INFO     Entry script is schemas/xxx.py
INFO     Use cached capsule /xxx/.pyarmor_capsule.zip
INFO     Normal mode is on
INFO     Save obfuscated scripts to "dist"
INFO     Read public key from capsule
INFO     Obfuscate scripts with default mode
INFO     	xxx.py -> dist/xxx.py
Traceback (most recent call last):
  File "/xxxx/bin/pyarmor", line 10, in <module>
    sys.exit(main_entry())
  File "/xxx/lib/python3.7/site-packages/pyarmor/pyarmor.py", line 966, in main_entry
    main(sys.argv[1:])
  File "/xxx/lib/python3.7/site-packages/pyarmor/pyarmor.py", line 951, in main
    args.func(args)
  File "/xxx/lib/python3.7/site-packages/pyarmor/pyarmor.py", line 501, in _obfuscate
    encrypt_script(prokey, a, b, protection=protection, plugins=plugins)
  File "/xxx/lib/python3.7/site-packages/pyarmor/utils.py", line 472, in encrypt_script
    co = compile(''.join(lines), modname, 'exec')
  File "<frozen data_market>", line 1
    from marshmallow import Schema
        ^
SyntaxError: invalid character in identifier
```
```bash
PT-IM-00
WR-PA-00
WR-PA-01
WR-PA-02
WR-PA-03
WR-PA-04
WR-PA-05.1
WR-PA-05.2
PT-IM-01
PT-ITC-00
PT-ITC-01
PT-ITC-02
PT-ITC-03
PT-ITC-04
PT-ITC-05
PT-ITC-06
PT-IM-02
LC-IV-01
LC-IV-02
LC-IV-03
LC-IV-04
LC-IV-05
PT-IM-03
PT-VL-00
PT-VL-01
Invalid input packet.
Check license failed
LC-CL-01
LC-CL-01
Invalid input packet.
Check license failed
LC-CL-01
```
any idea what's the message about, happens both trial and registered version

**Comment by jondy** [comment]
Something is wrong as compiling the file `data_market.py` .  Try to add encoding line at the beginning of `data_market.py` like this
```
# -*- coding: utf-8 -*-
```

**Comment by DeoLeung** [comment]
@jondy adding the line works, also we found that we have `UTF-8 BOM` encoding in the file, shall be the cause
