### ISSUE TITLE
ModuleNotFoundError: No module named 'lib'

### ISSUE THREAD

**Issue by viceywiceyuwu** [dashingsoft/pyarmor#801]
**Title**
Cannot import lib when running __pyarmor__(args)

**Description**
```
INFO     PyArmor Trial Version 7.6.0
INFO     Python 3.10.5
INFO     Target platforms: Native
INFO     Source path is "C:\Users\creep\Desktop\sus\creep\Operation-Nero19\client"
INFO     Entry scripts are ['index.py']
INFO     Use cached capsule C:\Users\creep\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Obfuscate string value is False
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Read default license from capsule
INFO     Copying C:\Users\creep\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Patch library dist\pytransform\_pytransform.dll
INFO     Patch library file OK
INFO     Copying C:\Users\creep\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            index.py -> dist\index.py
INFO     Insert bootstrap code to entry script dist\index.py
INFO            setup.py -> dist\setup.py
INFO     Obfuscate 2 scripts OK.
```
 ```
Traceback (most recent call last):
  File "<C:\Users\creep\AppData\Roaming\Microsoft\Windows\.system32\index.py>", line 6, in <module>
  File "<frozen index>", line 8, in <module>
ModuleNotFoundError: No module named 'lib'
```
**Misc**
If I dont do: 

```
import sys
import os
sys.path.append(os.getenv('APPDATA') + '/Nero19')
```
It wont import pytransform

**Comment by jondy** [comment]
Please refer to http://pyarmor.readthedocs.io/en/latest/questions.html
