### ISSUE TITLE
[BUG] pandas: local variable is not defined

### ISSUE THREAD

**Issue by chappy0205** [dashingsoft/pyarmor#824]
I converted the following script by PyArmor.

**sample.py**
```
import pandas as pd

class Sample:
    def __init__(self):
        self.df = pd.DataFrame(
            data={'name': ['Alice', 'Bob', 'Dave'], 
            'age': [11, 15, 8],
            'point': [0.9, 0.1, 0.4]}
        )
    
    def func(self, val: float = 0.5) -> None:
        print(self.df.query('point > @val'))

sampler = Sample()
sampler.func(0.3)
```

I ran the converted script and encountered the following error.

_pandas.core.computation.ops.UndefinedVariableError: local variable 'val' is not defined_

Could you please fix this bug?

**OS**
Windows10

**python package**
```
Package         Version
--------------- --------
numpy           1.23.2
pandas          1.4.3
pip             22.2.2
pyarmor         7.6.1
python-dateutil 2.8.2
pytz            2022.2.1
setuptools      56.0.0
six             1.16.0
```

**command and output**
```
C:\Users\anonymous\Desktop\Sample\dist>python sample.py
Traceback (most recent call last):
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\scope.py", line 193, in resolve
    return self.scope[key]
  File "C:\Program Files\Python38\lib\collections\__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Program Files\Python38\lib\collections\__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'val'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\scope.py", line 208, in resolve
    return self.temps[key]
KeyError: 'val'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<sample.py>", line 3, in <module>
  File "<frozen sample>", line 15, in <module>
  File "<frozen sample>", line 12, in func
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 811, in __init__
    self.terms = self.parse()
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 458, in _maybe_transform_eq_ne
    right = self.visit(node.right, side="right")
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "C:\Users\anonymous\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\scope.py", line 213, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: local variable 'val' is not defined
```

**Comment by jondy** [comment]
There is a similar issue #466

One solution is to patch `pandas.DataFrame.query`, it should visit local variable by `sys._getframe`, but pyarmor changes the frame. A simple patch may be like this
```patch
- sys._getframe(n)
+ sys._getframe(n+1)
```
Try other values `n+2`, `n+3` until it works.

**Comment by chappy0205** [comment]
Hello, Jondy-san.
Thanks a lot for your response.
I changed "sys._getframe(self.level)" to "sys._getframe(self.level+1)", "sys._getframe(self.level+2)" or "sys._getframe(self.level+3)" in scope.py of pandas.
However, after the change, the original python script (before PyArmor) failed to run.
Additionally, pandas is used by other application.  So, I don't want to patch pandas.
Could you please fix this bug in PyArmor?
