### ISSUE TITLE
Strange error 88 just for "-h"

### ISSUE THREAD

**Issue by neilyoung** [dashingsoft/pyarmor#826]
While my obfuscated app generally works fine, it excepts with 

```
XXX lineno: 1113, opcode: 88
```

if I just run it to get the help screen:

```
python main.py -h
```

My script doesn't have 1113 lines.

The help screen is printed OK, but then it comes:

```
ERROR:root:Unhandled exception: Traceback (most recent call last):
  File "<frozen main>", line 989, in <module>
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/pyenv_root/versions/3.9.5/lib/python3.9/argparse.py", line 1818, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/pyenv_root/versions/3.9.5/lib/python3.9/argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/pyenv_root/versions/3.9.5/lib/python3.9/argparse.py", line 2060, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/pyenv_root/versions/3.9.5/lib/python3.9/argparse.py", line 2000, in consume_optional
    take_action(action, args, option_string)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/pyenv_root/versions/3.9.5/lib/python3.9/argparse.py", line 1928, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/pyenv_root/versions/3.9.5/lib/python3.9/argparse.py", line 1093, in __call__
    parser.exit()
  File "/home/pi/code/parrot-groundsdk/out/olympe-linux/pyenv_root/versions/3.9.5/lib/python3.9/argparse.py", line 2562, in exit
    _sys.exit(status)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "</home/pi/my-project-dist/./main.py>", line 3, in <module>
  File "<frozen main>", line 1113, in <module>
SystemError: unknown opcode
```

The script and all others has been obfuscated using pyarmor 5.9.0 for linux.aarch64 only. The obfuscation was done on an Ubuntu 20.04 github actions server, using  python version 3.9.13 (on the pi runs 3.9.5, can this be the reason?)

**Comment by neilyoung** [comment]
OK, I was able to boil it down to this simple app. It has nothing to do with 3.9.13 or 3.9.5, that's good.

I'm running it on a Raspberry PI, 64 bit, Raspberry PI OS Bullseye. The pyarmor version is 5.9.0, installed like so:

```bash
pip3 install pyarmor==5.9.0
```

This is the simple test script running on the PI:

```python
import argparse
import textwrap

parser = argparse.ArgumentParser(prog='main.py',
                                     formatter_class=lambda prog: argparse.RawDescriptionHelpFormatter(
                                         prog, max_help_position=60, width=160
                                     ),
                                     description=textwrap.dedent('''\
bla bla
copyright: (c) 2022 NY
'''))

parser._action_groups.pop()
args = parser.parse_args()

```

If I run the non-obfuscated version the output is - as expected:

```console
pi@raspberrypi:~/test $ python3 main.py -h
usage: main.py [-h]

bla bla
copyright: (c) 2022 NY

```

The obfuscation is done like so:

```bash
 pi@raspberrypi:~/test $ /home/pi/.local/bin/pyarmor obfuscate main.py
```

(don't have pyarmor in the path)

Output of the obfuscation is:

```console
INFO     PyArmor Trial Version 5.9.0
INFO     Source path is "/home/pi/test"
INFO     Entry scripts are ['main.py']
INFO     Use cached capsule /home/pi/.pyarmor_capsule.zip
INFO     Normal mode is on
INFO     Save obfuscated scripts to "dist"
INFO     Read public key from capsule
INFO     Obfuscate scripts with default mode
INFO     Advanced mode is 0
INFO     Restrict mode is 1
INFO     	main.py -> dist/main.py
INFO     Insert bootstrap code to entry script dist/main.py
INFO     1 scripts have been obfuscated
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Extract license.lic
INFO     Copying /home/pi/.pyarmor/platforms/linux/aarch64/3/_pytransform.so
INFO     Generate runtime files OK
INFO     Obfuscate scripts with restrict mode on
INFO     Obfuscate 1 scripts OK.

```

Running it from dist:

```bash
pi@raspberrypi:~/test $ cd dist
pi@raspberrypi:~/test/dist $ python3 main.py -h
usage: main.py [-h]

bla bla
copyright: (c) 2022 NY
XXX lineno: 14, opcode: 88
Traceback (most recent call last):
  File "<frozen main>", line 14, in <module>
  File "/usr/lib/python3.9/argparse.py", line 1830, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 1863, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2072, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2012, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1940, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1105, in __call__
    parser.exit()
  File "/usr/lib/python3.9/argparse.py", line 2574, in exit
    _sys.exit(status)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "</home/pi/test/dist/main.py>", line 3, in <module>
  File "<frozen main>", line 14, in <module>
SystemError: unknown opcode
pi@raspberrypi:~/test/dist $ 

```

Please provide some pointer to narrow down the issue

Thanks

**Comment by jondy** [comment]
pyarmor uses different Python version, test it
```
python3 -v
/path/to/pyarmor -d obfuscate ...
```

**Comment by neilyoung** [comment]
Python 3 version is 

`Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
`
which python3 returns

`/usr/bin/python3
`

I already have another python version in a pyenv which initially showed this symptom:

```
olympe-python3) pi@raspberrypi:~ $ which python
/home/pi/code/parrot-groundsdk/out/olympe-linux/pyenv_root/shims/python

(olympe-python3) pi@raspberrypi:~ $ python
Python 3.9.5 (default, Aug 30 2022, 17:14:30) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Where do you see a version mismatch?

**Comment by jondy** [comment]
Try to use feature `0` to obfuscate the scripts
```
PYARMOR_PLATFORM=linux.aarch64.0 pyarmor obfuscate ...
```

Or upgrade pyarmor to latest version.

**Comment by neilyoung** [comment]
Feature 0 didn't help.

And I can't use the latest version due to a problem I reported a couple of weeks ago by mail (to be more precise on July 9th)

But this was for another problem, I could give it a try on this machine... 

Will report later

**Comment by neilyoung** [comment]
Yes, the latest version fixes it:

```
pi@raspberrypi:~/test $ pyarmor -d obfuscate main.py
DEBUG    PyArmor installation path: /home/pi/.local/lib/python3.9/site-packages/pyarmor
DEBUG    PyArmor home path: /home/pi/.pyarmor
DEBUG    Native platform is linux.aarch64
DEBUG    Search dynamic library in the path: /home/pi/.local/lib/python3.9/site-packages/pyarmor/platforms
DEBUG    Search dynamic library in the path: /home/pi/.pyarmor/platforms
INFO     Search library for platform: linux.aarch64
DEBUG    Load platform list from /home/pi/.pyarmor/platforms/index.json
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/index.json
INFO     Write cached platform list file /home/pi/.pyarmor/platforms/index.json
WARNING  The trial version could not download the latest core libraries, tag r41.15a is always used. Some bugs fixed in the latest version may not be fixed in the trial version
WARNING  The core library excepted version is r51.5, but got r41.15a from platform list file /home/pi/.pyarmor/platforms/index.json
INFO     Found available libraries: ['linux.aarch64.3']
INFO     Target path for linux.aarch64.3: /home/pi/.pyarmor/platforms/linux/aarch64/3
INFO     Downloading library file for linux.aarch64.3 ...
WARNING  The trial version could not download the latest platform library
INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/armv8.64-bit/_pytransform.so
INFO     Writing target file: /home/pi/.pyarmor/platforms/linux/aarch64/3/_pytransform.so
INFO     Download dynamic library linux.aarch64.3 OK
DEBUG    Loaded dynamic library: /home/pi/.pyarmor/platforms/linux/aarch64/3/_pytransform.so
DEBUG    The version of core library is (41, 15, 3)
INFO     Generating public capsule ...
INFO     Move old capsule /home/pi/.pyarmor/../.pyarmor_capsule.zip to /home/pi/.pyarmor/.pyarmor_capsule.zip
INFO     PyArmor Trial Version 7.6.1
INFO     Python 3.9.2
INFO     Target platforms: Native
INFO     Source path is "/home/pi/test"
INFO     Entry scripts are ['main.py']
INFO     Use cached capsule /home/pi/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Obfuscate string value is False
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Update capsule to add default license file
INFO     Copying /home/pi/.pyarmor/platforms/linux/aarch64/3/_pytransform.so
INFO     Patch library dist/pytransform/_pytransform.so
DEBUG    Patching dist/pytransform/_pytransform.so
DEBUG    Found pattern at a82e4
DEBUG    Patch 320 bytes from a8304
DEBUG    Patch 140 bytes from a8444
DEBUG    Patch 224 bytes from a84d0
INFO     Patch library file OK
INFO     Copying /home/pi/.local/lib/python3.9/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO     	main.py -> dist/main.py
INFO     Write patched script for debugging: /home/pi/test/main.py.pyarmor-patched
INFO     Insert bootstrap code to entry script dist/main.py
INFO     Obfuscate 1 scripts OK.
pi@raspberrypi:~/test $ cd dist
pi@raspberrypi:~/test/dist $ python3 main.py -h
usage: main.py [-h]

bla bla
copyright: (c) 2022 NY
pi@raspberrypi:~/test/dist $ 

```

**Comment by neilyoung** [comment]
...even though there are some error messages... To be concerned about?

**Comment by neilyoung** [comment]
No, this latest version doesn't work on github actions:


```
2022-08-31T15:00:36.5268920Z DEBUG    PyArmor installation path: /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pyarmor
2022-08-31T15:00:36.5270882Z DEBUG    PyArmor home path: /home/runner/.pyarmor
2022-08-31T15:00:36.5272946Z INFO     Create pyarmor home path: /home/runner/.pyarmor
2022-08-31T15:00:36.5275279Z INFO     Create trial license file: /home/runner/.pyarmor/license.lic
2022-08-31T15:00:36.5285755Z DEBUG    Native platform is linux.x86_64
2022-08-31T15:00:36.5287910Z DEBUG    Search dynamic library in the path: /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pyarmor/platforms
2022-08-31T15:00:36.5880567Z DEBUG    Loaded dynamic library: /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
2022-08-31T15:00:36.5881300Z DEBUG    The version of core library is (51, 5, 7)
2022-08-31T15:00:36.5947897Z INFO     Generating public capsule ...
2022-08-31T15:00:36.5948872Z DEBUG    Copy /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pyarmor/public_capsule.zip to /home/runner/.pyarmor/.pyarmor_capsule.zip
2022-08-31T15:00:36.5949350Z DEBUG    Generate public capsule /home/runner/.pyarmor/.pyarmor_capsule.zip OK.
2022-08-31T15:00:36.5949674Z INFO     PyArmor Trial Version 7.6.1
2022-08-31T15:00:36.5951242Z INFO     Python 3.9.13
2022-08-31T15:00:36.5952815Z INFO     Target platforms: ['linux.aarch64']
2022-08-31T15:00:36.5953437Z DEBUG    Load platform list from /home/runner/.pyarmor/platforms/index.json
2022-08-31T15:00:36.5954224Z WARNING  The trial version could not download the latest platform library
2022-08-31T15:00:36.5955153Z INFO     Getting remote file: https://github.com/dashingsoft/pyarmor-core/raw/r41.15a/platforms/index.json
2022-08-31T15:00:36.9540233Z INFO     Create platform path: /home/runner/.pyarmor/platforms
2022-08-31T15:00:36.9542297Z INFO     Write cached platform list file /home/runner/.pyarmor/platforms/index.json
2022-08-31T15:00:36.9674469Z Traceback (most recent call last):
2022-08-31T15:00:36.9692233Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/bin/pyarmor", line 8, in <module>
2022-08-31T15:00:36.9692598Z     sys.exit(main_entry())
2022-08-31T15:00:36.9693320Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pyarmor/pyarmor.py", line 1608, in main_entry
2022-08-31T15:00:36.9693677Z     main(sys.argv[1:])
2022-08-31T15:00:36.9694153Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pyarmor/pyarmor.py", line 1600, in main
2022-08-31T15:00:36.9694474Z     args.func(args)
2022-08-31T15:00:36.9694959Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pyarmor/pyarmor.py", line 589, in _obfuscate
2022-08-31T15:00:36.9695380Z     platforms = check_cross_platform(platforms, supermode, vmenabled)
2022-08-31T15:00:36.9695955Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pyarmor/utils.py", line 1211, in check_cross_platform
2022-08-31T15:00:36.9696580Z     platid = _get_preferred_platid(name, features=features)
2022-08-31T15:00:36.9697158Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pyarmor/utils.py", line 1176, in _get_preferred_platid
2022-08-31T15:00:36.9697640Z     plist = [x['id'] for x in _get_platform_list() if x['name'] == name]
2022-08-31T15:00:36.9698207Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pyarmor/utils.py", line 258, in _get_platform_list
2022-08-31T15:00:36.9698570Z     raise RuntimeError(
2022-08-31T15:00:36.9698983Z RuntimeError: The trial version pyarmor could not work, please use pyarmor < v7.0.0. For example, install latest work version by this command: pip install pyarmor=6.8.1
2022-08-31T15:00:36.9803156Z ##[error]Process completed with exit code 1.
2022-08-31T15:00:36.9862643Z Post job cleanup.
```

I will try to install 6.8.1 as suggested, but wtf...

**Comment by neilyoung** [comment]
It's getting "better" with each attempt.... 6.8.1:

```
RuntimeError: Too big code object, the limitation is 32768 bytes in trial version
```

**Comment by jondy** [comment]
Please check EULA of pyarmor for trial version limitations.

**Comment by neilyoung** [comment]
Forgot to report that I managed to deploy my license. It works now with 6.8.1
