### ISSUE TITLE
[BUG] flask 项目使用 pyarmor 加密之后, 无法自定义日志输出格式

### ISSUE THREAD

**Issue by YufengSoft** [dashingsoft/pyarmor#871]
以下是一个简单的代码示例：

main.py 文件内容：

`
import logging
from flask import Flask

app = Flask(__name__)

app.logger.setLevel(logging.DEBUG)
formatter = logging.Formatter("[%(asctime)s] [%(levelname)s] [%(filename)s:%(lineno)d] >>> %(message)s")
streamHandler = logging.StreamHandler()
streamHandler.setLevel(logging.DEBUG)
streamHandler.setFormatter(formatter)
app.logger.addHandler(streamHandler)

app.logger.info("test")

app.run(host="0.0.0.0", port=9000)
`

加密代码：
`pyarmor obfuscate main.py`

运行加密后的代码报错：
`
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Python310\lib\logging\__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "C:\Python310\lib\logging\__init__.py", line 650, in formatMessage
    return self._style.format(record)
  File "C:\Python310\lib\logging\__init__.py", line 440, in format
    return self._format(record)
  File "C:\Python310\lib\logging\__init__.py", line 436, in _format
    return self._fmt % values
TypeError: %d format: a real number is required, not NoneType
`

测试下来貌似是 %(filename)s, %(lineno)d 的问题

**Comment by jondy** [comment]
有可能是加密脚本的 lineno 无法获取到，请查看加密脚本和原脚本的区别，如果日志使用到了这些受影响的特性，会出现错误
https://pyarmor.readthedocs.io/zh/latest/understand-obfuscated-scripts.html#id18
