### ISSUE TITLE
Please add py3.11 runtimes :)

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#873]
As topic states, please add py3.11 runtimes

Thanks :)

**Comment by jondy** [comment]
The default mode (without `--advanced`) should work with python3.11

For super mode and spp mode, it may not support python 3.11+, because it need write private PyEval_Frame for each Python minor version.

I'm developing a new mode based on spp mode to support Python 3.7+, it works with the latest Python. It may be released in  several months.

**Comment by bvanelli** [comment]
I does not work for me, here is the log:

```
INFO     PyArmor Version 7.7.0
INFO     Python 3.11.0
INFO     Prepare to pack obfuscated scripts with PyInstaller...
INFO     entry script: data_collector_async/collector.py
INFO     src for searching scripts: data_collector_async
INFO     build path: dist/obf
INFO     Run PyArmor to obfuscate scripts...
INFO     
/usr/local/bin/python /usr/local/lib/python3.11/site-packages/pyarmor/pyarmor.py obfuscate -O dist/obf --package-runtime 0 -r --exclude dist data_collector_async/collector.py
INFO     ==================== Run command ====================
INFO     PyArmor Version 7.7.0
INFO     Python 3.11.0
INFO     Target platforms: Native
INFO     Source path is "/builds/dev/data-collector/data_collector_async"
INFO     Entry scripts are ['data_collector_async/collector.py']
INFO     Use cached capsule /root/.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Recursive
INFO     Exclude path "dist"
no previously-included directories found matching 'dist'
INFO     Save obfuscated scripts to "dist/obf"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Obfuscate string value is False
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Super plus mode is not enabled
INFO     Generating runtime files to dist/obf
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Update capsule to add default license file
INFO     Copying /usr/local/lib/python3.11/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
INFO     Patch library dist/obf/_pytransform.so
INFO     Patch library file OK
INFO     Copying /usr/local/lib/python3.11/site-packages/pyarmor/pytransform.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO     	collector.py -> dist/obf/collector.py
INFO     Patch this entry script with protection code
ERROR    Run command failed
```

The same succeeds on python 3.9 and 3.10.

**Comment by jondy** [comment]
@bvanelli  what's about obfuscating a simple script with Python 3.11 and option `-d`?
```
pyarmor --debug obfuscate --exact foo.py
```
Is there any extra information in the debug log?

**Comment by bvanelli** [comment]
I wrote a simple script:

```Dockerfile
FROM python:3.11-slim-bullseye
COPY . /build
WORKDIR /build
RUN apt-get update && apt-get install -y binutils && pip install pyarmor===7.7.0 pyinstaller===5.5
RUN pyarmor -d obfuscate --exact test.py
```

test.py
```python
print("hello world")
```

Here is the log

```
 > [5/6] RUN pyarmor -d obfuscate --exact test.py:
#9 1.169 DEBUG    PyArmor installation path: /usr/local/lib/python3.11/site-packages/pyarmor
#9 1.169 DEBUG    PyArmor home path: /root/.pyarmor
#9 1.169 INFO     Create pyarmor home path: /root/.pyarmor
#9 1.170 INFO     Create trial license file: /root/.pyarmor/license.lic
#9 1.171 DEBUG    Native platform is linux.x86_64
#9 1.171 DEBUG    Search dynamic library in the path: /usr/local/lib/python3.11/site-packages/pyarmor/platforms
#9 1.256 DEBUG    Loaded dynamic library: /usr/local/lib/python3.11/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
#9 1.256 DEBUG    The version of core library is (52, 6, 7)
#9 1.256 INFO     Generating public capsule ...
#9 1.256 DEBUG    Copy /usr/local/lib/python3.11/site-packages/pyarmor/public_capsule.zip to /root/.pyarmor/.pyarmor_capsule.zip
#9 1.257 DEBUG    Generate public capsule /root/.pyarmor/.pyarmor_capsule.zip OK.
#9 1.257 INFO     PyArmor Trial Version 7.7.0
#9 1.257 INFO     Python 3.11.0
#9 1.257 INFO     Target platforms: Native
#9 1.257 INFO     Source path is "/build"
#9 1.258 INFO     Entry scripts are ['test.py']
#9 1.258 INFO     Use cached capsule /root/.pyarmor/.pyarmor_capsule.zip
#9 1.258 INFO     Search scripts mode: Exact
#9 1.258 INFO     Save obfuscated scripts to "dist"
#9 1.258 INFO     Read product key from capsule
#9 1.259 INFO     Obfuscate module mode is 2
#9 1.259 INFO     Obfuscate code mode is 1
#9 1.259 INFO     Obfuscate string value is False
#9 1.260 INFO     Wrap mode is 1
#9 1.260 INFO     Restrict mode is 1
#9 1.260 INFO     Advanced value is 0
#9 1.260 INFO     Super mode is False
#9 1.260 INFO     Super plus mode is not enabled
#9 1.260 INFO     Generating runtime files to dist/pytransform
#9 1.261 INFO     Extract pytransform.key
#9 1.261 INFO     Generate default license file
#9 1.262 INFO     Update capsule to add default license file
#9 1.263 INFO     Copying /usr/local/lib/python3.11/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
#9 1.264 INFO     Patch library dist/pytransform/_pytransform.so
#9 1.264 DEBUG    Patching dist/pytransform/_pytransform.so
#9 1.446 DEBUG    Found pattern at c4384
#9 1.446 DEBUG    Patch 320 bytes from c43a4
#9 1.446 DEBUG    Patch 140 bytes from c44e4
#9 1.446 DEBUG    Patch 224 bytes from c4570
#9 1.448 INFO     Patch library file OK
#9 1.461 INFO     Copying /usr/local/lib/python3.11/site-packages/pyarmor/pytransform.py
#9 1.461 INFO     Rename it to pytransform/__init__.py
#9 1.462 INFO     Generate runtime files OK
#9 1.462 INFO     Start obfuscating the scripts...
#9 1.462 INFO           /build/test.py -> dist/test.py
#9 1.462 INFO     Write patched script for debugging: /build/test.py.pyarmor-patched
#9 1.507 Bus error
------
executor failed running [/bin/sh -c pyarmor -d obfuscate --exact test.py]: exit code: 135
```

Here is the log using instead build for the simple script (the command was `RUN pyarmor -d pack -O dist -n test test.py`)

```
#10 1.135 DEBUG    PyArmor installation path: /usr/local/lib/python3.11/site-packages/pyarmor
#10 1.135 DEBUG    PyArmor home path: /root/.pyarmor
#10 1.136 INFO     Create pyarmor home path: /root/.pyarmor
#10 1.136 INFO     Create trial license file: /root/.pyarmor/license.lic
#10 1.138 DEBUG    Native platform is linux.x86_64
#10 1.138 DEBUG    Search dynamic library in the path: /usr/local/lib/python3.11/site-packages/pyarmor/platforms
#10 1.234 DEBUG    Loaded dynamic library: /usr/local/lib/python3.11/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
#10 1.234 DEBUG    The version of core library is (52, 6, 7)
#10 1.234 INFO     Generating public capsule ...
#10 1.234 DEBUG    Copy /usr/local/lib/python3.11/site-packages/pyarmor/public_capsule.zip to /root/.pyarmor/.pyarmor_capsule.zip
#10 1.235 DEBUG    Generate public capsule /root/.pyarmor/.pyarmor_capsule.zip OK.
#10 1.235 INFO     PyArmor Trial Version 7.7.0
#10 1.235 INFO     Python 3.11.0
#10 1.236 INFO     Prepare to pack obfuscated scripts with PyInstaller...
#10 1.236 INFO     entry script: test.py
#10 1.236 INFO     src for searching scripts: .
#10 1.236 INFO     build path: dist/obf
#10 1.236 INFO     Run PyArmor to obfuscate scripts...
#10 1.237 INFO
#10 1.237
#10 1.237 /usr/local/bin/python /usr/local/lib/python3.11/site-packages/pyarmor/pyarmor.py obfuscate -O dist/obf --package-runtime 0 -r --exclude dist ./test.py
#10 1.237
#10 1.237
#10 1.237 INFO     ==================== Run command ====================
#10 1.617 INFO     PyArmor Trial Version 7.7.0
#10 1.617 INFO     Python 3.11.0
#10 1.617 INFO     Target platforms: Native
#10 1.617 INFO     Source path is "/build"
#10 1.617 INFO     Entry scripts are ['./test.py']
#10 1.618 INFO     Use cached capsule /root/.pyarmor/.pyarmor_capsule.zip
#10 1.618 INFO     Search scripts mode: Recursive
#10 1.618 INFO     Exclude path "dist"
#10 1.618 INFO     Auto exclude output path "dist/obf"
#10 1.619 no previously-included directories found matching 'dist'
#10 1.619 no previously-included directories found matching 'dist/obf'
#10 1.619 INFO     Save obfuscated scripts to "dist/obf"
#10 1.620 INFO     Read product key from capsule
#10 1.621 INFO     Obfuscate module mode is 2
#10 1.621 INFO     Obfuscate code mode is 1
#10 1.621 INFO     Obfuscate string value is False
#10 1.621 INFO     Wrap mode is 1
#10 1.621 INFO     Restrict mode is 1
#10 1.621 INFO     Advanced value is 0
#10 1.621 INFO     Super mode is False
#10 1.621 INFO     Super plus mode is not enabled
#10 1.622 INFO     Generating runtime files to dist/obf
#10 1.622 INFO     Extract pytransform.key
#10 1.623 INFO     Generate default license file
#10 1.624 INFO     Update capsule to add default license file
#10 1.624 INFO     Copying /usr/local/lib/python3.11/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
#10 1.625 INFO     Patch library dist/obf/_pytransform.so
#10 1.821 INFO     Patch library file OK
#10 1.835 INFO     Copying /usr/local/lib/python3.11/site-packages/pyarmor/pytransform.py
#10 1.836 INFO     Generate runtime files OK
#10 1.836 INFO     Start obfuscating the scripts...
#10 1.836 INFO          test.py -> dist/obf/test.py
#10 1.883 Traceback (most recent call last):
#10 1.883   File "/usr/local/bin/pyarmor", line 8, in <module>
#10 1.883     sys.exit(main_entry())
#10 1.883              ^^^^^^^^^^^^
#10 1.883   File "/usr/local/lib/python3.11/site-packages/pyarmor/pyarmor.py", line 1608, in main_entry
#10 1.884     main(sys.argv[1:])
#10 1.884   File "/usr/local/lib/python3.11/site-packages/pyarmor/pyarmor.py", line 1600, in main
#10 1.884     args.func(args)
#10 1.884   File "/usr/local/lib/python3.11/site-packages/pyarmor/packer.py", line 641, in packer
#10 1.884     _pyinstaller(src, entry, output, extra_options, xoptions, args)
#10 1.885   File "/usr/local/lib/python3.11/site-packages/pyarmor/packer.py", line 471, in _pyinstaller
#10 1.885     call_pyarmor(['obfuscate', '-O', obfdist, '--package-runtime', '0',
#10 1.885   File "/usr/local/lib/python3.11/site-packages/pyarmor/packer.py", line 176, in call_pyarmor
#10 1.885     run_command([sys.executable, s] + list(args))
#10 1.885   File "/usr/local/lib/python3.11/site-packages/pyarmor/packer.py", line 86, in run_command
#10 1.885     raise RuntimeError('Run command failed')
#10 1.885 RuntimeError: Run command failed
------
executor failed running [/bin/sh -c pyarmor -d pack -O dist -n test test.py]: exit code: 1
```

Changing the container to python 3.10 works, here is the log for obfuscate:

```
#9 [5/6] RUN pyarmor -d obfuscate --exact test.py
#9 sha256:c878118d1321f4b71763f653179864c4afc6b466798470d1fb3f8fc38eb08639
#9 1.143 DEBUG    PyArmor installation path: /usr/local/lib/python3.10/site-packages/pyarmor
#9 1.143 DEBUG    PyArmor home path: /root/.pyarmor
#9 1.143 INFO     Create pyarmor home path: /root/.pyarmor
#9 1.144 INFO     Create trial license file: /root/.pyarmor/license.lic
#9 1.145 DEBUG    Native platform is linux.x86_64
#9 1.145 DEBUG    Search dynamic library in the path: /usr/local/lib/python3.10/site-packages/pyarmor/platforms
#9 1.239 DEBUG    Loaded dynamic library: /usr/local/lib/python3.10/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
#9 1.239 DEBUG    The version of core library is (52, 6, 7)
#9 1.239 INFO     Generating public capsule ...
#9 1.240 DEBUG    Copy /usr/local/lib/python3.10/site-packages/pyarmor/public_capsule.zip to /root/.pyarmor/.pyarmor_capsule.zip
#9 1.240 DEBUG    Generate public capsule /root/.pyarmor/.pyarmor_capsule.zip OK.
#9 1.240 INFO     PyArmor Trial Version 7.7.0
#9 1.240 INFO     Python 3.10.8
#9 1.240 INFO     Target platforms: Native
#9 1.241 INFO     Source path is "/build"
#9 1.241 INFO     Entry scripts are ['test.py']
#9 1.241 INFO     Use cached capsule /root/.pyarmor/.pyarmor_capsule.zip
#9 1.241 INFO     Search scripts mode: Exact
#9 1.241 INFO     Save obfuscated scripts to "dist"
#9 1.242 INFO     Read product key from capsule
#9 1.243 INFO     Obfuscate module mode is 2
#9 1.243 INFO     Obfuscate code mode is 1
#9 1.243 INFO     Obfuscate string value is False
#9 1.243 INFO     Wrap mode is 1
#9 1.243 INFO     Restrict mode is 1
#9 1.244 INFO     Advanced value is 0
#9 1.244 INFO     Super mode is False
#9 1.244 INFO     Super plus mode is not enabled
#9 1.244 INFO     Generating runtime files to dist/pytransform
#9 1.245 INFO     Extract pytransform.key
#9 1.245 INFO     Generate default license file
#9 1.246 INFO     Update capsule to add default license file
#9 1.247 INFO     Copying /usr/local/lib/python3.10/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
#9 1.250 INFO     Patch library dist/pytransform/_pytransform.so
#9 1.250 DEBUG    Patching dist/pytransform/_pytransform.so
#9 1.464 DEBUG    Found pattern at c4384
#9 1.464 DEBUG    Patch 320 bytes from c43a4
#9 1.464 DEBUG    Patch 140 bytes from c44e4
#9 1.464 DEBUG    Patch 224 bytes from c4570
#9 1.466 INFO     Patch library file OK
#9 1.488 INFO     Copying /usr/local/lib/python3.10/site-packages/pyarmor/pytransform.py
#9 1.488 INFO     Rename it to pytransform/__init__.py
#9 1.489 INFO     Generate runtime files OK
#9 1.489 INFO     Start obfuscating the scripts...
#9 1.489 INFO           /build/test.py -> dist/test.py
#9 1.489 INFO     Write patched script for debugging: /build/test.py.pyarmor-patched
#9 1.534 INFO     Insert bootstrap code to entry script dist/test.py
#9 1.534 INFO     Obfuscate 1 scripts OK.
#9 DONE 1.6s
```

**Comment by jondy** [comment]
I'll check it.

**Comment by bvanelli** [comment]
> I'll check it.

Hello @jondy , did you have the time to take a look? Do you know when is a first release of a python 3.11 compliant wheel to come?

Best regards,
Brunno

**Comment by jondy** [comment]
Python 3.11 changes a lot, the first release for python 3.11 may be released in next month.

**Comment by VeNoMouS** [comment]
> Python 3.11 changes a lot, the first release for python 3.11 may be released in next month.

will this release have advanced modes? or it basic support only at first?

**Comment by jondy** [comment]
It's a new mode. And since Python 3.11, as my plan, only spp mode and this new mode is supported, super mode (`--advanced 2`) may not be supported since Python 3.11. Because in Python 3.11 PyCodeObject is changed a lot, I prefer to design a new mode, upgrading super mode need more effects.

**Comment by VeNoMouS** [comment]
Hi @jondy 

Do you have an update / timeline for the new pyarmor obfuscation methods and new runtimes?

**Comment by jondy** [comment]
@VeNoMouS 
Here it's a simple release plan
https://github.com/dashingsoft/pyarmor#release-plan

**Comment by SamComber** [comment]
Hey @jondy are there any pre-release 8.0 version we can use for now? Really keen to begin testing pyarmor 8+ with our stack

**Comment by jondy** [comment]
Sorry, there is no pre-release 8.0 before March, 1, there are still lot of code need to do.

**Comment by VeNoMouS** [comment]
Hi @jondy,

I'm sure you busy as, how are we looking at the release timeline you've given for version 8? my understanding we will need to purchase new licenses too correct?

**Comment by elstrm** [comment]
> 

New EULA

The big changes of EULA for Pyarmor 8.0+

    For non-profit usage, one license is OK.
    For commercial usage, one product one license.

There are only 2 new license types for Pyarmor 8.0+

    pyarmor-basic, one license price 52$
    pyarmor-pro, one license price 89$

The main differences for each type

    pyarmor-pro: 2 irreversible obfuscation modes BCC/RFT
    pyarmor-basic: no BCC/RFT modes
    pyarmor trial version: can't obfuscate big file

The old license code starts with "pyarmor-vax-" could be upgraded to pyarmor-basic without extra fee following new EULA. If it's personal license type, it need provide the product name bind to pyarmor-basic for commercial usage.

**Comment by elstrm** [comment]
> Hi @jondy,
> 
> I'm sure you busy as, how are we looking at the release timeline you've given for version 8? my understanding we will need to purchase new licenses too correct?

Old license -> new license, want more than this? buy pro

**Comment by VeNoMouS** [comment]
So the question is, when is 8.0 getting released and are the new licenses available for purchase?

**Comment by elstrm** [comment]
> So the question is, when is 8.0 getting released and are the new licenses available for purchase?

you cannot purchase and Pyarmor 8.0 release date is about 2023-03-08 (March 8, 2023) (delay one week). from github page of pyarmor.

**Comment by VeNoMouS** [comment]
> > So the question is, when is 8.0 getting released and are the new licenses available for purchase?
> 
> you cannot purchase and Pyarmor 8.0 release date is about 2023-03-08 (March 8, 2023) (delay one week). from github page of pyarmor.

ah that was only added yesterday after i posted on this ticket ;P i checked his readme changelog ;) 

All good we can wait :)

**Comment by jondy** [comment]
Pyarmor 8.2.0 should work for Python 3.11
