### ISSUE TITLE
[BUG] Bug while packing with --mix-str

### ISSUE THREAD

**Issue by kr1tx** [dashingsoft/pyarmor#908]
**After packing with the following command**

```pyarmor pack --with-license licenses\new\license.lic -x " --mix-str  --advanced 1 --plugin check_ntp_time" -e " --onefile --icon icon.ico" Script.py```

**I encounter the following error after packing successfully**
```
File "Script.py", line 4, in <module>
  File "<frozen Script>", line 202, in <module>
  File "<frozen Script>", line -1, in NTPException
NameError: name 'utf' is not defined
```
**Note that:** If I removed the ```--mix-str``` option the code will run with no problems at all after packing.

I have implemented these lines at the beginning of my code
```
# -*- coding: utf-8 -*-
# {PyArmor Plugins}
# PyArmor Plugin: check_ntp_time()
```
Any help?

**Comment by jondy** [comment]
What's line 202 of "Script.py"?

**Comment by kr1tx** [comment]
The problem is not in my code. Even with the following command the same error still persist `pyarmor obfuscate Script.py --mix-str`
I ran this command on a very simple script:
```
1. # -*- coding: utf-8 -*-
2. 
3. print("ok")
```
And still. I get the same error Whenever I run the script **after a successful Obfuscation**:
```
Traceback (most recent call last):
  File "<Script.py>", line 3, in <module>
  File "<frozen Script>", line -1, in <module>
NameError: name 'utf' is not defined
```

**Comment by jondy** [comment]
Which pyarmor version is used? I can't reproduce it in the latest version 7.7.4

**Comment by kr1tx** [comment]
I am using **PyArmor Version 7.7.4**

**Comment by kr1tx** [comment]
Python version used is **Python 3.10.8**

**Comment by jondy** [comment]
This patch e9b10f0936f2a26e549eac36e30313e356472e21 is a quick workaroud:

**Comment by kr1tx** [comment]
When will major version 8.0 be released? 
I have another issue, So if I tired to use `--advanced 5` I'll get this error `ERROR    No available c compiler found`
I already have a c compiler and I have added it to PATH, My c compiler is located at **_C:\MinGW\bin_**
Any help?

**Comment by jondy** [comment]
Here it's a simple release plan
https://github.com/dashingsoft/pyarmor#release-plan

Here it's how pyarmor to find c compiler, check it to find the solution
https://github.com/dashingsoft/pyarmor/blob/master/src/sppmode.py#L85

**Comment by kr1tx** [comment]
**Thanks! You were truly helpful.**
Sadly I am facing a new issue.. So If I tried to obfuscate a script using the following command: `pyarmor obfuscate --with-license licenses\new\license.lic --mix-str --advanced 5 --plugin check_ntp_time hello.py` the script will be obfuscated successfully but it would close after I run it. **Without showing any error or so.**

**The script used:**
```
# -*- coding: utf-8 -*-
# {PyArmor Plugins}
# PyArmor Plugin: check_ntp_time()


print("ok")
```

I tried removing `--plugin check_ntp_time` and the script worked after a successful obfuscation.
The problem is I need my software to be time-limited. I apologize for the oversight If there's something I have missed.

**Comment by kr1tx** [comment]
Removing `**--mix-str**` and keeping `--plugin check_ntp_time` Fixes the issue..: `pyarmor obfuscate --with-license licenses\new\license.lic --advanced 5 --plugin check_ntp_time hello.py`

**Comment by kr1tx** [comment]
Hey @jondy this problem still persists. Such script would not work
The commands used: pyarmor-7 pack --with-license licenses\new\license.lic -x " --mix-str --advanced 5 --plugin check_ntp_time" -e " --onefile --icon fuse.ico" Script.py
```
# -*- coding: utf-8 -*-
# {PyArmor Plugins}
# PyArmor Plugin: check_ntp_time()
"""it all done, you can rest now 1:48 PM"""
print("hello friend.")
```

**Comment by jondy** [comment]
What's the error message?

**Comment by kr1tx** [comment]
I get no errors, the script just exits.

**Comment by kr1tx** [comment]
@jondy hello?

**Comment by jondy** [comment]
I'll fix 7.x bug later.  This will be fixed in 8.1
