### ISSUE TITLE
ERROR    DLL load failed while importing pytransform3: 找不到指定的模块。

### ISSUE THREAD

**Issue by jekoie** [dashingsoft/pyarmor#971]
```console
PS E:\test>
PS E:\test> pyarmor.exe gen .\tt.py
INFO     Python 3.8.10
INFO     Pyarmor 8.0 (trial), 000000, non-profits
INFO     search inputs ...
INFO     find script .\tt.py
INFO     find 1 top resources
CRITICAL unknown error, please check pyarmor.error.log
ERROR    DLL load failed while importing pytransform3: 找不到指定的模块。
PS E:\test>
```

### pyarmor.error.log
```python
18172 MainProcess 2023-03-14 11:33:42,355
Traceback (most recent call last):
  File "C:\Users\jekoi\AppData\Local\Programs\Python\Python38\lib\site-packages\pyarmor\cli\__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "C:\Users\jekoi\AppData\Local\Programs\Python\Python38\lib\site-packages\pyarmor\cli\__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "C:\Users\jekoi\AppData\Local\Programs\Python\Python38\lib\site-packages\pyarmor\cli\__main__.py", line 144, in cmd_gen
    builder.process(options, pack=args.pack)
  File "C:\Users\jekoi\AppData\Local\Programs\Python\Python38\lib\site-packages\pyarmor\cli\generate.py", line 143, in process
    Pytransform3.pre_build(self.ctx)
  File "C:\Users\jekoi\AppData\Local\Programs\Python\Python38\lib\site-packages\pyarmor\cli\core\__init__.py", line 62, in pre_build
    m = Pytransform3.init(ctx)
  File "C:\Users\jekoi\AppData\Local\Programs\Python\Python38\lib\site-packages\pyarmor\cli\core\__init__.py", line 39, in init
    from . import pytransform3 as m
ImportError: DLL load failed while importing pytransform3: 找不到指定的模块。

```

**Comment by jondy** [comment]
Pyarmor 8.0.x new features now only support x86_64 platforms.
