### ISSUE TITLE
[BUG] RuntimeError: unknown license type

### ISSUE THREAD

**Issue by VeNoMouS** [dashingsoft/pyarmor#972]
When following license instructions with 
```
pyarmor reg -p helheim pyarmor-regcode-5005.txt
```

```
INFO     Python 3.9.2
INFO     Pyarmor 8.0 (trial), 000000, non-profits
INFO     prepare "/samba/ext4/pyarmor-regcode-5005.txt"
INFO     query key file from server
CRITICAL unknown error, please check pyarmor.error.log
ERROR    unknown license type
```

Generates the error log...
```
881064 MainProcess 2023-03-14 20:51:47,604
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/cli/__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/cli/__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/cli/__main__.py", line 178, in cmd_reg
    msg = regsvr.prepare(regfile, args.product, upgrade=args.upgrade)
  File "/usr/local/lib/python3.9/dist-packages/pyarmor/cli/register.py", line 253, in prepare
    raise RuntimeError('unknown license type %s' % info['lictype'])
```

**Comment by jondy** [comment]
got it, I'll check it.

**Comment by jondy** [comment]
In this case, it could not be upgraded. Please check this
https://pyarmor.readthedocs.io/en/latest/licenses.html#upgrading-old-license

**Comment by VeNoMouS** [comment]
I didnt try upgrade its a brand new license...

**Comment by jondy** [comment]
Fixed. Registering pro-license should work now.
