### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by stamshem** [dashingsoft/pyarmor#973]
PS C:\Users\user\Desktop> pyarmor gen .\dasd.py
INFO     Python 3.11.2
INFO     Pyarmor 8.0 (trial), 000000, non-profits
INFO     search inputs ...
INFO     find script .\dasd.py
INFO     find 1 top resources
CRITICAL unknown error, please check pyarmor.error.log
ERROR    [Errno 2] No such file or directory: 'C:\\Users\\user\\.pyarmor\\.pyarmor_capsule.zip'

**Comment by jondy** [comment]
Could you copy the content of pyarmor.error.log here?

**Comment by loverstamp** [comment]
@jondy same error with me.
`$ cat pyarmor.error.log 
7353 MainProcess 2023-03-15 15:19:46,402
Traceback (most recent call last):
  File "/home/mona/.local/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "/home/mona/.local/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "/home/mona/.local/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 144, in cmd_gen
    builder.process(options, pack=args.pack)
  File "/home/mona/.local/lib/python3.8/site-packages/pyarmor/cli/generate.py", line 145, in process
    self.ctx.runtime_key = self.generate_runtime_key()
  File "/home/mona/.local/lib/python3.8/site-packages/pyarmor/cli/generate.py", line 83, in generate_runtime_key
    return Pytransform3.generate_runtime_key(self.ctx, outer)
  File "/home/mona/.local/lib/python3.8/site-packages/pyarmor/cli/core/__init__.py", line 58, in generate_runtime_key
    return m.generate_runtime_key(ctx, outer)
  File "<maker>", line 723, in generate_runtime_key
  File "<maker>", line 234, in build
  File "/data/miniconda3/envs/whaler/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mona/.pyarmor/.pyarmor_capsule.zip'`

**Comment by jondy** [comment]
Fix it in 8.0.4

**Comment by Silur** [comment]
Issue still present in 8.0.5

**Comment by Crysiz2631** [comment]
i get the same error

`11592 MainProcess 2023-03-21 16:42:02,194
Traceback (most recent call last):
  File "c:\users\chris\appdata\local\programs\python\python38\lib\site-packages\pyarmor\cli\__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "c:\users\chris\appdata\local\programs\python\python38\lib\site-packages\pyarmor\cli\__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "c:\users\chris\appdata\local\programs\python\python38\lib\site-packages\pyarmor\cli\__main__.py", line 144, in cmd_gen
    builder.process(options, pack=args.pack)
  File "c:\users\chris\appdata\local\programs\python\python38\lib\site-packages\pyarmor\cli\generate.py", line 145, in process
    self.ctx.runtime_key = self.generate_runtime_key()
  File "c:\users\chris\appdata\local\programs\python\python38\lib\site-packages\pyarmor\cli\generate.py", line 83, in generate_runtime_key
    return Pytransform3.generate_runtime_key(self.ctx, outer)
  File "c:\users\chris\appdata\local\programs\python\python38\lib\site-packages\pyarmor\cli\core\__init__.py", line 58, in generate_runtime_key
    return m.generate_runtime_key(ctx, outer)
  File "<maker>", line 723, in generate_runtime_key
  File "<maker>", line 234, in build
  File "c:\users\chris\appdata\local\programs\python\python38\lib\site-packages\pyarmor\cli\context.py", line 263, in private_capsule
    copy(public_capsule, filename)
  File "c:\users\chris\appdata\local\programs\python\python38\lib\shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\users\chris\appdata\local\programs\python\python38\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\chris\\.pyarmor\\.pyarmor_capsule.zip'
`
