### ISSUE TITLE
[BUG] upgrade license

### ISSUE THREAD

**Issue by nblog** [dashingsoft/pyarmor#977]
pyarmor.error.log
```
4960 MainProcess 2023-03-15 21:14:32,255
Traceback (most recent call last):
  File "c:\python\python38\lib\site-packages\pyarmor\cli\__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "c:\python\python38\lib\site-packages\pyarmor\cli\__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "c:\python\python38\lib\site-packages\pyarmor\cli\__main__.py", line 178, in cmd_reg
    msg = regsvr.prepare(regfile, args.product, upgrade=args.upgrade)
  File "c:\python\python38\lib\site-packages\pyarmor\cli\register.py", line 240, in prepare
    raise RuntimeError(
RuntimeError: product name has been set to "non-profits"
```

```
INFO     Python 3.8.10
INFO     Pyarmor 8.0 (trial), 000000, non-profits
INFO     prepare "pyarmor-regcode-to-pro.txt"
INFO     query key file from server
CRITICAL unknown error, please check pyarmor.error.log
ERROR    product name has been set to "non-profits"
```

 Pyarmor 升级版(个人), 按照步骤使用`pyarmor reg -u pyarmor-regcode-to-pro.txt`时, 报错.

**Comment by nblog** [comment]
```
INFO     Python 3.8.10
INFO     Pyarmor 8.0 (trial), 000000, non-profits
INFO     prepare "pyarmor-regcode-to-pro.txt"
INFO     query key file from server
CRITICAL unknown error, please check pyarmor.error.log
ERROR    product name has been set to "non-profits"
```

**Comment by jondy** [comment]
Using latest version 8.0.5.

**Comment by nblog** [comment]
@jondy 
first: 
```
Are you sure to continue? (yes/no) yes
INFO     process upgrading file "pyarmor-regcode-to-pro.txt"
INFO     old license no: pyarmor-vax-001112
INFO     send upgrade request to server
INFO     update license token
CRITICAL unknown error, please check pyarmor.error.log
ERROR    DLL load failed while importing pytransform3: 找不到指定的模块。
```

second
```
Are you sure to continue? (yes/no) yes
INFO     process upgrading file "pyarmor-regcode-to-pro.txt"
INFO     old license no: pyarmor-vax-001112
INFO     send upgrade request to server
CRITICAL unknown error, please check pyarmor.error.log
ERROR    HTTP Error 400: Bad Request
```

**Comment by evios** [comment]
got same 
`ERROR    HTTP Error 400: Bad Request`
on license registration in 7.7.4

**Comment by nshout** [comment]
Got
```ERROR    request license token faild (16)```

**Comment by Mich-ele** [comment]
> Got `ERROR request license token faild (16)`

Same

**Comment by null-routed** [comment]
Getting the same, Python 3.9.1 and latest version of Pyarmor
`ERROR    request license token faild (16)`

**Comment by NoelisTired** [comment]
Same for me, this is really frustrating..
![image](https://user-images.githubusercontent.com/64641984/226580568-0a1c26c6-35f4-4f34-b106-fcead80cf78a.png)
