### ISSUE TITLE
[BUG] Can't upgrade my old pyarmor license with the upgrade function even tho I follow all instructions and have tried on different systems

### ISSUE THREAD

**Issue by JFuqX** [dashingsoft/pyarmor#988]
I get the following error:

pyarmor reg -u -p XXX pyarmor-regcode-to-pro.txt

```
INFO     Python 3.9.8
INFO     Pyarmor 8.0 (trial), 000000, non-profits
INFO     prepare "pyarmor-regcode-to-pro.txt"
INFO     query key file from server
CRITICAL unknown error, please check pyarmor.error.log
ERROR    product name has been set to "non-profits"

```

This is the pyarmor.error.log
```
12217 MainProcess 2023-03-18 18:38:43,268
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/__main__.py", line 178, in cmd_reg
    msg = regsvr.prepare(regfile, args.product, upgrade=args.upgrade)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyarmor/cli/register.py", line 241, in prepare
    raise RuntimeError(
RuntimeError: product name has been set to "non-profits"
```

**Comment by jondy** [comment]
Refer to pin issue #983
