### ISSUE TITLE
[BUG] license registration error.

### ISSUE THREAD

**Issue by xiene** [dashingsoft/pyarmor#993]
I installed pyarmor-8.0.7 and pyarmor.cli.core-1.0.2 then I got an error when I ran the following command.:
>pyarmor reg -p XXX C:\XXX\pyarmor\pyarmor-regcode-4002.txt
INFO     Python 3.11.2
INFO     Pyarmor 8.0.6 (trial), 000000, non-profits
INFO     prepare "C:\XXX\pyarmor\pyarmor-regcode-4002.txt"
INFO     query key file from server
This license registration information will be

License Type    : pyarmor-basic
License Owner   : XXXXXX
Bind Product    : XXX

Are you sure to continue? (yes/no) yes
INFO     process activation file "C:\XXX\pyarmor\pyarmor-regcode-4002.txt"
INFO     send register request to server
INFO     write registration file "pyarmor-regfile-4002.zip"
INFO     register "pyarmor-regfile-4002.zip"
INFO     update license token
CRITICAL unknown error, please check pyarmor.error.log
ERROR    <built-in function fspath> returned a result with an exception set

**Comment by jondy** [comment]
What's the content of `pyarmor.error.log`?

**Comment by xiene** [comment]
pyarmor.error.log:
1148 MainProcess 2023-03-23 08:54:45,874
RuntimeError: not machine id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\context.py", line 159, in save_token
    with open(self.license_token, 'wb') as f:
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\context.py", line 272, in license_token
    return os.path.join(self.reg_path, '.license.token')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 121, in join
SystemError: <built-in function fspath> returned a result with an exception set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 184, in cmd_reg
    getattr(regsvr, meth)(regfile, args.product)
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\register.py", line 310, in register
    self.register_regfile(regfile)
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\register.py", line 153, in register_regfile
    self.update_token()
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\register.py", line 110, in update_token
    Pytransform3._update_token(self.ctx)
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\core\__init__.py", line 72, in _update_token
    m = Pytransform3.init(ctx)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\core\__init__.py", line 42, in init
    m.init_ctx(ctx)
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\context.py", line 163, in clear_token
    if os.path.exists(self.license_token):
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dsk8843\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\context.py", line 272, in license_token
    return os.path.join(self.reg_path, '.license.token')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 121, in join
SystemError: <built-in function fspath> returned a result with an exception set

**Comment by jondy** [comment]
Fixed in 8.0.8 with pyarmor.cli.core==1.0.3
