### ISSUE TITLE
[BUG] RuntimeError: relative import overflow

### ISSUE THREAD

**Issue by fO-000** [dashingsoft/pyarmor#997]
When using pyarmor 8.0.8 to process a Python package, the following error is reported:

```txt
$ pyarmor gen --recursive src/xxx/__init__.py
INFO     Python 3.11.2
INFO     Pyarmor 8.0.8 (basic), 00xxxx, non-profits
INFO     search inputs ...
INFO     find script src/xxx/__init__.py
INFO     find 1 top resources
CRITICAL unknown error, please check pyarmor.error.log
ERROR    relative import overflow
```

The `pyarmor.error.log` is as follows:

```txt
43977 MainProcess 2023-03-23 17:16:22,336
Traceback (most recent call last):
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/__main__.py", line 144, in cmd_gen
    builder.process(options, pack=args.pack)
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/generate.py", line 143, in process
    Pytransform3.pre_build(self.ctx)
  File "/home/x/.local/lib/python3.11/site-packages/pyarmor/cli/core/__init__.py", line 63, in pre_build
    return m.pre_build(ctx)
           ^^^^^^^^^^^^^^^^
  File "<maker>", line 729, in pre_build
  File "<maker>", line 620, in build
  File "<maker>", line 2960, in process
  File "<maker>", line 2616, in using_modules
  File "<maker>", line 2722, in _get_using_modules
  File "<maker>", line 2720, in visit
  File "<maker>", line 2716, in visit
  File "<maker>", line 2367, in abs_name
RuntimeError: relative import overflow
```

**Comment by jondy** [comment]
Try to `pyarmor gen --recursive src/xxx/`
